In [1]:
%reload_ext autoreload
%autoreload 2
# notebooks/result_processing.ipynb

# ---
# # Experiment Results Analysis
# This notebook orchestrates the loading, analysis, validation, and reporting
# of experiment results logged to Weights & Biases.
# ---

# ## 1. Setup and Imports
# Import necessary libraries and custom modules. The `sys.path.append` line
# allows the notebook to find the custom `picid_report` package.
import sys
import pandas as pd

sys.path.append("..")

from picid_report.run_processor import load_runs_df
from picid_report.analysis import analyze_results
from picid_report.reporting import (
    create_summary_table,
    display_experiment_stats,
    display_hp_impact,
)
import picid_report.validators as validators
import picid_report.config as config
import os

# ---
# ## 2. Configuration
# Define all key parameters for the analysis in one place.
# ---
PROJECT_NAME = "29_01_2026_nb14_prognostics_combined"
USER = "imos-buildingenergy-1"

# Metrics to extract
METRIC_PREFIXES = ["val/", "test/", "test_best_rerun/", "val_best_rerun/"]
REPORTING_METRICS = ["loss", "mse", "mae", "rmse", "f1", "accuracy"]

# --- NEW: Scientific Rigor Settings ---
# If defined, the analysis will DROP any configuration group that does not
# contain exactly these seeds. Set to `None` to include all available data.

# Data seeds are set to None (Flexible mode)
REQUIRED_DATA_SEEDS = None

# Model seeds are strictly enforced (Strict mode)
REQUIRED_MODEL_SEEDS = {72, 88, 101, 666, 226688}

# Columns to ignore if they vary within a group (avoids "Hidden Variation" warnings)
ADDITIONAL_IGNORED_COLS = ["gpu_id", "slurm_job_id"]

# Configure pandas display options for better readability in the notebook.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# ---
# ## 3. Data Loading
# Fetch data from wandb (or a local cache) and prepare the initial DataFrame.
# The `load_runs_df` function handles all the complex cleaning and flattening.
# ---
print("🚀 Loading Run Data...")
df, config_columns, dropped_columns = load_runs_df(project_name=PROJECT_NAME, user=USER)
print(f"Loaded {len(df)} runs.")


# 2. PROACTIVE PREPROCESSING: Rename models and remove prefixes
def clean_and_rename_models(df):
    target_col = config.COLUMN_CONFIG["model_target"]
    type_col = "model.model_type"

    # Remove common prefix (e.g., 'picid.baselines.', 'picid.model.wrappers.')
    # This finds the common prefix among all unique model names
    unique_models = df[target_col].unique()
    if len(unique_models) > 1:
        prefix = os.path.commonprefix(list(unique_models))
        # Ensure we only strip up to the last dot if possible
        if "." in prefix:
            prefix = prefix.rsplit(".", 1)[0] + "."
        df[target_col] = df[target_col].str.replace(prefix, "", regex=False)

    # Distinguish Statistical Baselines (Linear vs Exponential)
    if type_col in df.columns:
        mask = df[type_col].notna()
        df.loc[mask, target_col] = (
            df.loc[mask, target_col] + " (" + df.loc[mask, type_col].astype(str) + ")"
        )

    return df


df = clean_and_rename_models(df)

validators.validate_schema(df, required_cols=config.REQUIRED_COLUMNS)

# ---
# ## 4. Core Analysis
# Run the main analysis function. This now includes:
# 1. Grouping by Model + Hyperparameters
# 2. Strict Seed Validation (Filtering incomplete groups)
# 3. Hidden Variation Detection (Warning about silent bugs)
# 4. Aggregation & Best Model Selection
# ---
print("\n🔬 Analyzing Results & Validating Consistency...")

all_results = analyze_results(
    df=df,
    config_columns=config_columns,
    dropped_columns=dropped_columns,
    reporting_metrics=REPORTING_METRICS,
    metric_prefixes=METRIC_PREFIXES,
    # --- New Validation Arguments ---
    required_data_seeds=REQUIRED_DATA_SEEDS,
    required_model_seeds=REQUIRED_MODEL_SEEDS,
    additional_ignored_cols=ADDITIONAL_IGNORED_COLS,
)

# ---
# ## 5. Reporting & Visualizations
# ---

# ### A. Experiment Statistics
# Shows how many configurations completed successfully and
# confirms which seeds were actually found in the data.
display_experiment_stats(all_results)

# ### B. Performance Leaderboards
# Displays a separate, clean pivot table for every metric found (MSE, MAE, etc.).
# display_performance_tables(all_results)

# ### C. Hyperparameter Impact Analysis
# Shows the top 10 configurations for each model, exposing exactly
# which hyperparameters led to the best results.
display_hp_impact(all_results)

# ### D. Legacy Summary Table
# A single flattened table containing all metrics (useful for copying to Excel/LaTeX).
print("\n📊 Full Summary Table:")
summary_df = create_summary_table(all_results)
display(summary_df)

🚀 Loading Run Data...
Loaded 582 runs from cached file: csv_files/29_01_2026_nb14_prognostics_combined.csv
Dropped 118 columns with >90% NaN values.
The columns were drropped: ['ckpt_path', 'profiler_cfg', 'subset_range', 'val_subset_ratio', 'optimizer_factory', 'scheduler_factory', 'test_subset_ratio', 'plots/test/pred_vs_target_unit_(16,)', 'plots/test/pred_vs_target_unit_(19,)', 'plots/test/pred_vs_target_unit_(24,)', 'plots/test/pred_vs_target_unit_(28,)', 'plots/test/pred_vs_target_unit_(6,)', 'plots/test/pred_vs_target_unit_(8,)', 'test/mae_(16,)_denormalized', 'test/mae_(16,)_normalized', 'test/mae_(19,)_denormalized', 'test/mae_(19,)_normalized', 'test/mae_(24,)_denormalized', 'test/mae_(24,)_normalized', 'test/mae_(28,)_denormalized', 'test/mae_(28,)_normalized', 'test/mae_(6,)_denormalized', 'test/mae_(6,)_normalized', 'test/mae_(8,)_denormalized', 'test/mae_(8,)_normalized', 'test/mape_(16,)_denormalized', 'test/mape_(16,)_normalized', 'test/mape_(19,)_denormalized', 'test/mape_(19,)_normalized', 'test/mape_(24,)_denormalized', 'test/mape_(24,)_normalized', 'test/mape_(28,)_denormalized', 'test/mape_(28,)_normalized', 'test/mape_(6,)_denormalized', 'test/mape_(6,)_normalized', 'test/mape_(8,)_denormalized', 'test/mape_(8,)_normalized', 'test/mse_(16,)_denormalized', 'test/mse_(16,)_normalized', 'test/mse_(19,)_denormalized', 'test/mse_(19,)_normalized', 'test/mse_(24,)_denormalized', 'test/mse_(24,)_normalized', 'test/mse_(28,)_denormalized', 'test/mse_(28,)_normalized', 'test/mse_(6,)_denormalized', 'test/mse_(6,)_normalized', 'test/mse_(8,)_denormalized', 'test/mse_(8,)_normalized', 'test/phm_score_(16,)_denormalized', 'test/phm_score_(16,)_normalized', 'test/phm_score_(19,)_denormalized', 'test/phm_score_(19,)_normalized', 'test/phm_score_(24,)_denormalized', 'test/phm_score_(24,)_normalized', 'test/phm_score_(28,)_denormalized', 'test/phm_score_(28,)_normalized', 'test/phm_score_(6,)_denormalized', 'test/phm_score_(6,)_normalized', 'test/phm_score_(8,)_denormalized', 'test/phm_score_(8,)_normalized', 'test/rmse_(16,)_denormalized', 'test/rmse_(16,)_normalized', 'test/rmse_(19,)_denormalized', 'test/rmse_(19,)_normalized', 'test/rmse_(24,)_denormalized', 'test/rmse_(24,)_normalized', 'test/rmse_(28,)_denormalized', 'test/rmse_(28,)_normalized', 'test/rmse_(6,)_denormalized', 'test/rmse_(6,)_normalized', 'test/rmse_(8,)_denormalized', 'test/rmse_(8,)_normalized', 'pad_value', 'null_value', 'target_mask', 'variable_emb_type', 'lr-Adam', 'seg_len', 'baseline', 'd_x_mask', 'win_size', 'decoder_embedding', 'freq', 'optimization.scheduler.gamma', 'optimization.scheduler.step_size', 'model.n_jobs', 'model.fit_mode', 'model.random_state', 'model.yield_strategy', 'model.model_cache_path', 'model.yield_batch_size', 'model.ignore_pretraining_limits', 'model.kernels', 'model.strides', 'model.dilations', 'model.latent_dim', 'model.dropout_prob', 'model.output_channels', 'model.factor', 'model.seg_len', 'model.baseline', 'model.win_size', 'model.decoder_embedding', 'model.freq', 'dataset.task_type', 'datamodule.val_subset_ratio', 'datamodule.test_subset_ratio', 'callbacks.early_stopping.stopping_threshold', 'callbacks.early_stopping.divergence_threshold', 'callbacks.early_stopping.check_on_train_epoch_end', 'callbacks.model_checkpoint.every_n_epochs', 'callbacks.model_checkpoint.every_n_train_steps', 'callbacks.model_checkpoint.train_time_interval', 'callbacks.model_checkpoint.save_on_train_epoch_end', 'evaluator._evaluator_defaults.inverse_transform_name', 'logger.wandb.anonymous', 'trainer.enable_checkpointing']
Dropped 60 columns based on name filters (e.g., 'paths.').
Loaded 582 runs.
✅ Schema Validation Passed: All 4 required columns present.

🔬 Analyzing Results & Validating Consistency...

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.patchtst_model.PatchTST_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.patchtst_model.PatchTST_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.patchtst_model.PatchTST_Forecaster'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.spacetimeformer_model.Spacetimeformer_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.spacetimeformer_model.Spacetimeformer_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.spacetimeformer_model.Spacetimeformer_Forecaster'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.crossformer_model.Crossformer_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (45, 620)
    Change:  537 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.crossformer_model.Crossformer_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.crossformer_model.Crossformer_Forecaster'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (exponential)' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (exponential): ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (exponential)'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (6, 620)
    Change:  576 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper: ['mae', 'mape', 'mse', 'phm_score', 'rmse']
  [Validator] NOTE: Strict filter on 'seed' removed all rows.
  [Validator] Fallback triggered: Ignoring seed filter for this model.

[PIPELINE STATUS] Mode: DATA-FIRST (Auto-Discovery)
    - No grid defined in config for: 'model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper'
    - Auto-discovered varying HPs: ['task_definition.seq_len', 'task_definition.stride_train']

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.tide_model.TiDE_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.tide_model.TiDE_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.tide_model.TiDE_Forecaster'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.cnn1d_wrapper.CNN1D_Wrapper' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (45, 620)
    Change:  537 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.cnn1d_wrapper.CNN1D_Wrapper: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'model.wrappers.cnn1d_wrapper.CNN1D_Wrapper'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.mlp_wrapper.MLPWrapper' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.mlp_wrapper.MLPWrapper: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'model.wrappers.mlp_wrapper.MLPWrapper'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (linear)' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (linear): ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (linear)'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.timeseries_transformer_model.Timeseries_Transformer_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.timeseries_transformer_model.Timeseries_Transformer_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.timeseries_transformer_model.Timeseries_Transformer_Forecaster'

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (6, 620)
    Change:  576 rows dropped
  ----------------------------------------
Dynamic metrics found for model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper: ['mae', 'mape', 'mse', 'phm_score', 'rmse']
  [Validator] NOTE: Strict filter on 'seed' removed all rows.
  [Validator] Fallback triggered: Ignoring seed filter for this model.

[PIPELINE STATUS] Mode: DATA-FIRST (Auto-Discovery)
    - No grid defined in config for: 'model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper'
    - Auto-discovered varying HPs: ['task_definition.seq_len', 'task_definition.stride_train']

  [DATAFRAME MODIFICATION] Subsetting DataFrame
    Context: Model='baselines.lstm_model.LSTM_Forecaster' | Dataset='NB14'
    Reason:  Filtering data to keep only runs matching the current target configuration.
    Shape:   (582, 620) -> (60, 620)
    Change:  522 rows dropped
  ----------------------------------------
Dynamic metrics found for baselines.lstm_model.LSTM_Forecaster: ['mae', 'mape', 'mse', 'phm_score', 'rmse']

[PIPELINE STATUS] Mode: SCHEMA-FIRST (Target Search Space)
    - Merging results with expected grid for model: 'baselines.lstm_model.LSTM_Forecaster'

========================================
  EXPERIMENT STATISTICS
========================================

========================================
  HYPERPARAMETER IMPACT ANALYSIS
========================================

>>> baselines.patchtst_model.PatchTST_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,optimization.lr,task_definition.seq_len,model.ts_in,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
6,0.0005,10,10.0,0.0043 ± 0.0001 (n=5),0.0045 ± 0.0000 (n=5),65.8630 ± 0.6700 (n=5),0.0608 ± 0.0006 (n=5),3.5010 ± 0.2680 (n=5),3.5010 ± 0.2680 (n=5),7089.4036 ± 213.7164 (n=5),0.0060 ± 0.0002 (n=5),0.2349 ± 0.0028 (n=5),0.2349 ± 0.0028 (n=5),77.5613 ± 0.5809 (n=5),0.0716 ± 0.0005 (n=5),0.0045 ± 0.0000 (n=5),65.8630 ± 0.6700 (n=5),0.0608 ± 0.0006 (n=5),3.5010 ± 0.2680 (n=5),3.5010 ± 0.2680 (n=5),7089.4036 ± 213.7164 (n=5),0.0060 ± 0.0002 (n=5),0.2349 ± 0.0028 (n=5),0.2349 ± 0.0028 (n=5),77.5613 ± 0.5809 (n=5),0.0716 ± 0.0005 (n=5),59.3844 ± 0.9261 (n=5),0.0548 ± 0.0009 (n=5),2.7441 ± 0.1956 (n=5),2.7441 ± 0.1956 (n=5),5637.7305 ± 236.8623 (n=5),0.0048 ± 0.0002 (n=5),0.2665 ± 0.0055 (n=5),0.2665 ± 0.0055 (n=5),73.9168 ± 1.2187 (n=5),0.0682 ± 0.0011 (n=5),0.0042 ± 0.0001 (n=5),58.8825 ± 0.5464 (n=5),0.0544 ± 0.0005 (n=5),2.8455 ± 0.2527 (n=5),2.8455 ± 0.2527 (n=5),5559.0275 ± 138.9670 (n=5),0.0047 ± 0.0001 (n=5),0.2683 ± 0.0033 (n=5),0.2683 ± 0.0033 (n=5),73.1268 ± 0.7099 (n=5),0.0675 ± 0.0007 (n=5)
12,0.0001,50,50.0,0.0044 ± 0.0003 (n=5),0.0038 ± 0.0004 (n=5),55.6478 ± 2.6616 (n=5),0.0514 ± 0.0025 (n=5),3.2511 ± 0.5221 (n=5),3.2511 ± 0.5221 (n=5),4801.2233 ± 508.8124 (n=5),0.0041 ± 0.0004 (n=5),0.2217 ± 0.0083 (n=5),0.2217 ± 0.0083 (n=5),68.1047 ± 3.5666 (n=5),0.0629 ± 0.0033 (n=5),0.0038 ± 0.0004 (n=5),55.6478 ± 2.6616 (n=5),0.0514 ± 0.0025 (n=5),3.2511 ± 0.5221 (n=5),3.2511 ± 0.5221 (n=5),4801.2233 ± 508.8124 (n=5),0.0041 ± 0.0004 (n=5),0.2217 ± 0.0083 (n=5),0.2217 ± 0.0083 (n=5),68.1047 ± 3.5666 (n=5),0.0629 ± 0.0033 (n=5),60.8264 ± 1.9023 (n=5),0.0562 ± 0.0018 (n=5),3.5879 ± 0.2995 (n=5),3.5879 ± 0.2995 (n=5),5650.4156 ± 427.7740 (n=5),0.0048 ± 0.0004 (n=5),0.2374 ± 0.0150 (n=5),0.2374 ± 0.0150 (n=5),74.2082 ± 2.6655 (n=5),0.0685 ± 0.0025 (n=5),0.0042 ± 0.0003 (n=5),59.2432 ± 1.7844 (n=5),0.0547 ± 0.0016 (n=5),3.5034 ± 0.2682 (n=5),3.5034 ± 0.2682 (n=5),5380.0936 ± 367.1143 (n=5),0.0046 ± 0.0003 (n=5),0.2406 ± 0.0049 (n=5),0.2406 ± 0.0049 (n=5),72.4304 ± 2.4957 (n=5),0.0669 ± 0.0023 (n=5)
11,0.0001,10,10.0,0.0057 ± 0.0006 (n=5),0.0063 ± 0.0005 (n=5),77.4232 ± 2.7448 (n=5),0.0715 ± 0.0025 (n=5),3.9369 ± 0.2649 (n=5),3.9369 ± 0.2649 (n=5),9896.7639 ± 626.0991 (n=5),0.0084 ± 0.0005 (n=5),0.2128 ± 0.0092 (n=5),0.2128 ± 0.0092 (n=5),91.2471 ± 3.4424 (n=5),0.0842 ± 0.0032 (n=5),0.0063 ± 0.0005 (n=5),77.4232 ± 2.7448 (n=5),0.0715 ± 0.0025 (n=5),3.9369 ± 0.2649 (n=5),3.9369 ± 0.2649 (n=5),9896.7639 ± 626.0991 (n=5),0.0084 ± 0.0005 (n=5),0.2128 ± 0.0092 (n=5),0.2128 ± 0.0092 (n=5),91.2471 ± 3.4424 (n=5),0.0842 ± 0.0032 (n=5),69.5823 ± 3.9376 (n=5),0.0642 ± 0.0036 (n=5),3.8673 ± 0.4068 (n=5),3.8673 ± 0.4068 (n=5),7933.1944 ± 934.6060 (n=5),0.0068 ± 0.0008 (n=5),0.2401 ± 0.0096 (n=5),0.2401 ± 0.0096 (n=5),85.6113 ± 4.4831 (n=5),0.0790 ± 0.0041 (n=5),0.0055 ± 0.0005 (n=5),67.8337 ± 2.7371 (n=5),0.0626 ± 0.0025 (n=5),3.5965 ± 0.4390 (n=5),3.5965 ± 0.4390 (n=5),7466.7702 ± 654.1410 (n=5),0.0064 ± 0.0006 (n=5),0.2477 ± 0.0058 (n=5),0.2477 ± 0.0058 (n=5),83.9034 ± 3.3923 (n=5),0.0775 ± 0.0031 (n=5)
1,0.0010,10,10.0,0.0062 ± 0.0018 (n=5),0.0062 ± 0.0020 (n=5),74.6767 ± 10.9751 (n=5),0.0689 ± 0.0101 (n=5),4.3004 ± 0.7699 (n=5),4.3004 ± 0.7699 (n=5),9114.0812 ± 2661.8913 (n=5),0.0078 ± 0.0023 (n=5),0.2127 ± 0.0250 (n=5),0.2127 ± 0.0250 (n=5),89.4532 ± 13.9031 (n=5),0.0826 ± 0.0128 (n=5),0.0062 ± 0.0020 (n=5),74.6767 ± 10.9751 (n=5),0.0689 ± 0.0101 (n=5),4.3004 ± 0.7699 (n=5),4.3004 ± 0.7699 (n=5),9114.0812 ± 2661.8913 (n=5),0.0078 ± 0.0023 (n=5),0.2127 ± 0.0250 (n=5),0.2127 ± 0.0250 (n=5),89.4532 ± 13.9031 (n=5),0.0826 ± 0.0128 (n=5),70.9329 ± 9.1587 (n=5),0.0655 ± 0.0085 (n=5),4.0516 ± 0.6063 (n=5),4.0516 ± 0.6063 (n=5),8092.8638 ± 1968.7178 (n=5),0.0069 ± 0.0017 (n=5),0.2330 ± 0.0195 (n=5),0.2330 ± 0.0195 (n=5),87.6884 ± 11.5974 (n=5),0.0810 ± 0.0107 (n=5),0.0058 ± 0.0018 (n=5),68.3172 ± 10.4001 (n=5),0.0631 ± 0.0096 (n=5),3.5223 ± 0.5649 (n=5),3.5223 ± 0.5649 (n=5),7578.5853 ± 2336.5879 (n=5),0.0065 ± 0.0020 (n=5),0.2445 ± 0.0288 (n=5),0.2445 ± 0.0288 (n=5),85.2341 ± 13.1016 (n=5),0.0787 ± 0.0121 (n=5)
13,0.0001,100,100.0,0.0109 ± 0.0027 (n=5),0.0073 ± 0.0013 (n=5),76.5314 ± 6.3881 (n=5),0.0707 ± 0.0059 (n=5),5.6483 ± 0.4328 (n=5),5.6483 ± 0.4328 (n=5),9111.1498 ± 1563.9615 (n=5),0.0078 ± 0.0013 (n=5),0.1567 ± 0.0083 (n=5),0.1567 ± 0.0083 (n=5),94.8225 ± 8.1161 (n=5),0.0875 ± 0.0075 (n=5),0.0073 ± 0.0013 (n=5),76.5314 ± 6.3881 (n=5),0.0707 ± 0.0059 (n=5),5.6483 ± 0.4328 (n=5),5.6483 ± 0.4328 (n=5),9111.1498 ± 1563.9615 (n=5),0.0078 ± 0.0013 (n=5),0.1567 ± 0.0083 (n=5),0.1567 ± 0.0083 (n=5),94.8225 ± 8.1161 (n=5),0.0875 ± 0.0075 (n=5),96.4645 ± 16.5355 (n=5),0.0891 ± 0.0153 (n=5),5.8584 ± 1.2235 (n=5),5.8584 ± 1.2235 (n=5),13906.5786 ± 3576.6664 (n=5),0.0119 ± 0.0030 (n=5),0.1139 ± 0.0443 (n=5),0.1139 ± 0.0443 (n=5),115.5180 ± 16.2859 (n=5),0.1066 ± 0.0150 (n=5),0.0076 ± 0.0016 (n=5),74.6831 ± 7.3380 (n=5),0.0689 ± 0.0068 (n=5),4.2003 ± 0.5420 (n=5),4.2003 ± 0.5420 (n=5),9083.3835 ± 1773.6313 (n=5),0.0077 ± 0.0015 (n=5),0.1798 ± 0.0081 (n=5),0.1798 ± 0.0081 (n=5),94.4348 ± 9.3176 (n=5),0.0872 ± 0.0086 (n=5)
2,0.0010,50,50.0,0.0267 ± 0.0164 (n=5),0.0120 ± 0.0001 (n=5),94.8020 ± 2.1179 (n=5),0.0875 ± 0.0020 (n=5),9.4568 ± 0.6758 (n=5),9.4568 ± 0.6758 (n=5),12495.6529 ± 211.9479 (n=5),0.0106 ± 0.0002 (n=5),0.1708 ± 0.0020 (n=5),0.1708 ± 0.0020 (n=5),110.2937 ± 1.3184 (n=5),0.1018 ± 0.0012 (n=5),0.0120 ± 0.0001 (n=5),94.8020 ± 2.1179 (n=5),0.0875 ± 0.0020 (n=5),9.4568 ± 0.6758 (n=5),9.4568 ± 0.6758 (n=5),12495.6529 ± 211.9479 (n=5),0.0106 ± 0.0002 (n=5),0.1708 ± 0.0020 (n=5),0.1708 ± 0.0020 (n=5),110.2937 ± 1.3184 (n=5),0.1018 ± 0.0012 (n=5),143.4334 ± 47.5509 (n=5),0.1324 ± 0.0439 (n=5),9.0515 ± 4.8848 (n=5),9.0515 ± 4.8848 (n=5),30340.6645 ± 19135.4340 (n=5),0.0259 ± 0.0163 (n=5),0.1285 ± 0.0695 (n=5),0.1285 ± 0.0695 (n=5),167.1870 ± 51.5974 (n=5),0.1543 ± 0.0476 (n=5),0.0133 ± 0.0002 (n=5),102.2476 ± 0.7855 (n=5),0.0944 ± 0.0007 (n=5),7.8602 ± 0.5596 (n=5),7.8602 ± 0.5596 (n=5),14609.1264 ± 227.5637 (n=5),0.0125 ± 0.0002 (n=5),0.1745 ± 0.0002 (n=5),0.1745 ± 0.0002 (n=5),119.7533 ± 0.8018 (n=5),0.1106 ± 0.0007 (n=5)
8,0.0005,100,100.0,0.0374 ± 0.0335 (n=5),0.0065 ± 0.0035 (n=5),68.8167 ± 17.4736 (n=5),0.0635 ± 0.0161 (n=5),6.4741 ± 2.6633 (n=5),6.4741 ± 2.6633 (n=5),7429.3184 ± 3121.5273 (n=5),0.0063 ± 0.0027 (n=5),0.2104 ± 0.0399 (n=5),0.2104 ± 0.0399 (n=5),83.1212 ± 18.9700 (n=5),0.0767 ± 0.0175 (n=5),0.0065 ± 0.0035 (n=5),68.8167 ± 17.4736 (n=5),0.0635 ± 0.0161 (n=5),6.4741 ± 2.6633 (n=5),6.4741 ± 2.6633 (n=5),7429.3184 ± 3121.5273 (n=5),0.0063 ± 0.0027 (n=5),0.2104 ± 0.0399 (n=5),0.2104 ± 0.0399 (n=5),83.1212 ± 18.9700 (n=5),0.0767 ± 0.0175 (n=5),179.8025 ± 108.5517 (n=5),0.1660 ± 0.1002 (n=5),12.4708 ± 8.2750 (n=5),12.4708 ± 8.2750 (n=5),48286.5408 ± 42234.9777 (n=5),0.0412 ± 0.0360 (n=5),0.0902 ± 0.1012 (n=5),0.0902 ± 0.1012 (n=5),193.7096 ± 108.5721 (n=5),0.1788 ± 0.1002 (n=5),0.0072 ± 0.0035 (n=5),73.7587 ± 17.5492 (n=5),0.0681 ± 0.0162 (n=5),5.3213 ± 2.2862 (n=5),5.3213 ± 2.2862 (n=5),8379.5981 ± 3443.0439 (n=5),0.0071 ± 0.0029 (n=5),0.2168 ± 0.0356 (n=5),0.2168 ± 0.0356 (n=5),89.1270 ± 19.1970 (n=5),0.0823 ± 0.0177 (n=5)
7,0.0005,50,50.0,0.0471 ± 0.0721 (n=5),0.0067 ± 0.0040 (n=5),73.5689 ± 19.3970 (n=5),0.0679 ± 0.0179 (n=5),5.1486 ± 2.3070 (n=5),5.1486 ± 2.3070 (n=5),8706.1924 ± 4897.1039 (n=5),0.0074 ± 0.0042 (n=5),0.1978 ± 0.0275 (n=5),0.1978 ± 0.0275 (n=5),89.2876 ± 23.7582 (n=5),0.0824 ± 0.0219 (n=5),0.0067 ± 0.0040 (n=5),73.5689 ± 19.3970 (n=5),0.0679 ± 0.0179 (n=5),5.1486 ± 2.3070 (n=5),5.1486 ± 2.3070 (n=5),8706.1924 ± 4897.1039 (n=5),0.0074 ± 0.0042 (n=5),0.1978 ± 0.0275 (n=5),0.1978 ± 0.0275 (n=5),89.2876 ± 23.7582 (n=5),0.0824 ± 0.0219 (n=5),177.3207 ± 153.2531 (n=5),0.1637 ± 0.1415 (n=5),11.5471 ± 11.2471 (n=5),11.5471 ± 11.2471 (n=5),56594.9993 ± 84179.2905 (n=5),0.0482 ± 0.0717 (n=5),0.1133 ± 0.0992 (n=5),0.1133 ± 0.0992 (n=5),192.5819 ± 153.3795 (n=5),0.1778 ± 0.1416 (n=5),0.0066 ± 0.0040 (n=5),72.0378 ± 18.7246 (n=5),0.0665 ± 0.0173 (n=5),4.2213 ± 2.0758 (n=5),4.2213 ± 2.0758 (n=5),8476.0128 ± 4691.6217 (n=5),0.0072 ± 0.0040 (n=5),0.2325 ± 0.0302 (n=5),0.2325 ± 0.0302 (n=5),88.5456 ± 23.0073 (n=5),0.0817 ± 0.0212 (n=5)
3,0.0010,100,100.0,0.0982 ± 0.0304 (n=5),0.0110 ± 0.0019 (n=5),87.6141 ± 2.4344 (n=5),0.0809 ± 0.0022 (n=5),8.5990 ± 2.5405 (n=5),8.5990 ± 2.5405 (n=5),11291.1736 ± 1612.6619 (n=5),0.0096 ± 0.0014 (n=5),0.1666 ± 0.0062 (n=5),0.1666 ± 0.0062 (n=5),104.2333 ± 6.1457 (n=5),0.0962 ± 0.0057 (n=5),0.0110 ± 0.0019 (n=5),87.6141 ± 2.4344 (n=5),0.0809 ± 0.0022 (n=5),8.5990 ± 2.5405 (n=5),8.5990 ± 2.5405 (n=5),11291.1736 ± 1612.6619 (n=5),0.0096 ± 0.0014 (n=5),0.1666 ± 0.0062 (n=5),0.1666 ± 0.0062 (n=5),104.2333 ± 6.1457 (n=5),0.0962 ± 0.0057 (n=5),317.2942 ± 56.7914 (n=5),0.2929 ± 0.0524 (n=5),22.1752 ± 8.5071 (n=5),22.1752 ± 8.5071 (n=5),115045.1625 ± 36284.3866 (n=5),0.0980 ± 0.0309 (n=5),0.0079 ± 0.0123 (n=5),0.0079 ± 0.0123 (n=5),335.3402 ± 53.9679 (n=5),0.3096 ± 0.0498 (n=5),0.0123 ± 0.0028 (n=5),95.3180 ± 4.9646 (n=5),0.0880 ± 0.0046 (n=5),7.0971 ± 2.0694 (n=5),7.0971 ± 2.0694 (n=5),13394.0584 ± 3122.3418 (n=5),0.0114 ± 0.0027 (n=5),0.1722 ± 0.0109 (n=5),0.1722 ± 0.0109 (n=5),113.8665 ± 12.2956 (n=5),0.1051 ± 0.0114 (n=5)
0,0.0010,1,1.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,0.0010,150,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
5,0.0005,1,1.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9,0.0005,150,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
10,0.0001,1,1.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,0.0001,150,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> baselines.spacetimeformer_model.Spacetimeformer_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
11,100,0.0001,1.0792 ± 0.5181 (n=5),0.0053 ± 0.0017 (n=5),68.0611 ± 8.7032 (n=5),0.0628 ± 0.0080 (n=5),5.6071 ± 2.1299 (n=5),5.6071 ± 2.1299 (n=5),7230.2074 ± 1637.3606 (n=5),0.0062 ± 0.0014 (n=5),0.2029 ± 0.0310 (n=5),0.2029 ± 0.0310 (n=5),80.1586 ± 9.8126 (n=5),0.0740 ± 0.0091 (n=5),0.0053 ± 0.0017 (n=5),68.0611 ± 8.7032 (n=5),0.0628 ± 0.0080 (n=5),5.6071 ± 2.1299 (n=5),5.6071 ± 2.1299 (n=5),7230.2074 ± 1637.3606 (n=5),0.0062 ± 0.0014 (n=5),0.2029 ± 0.0310 (n=5),0.2029 ± 0.0310 (n=5),80.1586 ± 9.8126 (n=5),0.0740 ± 0.0091 (n=5),133.9338 ± 26.8927 (n=5),0.1236 ± 0.0248 (n=5),4.3979 ± 0.6118 (n=5),4.3979 ± 0.6118 (n=5),926752.0938 ± 444094.9471 (n=5),0.7898 ± 0.3785 (n=5),0.2836 ± 0.0281 (n=5),0.2836 ± 0.0281 (n=5),434.6919 ± 109.0902 (n=5),0.4013 ± 0.1007 (n=5),0.0165 ± 0.0154 (n=5),71.1634 ± 11.3819 (n=5),0.0657 ± 0.0105 (n=5),4.1641 ± 0.8281 (n=5),4.1641 ± 0.8281 (n=5),16298.6870 ± 13163.8813 (n=5),0.0139 ± 0.0112 (n=5),0.2450 ± 0.0160 (n=5),0.2450 ± 0.0160 (n=5),101.8871 ± 30.3932 (n=5),0.0941 ± 0.0281 (n=5)
5,10,0.0001,2.9072 ± 1.3807 (n=5),0.0076 ± 0.0022 (n=5),82.6924 ± 13.1989 (n=5),0.0763 ± 0.0122 (n=5),4.8819 ± 1.1705 (n=5),4.8819 ± 1.1705 (n=5),10703.6891 ± 2881.4581 (n=5),0.0091 ± 0.0025 (n=5),0.1974 ± 0.0359 (n=5),0.1974 ± 0.0359 (n=5),97.9797 ± 13.9942 (n=5),0.0905 ± 0.0129 (n=5),0.0076 ± 0.0022 (n=5),82.6924 ± 13.1989 (n=5),0.0763 ± 0.0122 (n=5),4.8819 ± 1.1705 (n=5),4.8819 ± 1.1705 (n=5),10703.6891 ± 2881.4581 (n=5),0.0091 ± 0.0025 (n=5),0.1974 ± 0.0359 (n=5),0.1974 ± 0.0359 (n=5),97.9797 ± 13.9942 (n=5),0.0905 ± 0.0129 (n=5),185.9101 ± 31.0345 (n=5),0.1716 ± 0.0286 (n=5),3.4862 ± 0.0874 (n=5),3.4862 ± 0.0874 (n=5),2562420.5000 ± 1216170.1226 (n=5),2.1838 ± 1.0365 (n=5),0.2673 ± 0.0034 (n=5),0.2673 ± 0.0034 (n=5),701.3545 ± 155.3427 (n=5),0.6475 ± 0.1434 (n=5),0.0194 ± 0.0085 (n=5),84.7061 ± 14.9168 (n=5),0.0782 ± 0.0138 (n=5),4.3916 ± 1.4213 (n=5),4.3916 ± 1.4213 (n=5),20388.3996 ± 8213.7149 (n=5),0.0174 ± 0.0070 (n=5),0.2407 ± 0.0445 (n=5),0.2407 ± 0.0445 (n=5),126.8075 ± 23.9892 (n=5),0.1171 ± 0.0221 (n=5)
8,50,0.0001,4.5866 ± 2.4017 (n=5),0.0063 ± 0.0021 (n=5),72.4299 ± 5.5381 (n=5),0.0669 ± 0.0051 (n=5),4.4130 ± 0.3664 (n=5),4.4130 ± 0.3664 (n=5),8248.4198 ± 1339.6633 (n=5),0.0070 ± 0.0011 (n=5),0.2093 ± 0.0166 (n=5),0.2093 ± 0.0166 (n=5),86.1155 ± 8.4074 (n=5),0.0795 ± 0.0078 (n=5),0.0063 ± 0.0021 (n=5),72.4299 ± 5.5381 (n=5),0.0669 ± 0.0051 (n=5),4.4130 ± 0.3664 (n=5),4.4130 ± 0.3664 (n=5),8248.4198 ± 1339.6633 (n=5),0.0070 ± 0.0011 (n=5),0.2093 ± 0.0166 (n=5),0.2093 ± 0.0166 (n=5),86.1155 ± 8.4074 (n=5),0.0795 ± 0.0078 (n=5),228.0792 ± 45.1705 (n=5),0.2106 ± 0.0417 (n=5),4.2905 ± 0.3295 (n=5),4.2905 ± 0.3295 (n=5),3995640.6500 ± 2090893.5393 (n=5),3.4052 ± 1.7819 (n=5),0.2806 ± 0.0322 (n=5),0.2806 ± 0.0322 (n=5),851.5121 ± 204.6425 (n=5),0.7861 ± 0.1889 (n=5),0.0234 ± 0.0198 (n=5),78.2014 ± 15.5336 (n=5),0.0722 ± 0.0143 (n=5),3.6998 ± 0.7432 (n=5),3.6998 ± 0.7432 (n=5),22817.6748 ± 17387.1056 (n=5),0.0194 ± 0.0148 (n=5),0.2335 ± 0.0292 (n=5),0.2335 ± 0.0292 (n=5),122.6335 ± 33.6397 (n=5),0.1132 ± 0.0311 (n=5)
9,100,0.0010,5.9619 ± 4.5952 (n=5),0.0087 ± 0.0048 (n=5),85.3502 ± 26.9908 (n=5),0.0788 ± 0.0249 (n=5),6.9757 ± 2.6724 (n=5),6.9757 ± 2.6724 (n=5),11266.1282 ± 6168.2373 (n=5),0.0096 ± 0.0053 (n=5),0.1657 ± 0.0672 (n=5),0.1657 ± 0.0672 (n=5),98.1453 ± 25.6763 (n=5),0.0906 ± 0.0237 (n=5),0.0087 ± 0.0048 (n=5),85.3502 ± 26.9908 (n=5),0.0788 ± 0.0249 (n=5),6.9757 ± 2.6724 (n=5),6.9757 ± 2.6724 (n=5),11266.1282 ± 6168.2373 (n=5),0.0096 ± 0.0053 (n=5),0.1657 ± 0.0672 (n=5),0.1657 ± 0.0672 (n=5),98.1453 ± 25.6763 (n=5),0.0906 ± 0.0237 (n=5),243.1878 ± 108.8800 (n=5),0.2245 ± 0.1005 (n=5),4.2109 ± 0.6609 (n=5),4.2109 ± 0.6609 (n=5),5112593.7566 ± 3938394.0730 (n=5),4.3571 ± 3.3564 (n=5),0.2265 ± 0.0744 (n=5),0.2265 ± 0.0744 (n=5),871.7560 ± 485.5491 (n=5),0.8048 ± 0.4482 (n=5),0.0108 ± 0.0037 (n=5),85.1056 ± 21.3734 (n=5),0.0786 ± 0.0197 (n=5),4.9241 ± 1.7434 (n=5),4.9241 ± 1.7434 (n=5),12438.9776 ± 4169.1702 (n=5),0.0106 ± 0.0036 (n=5),0.1907 ± 0.0698 (n=5),0.1907 ± 0.0698 (n=5),105.3412 ± 17.4680 (n=5),0.0972 ± 0.0161 (n=5)
2,1,0.0001,6.1428 ± 6.1213 (n=5),0.0167 ± 0.0044 (n=5),105.6373 ± 21.3772 (n=5),0.0975 ± 0.0197 (n=5),6.9590 ± 4.2970 (n=5),6.9590 ± 4.2970 (n=5),17278.1467 ± 5138.8148 (n=5),0.0147 ± 0.0044 (n=5),0.1707 ± 0.0331 (n=5),0.1707 ± 0.0331 (n=5),127.0001 ± 20.7327 (n=5),0.1172 ± 0.0191 (n=5),0.0167 ± 0.0044 (n=5),105.6373 ± 21.3772 (n=5),0.0975 ± 0.0197 (n=5),6.9590 ± 4.2970 (n=5),6.9590 ± 4.2970 (n=5),17278.1467 ± 5138.8148 (n=5),0.0147 ± 0.0044 (n=5),0.1707 ± 0.0331 (n=5),0.1707 ± 0.0331 (n=5),127.0001 ± 20.7327 (n=5),0.1172 ± 0.0191 (n=5),159.4012 ± 50.1707 (n=5),0.1472 ± 0.0463 (n=5),3.1733 ± 0.6308 (n=5),3.1733 ± 0.6308 (n=5),5425106.4375 ± 5404537.4027 (n=5),4.6234 ± 4.6059 (n=5),0.2624 ± 0.0167 (n=5),0.2624 ± 0.0167 (n=5),923.1062 ± 473.3946 (n=5),0.8522 ± 0.4370 (n=5),0.0718 ± 0.1063 (n=5),121.6011 ± 17.6777 (n=5),0.1123 ± 0.0163 (n=5),5.8774 ± 3.4954 (n=5),5.8774 ± 3.4954 (n=5),67339.3270 ± 93995.2202 (n=5),0.0574 ± 0.0801 (n=5),0.1681 ± 0.0288 (n=5),0.1681 ± 0.0288 (n=5),183.2484 ± 72.4177 (n=5),0.1692 ± 0.0669 (n=5)
10,100,0.0005,6.2009 ± 3.0411 (n=5),0.0074 ± 0.0039 (n=5),76.6514 ± 11.2201 (n=5),0.0708 ± 0.0104 (n=5),5.5111 ± 0.9081 (n=5),5.5111 ± 0.9081 (n=5),9106.7892 ± 2338.9695 (n=5),0.0078 ± 0.0020 (n=5),0.1821 ± 0.0233 (n=5),0.1821 ± 0.0233 (n=5),88.7094 ± 12.0787 (n=5),0.0819 ± 0.0112 (n=5),0.0074 ± 0.0039 (n=5),76.6514 ± 11.2201 (n=5),0.0708 ± 0.0104 (n=5),5.5111 ± 0.9081 (n=5),5.5111 ± 0.9081 (n=5),9106.7892 ± 2338.9695 (n=5),0.0078 ± 0.0020 (n=5),0.1821 ± 0.0233 (n=5),0.1821 ± 0.0233 (n=5),88.7094 ± 12.0787 (n=5),0.0819 ± 0.0112 (n=5),261.1995 ± 46.7323 (n=5),0.2411 ± 0.0431 (n=5),4.7450 ± 0.8675 (n=5),4.7450 ± 0.8675 (n=5),5316807.9000 ± 2606953.2872 (n=5),4.5311 ± 2.2217 (n=5),0.2789 ± 0.0273 (n=5),0.2789 ± 0.0273 (n=5),972.8881 ± 223.3669 (n=5),0.8981 ± 0.2062 (n=5),0.0108 ± 0.0043 (n=5),79.3459 ± 18.4242 (n=5),0.0732 ± 0.0170 (n=5),4.1383 ± 0.6253 (n=5),4.1383 ± 0.6253 (n=5),11708.1333 ± 3850.4641 (n=5),0.0100 ± 0.0033 (n=5),0.2146 ± 0.0449 (n=5),0.2146 ± 0.0449 (n=5),102.0875 ± 17.3909 (n=5),0.0942 ± 0.0161 (n=5)
4,10,0.0005,6.4836 ± 3.0719 (n=5),0.0105 ± 0.0051 (n=5),100.0601 ± 28.3956 (n=5),0.0924 ± 0.0262 (n=5),6.2103 ± 2.6809 (n=5),6.2103 ± 2.6809 (n=5),15346.5156 ± 7343.1509 (n=5),0.0131 ± 0.0063 (n=5),0.1593 ± 0.0533 (n=5),0.1593 ± 0.0533 (n=5),115.3586 ± 27.5955 (n=5),0.1065 ± 0.0255 (n=5),0.0105 ± 0.0051 (n=5),100.0601 ± 28.3956 (n=5),0.0924 ± 0.0262 (n=5),6.2103 ± 2.6809 (n=5),6.2103 ± 2.6809 (n=5),15346.5156 ± 7343.1509 (n=5),0.0131 ± 0.0063 (n=5),0.1593 ± 0.0533 (n=5),0.1593 ± 0.0533 (n=5),115.3586 ± 27.5955 (n=5),0.1065 ± 0.0255 (n=5),268.0390 ± 35.5658 (n=5),0.2474 ± 0.0328 (n=5),4.6156 ± 1.5646 (n=5),4.6156 ± 1.5646 (n=5),5713999.5500 ± 2703896.9363 (n=5),4.8696 ± 2.3043 (n=5),0.2018 ± 0.0929 (n=5),0.2018 ± 0.0929 (n=5),1027.4871 ± 225.1829 (n=5),0.9485 ± 0.2079 (n=5),0.0269 ± 0.0144 (n=5),99.3097 ± 24.3568 (n=5),0.0917 ± 0.0225 (n=5),5.3633 ± 2.3360 (n=5),5.3633 ± 2.3360 (n=5),28436.2084 ± 13693.5570 (n=5),0.0242 ± 0.0117 (n=5),0.1978 ± 0.0526 (n=5),0.1978 ± 0.0526 (n=5),146.3827 ± 31.9791 (n=5),0.1351 ± 0.0295 (n=5)
3,10,0.0010,10.6809 ± 6.2683 (n=5),0.0457 ± 0.0520 (n=5),184.5798 ± 137.7902 (n=5),0.1704 ± 0.1272 (n=5),10.9074 ± 7.5680 (n=5),10.9074 ± 7.5680 (n=5),55706.4461 ± 65207.1756 (n=5),0.0475 ± 0.0556 (n=5),0.1116 ± 0.1006 (n=5),0.1116 ± 0.1006 (n=5),197.4231 ± 135.1110 (n=5),0.1823 ± 0.1247 (n=5),0.0457 ± 0.0520 (n=5),184.5798 ± 137.7902 (n=5),0.1704 ± 0.1272 (n=5),10.9074 ± 7.5680 (n=5),10.9074 ± 7.5680 (n=5),55706.4461 ± 65207.1756 (n=5),0.0475 ± 0.0556 (n=5),0.1116 ± 0.1006 (n=5),0.1116 ± 0.1006 (n=5),197.4231 ± 135.1110 (n=5),0.1823 ± 0.1247 (n=5),311.3586 ± 72.7803 (n=5),0.2874 ± 0.0672 (n=5),3.9874 ± 0.9778 (n=5),3.9874 ± 0.9778 (n=5),9409780.1000 ± 5520983.9825 (n=5),8.0193 ± 4.7051 (n=5),0.2119 ± 0.0812 (n=5),0.2119 ± 0.0812 (n=5),1280.2894 ± 367.9501 (n=5),1.1819 ± 0.3397 (n=5),0.0610 ± 0.0646 (n=5),188.2743 ± 138.4104 (n=5),0.1738 ± 0.1278 (n=5),8.9286 ± 6.5993 (n=5),8.9286 ± 6.5993 (n=5),68546.3318 ± 74784.5946 (n=5),0.0584 ± 0.0637 (n=5),0.1298 ± 0.1156 (n=5),0.1298 ± 0.1156 (n=5),220.7244 ± 140.6602 (n=5),0.2038 ± 0.1299 (n=5)
1,1,0.0005,22.3652 ± 13.4417 (n=5),0.0135 ± 0.0038 (n=5),95.3722 ± 14.8136 (n=5),0.0880 ± 0.0137 (n=5),6.5322 ± 3.2551 (n=5),6.5322 ± 3.2551 (n=5),14325.0686 ± 3732.8282 (n=5),0.0122 ± 0.0032 (n=5),0.1877 ± 0.0292 (n=5),0.1877 ± 0.0292 (n=5),116.8855 ± 16.1198 (n=5),0.1079 ± 0.0149 (n=5),0.0135 ± 0.0038 (n=5),95.3722 ± 14.8136 (n=5),0.0880 ± 0.0137 (n=5),6.5322 ± 3.2551 (n=5),6.5322 ± 3.2551 (n=5),14325.0686 ± 3732.8282 (n=5),0.0122 ± 0.0032 (n=5),0.1877 ± 0.0292 (n=5),0.1877 ± 0.0292 (n=5),116.8855 ± 16.1198 (n=5),0.1079 ± 0.0149 (n=5),267.3631 ± 62.6212 (n=5),0.2468 ± 0.0578 (n=5),4.1291 ± 1.2924 (n=5),4.1291 ± 1.2924 (n=5),19748366.9000 ± 11868225.6562 (n=5),16.8301 ± 10.1144 (n=5),0.2107 ± 0.0479 (n=5),0.2107 ± 0.0479 (n=5),1823.3071 ± 572.1233 (n=5),1.6832 ± 0.5282 (n=5),0.0251 ± 0.0151 (n=5),107.1322 ± 16.1673 (n=5),0.0989 ± 0.0149 (n=5),5.7736 ± 2.5646 (n=5),5.7736 ± 2.5646 (n=5),25771.0053 ± 13792.3112 (n=5),0.0220 ± 0.0118 (n=5),0.1876 ± 0.0286 (n=5),0.1876 ± 0.0286 (n=5),146.2356 ± 31.5242 (n=5),0.1350 ± 0.0291 (n=5)
0,1,0.0010,26.2514 ± 6.2272 (n=5),0.0192 ± 0.0115 (n=5),110.1102 ± 32.7874 (n=5),0.1016 ± 0.0303 (n=5),5.4368 ± 2.7953 (n=5),5.4368 ± 2.7953 (n=5),20084.3104 ± 12365.4759 (n=5),0.0171 ± 0.0105 (n=5),0.1501 ± 0.0705 (n=5),0.1501 ± 0.0705 (n=5),135.0236 ± 38.3049 (n=5),0.1246 ± 0.0354 (n=5),0.0192 ± 0.0115 (n=5),110.1102 ± 32.7874 (n=5),0.1016 ± 0.0303 (n=5),5.4368 ± 2.7953 (n=5),5.4368 ± 2.7953 (n=5),20084.3104 ± 12365.4759 (n=5),0.0171 ± 0.0105 (n=5),0.1501 ± 0.0705 (n=5),0.1501 ± 0.0705 (n=5),135.0236 ± 38.3049 (n=5),0.1246 ± 0.0354 (n=5),278.7269 ± 31.0524 (n=5),0.2573 ± 0.0287 (n=5),4.1753 ± 0.9225 (n=5),4.1753 ± 0.9225 (n=5),23178784.6000 ± 5498055.8846 (n=5),19.7536 ± 4.6856 (n=5),0.2346 ± 0.0459 (n=5),0.2346 ± 0.0459 (n=5),2026.0986 ± 252.3456 (n=5),1.8704 ± 0.2330 (n=5),0.0248 ± 0.0121 (n=5),123.9314 ± 36.0310 (n=5),0.1144 ± 0.0333 (n=5),4.5465 ± 2.2457 (n=5),4.5465 ± 2.2457 (n=5),27147.1377 ± 14094.0948 (n=5),0.0231 ± 0.0120 (n=5),0.1491 ± 0.0706 (n=5),0.1491 ± 0.0706 (n=5),158.2847 ± 39.2161 (n=5),0.1461 ± 0.0362 (n=5)
7,50,0.0005,27.4623 ± 16.9051 (n=5),0.0077 ± 0.0034 (n=5),77.1145 ± 7.7838 (n=5),0.0712 ± 0.0072 (n=5),4.8498 ± 0.9964 (n=5),4.8498 ± 0.9964 (n=5),9372.9787 ± 2274.1186 (n=5),0.0080 ± 0.0019 (n=5),0.1997 ± 0.0251 (n=5),0.1997 ± 0.0251 (n=5),91.7416 ± 11.3060 (n=5),0.0847 ± 0.0104 (n=5),0.0077 ± 0.0034 (n=5),77.1145 ± 7.7838 (n=5),0.0712 ± 0.0072 (n=5),4.8498 ± 0.9964 (n=5),4.8498 ± 0.9964 (n=5),9372.9787 ± 2274.1186 (n=5),0.0080 ± 0.0019 (n=5),0.1997 ± 0.0251 (n=5),0.1997 ± 0.0251 (n=5),91.7416 ± 11.3060 (n=5),0.0847 ± 0.0104 (n=5),488.5657 ± 155.8938 (n=5),0.4510 ± 0.1439 (n=5),4.2416 ± 0.7453 (n=5),4.2416 ± 0.7453 (n=5),23913627.1000 ± 14719331.0468 (n=5),20.3799 ± 12.5442 (n=5),0.2500 ± 0.0552 (n=5),0.2500 ± 0.0552 (n=5),1968.2912 ± 666.9344 (n=5),1.8171 ± 0.6157 (n=5),0.0520 ± 0.0690 (n=5),88.2004 ± 18.5449 (n=5),0.0814 ± 0.0171 (n=5),3.4108 ± 0.5101 (n=5),3.4108 ± 0.5101 (n=5),47738.4795 ± 59909.7031 (n=5),0.0407 ± 0.0511 (n=5),0.2175 ± 0.0348 (n=5),0.2175 ± 0.0348 (n=5),145.1412 ± 59.4665 (n=5),0.1340 ± 0.0549 (n=5)
6,50,0.0010,32.3751 ± 29.3709 (n=5),0.0073 ± 0.0010 (n=5),78.4073 ± 3.3861 (n=5),0.0724 ± 0.0031 (n=5),5.2264 ± 0.2581 (n=5),5.2264 ± 0.2581 (n=5),9296.8077 ± 1486.8849 (n=5),0.0079 ± 0.0013 (n=5),0.1951 ± 0.0162 (n=5),0.1951 ± 0.0162 (n=5),91.5529 ± 3.2070 (n=5),0.0845 ± 0.0030 (n=5),0.0073 ± 0.0010 (n=5),78.4073 ± 3.3861 (n=5),0.0724 ± 0.0031 (n=5),5.2264 ± 0.2581 (n=5),5.2264 ± 0.2581 (n=5),9296.8077 ± 1486.8849 (n=5),0.0079 ± 0.0013 (n=5),0.1951 ± 0.0162 (n=5),0.1951 ± 0.0162 (n=5),91.5529 ± 3.2070 (n=5),0.0845 ± 0.0030 (n=5),470.6558 ± 266.0878 (n=5),0.4345 ± 0.2456 (n=5),3.7532 ± 0.5868 (n=5),3.7532 ± 0.5868 (n=5),28191145.2135 ± 25573324.4358 (n=5),24.0253 ± 21.7943 (n=5),0.2887 ± 0.0665 (n=5),0.2887 ± 0.0665 (n=5),1929.4633 ± 1206.4273 (n=5),1.7812 ± 1.1137 (n=5),0.0554 ± 0.0762 (n=5),87.1553 ± 15.1604 (n=5),0.0805 ± 0.0140 (n=5),4.0222 ± 0.5119 (n=5),4.0222 ± 0.5119 (n=5),50624.5664 ± 65898.7903 (n=5),0.0431 ± 0.0562 (n=5),0.2215 ± 0.0215 (n=5),0.2215 ± 0.0215 (n=5),143.5148 ± 59.8282 (n=5),0.1325 ± 0.0552 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> baselines.crossformer_model.Crossformer_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.ts_in,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
10,100,0.0005,100.0,0.0018 ± 0.0003 (n=5),0.0018 ± 0.0003 (n=5),41.8399 ± 3.6838 (n=5),0.0386 ± 0.0034 (n=5),2.8595 ± 0.4221 (n=5),2.8595 ± 0.4221 (n=5),3142.0465 ± 806.7998 (n=5),0.0027 ± 0.0007 (n=5),0.3083 ± 0.0163 (n=5),0.3083 ± 0.0163 (n=5),49.4970 ± 4.0689 (n=5),0.0457 ± 0.0038 (n=5),0.0018 ± 0.0003 (n=5),41.8399 ± 3.6838 (n=5),0.0386 ± 0.0034 (n=5),2.8595 ± 0.4221 (n=5),2.8595 ± 0.4221 (n=5),3142.0465 ± 806.7998 (n=5),0.0027 ± 0.0007 (n=5),0.3083 ± 0.0163 (n=5),0.3083 ± 0.0163 (n=5),49.4970 ± 4.0689 (n=5),0.0457 ± 0.0038 (n=5),37.7371 ± 4.6903 (n=5),0.0348 ± 0.0043 (n=5),2.1162 ± 0.3232 (n=5),2.1162 ± 0.3232 (n=5),2503.3202 ± 528.8147 (n=5),0.0021 ± 0.0005 (n=5),0.3082 ± 0.0429 (n=5),0.3082 ± 0.0429 (n=5),47.1271 ± 5.0668 (n=5),0.0435 ± 0.0047 (n=5),0.0015 ± 0.0003 (n=5),34.7986 ± 2.4594 (n=5),0.0321 ± 0.0023 (n=5),2.2103 ± 0.2945 (n=5),2.2103 ± 0.2945 (n=5),2191.7511 ± 281.0620 (n=5),0.0019 ± 0.0002 (n=5),0.3328 ± 0.0170 (n=5),0.3328 ± 0.0170 (n=5),44.1918 ± 3.1795 (n=5),0.0408 ± 0.0029 (n=5)
9,100,0.0010,100.0,0.0018 ± 0.0003 (n=5),0.0018 ± 0.0002 (n=5),40.5971 ± 2.9634 (n=5),0.0375 ± 0.0027 (n=5),2.3542 ± 0.4979 (n=5),2.3542 ± 0.4979 (n=5),2688.2256 ± 502.1008 (n=5),0.0023 ± 0.0004 (n=5),0.2708 ± 0.0260 (n=5),0.2708 ± 0.0260 (n=5),48.7875 ± 3.0194 (n=5),0.0450 ± 0.0028 (n=5),0.0018 ± 0.0002 (n=5),40.5971 ± 2.9634 (n=5),0.0375 ± 0.0027 (n=5),2.3542 ± 0.4979 (n=5),2.3542 ± 0.4979 (n=5),2688.2256 ± 502.1008 (n=5),0.0023 ± 0.0004 (n=5),0.2708 ± 0.0260 (n=5),0.2708 ± 0.0260 (n=5),48.7875 ± 3.0194 (n=5),0.0450 ± 0.0028 (n=5),37.5602 ± 5.6912 (n=5),0.0347 ± 0.0053 (n=5),2.4796 ± 0.5631 (n=5),2.4796 ± 0.5631 (n=5),2670.2017 ± 538.4720 (n=5),0.0023 ± 0.0005 (n=5),0.2917 ± 0.0540 (n=5),0.2917 ± 0.0540 (n=5),45.7515 ± 5.0806 (n=5),0.0422 ± 0.0047 (n=5),0.0013 ± 0.0002 (n=5),32.0178 ± 3.1314 (n=5),0.0296 ± 0.0029 (n=5),2.1410 ± 0.4341 (n=5),2.1410 ± 0.4341 (n=5),1915.9796 ± 256.7490 (n=5),0.0016 ± 0.0002 (n=5),0.3573 ± 0.0311 (n=5),0.3573 ± 0.0311 (n=5),40.5766 ± 3.0373 (n=5),0.0375 ± 0.0028 (n=5)
6,50,0.0010,50.0,0.0023 ± 0.0004 (n=5),0.0021 ± 0.0002 (n=5),43.7746 ± 4.0747 (n=5),0.0404 ± 0.0038 (n=5),2.4205 ± 0.4776 (n=5),2.4205 ± 0.4776 (n=5),3155.8523 ± 660.1726 (n=5),0.0027 ± 0.0006 (n=5),0.2863 ± 0.0131 (n=5),0.2863 ± 0.0131 (n=5),51.9987 ± 3.4178 (n=5),0.0480 ± 0.0032 (n=5),0.0021 ± 0.0002 (n=5),43.7746 ± 4.0747 (n=5),0.0404 ± 0.0038 (n=5),2.4205 ± 0.4776 (n=5),2.4205 ± 0.4776 (n=5),3155.8523 ± 660.1726 (n=5),0.0027 ± 0.0006 (n=5),0.2863 ± 0.0131 (n=5),0.2863 ± 0.0131 (n=5),51.9987 ± 3.4178 (n=5),0.0480 ± 0.0032 (n=5),43.1280 ± 5.1868 (n=5),0.0398 ± 0.0048 (n=5),2.3912 ± 0.4381 (n=5),2.3912 ± 0.4381 (n=5),3279.5517 ± 685.9304 (n=5),0.0028 ± 0.0006 (n=5),0.3097 ± 0.0420 (n=5),0.3097 ± 0.0420 (n=5),53.5987 ± 4.7422 (n=5),0.0495 ± 0.0044 (n=5),0.0021 ± 0.0002 (n=5),40.6806 ± 2.7326 (n=5),0.0376 ± 0.0025 (n=5),2.2724 ± 0.1810 (n=5),2.2724 ± 0.1810 (n=5),2919.7072 ± 231.6462 (n=5),0.0025 ± 0.0002 (n=5),0.3260 ± 0.0227 (n=5),0.3260 ± 0.0227 (n=5),51.2661 ± 2.3172 (n=5),0.0473 ± 0.0021 (n=5)
11,100,0.0001,100.0,0.0024 ± 0.0005 (n=5),0.0021 ± 0.0003 (n=5),46.5383 ± 3.5297 (n=5),0.0430 ± 0.0033 (n=5),3.4607 ± 0.3174 (n=5),3.4607 ± 0.3174 (n=5),3747.4177 ± 737.2359 (n=5),0.0032 ± 0.0006 (n=5),0.3046 ± 0.0098 (n=5),0.3046 ± 0.0098 (n=5),53.2307 ± 3.3386 (n=5),0.0491 ± 0.0031 (n=5),0.0021 ± 0.0003 (n=5),46.5383 ± 3.5297 (n=5),0.0430 ± 0.0033 (n=5),3.4607 ± 0.3174 (n=5),3.4607 ± 0.3174 (n=5),3747.4177 ± 737.2359 (n=5),0.0032 ± 0.0006 (n=5),0.3046 ± 0.0098 (n=5),0.3046 ± 0.0098 (n=5),53.2307 ± 3.3386 (n=5),0.0491 ± 0.0031 (n=5),47.0295 ± 7.5728 (n=5),0.0434 ± 0.0070 (n=5),3.6134 ± 0.6432 (n=5),3.6134 ± 0.6432 (n=5),3687.3140 ± 966.1767 (n=5),0.0031 ± 0.0008 (n=5),0.2617 ± 0.0594 (n=5),0.2617 ± 0.0594 (n=5),56.2205 ± 6.6670 (n=5),0.0519 ± 0.0062 (n=5),0.0022 ± 0.0004 (n=5),42.7494 ± 4.6518 (n=5),0.0395 ± 0.0043 (n=5),3.0583 ± 0.5791 (n=5),3.0583 ± 0.5791 (n=5),3097.6836 ± 509.6798 (n=5),0.0026 ± 0.0004 (n=5),0.3083 ± 0.0356 (n=5),0.3083 ± 0.0356 (n=5),52.6575 ± 4.4221 (n=5),0.0486 ± 0.0041 (n=5)
7,50,0.0005,50.0,0.0027 ± 0.0008 (n=5),0.0021 ± 0.0004 (n=5),44.6209 ± 4.6139 (n=5),0.0412 ± 0.0043 (n=5),2.4459 ± 0.2410 (n=5),2.4459 ± 0.2410 (n=5),3390.8361 ± 867.9887 (n=5),0.0029 ± 0.0007 (n=5),0.2978 ± 0.0100 (n=5),0.2978 ± 0.0100 (n=5),53.0801 ± 4.2924 (n=5),0.0490 ± 0.0040 (n=5),0.0021 ± 0.0004 (n=5),44.6209 ± 4.6139 (n=5),0.0412 ± 0.0043 (n=5),2.4459 ± 0.2410 (n=5),2.4459 ± 0.2410 (n=5),3390.8361 ± 867.9887 (n=5),0.0029 ± 0.0007 (n=5),0.2978 ± 0.0100 (n=5),0.2978 ± 0.0100 (n=5),53.0801 ± 4.2924 (n=5),0.0490 ± 0.0040 (n=5),47.2361 ± 9.3018 (n=5),0.0436 ± 0.0086 (n=5),3.0259 ± 0.7097 (n=5),3.0259 ± 0.7097 (n=5),3877.2660 ± 1327.3941 (n=5),0.0033 ± 0.0011 (n=5),0.2785 ± 0.0693 (n=5),0.2785 ± 0.0693 (n=5),57.5622 ± 8.7367 (n=5),0.0531 ± 0.0081 (n=5),0.0021 ± 0.0002 (n=5),41.0568 ± 2.5566 (n=5),0.0379 ± 0.0024 (n=5),2.4661 ± 0.1842 (n=5),2.4661 ± 0.1842 (n=5),2980.2702 ± 268.3994 (n=5),0.0025 ± 0.0002 (n=5),0.3302 ± 0.0194 (n=5),0.3302 ± 0.0194 (n=5),51.7927 ± 2.5802 (n=5),0.0478 ± 0.0024 (n=5)
4,10,0.0005,10.0,0.0028 ± 0.0002 (n=5),0.0026 ± 0.0004 (n=5),46.6721 ± 5.3638 (n=5),0.0431 ± 0.0050 (n=5),2.5458 ± 0.3892 (n=5),2.5458 ± 0.3892 (n=5),3807.6111 ± 913.0379 (n=5),0.0032 ± 0.0008 (n=5),0.2996 ± 0.0131 (n=5),0.2996 ± 0.0131 (n=5),58.0651 ± 4.7019 (n=5),0.0536 ± 0.0043 (n=5),0.0026 ± 0.0004 (n=5),46.6721 ± 5.3638 (n=5),0.0431 ± 0.0050 (n=5),2.5458 ± 0.3892 (n=5),2.5458 ± 0.3892 (n=5),3807.6111 ± 913.0379 (n=5),0.0032 ± 0.0008 (n=5),0.2996 ± 0.0131 (n=5),0.2996 ± 0.0131 (n=5),58.0651 ± 4.7019 (n=5),0.0536 ± 0.0043 (n=5),48.4285 ± 2.5117 (n=5),0.0447 ± 0.0023 (n=5),2.2874 ± 0.5375 (n=5),2.2874 ± 0.5375 (n=5),3976.8660 ± 400.3725 (n=5),0.0034 ± 0.0003 (n=5),0.3064 ± 0.0285 (n=5),0.3064 ± 0.0285 (n=5),59.9596 ± 2.3593 (n=5),0.0554 ± 0.0022 (n=5),0.0027 ± 0.0003 (n=5),46.5177 ± 2.9409 (n=5),0.0429 ± 0.0027 (n=5),2.1842 ± 0.1674 (n=5),2.1842 ± 0.1674 (n=5),3720.4938 ± 382.0906 (n=5),0.0032 ± 0.0003 (n=5),0.3221 ± 0.0237 (n=5),0.3221 ± 0.0237 (n=5),58.3660 ± 2.9106 (n=5),0.0539 ± 0.0027 (n=5)
3,10,0.0010,10.0,0.0029 ± 0.0002 (n=5),0.0025 ± 0.0004 (n=5),45.5637 ± 4.8539 (n=5),0.0421 ± 0.0045 (n=5),2.2725 ± 0.2293 (n=5),2.2725 ± 0.2293 (n=5),3566.7398 ± 659.0285 (n=5),0.0030 ± 0.0006 (n=5),0.3010 ± 0.0238 (n=5),0.3010 ± 0.0238 (n=5),56.5922 ± 4.5790 (n=5),0.0522 ± 0.0042 (n=5),0.0025 ± 0.0004 (n=5),45.5637 ± 4.8539 (n=5),0.0421 ± 0.0045 (n=5),2.2725 ± 0.2293 (n=5),2.2725 ± 0.2293 (n=5),3566.7398 ± 659.0285 (n=5),0.0030 ± 0.0006 (n=5),0.3010 ± 0.0238 (n=5),0.3010 ± 0.0238 (n=5),56.5922 ± 4.5790 (n=5),0.0522 ± 0.0042 (n=5),49.2864 ± 3.0077 (n=5),0.0455 ± 0.0028 (n=5),2.2154 ± 0.5692 (n=5),2.2154 ± 0.5692 (n=5),4170.5165 ± 605.8980 (n=5),0.0036 ± 0.0005 (n=5),0.2989 ± 0.0272 (n=5),0.2989 ± 0.0272 (n=5),60.6122 ± 3.0327 (n=5),0.0560 ± 0.0028 (n=5),0.0027 ± 0.0003 (n=5),46.0342 ± 3.0340 (n=5),0.0425 ± 0.0028 (n=5),2.1279 ± 0.0809 (n=5),2.1279 ± 0.0809 (n=5),3652.7220 ± 363.0030 (n=5),0.0031 ± 0.0003 (n=5),0.3273 ± 0.0222 (n=5),0.3273 ± 0.0222 (n=5),57.8500 ± 3.1490 (n=5),0.0534 ± 0.0029 (n=5)
5,10,0.0001,10.0,0.0038 ± 0.0004 (n=5),0.0038 ± 0.0007 (n=5),59.8958 ± 5.6195 (n=5),0.0553 ± 0.0052 (n=5),3.2999 ± 0.5148 (n=5),3.2999 ± 0.5148 (n=5),5979.6520 ± 1147.4008 (n=5),0.0051 ± 0.0010 (n=5),0.2662 ± 0.0111 (n=5),0.2662 ± 0.0111 (n=5),70.9022 ± 5.7897 (n=5),0.0655 ± 0.0053 (n=5),0.0038 ± 0.0007 (n=5),59.8958 ± 5.6195 (n=5),0.0553 ± 0.0052 (n=5),3.2999 ± 0.5148 (n=5),3.2999 ± 0.5148 (n=5),5979.6520 ± 1147.4008 (n=5),0.0051 ± 0.0010 (n=5),0.2662 ± 0.0111 (n=5),0.2662 ± 0.0111 (n=5),70.9022 ± 5.7897 (n=5),0.0655 ± 0.0053 (n=5),57.2109 ± 3.6887 (n=5),0.0528 ± 0.0034 (n=5),3.1048 ± 0.4004 (n=5),3.1048 ± 0.4004 (n=5),5295.0675 ± 629.6617 (n=5),0.0045 ± 0.0005 (n=5),0.2797 ± 0.0083 (n=5),0.2797 ± 0.0083 (n=5),69.7233 ± 3.8757 (n=5),0.0644 ± 0.0036 (n=5),0.0037 ± 0.0004 (n=5),55.9433 ± 3.5292 (n=5),0.0516 ± 0.0033 (n=5),2.7020 ± 0.3300 (n=5),2.7020 ± 0.3300 (n=5),5043.3400 ± 572.2990 (n=5),0.0043 ± 0.0005 (n=5),0.2858 ± 0.0098 (n=5),0.2858 ± 0.0098 (n=5),68.6605 ± 3.7821 (n=5),0.0634 ± 0.0035 (n=5)
8,50,0.0001,50.0,0.0053 ± 0.0034 (n=5),0.0050 ± 0.0032 (n=5),66.2318 ± 17.4330 (n=5),0.0611 ± 0.0161 (n=5),5.0099 ± 2.1357 (n=5),5.0099 ± 2.1357 (n=5),7440.5992 ± 3115.1071 (n=5),0.0063 ± 0.0027 (n=5),0.2460 ± 0.0554 (n=5),0.2460 ± 0.0554 (n=5),76.0534 ± 21.0503 (n=5),0.0702 ± 0.0194 (n=5),0.0050 ± 0.0032 (n=5),66.2318 ± 17.4330 (n=5),0.0611 ± 0.0161 (n=5),5.0099 ± 2.1357 (n=5),5.0099 ± 2.1357 (n=5),7440.5992 ± 3115.1071 (n=5),0.0063 ± 0.0027 (n=5),0.2460 ± 0.0554 (n=5),0.2460 ± 0.0554 (n=5),76.0534 ± 21.0503 (n=5),0.0702 ± 0.0194 (n=5),66.7384 ± 18.0485 (n=5),0.0616 ± 0.0167 (n=5),4.9687 ± 1.6019 (n=5),4.9687 ± 1.6019 (n=5),7076.2084 ± 3395.5314 (n=5),0.0060 ± 0.0029 (n=5),0.2337 ± 0.0357 (n=5),0.2337 ± 0.0357 (n=5),78.2550 ± 20.8409 (n=5),0.0722 ± 0.0192 (n=5),0.0051 ± 0.0035 (n=5),64.3667 ± 19.7778 (n=5),0.0594 ± 0.0183 (n=5),4.6761 ± 1.6771 (n=5),4.6761 ± 1.6771 (n=5),6688.4118 ± 3646.6528 (n=5),0.0057 ± 0.0031 (n=5),0.2520 ± 0.0466 (n=5),0.2520 ± 0.0466 (n=5),76.2060 ± 22.5070 (n=5),0.0704 ± 0.0208 (n=5)
0,1,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,1,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,1,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (exponential) on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.seq_len,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
9,100,0.0010,100.0,0.0508 ± 0.0457 (n=5),0.0260 ± 0.0000 (n=5),130.1766 ± 0.0116 (n=5),0.1202 ± 0.0000 (n=5),0.9991 ± 0.0005 (n=5),0.9991 ± 0.0005 (n=5),26790.7039 ± 3.2606 (n=5),0.0228 ± 0.0000 (n=5),0.0313 ± 0.0001 (n=5),0.0313 ± 0.0001 (n=5),160.4152 ± 0.0102 (n=5),0.1481 ± 0.0000 (n=5),0.0260 ± 0.0000 (n=5),130.1766 ± 0.0116 (n=5),0.1202 ± 0.0000 (n=5),0.9991 ± 0.0005 (n=5),0.9991 ± 0.0005 (n=5),26790.7039 ± 3.2606 (n=5),0.0228 ± 0.0000 (n=5),0.0313 ± 0.0001 (n=5),0.0313 ± 0.0001 (n=5),160.4152 ± 0.0102 (n=5),0.1481 ± 0.0000 (n=5),149.6378 ± 1.5809 (n=5),0.1381 ± 0.0015 (n=5),1.0014 ± 0.0039 (n=5),1.0014 ± 0.0039 (n=5),51613.6133 ± 39217.9905 (n=5),0.0440 ± 0.0334 (n=5),0.0313 ± 0.0000 (n=5),0.0313 ± 0.0000 (n=5),202.2958 ± 42.9449 (n=5),0.1868 ± 0.0396 (n=5),0.0496 ± 0.0430 (n=5),149.6019 ± 1.5401 (n=5),0.1381 ± 0.0014 (n=5),1.0009 ± 0.0041 (n=5),1.0009 ± 0.0041 (n=5),50561.5250 ± 36885.6546 (n=5),0.0431 ± 0.0314 (n=5),0.0314 ± 0.0002 (n=5),0.0314 ± 0.0002 (n=5),201.5641 ± 41.3645 (n=5),0.1861 ± 0.0382 (n=5)
1,1,0.0005,1.0,182408325.0762 ± 407817619.4597 (n=5),0.2860 ± 0.6110 (n=5),333.0153 ± 525.8709 (n=5),0.3074 ± 0.4855 (n=5),21.2090 ± 31.7887 (n=5),21.2090 ± 31.7887 (n=5),343675.8537 ± 736490.5933 (n=5),0.2929 ± 0.6277 (n=5),0.1446 ± 0.0810 (n=5),0.1446 ± 0.0810 (n=5),352.4982 ± 522.4709 (n=5),0.3254 ± 0.4823 (n=5),0.2860 ± 0.6110 (n=5),333.0153 ± 525.8709 (n=5),0.3074 ± 0.4855 (n=5),21.2090 ± 31.7887 (n=5),21.2090 ± 31.7887 (n=5),343675.8537 ± 736490.5933 (n=5),0.2929 ± 0.6277 (n=5),0.1446 ± 0.0810 (n=5),0.1446 ± 0.0810 (n=5),352.4982 ± 522.4709 (n=5),0.3254 ± 0.4823 (n=5),248617.3397 ± 548158.0934 (n=5),229.5141 ± 506.0388 (n=5),566.4518 ± 1230.8608 (n=5),566.4518 ± 1230.8608 (n=5),161038177763046.2188 ± 360039522693110.7500 (n=5),137241261.2307 ± 306835800.5163 (n=5),0.1759 ± 0.0454 (n=5),0.1759 ± 0.0454 (n=5),2342287.9687 ± 5166465.3750 (n=5),2162.3112 ± 4769.4843 (n=5),154380559.8757 ± 345145637.2831 (n=5),229106.0569 ± 503951.8351 (n=5),211.5020 ± 465.2292 (n=5),532.7619 ± 1126.1966 (n=5),532.7619 ± 1126.1967 (n=5),136294023917179.7500 ± 304709917770815.3750 (n=5),116153592.5973 ± 259682344.3309 (n=5),0.1550 ± 0.0872 (n=5),0.1550 ± 0.0872 (n=5),2156908.2401 ± 4751826.9234 (n=5),1991.1757 ± 4386.7061 (n=5)
10,100,0.0005,100.0,224245255.4516 ± 498581796.3531 (n=5),0.0162 ± 0.0124 (n=5),97.9239 ± 40.2739 (n=5),0.0904 ± 0.0372 (n=5),1.9277 ± 1.3001 (n=5),1.9277 ± 1.3001 (n=5),17565.8543 ± 11515.2299 (n=5),0.0150 ± 0.0098 (n=5),0.1313 ± 0.1181 (n=5),0.1313 ± 0.1181 (n=5),118.8662 ± 53.3954 (n=5),0.1097 ± 0.0493 (n=5),0.0162 ± 0.0124 (n=5),97.9239 ± 40.2739 (n=5),0.0904 ± 0.0372 (n=5),1.9277 ± 1.3001 (n=5),1.9277 ± 1.3001 (n=5),17565.8543 ± 11515.2299 (n=5),0.0150 ± 0.0098 (n=5),0.1313 ± 0.1181 (n=5),0.1313 ± 0.1181 (n=5),118.8662 ± 53.3954 (n=5),0.1097 ± 0.0493 (n=5),82990.5145 ± 164636.9002 (n=5),76.6137 ± 151.9866 (n=5),213.8834 ± 417.9298 (n=5),213.8834 ± 417.9299 (n=5),192234932576804.0312 ± 427410772481913.8750 (n=5),163828053.4644 ± 364251564.8174 (n=5),0.1223 ± 0.0961 (n=5),0.1223 ± 0.0961 (n=5),2751647.9846 ± 5530417.9627 (n=5),2540.2172 ± 5105.4724 (n=5),22286725.5801 ± 49752442.0391 (n=5),25247.0317 ± 52501.5797 (n=5),23.3071 ± 48.4675 (n=5),65.9430 ± 133.0010 (n=5),65.9430 ± 133.0010 (n=5),19105367189884.8750 ± 42650440953997.3281 (n=5),16282132.0408 ± 36347907.0729 (n=5),0.1228 ± 0.1089 (n=5),0.1228 ± 0.1089 (n=5),836821.6082 ± 1762176.2760 (n=5),772.5220 ± 1626.7743 (n=5)
0,1,0.0010,1.0,248830211.9378 ± 556401257.7421 (n=5),0.1922 ± 0.4028 (n=5),283.9621 ± 420.4751 (n=5),0.2621 ± 0.3882 (n=5),18.0668 ± 25.6628 (n=5),18.0668 ± 25.6628 (n=5),231864.0033 ± 487597.0665 (n=5),0.1976 ± 0.4155 (n=5),0.1459 ± 0.0817 (n=5),0.1459 ± 0.0817 (n=5),303.0363 ± 416.9773 (n=5),0.2798 ± 0.3849 (n=5),0.1922 ± 0.4028 (n=5),283.9621 ± 420.4751 (n=5),0.2621 ± 0.3882 (n=5),18.0668 ± 25.6628 (n=5),18.0668 ± 25.6628 (n=5),231864.0033 ± 487597.0665 (n=5),0.1976 ± 0.4155 (n=5),0.1459 ± 0.0817 (n=5),0.1459 ± 0.0817 (n=5),303.0363 ± 416.9773 (n=5),0.2798 ± 0.3849 (n=5),287272.1790 ± 642085.1442 (n=5),265.1988 ± 592.7486 (n=5),651.8517 ± 1442.6800 (n=5),651.8516 ± 1442.6799 (n=5),219678386755408.5625 ± 491215796247429.9375 (n=5),187216092.5652 ± 418627901.1697 (n=5),0.1979 ± 0.0166 (n=5),0.1979 ± 0.0166 (n=5),2706492.7678 ± 6050676.0196 (n=5),2498.5314 ± 5585.7545 (n=5),182636571.2667 ± 408387783.8712 (n=5),246207.8278 ± 549774.1171 (n=5),227.2897 ± 507.5306 (n=5),568.6223 ± 1230.5601 (n=5),568.6223 ± 1230.5601 (n=5),161239663913360.4375 ± 360542844900007.1875 (n=5),137412967.7048 ± 307264733.1309 (n=5),0.1603 ± 0.0903 (n=5),0.1603 ± 0.0903 (n=5),2318810.5948 ± 5183736.3650 (n=5),2140.6378 ± 4785.4284 (n=5)
7,50,0.0005,50.0,1302329339.0206 ± 2911706272.5208 (n=5),0.0081 ± 0.0092 (n=5),75.7096 ± 26.0103 (n=5),0.0699 ± 0.0240 (n=5),2.8150 ± 0.8695 (n=5),2.8150 ± 0.8695 (n=5),10750.2743 ± 8346.6172 (n=5),0.0092 ± 0.0071 (n=5),0.2138 ± 0.0661 (n=5),0.2138 ± 0.0661 (n=5),89.2384 ± 38.2357 (n=5),0.0824 ± 0.0353 (n=5),0.0081 ± 0.0092 (n=5),75.7096 ± 26.0103 (n=5),0.0699 ± 0.0240 (n=5),2.8150 ± 0.8695 (n=5),2.8150 ± 0.8695 (n=5),10750.2743 ± 8346.6172 (n=5),0.0092 ± 0.0071 (n=5),0.2138 ± 0.0661 (n=5),0.2138 ± 0.0661 (n=5),89.2384 ± 38.2357 (n=5),0.0824 ± 0.0353 (n=5),184661.7378 ± 404859.2419 (n=5),170.4727 ± 373.7506 (n=5),452.0227 ± 983.2495 (n=5),452.0227 ± 983.2495 (n=5),1133960962348893.5000 ± 2535273642311850.5000 ...,966393432.2910 ± 2160631519.3674 (n=5),0.2264 ± 0.0100 (n=5),0.2264 ± 0.0100 (n=5),6225764.2378 ± 13703745.3559 (n=5),5747.3891 ± 12650.7774 (n=5),705603044.2689 ± 1577759276.6757 (n=5),137497.3299 ± 305748.3386 (n=5),126.9323 ± 282.2552 (n=5),336.5818 ± 742.8643 (n=5),336.5818 ± 742.8643 (n=5),614381016199837.6250 ± 1373782830996361.5000 (...,523592685.7798 ± 1170776152.2470 (n=5),0.2025 ± 0.0616 (n=5),0.2025 ± 0.0616 (n=5),4541177.5432 ± 10110334.6877 (n=5),4192.2421 ± 9333.4758 (n=5)
11,100,0.0001,100.0,23605641949.8018 ± 51454091215.3192 (n=5),0.0042 ± 0.0009 (n=5),65.8904 ± 6.0857 (n=5),0.0608 ± 0.0056 (n=5),4.1315 ± 0.7564 (n=5),4.1315 ± 0.7564 (n=5),7079.3794 ± 929.4457 (n=5),0.0060 ± 0.0008 (n=5),0.2144 ± 0.0295 (n=5),0.2144 ± 0.0295 (n=5),74.8168 ± 7.9857 (n=5),0.0691 ± 0.0074 (n=5),0.0042 ± 0.0009 (n=5),65.8904 ± 6.0857 (n=5),0.0608 ± 0.0056 (n=5),4.1315 ± 0.7564 (n=5),4.1315 ± 0.7564 (n=5),7079.3794 ± 929.4457 (n=5),0.0060 ± 0.0008 (n=5),0.2144 ± 0.0295 (n=5),0.2144 ± 0.0295 (n=5),74.8168 ± 7.9857 (n=5),0.0691 ± 0.0074 (n=5),915518.5360 ± 1660193.5668 (n=5),845.1719 ± 1532.6275 (n=5),2362.8932 ± 4221.5488 (n=5),2362.8932 ± 4221.5488 (n=5),20236014768097592.0000 ± 44109190176120872.000...,17245698631.0020 ± 37591087274.3434 (n=5),0.2300 ± 0.0228 (n=5),0.2300 ± 0.0228 (n=5),29562126.4095 ± 55887766.2917 (n=5),27290.6318 ± 51593.4619 (n=5),23605641949.8018 ± 51454091215.3192 (n=5),915518.2764 ± 1660193.7457 (n=5),845.1716 ± 1532.6277 (n=5),2362.8788 ± 4221.5589 (n=5),2362.8788 ± 4221.5589 (n=5),20236014768097544.0000 ± 44109190176120888.000...,17245698631.0020 ± 37591087274.3434 (n=5),0.2319 ± 0.0203 (n=5),0.2319 ± 0.0203 (n=5),29562126.1721 ± 55887766.4487 (n=5),27290.6316 ± 51593.4620 (n=5)
8,50,0.0001,50.0,250221542878.2610 ± 559512353359.2537 (n=5),0.0046 ± 0.0005 (n=5),68.9213 ± 3.1338 (n=5),0.0636 ± 0.0029 (n=5),3.5527 ± 0.4856 (n=5),3.5527 ± 0.4856 (n=5),7926.0566 ± 284.5815 (n=5),0.0068 ± 0.0002 (n=5),0.2252 ± 0.0164 (n=5),0.2252 ± 0.0164 (n=5),77.8655 ± 4.4500 (n=5),0.0719 ± 0.0041 (n=5),0.0046 ± 0.0005 (n=5),68.9213 ± 3.1338 (n=5),0.0636 ± 0.0029 (n=5),3.5527 ± 0.4856 (n=5),3.5527 ± 0.4856 (n=5),7926.0566 ± 284.5815 (n=5),0.0068 ± 0.0002 (n=5),0.2252 ± 0.0164 (n=5),0.2252 ± 0.0164 (n=5),77.8655 ± 4.4500 (n=5),0.0719 ± 0.0041 (n=5),3248452.3265 ± 7261331.5414 (n=5),2998.8481 ± 6703.3860 (n=5),7892.9445 ± 17635.9408 (n=5),7892.9445 ± 17635.9408 (n=5),217872319065051808.0000 ± 487177293248619968.0...,185676877340.8834 ± 415186100326.8553 (n=5),0.2349 ± 0.0163 (n=5),0.2349 ± 0.0163 (n=5),85245788.7990 ± 190542708.0030 (n=5),78695.6710 ± 175901.7831 (n=5),250221541653.8043 ± 559512354043.7458 (n=5),3248429.5485 ± 7261344.2698 (n=5),2998.8270 ± 6703.3978 (n=5),7892.9660 ± 17635.9288 (n=5),7892.9660 ± 17635.9288 (n=5),217872317998897152.0000 ± 487177293844618496.0...,185676876432.2766 ± 415186100834.7819 (n=5),0.2364 ± 0.0176 (n=5),0.2364 ± 0.0176 (n=5),85244206.9869 ± 190543592.0064 (n=5),78694.2107 ± 175902.5992 (n=5)
2,1,0.0001,1.0,1062519837130242.0000 ± 2375864151405445.0000 ...,0.4006 ± 0.8609 (n=5),389.5036 ± 626.5227 (n=5),0.3596 ± 0.5784 (n=5),25.7068 ± 37.2813 (n=5),25.7068 ± 37.2813 (n=5),479711.3762 ± 1034250.2452 (n=5),0.4088 ± 0.8814 (n=5),0.1330 ± 0.0746 (n=5),0.1330 ± 0.0746 (n=5),408.9279 ± 623.7702 (n=5),0.3775 ± 0.5758 (n=5),0.4006 ± 0.8609 (n=5),389.5036 ± 626.5227 (n=5),0.3596 ± 0.5784 (n=5),25.7068 ± 37.2813 (n=5),25.7068 ± 37.2813 (n=5),479711.3762 ± 1034250.2452 (n=5),0.4088 ± 0.8814 (n=5),0.1330 ± 0.0746 (n=5),0.1330 ± 0.0746 (n=5),408.9279 ± 623.7702 (n=5),0.3775 ± 0.5758 (n=5),531969159.9887 ± 1188016326.7691 (n=5),491093.7593 ± 1096731.6301 (n=5),1192632.4856 ± 2663394.1543 (n=5),1192632.4856 ± 2663394.1543 (n=5),938039603019123654656.0000 ± 20975181709838036...,799423830096641.5000 ± 1787564197234817.7500 (...,0.1402 ± 0.0785 (n=5),0.1402 ± 0.0785 (n=5),5596836933.6806 ± 12500768191.2136 (n=5),5166787.2368 ± 11540234.2964 (n=5),1062519837130241.3750 ± 2375864151405445.0000 ...,531969307.4040 ± 1188016244.2574 (n=5),491093.8954 ± 1096731.5539 (n=5),1192640.0955 ± 2663389.8950 (n=5),1192640.0955 ± 2663389.8950 (n=5),938039603019123392512.0000 ± 20975181709838039...,799423830096641.2500 ± 1787564197234818.2500 (...,0.1396 ± 0.0782 (n=5),0.1396 ± 0.0782 (n=5),5596837008.7259 ± 12500768149.2147 (n=5),5166787.3060 ± 11540234.2576 (n=5)
6,50,0.0010,50.0,5353271426991647744.0000 ± 1197027881275661107...,0.0254 ± 0.0121 (n=5),127.2954 ± 35.8195 (n=5),0.1175 ± 0.0331 (n=5),1.3672 ± 0.8747 (n=5),1.3672 ± 0.8747 (n=5),27490.3556 ± 11472.2341 (n=5),0.0234 ± 0.0098 (n=5),0.0834 ± 0.0953 (n=5),0.0834 ± 0.0953 (n=5),156.5347 ± 47.8689 (n=5),0.1445 ± 0.0442 (n=5),0.0254 ± 0.0121 (n=5),127.2954 ± 35.8195 (n=5),0.1175 ± 0.0331 (n=5),1.3672 ± 0.8747 (n=5),1.3672 ± 0.8747 (n=5),27490.3556 ± 11472.2341 (n=5),0.0234 ± 0.0098 (n=5),0.0834 ± 0.0953 (n=5),0.0834 ± 0.0953 (n=5),156.5347 ± 47.8689 (n=5),0.1445 ± 0.0442 (n=5),16220955876.8309 ± 36271138180.9829 (n=5),14974572.0066 ± 33484140.7977 (n=5),39389625.0750 ± 88077818.1334 (n=5),39389625.0750 ± 88077818.1334 (n=5),4661187394981837196492800.0000 ± 1042273187104...,3972394773667399168.0000 ± 8882544747382214656...,0.2156 ± 0.0580 (n=5),0.2156 ± 0.0580 (n=5),394173956652.5521 ± 881399091877.4347 (n=5),363886403.7400 ± 813674116.1865 (n=5),3287447408074156032.0000 ± 7350955876907488256...,12618431526.6374 ± 28215657389.0264 (n=5),11648857.9841 ± 26047626.0587 (n=5),30642274.6656 ± 68518174.8541 (n=5),30642277.8656 ± 68518182.0095 (n=5),2862438232240403920191488.0000 ± 6400606468682...,2439450164663376384.0000 ± 5454776395909018624...,0.0768 ± 0.0847 (n=5),0.0768 ± 0.0847 (n=5),308892696824.6571 ± 690704682482.9664 (n=5),285157989.6803 ± 637632293.4931 (n=5)
4,10,0.0005,10.0,inf ± 0.0000 (n=5),0.0478 ± 0.0938 (n=5),157.2292 ± 182.6908 (n=5),0.1451 ± 0.1687 (n=5),10.1958 ± 14.8149 (n=5),10.1958 ± 14.8149 (n=5),59489.0837 ± 112199.0523 (n=5),0.0507 ± 0.0956 (n=5),0.1737 ± 0.0965 (n=5),0.1737 ± 0.0965 (n=5),171.0835 ± 186.1739 (n=5),0.1579 ± 0.1719 (n=5),0.0478 ± 0.0938 (n=5),157.2292 ± 182.6908 (n=5),0.1451 ± 0.1687 (n=5),10.1958 ± 14.8149 (n=5),10.1958 ± 14.8149 (n=5),59489.0837 ± 112199.0523 (n=5),0.0507 ± 0.0956 (n=5),0.1737 ± 0.0965 (n=5),0.1737 ± 0.0965 (n=5),171.0835 ± 186.1739 (n=5),0.1579 ± 0.1719 (n=5),30944451182769627136.0000 ± 691938963710966579...,28566741454736588.0000 ± 63877175788452240.000...,68936561563009024.0000 ± 154146837789987328.00...,68936561563009024.0000 ± 154146837789987328.00...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.1994 ± 0.1106 (n=5),0.1994 ± 0.1106 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),30944451182769627136.0000 ± 691938963710966579...,28566741454736588.0000 ± 63877175788452240.000...,68936561563009024.0000 ± 154146837789987328.00...,68936561563009024.0000 ± 154146837789987328.00...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.1999 ± 0.1109 (n=5),0.1999 ± 0.1109 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5)
3,10,0.0010,10.0,inf ± 0.0000 (n=5),0.0104 ± 0.0100 (n=5),92.6828 ± 37.4084 (n=5),0.0856 ± 0.0345 (n=5),5.9095 ± 5.1412 (n=5),5.9095 ± 5.1412 (n=5),14418.5088 ± 11178.3075 (n=5),0.0123 ± 0.0095 (n=5),0.1967 ± 0.0417 (n=5),0.1967 ± 0.0417 (n=5),107.0424 ± 41.7958 (n=5),0.0988 ± 0.0386 (n=5),0.0104 ± 0.0100 (n=5),92.6828 ± 37.4084 (n=5),0.0856 ± 0.0345 (n=5),5.9095 ± 5.1412 (n=5),5.9095 ± 5.1412 (n=5),14418.5088 ± 11178.3075 (n=5),0.0123 ± 0.0095 (n=5),0.1967 ± 0.0417 (n=5),0.1967 ± 0.0417 (n=5),107.0424 ± 41.7958 (n=5),0.0988 ± 0.0386 (n=5),1128422406419110656.0000 ± 2523229208086906368...,1041716507731598.0000 ± 2329348924571428.0000 ...,2513846076335818.0000 ± 5621130711657736.0000 ...,2513846076335818.0000 ± 5621130711657736.0000 ...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.2282 ± 0.0448 (n=5),0.2282 ± 0.0448 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),1128422406419069568.0000 ± 2523229208086929408...,1041716507731560.2500 ± 2329348924571449.0000 ...,2513846076335725.0000 ± 5621130711657788.0000 ...,2513846076335725.0000 ± 5621130711657788.0000 ...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.2279 ± 0.0447 (n=5),0.2279 ± 0.0447 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5)
5,10,0.0001,10.0,inf ± 0.0000 (n=5),0.4897 ± 1.0759 (n=5),400.6903 ± 702.1925 (n=5),0.3699 ± 0.6482 (n=5),27.4345 ± 48.9743 (n=5),27.4345 ± 48.9743 (n=5),574103.9705 ± 1258574.9012 (n=5),0.4893 ± 1.0726 (n=5),0.1546 ± 0.0865 (n=5),0.1546 ± 0.0865 (n=5),417.8361 ± 703.2748 (n=5),0.3857 ± 0.6492 (n=5),0.4897 ± 1.0759 (n=5),400.6903 ± 702.1925 (n=5),0.3699 ± 0.6482 (n=5),27.4345 ± 48.9743 (n=5),27.4345 ± 48.9743 (n=5),574103.9705 ± 1258574.9012 (n=5),0.4893 ± 1.0726 (n=5),0.1546 ± 0.0865 (n=5),0.1546 ± 0.0865 (n=5),417.8361 ± 703.2748 (n=5),0.3857 ± 0.6492 (n=5),2254115114253680377856.0000 ± 5040354624580930...,2080913496593978112.0000 ± 4653064033680909312...,5021609901736698880.0000 ± 1122866109676929024...,5021609901736698880.0000 ± 1122866109676929024...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.1854 ± 0.1039 (n=5),0.1854 ± 0.1039 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),2254115114253680377856.0000 ± 5040354624580930...,2080913496593978112.0000 ± 4653064033680909312...,5021609901736698880.0000 ± 1122866109676929024...,5021609901736698880.0000 ± 1122866109676929024...,inf ± 0.0000 (n=5),inf ± 0.0000 (n=5),0.1854 ± 0.1039 (n=5),0.1854 ± 0.1039 (n=5),inf ± 0.0000 (n=5),inf ± 0.0000 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,task_definition.stride_train,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
0,1,1,-,1.0000 ± 0.0000 (n=1),41.7476 ± 0.0000 (n=1),0.0385 ± 0.0000 (n=1),1.4111 ± 0.0000 (n=1),1.4111 ± 0.0000 (n=1),2862.3887 ± 0.0000 (n=1),0.0024 ± 0.0000 (n=1),0.2363 ± 0.0000 (n=1),0.2363 ± 0.0000 (n=1),52.6333 ± 0.0000 (n=1),0.0486 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,5,1,-,1.0000 ± 0.0000 (n=1),44.0298 ± 0.0000 (n=1),0.0406 ± 0.0000 (n=1),1.6681 ± 0.0000 (n=1),1.6681 ± 0.0000 (n=1),3142.6038 ± 0.0000 (n=1),0.0027 ± 0.0000 (n=1),0.2403 ± 0.0000 (n=1),0.2403 ± 0.0000 (n=1),53.9445 ± 0.0000 (n=1),0.0498 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,10,5,-,1.0000 ± 0.0000 (n=1),41.8255 ± 0.0000 (n=1),0.0386 ± 0.0000 (n=1),1.8267 ± 0.0000 (n=1),1.8267 ± 0.0000 (n=1),2861.1985 ± 0.0000 (n=1),0.0024 ± 0.0000 (n=1),0.2597 ± 0.0000 (n=1),0.2597 ± 0.0000 (n=1),51.0339 ± 0.0000 (n=1),0.0471 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3,20,5,-,1.0000 ± 0.0000 (n=1),43.2267 ± 0.0000 (n=1),0.0399 ± 0.0000 (n=1),1.8971 ± 0.0000 (n=1),1.8971 ± 0.0000 (n=1),2974.7131 ± 0.0000 (n=1),0.0025 ± 0.0000 (n=1),0.2367 ± 0.0000 (n=1),0.2367 ± 0.0000 (n=1),52.4762 ± 0.0000 (n=1),0.0484 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,50,50,-,1.0000 ± 0.0000 (n=1),66.1928 ± 0.0000 (n=1),0.0611 ± 0.0000 (n=1),2.8300 ± 0.0000 (n=1),2.8300 ± 0.0000 (n=1),7690.1328 ± 0.0000 (n=1),0.0066 ± 0.0000 (n=1),0.2071 ± 0.0000 (n=1),0.2071 ± 0.0000 (n=1),76.7866 ± 0.0000 (n=1),0.0709 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
5,100,100,-,1.0000 ± 0.0000 (n=1),64.2354 ± 0.0000 (n=1),0.0593 ± 0.0000 (n=1),4.1362 ± 0.0000 (n=1),4.1362 ± 0.0000 (n=1),8516.6865 ± 0.0000 (n=1),0.0073 ± 0.0000 (n=1),0.2274 ± 0.0000 (n=1),0.2274 ± 0.0000 (n=1),71.7181 ± 0.0000 (n=1),0.0662 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> baselines.tide_model.TiDE_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.ts_in,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
10,100,0.0005,100.0,0.0019 ± 0.0006 (n=5),0.0014 ± 0.0002 (n=5),36.3731 ± 1.1665 (n=5),0.0336 ± 0.0011 (n=5),2.6982 ± 0.4399 (n=5),2.6982 ± 0.4399 (n=5),2174.5901 ± 157.9304 (n=5),0.0019 ± 0.0001 (n=5),0.2949 ± 0.0297 (n=5),0.2949 ± 0.0297 (n=5),42.7440 ± 1.6112 (n=5),0.0395 ± 0.0015 (n=5),0.0014 ± 0.0002 (n=5),36.3731 ± 1.1665 (n=5),0.0336 ± 0.0011 (n=5),2.6982 ± 0.4399 (n=5),2.6982 ± 0.4399 (n=5),2174.5901 ± 157.9304 (n=5),0.0019 ± 0.0001 (n=5),0.2949 ± 0.0297 (n=5),0.2949 ± 0.0297 (n=5),42.7440 ± 1.6112 (n=5),0.0395 ± 0.0015 (n=5),39.3759 ± 5.0496 (n=5),0.0364 ± 0.0047 (n=5),2.3988 ± 0.2799 (n=5),2.3988 ± 0.2799 (n=5),2648.1651 ± 759.5156 (n=5),0.0023 ± 0.0006 (n=5),0.3068 ± 0.0365 (n=5),0.3068 ± 0.0365 (n=5),47.9501 ± 6.5718 (n=5),0.0443 ± 0.0061 (n=5),0.0014 ± 0.0001 (n=5),34.7803 ± 1.7461 (n=5),0.0321 ± 0.0016 (n=5),2.1828 ± 0.1450 (n=5),2.1828 ± 0.1450 (n=5),2101.1207 ± 189.7643 (n=5),0.0018 ± 0.0002 (n=5),0.3535 ± 0.0223 (n=5),0.3535 ± 0.0223 (n=5),42.3321 ± 1.9132 (n=5),0.0391 ± 0.0018 (n=5)
9,100,0.0010,100.0,0.0019 ± 0.0004 (n=5),0.0014 ± 0.0001 (n=5),36.5344 ± 1.7977 (n=5),0.0337 ± 0.0017 (n=5),2.3075 ± 0.5362 (n=5),2.3075 ± 0.5362 (n=5),2193.3972 ± 249.1808 (n=5),0.0019 ± 0.0002 (n=5),0.2853 ± 0.0121 (n=5),0.2853 ± 0.0121 (n=5),43.8351 ± 2.1091 (n=5),0.0405 ± 0.0019 (n=5),0.0014 ± 0.0001 (n=5),36.5344 ± 1.7977 (n=5),0.0337 ± 0.0017 (n=5),2.3075 ± 0.5362 (n=5),2.3075 ± 0.5362 (n=5),2193.3972 ± 249.1808 (n=5),0.0019 ± 0.0002 (n=5),0.2853 ± 0.0121 (n=5),0.2853 ± 0.0121 (n=5),43.8351 ± 2.1091 (n=5),0.0405 ± 0.0019 (n=5),38.0418 ± 4.4770 (n=5),0.0351 ± 0.0041 (n=5),1.9946 ± 0.3450 (n=5),1.9946 ± 0.3450 (n=5),2685.5196 ± 647.1489 (n=5),0.0023 ± 0.0006 (n=5),0.3150 ± 0.0289 (n=5),0.3150 ± 0.0289 (n=5),47.5366 ± 5.8629 (n=5),0.0439 ± 0.0054 (n=5),0.0014 ± 0.0002 (n=5),34.0945 ± 2.1091 (n=5),0.0315 ± 0.0019 (n=5),2.0269 ± 0.4353 (n=5),2.0269 ± 0.4353 (n=5),2075.3664 ± 328.8053 (n=5),0.0018 ± 0.0003 (n=5),0.3610 ± 0.0238 (n=5),0.3610 ± 0.0238 (n=5),42.5046 ± 2.9612 (n=5),0.0392 ± 0.0027 (n=5)
11,100,0.0001,100.0,0.0021 ± 0.0004 (n=5),0.0015 ± 0.0001 (n=5),37.9077 ± 2.0921 (n=5),0.0350 ± 0.0019 (n=5),3.0728 ± 0.4585 (n=5),3.0728 ± 0.4585 (n=5),2351.0162 ± 235.4320 (n=5),0.0020 ± 0.0002 (n=5),0.2908 ± 0.0124 (n=5),0.2908 ± 0.0124 (n=5),44.4430 ± 1.5805 (n=5),0.0410 ± 0.0015 (n=5),0.0015 ± 0.0001 (n=5),37.9077 ± 2.0921 (n=5),0.0350 ± 0.0019 (n=5),3.0728 ± 0.4585 (n=5),3.0728 ± 0.4585 (n=5),2351.0162 ± 235.4320 (n=5),0.0020 ± 0.0002 (n=5),0.2908 ± 0.0124 (n=5),0.2908 ± 0.0124 (n=5),44.4430 ± 1.5805 (n=5),0.0410 ± 0.0015 (n=5),41.2287 ± 4.3333 (n=5),0.0381 ± 0.0040 (n=5),2.7206 ± 0.3442 (n=5),2.7206 ± 0.3442 (n=5),3075.9235 ± 632.4354 (n=5),0.0026 ± 0.0005 (n=5),0.2851 ± 0.0400 (n=5),0.2851 ± 0.0400 (n=5),51.5748 ± 5.1323 (n=5),0.0476 ± 0.0047 (n=5),0.0017 ± 0.0002 (n=5),36.6995 ± 2.3149 (n=5),0.0339 ± 0.0021 (n=5),2.6472 ± 0.2858 (n=5),2.6472 ± 0.2858 (n=5),2415.1293 ± 266.1472 (n=5),0.0021 ± 0.0002 (n=5),0.3494 ± 0.0112 (n=5),0.3494 ± 0.0112 (n=5),46.3913 ± 2.7761 (n=5),0.0428 ± 0.0026 (n=5)
7,50,0.0005,50.0,0.0022 ± 0.0004 (n=5),0.0017 ± 0.0001 (n=5),40.4857 ± 1.6345 (n=5),0.0374 ± 0.0015 (n=5),2.7877 ± 0.5325 (n=5),2.7877 ± 0.5325 (n=5),2730.0665 ± 276.3778 (n=5),0.0023 ± 0.0002 (n=5),0.2996 ± 0.0171 (n=5),0.2996 ± 0.0171 (n=5),47.6054 ± 1.3469 (n=5),0.0439 ± 0.0012 (n=5),0.0017 ± 0.0001 (n=5),40.4857 ± 1.6345 (n=5),0.0374 ± 0.0015 (n=5),2.7877 ± 0.5325 (n=5),2.7877 ± 0.5325 (n=5),2730.0665 ± 276.3778 (n=5),0.0023 ± 0.0002 (n=5),0.2996 ± 0.0171 (n=5),0.2996 ± 0.0171 (n=5),47.6054 ± 1.3469 (n=5),0.0439 ± 0.0012 (n=5),41.7457 ± 3.8444 (n=5),0.0385 ± 0.0035 (n=5),2.3032 ± 0.3001 (n=5),2.3032 ± 0.3001 (n=5),3059.1864 ± 596.3163 (n=5),0.0026 ± 0.0005 (n=5),0.3197 ± 0.0377 (n=5),0.3197 ± 0.0377 (n=5),52.5552 ± 4.9370 (n=5),0.0485 ± 0.0046 (n=5),0.0019 ± 0.0001 (n=5),39.3713 ± 1.4821 (n=5),0.0363 ± 0.0014 (n=5),2.2154 ± 0.2046 (n=5),2.2154 ± 0.2046 (n=5),2664.0612 ± 257.0512 (n=5),0.0023 ± 0.0002 (n=5),0.3370 ± 0.0081 (n=5),0.3370 ± 0.0081 (n=5),48.4498 ± 2.3587 (n=5),0.0447 ± 0.0022 (n=5)
6,50,0.0010,50.0,0.0025 ± 0.0003 (n=5),0.0017 ± 0.0001 (n=5),40.9337 ± 1.3750 (n=5),0.0378 ± 0.0013 (n=5),2.5849 ± 0.2207 (n=5),2.5849 ± 0.2207 (n=5),2844.2053 ± 249.2025 (n=5),0.0024 ± 0.0002 (n=5),0.3118 ± 0.0241 (n=5),0.3118 ± 0.0241 (n=5),48.1068 ± 1.6843 (n=5),0.0444 ± 0.0016 (n=5),0.0017 ± 0.0001 (n=5),40.9337 ± 1.3750 (n=5),0.0378 ± 0.0013 (n=5),2.5849 ± 0.2207 (n=5),2.5849 ± 0.2207 (n=5),2844.2053 ± 249.2025 (n=5),0.0024 ± 0.0002 (n=5),0.3118 ± 0.0241 (n=5),0.3118 ± 0.0241 (n=5),48.1068 ± 1.6843 (n=5),0.0444 ± 0.0016 (n=5),43.2767 ± 3.3077 (n=5),0.0400 ± 0.0031 (n=5),2.3700 ± 0.1303 (n=5),2.3700 ± 0.1303 (n=5),3450.8892 ± 561.4366 (n=5),0.0029 ± 0.0005 (n=5),0.3048 ± 0.0430 (n=5),0.3048 ± 0.0430 (n=5),54.9703 ± 4.2222 (n=5),0.0507 ± 0.0039 (n=5),0.0020 ± 0.0001 (n=5),39.2388 ± 1.1213 (n=5),0.0362 ± 0.0010 (n=5),2.0485 ± 0.2565 (n=5),2.0485 ± 0.2565 (n=5),2715.1262 ± 201.8251 (n=5),0.0023 ± 0.0002 (n=5),0.3480 ± 0.0152 (n=5),0.3480 ± 0.0152 (n=5),49.1809 ± 2.1954 (n=5),0.0454 ± 0.0020 (n=5)
8,50,0.0001,50.0,0.0027 ± 0.0008 (n=5),0.0020 ± 0.0006 (n=5),44.0117 ± 7.9660 (n=5),0.0406 ± 0.0074 (n=5),3.1034 ± 0.7718 (n=5),3.1034 ± 0.7718 (n=5),3234.7648 ± 1213.3369 (n=5),0.0028 ± 0.0010 (n=5),0.2889 ± 0.0233 (n=5),0.2889 ± 0.0233 (n=5),50.9608 ± 8.0403 (n=5),0.0470 ± 0.0074 (n=5),0.0020 ± 0.0006 (n=5),44.0117 ± 7.9660 (n=5),0.0406 ± 0.0074 (n=5),3.1034 ± 0.7718 (n=5),3.1034 ± 0.7718 (n=5),3234.7648 ± 1213.3369 (n=5),0.0028 ± 0.0010 (n=5),0.2889 ± 0.0233 (n=5),0.2889 ± 0.0233 (n=5),50.9608 ± 8.0403 (n=5),0.0470 ± 0.0074 (n=5),43.5725 ± 4.7389 (n=5),0.0402 ± 0.0044 (n=5),2.7463 ± 0.2345 (n=5),2.7463 ± 0.2345 (n=5),3653.0333 ± 947.6839 (n=5),0.0031 ± 0.0008 (n=5),0.3054 ± 0.0173 (n=5),0.3054 ± 0.0173 (n=5),56.6362 ± 7.0905 (n=5),0.0523 ± 0.0065 (n=5),0.0024 ± 0.0007 (n=5),42.7632 ± 5.8923 (n=5),0.0395 ± 0.0054 (n=5),2.7745 ± 0.3955 (n=5),2.7745 ± 0.3955 (n=5),3351.5885 ± 981.3608 (n=5),0.0029 ± 0.0008 (n=5),0.3277 ± 0.0266 (n=5),0.3277 ± 0.0266 (n=5),54.7102 ± 7.5141 (n=5),0.0505 ± 0.0069 (n=5)
3,10,0.0010,10.0,0.0027 ± 0.0004 (n=5),0.0021 ± 0.0001 (n=5),43.3145 ± 1.1308 (n=5),0.0400 ± 0.0010 (n=5),2.3384 ± 0.2437 (n=5),2.3384 ± 0.2437 (n=5),3273.7067 ± 253.8339 (n=5),0.0028 ± 0.0002 (n=5),0.3072 ± 0.0109 (n=5),0.3072 ± 0.0109 (n=5),52.6117 ± 1.7992 (n=5),0.0486 ± 0.0017 (n=5),0.0021 ± 0.0001 (n=5),43.3145 ± 1.1308 (n=5),0.0400 ± 0.0010 (n=5),2.3384 ± 0.2437 (n=5),2.3384 ± 0.2437 (n=5),3273.7067 ± 253.8339 (n=5),0.0028 ± 0.0002 (n=5),0.3072 ± 0.0109 (n=5),0.3072 ± 0.0109 (n=5),52.6117 ± 1.7992 (n=5),0.0486 ± 0.0017 (n=5),45.1820 ± 4.7951 (n=5),0.0417 ± 0.0044 (n=5),2.1329 ± 0.2858 (n=5),2.1329 ± 0.2858 (n=5),3756.5662 ± 685.5549 (n=5),0.0032 ± 0.0006 (n=5),0.2952 ± 0.0317 (n=5),0.2952 ± 0.0317 (n=5),57.3233 ± 4.5606 (n=5),0.0529 ± 0.0042 (n=5),0.0023 ± 0.0002 (n=5),41.8114 ± 2.8828 (n=5),0.0386 ± 0.0027 (n=5),1.9880 ± 0.2191 (n=5),1.9880 ± 0.2191 (n=5),3055.9850 ± 316.0038 (n=5),0.0026 ± 0.0003 (n=5),0.3338 ± 0.0221 (n=5),0.3338 ± 0.0221 (n=5),52.9485 ± 3.2301 (n=5),0.0489 ± 0.0030 (n=5)
5,10,0.0001,10.0,0.0028 ± 0.0009 (n=5),0.0022 ± 0.0002 (n=5),45.0782 ± 2.1903 (n=5),0.0416 ± 0.0020 (n=5),2.4780 ± 0.4006 (n=5),2.4780 ± 0.4006 (n=5),3498.3088 ± 339.4335 (n=5),0.0030 ± 0.0003 (n=5),0.3019 ± 0.0085 (n=5),0.3019 ± 0.0085 (n=5),53.7248 ± 2.1060 (n=5),0.0496 ± 0.0019 (n=5),0.0022 ± 0.0002 (n=5),45.0782 ± 2.1903 (n=5),0.0416 ± 0.0020 (n=5),2.4780 ± 0.4006 (n=5),2.4780 ± 0.4006 (n=5),3498.3088 ± 339.4335 (n=5),0.0030 ± 0.0003 (n=5),0.3019 ± 0.0085 (n=5),0.3019 ± 0.0085 (n=5),53.7248 ± 2.1060 (n=5),0.0496 ± 0.0019 (n=5),44.1029 ± 3.5579 (n=5),0.0407 ± 0.0033 (n=5),2.2184 ± 0.1633 (n=5),2.2184 ± 0.1633 (n=5),3655.7329 ± 954.1545 (n=5),0.0031 ± 0.0008 (n=5),0.3145 ± 0.0158 (n=5),0.3145 ± 0.0158 (n=5),57.2540 ± 7.0318 (n=5),0.0529 ± 0.0065 (n=5),0.0027 ± 0.0009 (n=5),43.6462 ± 3.5470 (n=5),0.0403 ± 0.0033 (n=5),2.2031 ± 0.1578 (n=5),2.2031 ± 0.1578 (n=5),3509.4798 ± 945.7828 (n=5),0.0030 ± 0.0008 (n=5),0.3229 ± 0.0161 (n=5),0.3229 ± 0.0161 (n=5),56.4190 ± 7.1534 (n=5),0.0521 ± 0.0066 (n=5)
4,10,0.0005,10.0,0.0029 ± 0.0008 (n=5),0.0022 ± 0.0003 (n=5),45.0022 ± 2.9132 (n=5),0.0415 ± 0.0027 (n=5),2.6505 ± 0.4300 (n=5),2.6505 ± 0.4300 (n=5),3474.1562 ± 483.6460 (n=5),0.0030 ± 0.0004 (n=5),0.2940 ± 0.0098 (n=5),0.2940 ± 0.0098 (n=5),53.6557 ± 2.9391 (n=5),0.0495 ± 0.0027 (n=5),0.0022 ± 0.0003 (n=5),45.0022 ± 2.9132 (n=5),0.0415 ± 0.0027 (n=5),2.6505 ± 0.4300 (n=5),2.6505 ± 0.4300 (n=5),3474.1562 ± 483.6460 (n=5),0.0030 ± 0.0004 (n=5),0.2940 ± 0.0098 (n=5),0.2940 ± 0.0098 (n=5),53.6557 ± 2.9391 (n=5),0.0495 ± 0.0027 (n=5),47.0875 ± 7.5749 (n=5),0.0435 ± 0.0070 (n=5),2.2298 ± 0.4412 (n=5),2.2298 ± 0.4412 (n=5),4088.1491 ± 1222.9068 (n=5),0.0035 ± 0.0010 (n=5),0.2849 ± 0.0639 (n=5),0.2849 ± 0.0639 (n=5),59.6155 ± 8.0977 (n=5),0.0550 ± 0.0075 (n=5),0.0023 ± 0.0003 (n=5),42.8324 ± 3.8164 (n=5),0.0395 ± 0.0035 (n=5),2.1364 ± 0.2398 (n=5),2.1364 ± 0.2398 (n=5),3165.1710 ± 459.4481 (n=5),0.0027 ± 0.0004 (n=5),0.3235 ± 0.0249 (n=5),0.3235 ± 0.0249 (n=5),53.7555 ± 3.9966 (n=5),0.0496 ± 0.0037 (n=5)
0,1,0.0010,1.0,0.0070 ± 0.0024 (n=5),0.0036 ± 0.0002 (n=5),52.8072 ± 2.1906 (n=5),0.0487 ± 0.0020 (n=5),2.6361 ± 0.5217 (n=5),2.6361 ± 0.5217 (n=5),5051.7524 ± 394.2061 (n=5),0.0043 ± 0.0003 (n=5),0.2899 ± 0.0167 (n=5),0.2899 ± 0.0167 (n=5),66.4216 ± 2.0318 (n=5),0.0613 ± 0.0019 (n=5),0.0036 ± 0.0002 (n=5),52.8072 ± 2.1906 (n=5),0.0487 ± 0.0020 (n=5),2.6361 ± 0.5217 (n=5),2.6361 ± 0.5217 (n=5),5051.7524 ± 394.2061 (n=5),0.0043 ± 0.0003 (n=5),0.2899 ± 0.0167 (n=5),0.2899 ± 0.0167 (n=5),66.4216 ± 2.0318 (n=5),0.0613 ± 0.0019 (n=5),56.5557 ± 2.9603 (n=5),0.0522 ± 0.0027 (n=5),2.5440 ± 0.4435 (n=5),2.5440 ± 0.4435 (n=5),7935.7041 ± 1799.3496 (n=5),0.0068 ± 0.0015 (n=5),0.2622 ± 0.0225 (n=5),0.2622 ± 0.0225 (n=5),81.9608 ± 5.1762 (n=5),0.0757 ± 0.0048 (n=5),0.0059 ± 0.0018 (n=5),52.4401 ± 1.1624 (n=5),0.0484 ± 0.0011 (n=5),2.2917 ± 0.4526 (n=5),2.2917 ± 0.4526 (n=5),6468.0030 ± 1482.8324 (n=5),0.0055 ± 0.0013 (n=5),0.2946 ± 0.0139 (n=5),0.2946 ± 0.0139 (n=5),76.0722 ± 5.4030 (n=5),0.0702 ± 0.0050 (n=5)
2,1,0.0001,1.0,0.0077 ± 0.0027 (n=5),0.0057 ± 0.0017 (n=5),67.5170 ± 10.4351 (n=5),0.0623 ± 0.0096 (n=5),3.8889 ± 0.7358 (n=5),3.8889 ± 0.7358 (n=5),7681.8562 ± 1896.7239 (n=5),0.0065 ± 0.0016 (n=5),0.2353 ± 0.0315 (n=5),0.2353 ± 0.0315 (n=5),83.3755 ± 12.5238 (n=5),0.0770 ± 0.0116 (n=5),0.0057 ± 0.0017 (n=5),67.5170 ± 10.4351 (n=5),0.0623 ± 0.0096 (n=5),3.8889 ± 0.7358 (n=5),3.8889 ± 0.7358 (n=5),7681.8562 ± 1896.7239 (n=5),0.0065 ± 0.0016 (n=5),0.2353 ± 0.0315 (n=5),0.2353 ± 0.0315 (n=5),83.3755 ± 12.5238 (n=5),0.0770 ± 0.0116 (n=5),61.8479 ± 5.6222 (n=5),0.0571 ± 0.0052 (n=5),3.1249 ± 0.4338 (n=5),3.1249 ± 0.4338 (n=5),8990.7816 ± 2768.3044 (n=5),0.0077 ± 0.0024 (n=5),0.2697 ± 0.0076 (n=5),0.2697 ± 0.0076 (n=5),88.1159 ± 12.3832 (n=5),0.0813 ± 0.0114 (n=5),0.0067 ± 0.0019 (n=5),66.2036 ± 11.0733 (n=5),0.0611 ± 0.0102 (n=5),3.3230 ± 0.6816 (n=5),3.3230 ± 0.6816 (n=5),8250.0700 ± 2395.5331 (n=5),0.0070 ± 0.0020 (n=5),0.2719 ± 0.0137 (n=5),0.2719 ± 0.0137 (n=5),88.1912 ± 13.9150 (n=5),0.0814 ± 0.0128 (n=5)
1,1,0.0005,1.0,0.0086 ± 0.0058 (n=5),0.0043 ± 0.0018 (n=5),58.3791 ± 11.0784 (n=5),0.0539 ± 0.0102 (n=5),3.1496 ± 0.8370 (n=5),3.1496 ± 0.8370 (n=5),6079.3462 ± 2052.0118 (n=5),0.0052 ± 0.0017 (n=5),0.2625 ± 0.0305 (n=5),0.2625 ± 0.0305 (n=5),72.5801 ± 13.4291 (n=5),0.0670 ± 0.0124 (n=5),0.0043 ± 0.0018 (n=5),58.3791 ± 11.0784 (n=5),0.0539 ± 0.0102 (n=5),3.1496 ± 0.8370 (n=5),3.1496 ± 0.8370 (n=5),6079.3462 ± 2052.0118 (n=5),0.0052 ± 0.0017 (n=5),0.2625 ± 0.0305 (n=5),0.2625 ± 0.0305 (n=5),72.5801 ± 13.4291 (n=5),0.0670 ± 0.0124 (n=5),57.3703 ± 5.4386 (n=5),0.0530 ± 0.0050 (n=5),2.8403 ± 0.4151 (n=5),2.8403 ± 0.4151 (n=5),9450.5424 ± 5424.2317 (n=5),0.0081 ± 0.0046 (n=5),0.2566 ± 0.0140 (n=5),0.2566 ± 0.0140 (n=5),85.5598 ± 16.4283 (n=5),0.0790 ± 0.0152 (n=5),0.0060 ± 0.0021 (n=5),57.6761 ± 11.8300 (n=5),0.0532 ± 0.0109 (n=5),2.7542 ± 0.8111 (n=5),2.7542 ± 0.8111 (n=5),7014.1522 ± 2516.7784 (n=5),0.0060 ± 0.0021 (n=5),0.2795 ± 0.0174 (n=5),0.2795 ± 0.0174 (n=5),80.2224 ± 14.3868 (n=5),0.0741 ± 0.0133 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.cnn1d_wrapper.CNN1D_Wrapper on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.seq_len,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
1,1,0.0005,1.0,0.0949 ± 0.1182 (n=5),0.0131 ± 0.0059 (n=5),98.9557 ± 15.4816 (n=5),0.0914 ± 0.0143 (n=5),6.1727 ± 1.1110 (n=5),6.1727 ± 1.1110 (n=5),15644.7350 ± 6266.1642 (n=5),0.0133 ± 0.0053 (n=5),0.1759 ± 0.0179 (n=5),0.1759 ± 0.0179 (n=5),122.1711 ± 22.0143 (n=5),0.1128 ± 0.0203 (n=5),0.0131 ± 0.0059 (n=5),98.9557 ± 15.4816 (n=5),0.0914 ± 0.0143 (n=5),6.1727 ± 1.1110 (n=5),6.1727 ± 1.1110 (n=5),15644.7350 ± 6266.1642 (n=5),0.0133 ± 0.0053 (n=5),0.1759 ± 0.0179 (n=5),0.1759 ± 0.0179 (n=5),122.1711 ± 22.0143 (n=5),0.1128 ± 0.0203 (n=5),105.7017 ± 18.6495 (n=5),0.0976 ± 0.0172 (n=5),5.9408 ± 1.4956 (n=5),5.9408 ± 1.4956 (n=5),87644.9619 ± 104535.4546 (n=5),0.0747 ± 0.0891 (n=5),0.2046 ± 0.0213 (n=5),0.2046 ± 0.0213 (n=5),192.4116 ± 78.5082 (n=5),0.1776 ± 0.0725 (n=5),0.0920 ± 0.1188 (n=5),107.2691 ± 19.5382 (n=5),0.0990 ± 0.0180 (n=5),5.7658 ± 1.1495 (n=5),5.7658 ± 1.1495 (n=5),85361.5291 ± 104874.6253 (n=5),0.0727 ± 0.0894 (n=5),0.2023 ± 0.0235 (n=5),0.2023 ± 0.0235 (n=5),192.4148 ± 78.0128 (n=5),0.1776 ± 0.0720 (n=5)
0,1,0.0010,1.0,0.1029 ± 0.1264 (n=5),0.0150 ± 0.0116 (n=5),102.1093 ± 33.5158 (n=5),0.0943 ± 0.0309 (n=5),6.0449 ± 2.3475 (n=5),6.0449 ± 2.3475 (n=5),18356.3836 ± 14821.2370 (n=5),0.0156 ± 0.0126 (n=5),0.1768 ± 0.0384 (n=5),0.1768 ± 0.0384 (n=5),128.0405 ± 46.2144 (n=5),0.1182 ± 0.0427 (n=5),0.0150 ± 0.0116 (n=5),102.1093 ± 33.5158 (n=5),0.0943 ± 0.0309 (n=5),6.0449 ± 2.3475 (n=5),6.0449 ± 2.3475 (n=5),18356.3836 ± 14821.2370 (n=5),0.0156 ± 0.0126 (n=5),0.1768 ± 0.0384 (n=5),0.1768 ± 0.0384 (n=5),128.0405 ± 46.2144 (n=5),0.1182 ± 0.0427 (n=5),101.3890 ± 13.3461 (n=5),0.0936 ± 0.0123 (n=5),5.7114 ± 1.6589 (n=5),5.7114 ± 1.6589 (n=5),94430.8477 ± 111455.5623 (n=5),0.0805 ± 0.0950 (n=5),0.2091 ± 0.0136 (n=5),0.2091 ± 0.0136 (n=5),191.0398 ± 82.4364 (n=5),0.1764 ± 0.0761 (n=5),0.0940 ± 0.1269 (n=5),109.5606 ± 31.1061 (n=5),0.1011 ± 0.0287 (n=5),5.8280 ± 1.7104 (n=5),5.8280 ± 1.7104 (n=5),87975.6418 ± 111690.0783 (n=5),0.0750 ± 0.0952 (n=5),0.1985 ± 0.0357 (n=5),0.1985 ± 0.0357 (n=5),193.0563 ± 87.0860 (n=5),0.1782 ± 0.0804 (n=5)
2,1,0.0001,1.0,0.1140 ± 0.1403 (n=5),0.0148 ± 0.0044 (n=5),105.4195 ± 18.2772 (n=5),0.0973 ± 0.0169 (n=5),7.3601 ± 2.0613 (n=5),7.3601 ± 2.0613 (n=5),17468.6869 ± 5309.2775 (n=5),0.0149 ± 0.0045 (n=5),0.1695 ± 0.0257 (n=5),0.1695 ± 0.0257 (n=5),129.7948 ± 20.5862 (n=5),0.1198 ± 0.0190 (n=5),0.0148 ± 0.0044 (n=5),105.4195 ± 18.2772 (n=5),0.0973 ± 0.0169 (n=5),7.3601 ± 2.0613 (n=5),7.3601 ± 2.0613 (n=5),17468.6869 ± 5309.2775 (n=5),0.0149 ± 0.0045 (n=5),0.1695 ± 0.0257 (n=5),0.1695 ± 0.0257 (n=5),129.7948 ± 20.5862 (n=5),0.1198 ± 0.0190 (n=5),116.5239 ± 18.2821 (n=5),0.1076 ± 0.0169 (n=5),6.1807 ± 1.4493 (n=5),6.1807 ± 1.4493 (n=5),105181.7742 ± 124888.1993 (n=5),0.0896 ± 0.1064 (n=5),0.1894 ± 0.0212 (n=5),0.1894 ± 0.0212 (n=5),215.1081 ± 78.9173 (n=5),0.1986 ± 0.0729 (n=5),0.1134 ± 0.1406 (n=5),117.2028 ± 18.1063 (n=5),0.1082 ± 0.0167 (n=5),6.2499 ± 1.1453 (n=5),6.2499 ± 1.1453 (n=5),104828.5070 ± 125068.9464 (n=5),0.0893 ± 0.1066 (n=5),0.1875 ± 0.0203 (n=5),0.1875 ± 0.0203 (n=5),215.0677 ± 78.7996 (n=5),0.1985 ± 0.0727 (n=5)
7,50,0.0005,50.0,0.4427 ± 0.3180 (n=5),0.0101 ± 0.0085 (n=5),87.3221 ± 23.5418 (n=5),0.0806 ± 0.0217 (n=5),5.7865 ± 1.9446 (n=5),5.7865 ± 1.9446 (n=5),12801.7127 ± 8200.3617 (n=5),0.0109 ± 0.0070 (n=5),0.1796 ± 0.0243 (n=5),0.1796 ± 0.0243 (n=5),105.0099 ± 31.8595 (n=5),0.0969 ± 0.0294 (n=5),0.0101 ± 0.0085 (n=5),87.3221 ± 23.5418 (n=5),0.0806 ± 0.0217 (n=5),5.7865 ± 1.9446 (n=5),5.7865 ± 1.9446 (n=5),12801.7127 ± 8200.3617 (n=5),0.0109 ± 0.0070 (n=5),0.1796 ± 0.0243 (n=5),0.1796 ± 0.0243 (n=5),105.0099 ± 31.8595 (n=5),0.0969 ± 0.0294 (n=5),121.9241 ± 30.2033 (n=5),0.1126 ± 0.0279 (n=5),4.6843 ± 0.9904 (n=5),4.6843 ± 0.9904 (n=5),388720.9125 ± 277589.7261 (n=5),0.3313 ± 0.2366 (n=5),0.2233 ± 0.0324 (n=5),0.2233 ± 0.0324 (n=5),322.4004 ± 107.8608 (n=5),0.2976 ± 0.0996 (n=5),0.4366 ± 0.3074 (n=5),125.9304 ± 38.7301 (n=5),0.1163 ± 0.0358 (n=5),4.9645 ± 1.6005 (n=5),4.9645 ± 1.6005 (n=5),383601.8625 ± 268793.5374 (n=5),0.3269 ± 0.2291 (n=5),0.2196 ± 0.0404 (n=5),0.2196 ± 0.0404 (n=5),325.0637 ± 112.5539 (n=5),0.3001 ± 0.1039 (n=5)
8,50,0.0001,50.0,0.5642 ± 0.3695 (n=5),0.0115 ± 0.0052 (n=5),94.0104 ± 14.2058 (n=5),0.0868 ± 0.0131 (n=5),6.8591 ± 1.4006 (n=5),6.8591 ± 1.4006 (n=5),13905.1186 ± 4954.9124 (n=5),0.0119 ± 0.0042 (n=5),0.1679 ± 0.0120 (n=5),0.1679 ± 0.0120 (n=5),113.9072 ± 19.5854 (n=5),0.1052 ± 0.0181 (n=5),0.0115 ± 0.0052 (n=5),94.0104 ± 14.2058 (n=5),0.0868 ± 0.0131 (n=5),6.8591 ± 1.4006 (n=5),6.8591 ± 1.4006 (n=5),13905.1186 ± 4954.9124 (n=5),0.0119 ± 0.0042 (n=5),0.1679 ± 0.0120 (n=5),0.1679 ± 0.0120 (n=5),113.9072 ± 19.5854 (n=5),0.1052 ± 0.0181 (n=5),139.4795 ± 28.1184 (n=5),0.1288 ± 0.0260 (n=5),5.6507 ± 0.7641 (n=5),5.6507 ± 0.7641 (n=5),494843.2469 ± 322184.3334 (n=5),0.4217 ± 0.2746 (n=5),0.1985 ± 0.0201 (n=5),0.1985 ± 0.0201 (n=5),369.0697 ± 100.6645 (n=5),0.3407 ± 0.0929 (n=5),0.5633 ± 0.3679 (n=5),141.1587 ± 31.6111 (n=5),0.1303 ± 0.0292 (n=5),5.8005 ± 1.0292 (n=5),5.8005 ± 1.0292 (n=5),494268.0594 ± 321036.2171 (n=5),0.4212 ± 0.2736 (n=5),0.1961 ± 0.0247 (n=5),0.1961 ± 0.0247 (n=5),370.6670 ± 103.7816 (n=5),0.3422 ± 0.0958 (n=5)
4,10,0.0005,10.0,0.6074 ± 0.6260 (n=5),0.0160 ± 0.0188 (n=5),100.7058 ± 45.8236 (n=5),0.0930 ± 0.0423 (n=5),6.2539 ± 2.6347 (n=5),6.2539 ± 2.6347 (n=5),19210.7070 ± 20951.2011 (n=5),0.0164 ± 0.0179 (n=5),0.1848 ± 0.0415 (n=5),0.1848 ± 0.0415 (n=5),123.8047 ± 61.4285 (n=5),0.1143 ± 0.0567 (n=5),0.0160 ± 0.0188 (n=5),100.7058 ± 45.8236 (n=5),0.0930 ± 0.0423 (n=5),6.2539 ± 2.6347 (n=5),6.2539 ± 2.6347 (n=5),19210.7070 ± 20951.2011 (n=5),0.0164 ± 0.0179 (n=5),0.1848 ± 0.0415 (n=5),0.1848 ± 0.0415 (n=5),123.8047 ± 61.4285 (n=5),0.1143 ± 0.0567 (n=5),132.7816 ± 41.7748 (n=5),0.1226 ± 0.0386 (n=5),5.2595 ± 1.7101 (n=5),5.2595 ± 1.7101 (n=5),538526.1406 ± 552715.3760 (n=5),0.4589 ± 0.4710 (n=5),0.2242 ± 0.0354 (n=5),0.2242 ± 0.0354 (n=5),366.4747 ± 149.9049 (n=5),0.3383 ± 0.1384 (n=5),0.6001 ± 0.6106 (n=5),144.2152 ± 65.9925 (n=5),0.1331 ± 0.0609 (n=5),5.8260 ± 2.9285 (n=5),5.8260 ± 2.9285 (n=5),533047.6969 ± 541194.8488 (n=5),0.4543 ± 0.4612 (n=5),0.2157 ± 0.0513 (n=5),0.2157 ± 0.0513 (n=5),376.8271 ± 172.0356 (n=5),0.3479 ± 0.1588 (n=5)
3,10,0.0010,10.0,0.6562 ± 0.7622 (n=5),0.0241 ± 0.0383 (n=5),111.9494 ± 76.2577 (n=5),0.1033 ± 0.0704 (n=5),7.9428 ± 7.2472 (n=5),7.9428 ± 7.2472 (n=5),28468.7596 ± 42408.5931 (n=5),0.0243 ± 0.0361 (n=5),0.1846 ± 0.0531 (n=5),0.1846 ± 0.0531 (n=5),138.2694 ± 100.2780 (n=5),0.1276 ± 0.0926 (n=5),0.0241 ± 0.0383 (n=5),111.9494 ± 76.2577 (n=5),0.1033 ± 0.0704 (n=5),7.9428 ± 7.2472 (n=5),7.9428 ± 7.2472 (n=5),28468.7596 ± 42408.5931 (n=5),0.0243 ± 0.0361 (n=5),0.1846 ± 0.0531 (n=5),0.1846 ± 0.0531 (n=5),138.2694 ± 100.2780 (n=5),0.1276 ± 0.0926 (n=5),128.7447 ± 47.4912 (n=5),0.1189 ± 0.0438 (n=5),4.9063 ± 1.7196 (n=5),4.9063 ± 1.7196 (n=5),581414.0406 ± 672501.6995 (n=5),0.4955 ± 0.5731 (n=5),0.2350 ± 0.0418 (n=5),0.2350 ± 0.0418 (n=5),366.4893 ± 172.9576 (n=5),0.3383 ± 0.1597 (n=5),0.6173 ± 0.6771 (n=5),153.3148 ± 100.5963 (n=5),0.1415 ± 0.0929 (n=5),7.0873 ± 6.4714 (n=5),7.0873 ± 6.4714 (n=5),549864.6906 ± 603498.2559 (n=5),0.4686 ± 0.5143 (n=5),0.2232 ± 0.0652 (n=5),0.2232 ± 0.0652 (n=5),386.9801 ± 216.9688 (n=5),0.3572 ± 0.2003 (n=5)
5,10,0.0001,10.0,0.7189 ± 0.4973 (n=5),0.0119 ± 0.0030 (n=5),98.2599 ± 10.2446 (n=5),0.0907 ± 0.0095 (n=5),6.3440 ± 0.9000 (n=5),6.3440 ± 0.9000 (n=5),15064.8854 ± 3347.2037 (n=5),0.0128 ± 0.0029 (n=5),0.1722 ± 0.0173 (n=5),0.1722 ± 0.0173 (n=5),119.1708 ± 13.3537 (n=5),0.1100 ± 0.0123 (n=5),0.0119 ± 0.0030 (n=5),98.2599 ± 10.2446 (n=5),0.0907 ± 0.0095 (n=5),6.3440 ± 0.9000 (n=5),6.3440 ± 0.9000 (n=5),15064.8854 ± 3347.2037 (n=5),0.0128 ± 0.0029 (n=5),0.1722 ± 0.0173 (n=5),0.1722 ± 0.0173 (n=5),119.1708 ± 13.3537 (n=5),0.1100 ± 0.0123 (n=5),148.1619 ± 25.6561 (n=5),0.1368 ± 0.0237 (n=5),6.4097 ± 1.3577 (n=5),6.4097 ± 1.3577 (n=5),637282.5188 ± 438420.4242 (n=5),0.5431 ± 0.3736 (n=5),0.1981 ± 0.0202 (n=5),0.1981 ± 0.0202 (n=5),411.6997 ± 112.8314 (n=5),0.3801 ± 0.1042 (n=5),0.7183 ± 0.4963 (n=5),148.2412 ± 26.0716 (n=5),0.1369 ± 0.0241 (n=5),6.4113 ± 1.4175 (n=5),6.4113 ± 1.4175 (n=5),636634.0750 ± 437619.3744 (n=5),0.5426 ± 0.3730 (n=5),0.1990 ± 0.0195 (n=5),0.1990 ± 0.0195 (n=5),411.7896 ± 113.3282 (n=5),0.3801 ± 0.1046 (n=5)
6,50,0.0010,50.0,0.8027 ± 0.8530 (n=5),0.0316 ± 0.0404 (n=5),129.6568 ± 75.2025 (n=5),0.1197 ± 0.0694 (n=5),8.8920 ± 5.1365 (n=5),8.8920 ± 5.1365 (n=5),34707.5191 ± 40985.6014 (n=5),0.0296 ± 0.0349 (n=5),0.1496 ± 0.0522 (n=5),0.1496 ± 0.0522 (n=5),159.4578 ± 96.7744 (n=5),0.1472 ± 0.0893 (n=5),0.0316 ± 0.0404 (n=5),129.6568 ± 75.2025 (n=5),0.1197 ± 0.0694 (n=5),8.8920 ± 5.1365 (n=5),8.8920 ± 5.1365 (n=5),34707.5191 ± 40985.6014 (n=5),0.0296 ± 0.0349 (n=5),0.1496 ± 0.0522 (n=5),0.1496 ± 0.0522 (n=5),159.4578 ± 96.7744 (n=5),0.1472 ± 0.0893 (n=5),152.2460 ± 59.4262 (n=5),0.1405 ± 0.0549 (n=5),5.9233 ± 2.0206 (n=5),5.9233 ± 2.0206 (n=5),703034.7672 ± 743913.5126 (n=5),0.5991 ± 0.6340 (n=5),0.1929 ± 0.0415 (n=5),0.1929 ± 0.0415 (n=5),402.5506 ± 202.8033 (n=5),0.3716 ± 0.1872 (n=5),0.7498 ± 0.7658 (n=5),183.2704 ± 110.4187 (n=5),0.1692 ± 0.1019 (n=5),7.8154 ± 4.9542 (n=5),7.8154 ± 4.9542 (n=5),660481.1922 ± 674147.9862 (n=5),0.5629 ± 0.5745 (n=5),0.1740 ± 0.0704 (n=5),0.1740 ± 0.0704 (n=5),426.0855 ± 240.3197 (n=5),0.3933 ± 0.2219 (n=5)
9,100,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
10,100,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
11,100,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.mlp_wrapper.MLPWrapper on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.seq_len,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
2,1,0.0001,1.0,0.2057 ± 0.2304 (n=5),0.0510 ± 0.0571 (n=5),161.9690 ± 96.3975 (n=5),0.1495 ± 0.0890 (n=5),9.7809 ± 4.6053 (n=5),9.7809 ± 4.6053 (n=5),59727.6617 ± 67912.0565 (n=5),0.0509 ± 0.0579 (n=5),0.1447 ± 0.0603 (n=5),0.1447 ± 0.0603 (n=5),209.2534 ± 119.6525 (n=5),0.1932 ± 0.1105 (n=5),0.0510 ± 0.0571 (n=5),161.9690 ± 96.3975 (n=5),0.1495 ± 0.0890 (n=5),9.7809 ± 4.6053 (n=5),9.7809 ± 4.6053 (n=5),59727.6617 ± 67912.0565 (n=5),0.0509 ± 0.0579 (n=5),0.1447 ± 0.0603 (n=5),0.1447 ± 0.0603 (n=5),209.2534 ± 119.6525 (n=5),0.1932 ± 0.1105 (n=5),163.7118 ± 81.1831 (n=5),0.1511 ± 0.0749 (n=5),11.4112 ± 6.4508 (n=5),11.4112 ± 6.4508 (n=5),191302.3578 ± 211946.3189 (n=5),0.1630 ± 0.1806 (n=5),0.1680 ± 0.0632 (n=5),0.1680 ± 0.0632 (n=5),301.2852 ± 156.1535 (n=5),0.2781 ± 0.1442 (n=5),0.2021 ± 0.2233 (n=5),178.0915 ± 104.0082 (n=5),0.1644 ± 0.0960 (n=5),12.5762 ± 8.6357 (n=5),12.5762 ± 8.6357 (n=5),191383.9984 ± 211752.6192 (n=5),0.1631 ± 0.1805 (n=5),0.1622 ± 0.0712 (n=5),0.1622 ± 0.0712 (n=5),313.7558 ± 175.9382 (n=5),0.2896 ± 0.1624 (n=5)
1,1,0.0005,1.0,0.2120 ± 0.2772 (n=5),0.0535 ± 0.0661 (n=5),165.9895 ± 102.4971 (n=5),0.1532 ± 0.0946 (n=5),9.8047 ± 4.7846 (n=5),9.8047 ± 4.7846 (n=5),62788.0041 ± 77467.2938 (n=5),0.0535 ± 0.0660 (n=5),0.1369 ± 0.0515 (n=5),0.1369 ± 0.0515 (n=5),212.9039 ± 126.5300 (n=5),0.1965 ± 0.1168 (n=5),0.0535 ± 0.0661 (n=5),165.9895 ± 102.4971 (n=5),0.1532 ± 0.0946 (n=5),9.8047 ± 4.7846 (n=5),9.8047 ± 4.7846 (n=5),62788.0041 ± 77467.2938 (n=5),0.0535 ± 0.0660 (n=5),0.1369 ± 0.0515 (n=5),0.1369 ± 0.0515 (n=5),212.9039 ± 126.5300 (n=5),0.1965 ± 0.1168 (n=5),128.8835 ± 49.4990 (n=5),0.1190 ± 0.0457 (n=5),8.0992 ± 3.5566 (n=5),8.0992 ± 3.5566 (n=5),192448.5293 ± 247441.1436 (n=5),0.1640 ± 0.2109 (n=5),0.1928 ± 0.0465 (n=5),0.1928 ± 0.0465 (n=5),264.9073 ± 137.8931 (n=5),0.2446 ± 0.1273 (n=5),0.1815 ± 0.2337 (n=5),178.5310 ± 110.6415 (n=5),0.1648 ± 0.1021 (n=5),12.7340 ± 9.1979 (n=5),12.7340 ± 9.1979 (n=5),174255.1773 ± 223318.7989 (n=5),0.1485 ± 0.1903 (n=5),0.1554 ± 0.0628 (n=5),0.1554 ± 0.0628 (n=5),297.3958 ± 190.4169 (n=5),0.2745 ± 0.1758 (n=5)
0,1,0.0010,1.0,0.2341 ± 0.3247 (n=5),0.0509 ± 0.0691 (n=5),160.6802 ± 104.6852 (n=5),0.1483 ± 0.0966 (n=5),9.9584 ± 5.5869 (n=5),9.9584 ± 5.5869 (n=5),60880.7148 ± 79976.7744 (n=5),0.0519 ± 0.0682 (n=5),0.1447 ± 0.0563 (n=5),0.1447 ± 0.0563 (n=5),204.0245 ± 130.8890 (n=5),0.1883 ± 0.1208 (n=5),0.0509 ± 0.0691 (n=5),160.6802 ± 104.6852 (n=5),0.1483 ± 0.0966 (n=5),9.9584 ± 5.5869 (n=5),9.9584 ± 5.5869 (n=5),60880.7148 ± 79976.7744 (n=5),0.0519 ± 0.0682 (n=5),0.1447 ± 0.0563 (n=5),0.1447 ± 0.0563 (n=5),204.0245 ± 130.8890 (n=5),0.1883 ± 0.1208 (n=5),115.8713 ± 41.8173 (n=5),0.1070 ± 0.0386 (n=5),6.8698 ± 2.4660 (n=5),6.8698 ± 2.4660 (n=5),210937.4000 ± 288257.3469 (n=5),0.1798 ± 0.2457 (n=5),0.2073 ± 0.0416 (n=5),0.2073 ± 0.0416 (n=5),254.9613 ± 144.6223 (n=5),0.2354 ± 0.1335 (n=5),0.1722 ± 0.2295 (n=5),167.9400 ± 112.9772 (n=5),0.1550 ± 0.1043 (n=5),12.2095 ± 10.1825 (n=5),12.2095 ± 10.1825 (n=5),165275.1551 ± 219725.7190 (n=5),0.1409 ± 0.1873 (n=5),0.1688 ± 0.0681 (n=5),0.1688 ± 0.0681 (n=5),283.6997 ± 192.7401 (n=5),0.2619 ± 0.1779 (n=5)
6,50,0.0010,50.0,0.3201 ± 0.1180 (n=5),0.0101 ± 0.0087 (n=5),84.4100 ± 29.2019 (n=5),0.0779 ± 0.0270 (n=5),6.0099 ± 1.6653 (n=5),6.0099 ± 1.6653 (n=5),12700.8259 ± 9538.7684 (n=5),0.0108 ± 0.0081 (n=5),0.1859 ± 0.0367 (n=5),0.1859 ± 0.0367 (n=5),103.5596 ± 37.1848 (n=5),0.0956 ± 0.0343 (n=5),0.0101 ± 0.0087 (n=5),84.4100 ± 29.2019 (n=5),0.0779 ± 0.0270 (n=5),6.0099 ± 1.6653 (n=5),6.0099 ± 1.6653 (n=5),12700.8259 ± 9538.7684 (n=5),0.0108 ± 0.0081 (n=5),0.1859 ± 0.0367 (n=5),0.1859 ± 0.0367 (n=5),103.5596 ± 37.1848 (n=5),0.0956 ± 0.0343 (n=5),119.1213 ± 26.3183 (n=5),0.1100 ± 0.0243 (n=5),5.2895 ± 0.9502 (n=5),5.2895 ± 0.9502 (n=5),282169.6250 ± 103823.2042 (n=5),0.2405 ± 0.0885 (n=5),0.1963 ± 0.0295 (n=5),0.1963 ± 0.0295 (n=5),298.5799 ± 56.3666 (n=5),0.2756 ± 0.0520 (n=5),0.3189 ± 0.1162 (n=5),120.0518 ± 34.9537 (n=5),0.1108 ± 0.0323 (n=5),5.4975 ± 1.5627 (n=5),5.4975 ± 1.5627 (n=5),280990.8438 ± 102849.2668 (n=5),0.2395 ± 0.0877 (n=5),0.2052 ± 0.0404 (n=5),0.2052 ± 0.0404 (n=5),299.3602 ± 64.2177 (n=5),0.2764 ± 0.0593 (n=5)
7,50,0.0005,50.0,0.3231 ± 0.1162 (n=5),0.0083 ± 0.0017 (n=5),80.8658 ± 7.0529 (n=5),0.0747 ± 0.0065 (n=5),5.7579 ± 0.4865 (n=5),5.7579 ± 0.4865 (n=5),10848.5552 ± 1934.1414 (n=5),0.0092 ± 0.0016 (n=5),0.1865 ± 0.0113 (n=5),0.1865 ± 0.0113 (n=5),99.6298 ± 9.5168 (n=5),0.0920 ± 0.0088 (n=5),0.0083 ± 0.0017 (n=5),80.8658 ± 7.0529 (n=5),0.0747 ± 0.0065 (n=5),5.7579 ± 0.4865 (n=5),5.7579 ± 0.4865 (n=5),10848.5552 ± 1934.1414 (n=5),0.0092 ± 0.0016 (n=5),0.1865 ± 0.0113 (n=5),0.1865 ± 0.0113 (n=5),99.6298 ± 9.5168 (n=5),0.0920 ± 0.0088 (n=5),116.9863 ± 11.3670 (n=5),0.1080 ± 0.0105 (n=5),5.2275 ± 0.4981 (n=5),5.2275 ± 0.4981 (n=5),284258.0438 ± 101254.0404 (n=5),0.2423 ± 0.0863 (n=5),0.2025 ± 0.0161 (n=5),0.2025 ± 0.0161 (n=5),297.5290 ± 40.1539 (n=5),0.2747 ± 0.0371 (n=5),0.3231 ± 0.1162 (n=5),116.9863 ± 11.3670 (n=5),0.1080 ± 0.0105 (n=5),5.2275 ± 0.4981 (n=5),5.2275 ± 0.4981 (n=5),284258.0438 ± 101254.0404 (n=5),0.2423 ± 0.0863 (n=5),0.2025 ± 0.0161 (n=5),0.2025 ± 0.0161 (n=5),297.5290 ± 40.1539 (n=5),0.2747 ± 0.0371 (n=5)
8,50,0.0001,50.0,0.3971 ± 0.0859 (n=5),0.0256 ± 0.0086 (n=5),132.7968 ± 21.1635 (n=5),0.1226 ± 0.0195 (n=5),9.0617 ± 1.4069 (n=5),9.0617 ± 1.4069 (n=5),29876.3797 ± 9290.0388 (n=5),0.0255 ± 0.0079 (n=5),0.1323 ± 0.0169 (n=5),0.1323 ± 0.0169 (n=5),165.8619 ± 26.6756 (n=5),0.1531 ± 0.0246 (n=5),0.0256 ± 0.0086 (n=5),132.7968 ± 21.1635 (n=5),0.1226 ± 0.0195 (n=5),9.0617 ± 1.4069 (n=5),9.0617 ± 1.4069 (n=5),29876.3797 ± 9290.0388 (n=5),0.0255 ± 0.0079 (n=5),0.1323 ± 0.0169 (n=5),0.1323 ± 0.0169 (n=5),165.8619 ± 26.6756 (n=5),0.1531 ± 0.0246 (n=5),172.1543 ± 26.0239 (n=5),0.1589 ± 0.0240 (n=5),8.3620 ± 2.1247 (n=5),8.3620 ± 2.1247 (n=5),352284.3312 ± 76402.2472 (n=5),0.3002 ± 0.0651 (n=5),0.1406 ± 0.0210 (n=5),0.1406 ± 0.0210 (n=5),373.7128 ± 44.7730 (n=5),0.3450 ± 0.0413 (n=5),0.3971 ± 0.0859 (n=5),172.1543 ± 26.0239 (n=5),0.1589 ± 0.0240 (n=5),8.3620 ± 2.1247 (n=5),8.3620 ± 2.1247 (n=5),352284.3312 ± 76402.2472 (n=5),0.3002 ± 0.0651 (n=5),0.1406 ± 0.0210 (n=5),0.1406 ± 0.0210 (n=5),373.7128 ± 44.7730 (n=5),0.3450 ± 0.0413 (n=5)
9,100,0.0010,100.0,0.4035 ± 0.2039 (n=5),0.0164 ± 0.0090 (n=5),104.7695 ± 23.9430 (n=5),0.0967 ± 0.0221 (n=5),8.4178 ± 1.8669 (n=5),8.4178 ± 1.8669 (n=5),18943.3039 ± 8993.4264 (n=5),0.0161 ± 0.0077 (n=5),0.1447 ± 0.0204 (n=5),0.1447 ± 0.0204 (n=5),130.1475 ± 31.9227 (n=5),0.1201 ± 0.0295 (n=5),0.0164 ± 0.0090 (n=5),104.7695 ± 23.9430 (n=5),0.0967 ± 0.0221 (n=5),8.4178 ± 1.8669 (n=5),8.4178 ± 1.8669 (n=5),18943.3039 ± 8993.4264 (n=5),0.0161 ± 0.0077 (n=5),0.1447 ± 0.0204 (n=5),0.1447 ± 0.0204 (n=5),130.1475 ± 31.9227 (n=5),0.1201 ± 0.0295 (n=5),137.9857 ± 25.3293 (n=5),0.1274 ± 0.0234 (n=5),6.1659 ± 0.6558 (n=5),6.1659 ± 0.6558 (n=5),349737.0094 ± 175220.3040 (n=5),0.2981 ± 0.1493 (n=5),0.1678 ± 0.0199 (n=5),0.1678 ± 0.0199 (n=5),332.3013 ± 70.3087 (n=5),0.3068 ± 0.0649 (n=5),0.3965 ± 0.2084 (n=5),147.2262 ± 34.1757 (n=5),0.1359 ± 0.0315 (n=5),6.7649 ± 1.3720 (n=5),6.7649 ± 1.3720 (n=5),344431.8406 ± 179211.5426 (n=5),0.2935 ± 0.1527 (n=5),0.1601 ± 0.0320 (n=5),0.1601 ± 0.0320 (n=5),338.8944 ± 75.1503 (n=5),0.3129 ± 0.0694 (n=5)
10,100,0.0005,100.0,0.4398 ± 0.2567 (n=5),0.0135 ± 0.0059 (n=5),97.6462 ± 19.5047 (n=5),0.0901 ± 0.0180 (n=5),7.9199 ± 1.7684 (n=5),7.9199 ± 1.7684 (n=5),16245.0691 ± 6529.5060 (n=5),0.0138 ± 0.0056 (n=5),0.1530 ± 0.0218 (n=5),0.1530 ± 0.0218 (n=5),120.9233 ± 25.4324 (n=5),0.1116 ± 0.0235 (n=5),0.0135 ± 0.0059 (n=5),97.6462 ± 19.5047 (n=5),0.0901 ± 0.0180 (n=5),7.9199 ± 1.7684 (n=5),7.9199 ± 1.7684 (n=5),16245.0691 ± 6529.5060 (n=5),0.0138 ± 0.0056 (n=5),0.1530 ± 0.0218 (n=5),0.1530 ± 0.0218 (n=5),120.9233 ± 25.4324 (n=5),0.1116 ± 0.0235 (n=5),137.9411 ± 23.0610 (n=5),0.1273 ± 0.0213 (n=5),6.2301 ± 0.9328 (n=5),6.2301 ± 0.9328 (n=5),380754.6531 ± 220136.6451 (n=5),0.3245 ± 0.1876 (n=5),0.1746 ± 0.0222 (n=5),0.1746 ± 0.0222 (n=5),339.5833 ± 74.9843 (n=5),0.3135 ± 0.0692 (n=5),0.4390 ± 0.2574 (n=5),141.6336 ± 24.2277 (n=5),0.1308 ± 0.0224 (n=5),6.4819 ± 1.3095 (n=5),6.4819 ± 1.3095 (n=5),380431.0187 ± 220457.7314 (n=5),0.3242 ± 0.1879 (n=5),0.1701 ± 0.0280 (n=5),0.1701 ± 0.0280 (n=5),342.8983 ± 72.5357 (n=5),0.3166 ± 0.0670 (n=5)
3,10,0.0010,10.0,0.4855 ± 0.2546 (n=5),0.0302 ± 0.0299 (n=5),128.3049 ± 62.4210 (n=5),0.1184 ± 0.0576 (n=5),8.7806 ± 4.2180 (n=5),8.7806 ± 4.2180 (n=5),33870.1176 ± 32330.2110 (n=5),0.0289 ± 0.0276 (n=5),0.1614 ± 0.0489 (n=5),0.1614 ± 0.0489 (n=5),162.8724 ± 82.1563 (n=5),0.1504 ± 0.0758 (n=5),0.0302 ± 0.0299 (n=5),128.3049 ± 62.4210 (n=5),0.1184 ± 0.0576 (n=5),8.7806 ± 4.2180 (n=5),8.7806 ± 4.2180 (n=5),33870.1176 ± 32330.2110 (n=5),0.0289 ± 0.0276 (n=5),0.1614 ± 0.0489 (n=5),0.1614 ± 0.0489 (n=5),162.8724 ± 82.1563 (n=5),0.1504 ± 0.0758 (n=5),152.0667 ± 54.9046 (n=5),0.1404 ± 0.0507 (n=5),7.3885 ± 4.0037 (n=5),7.3885 ± 4.0037 (n=5),432979.3187 ± 227307.1094 (n=5),0.3690 ± 0.1937 (n=5),0.1850 ± 0.0464 (n=5),0.1850 ± 0.0464 (n=5),375.5414 ± 102.9577 (n=5),0.3467 ± 0.0950 (n=5),0.4767 ± 0.2538 (n=5),168.4002 ± 70.9128 (n=5),0.1555 ± 0.0655 (n=5),8.9930 ± 6.1560 (n=5),8.9930 ± 6.1560 (n=5),426706.9156 ± 227514.2781 (n=5),0.3637 ± 0.1939 (n=5),0.1761 ± 0.0578 (n=5),0.1761 ± 0.0578 (n=5),389.2922 ± 113.8087 (n=5),0.3594 ± 0.1051 (n=5)
4,10,0.0005,10.0,0.5135 ± 0.2791 (n=5),0.0237 ± 0.0155 (n=5),121.1249 ± 38.1166 (n=5),0.1118 ± 0.0352 (n=5),8.2521 ± 2.5966 (n=5),8.2521 ± 2.5966 (n=5),27071.7518 ± 16949.6202 (n=5),0.0231 ± 0.0144 (n=5),0.1578 ± 0.0341 (n=5),0.1578 ± 0.0341 (n=5),154.0605 ± 49.4565 (n=5),0.1422 ± 0.0457 (n=5),0.0237 ± 0.0155 (n=5),121.1249 ± 38.1166 (n=5),0.1118 ± 0.0352 (n=5),8.2521 ± 2.5966 (n=5),8.2521 ± 2.5966 (n=5),27071.7518 ± 16949.6202 (n=5),0.0231 ± 0.0144 (n=5),0.1578 ± 0.0341 (n=5),0.1578 ± 0.0341 (n=5),154.0605 ± 49.4565 (n=5),0.1422 ± 0.0457 (n=5),153.9798 ± 35.4806 (n=5),0.1421 ± 0.0328 (n=5),6.8156 ± 2.0819 (n=5),6.8156 ± 2.0819 (n=5),457471.9250 ± 246951.9277 (n=5),0.3899 ± 0.2105 (n=5),0.1791 ± 0.0343 (n=5),0.1791 ± 0.0343 (n=5),384.6586 ± 85.4290 (n=5),0.3551 ± 0.0789 (n=5),0.5101 ± 0.2823 (n=5),162.1429 ± 38.7969 (n=5),0.1497 ± 0.0358 (n=5),7.4907 ± 2.9658 (n=5),7.4907 ± 2.9658 (n=5),455115.5500 ± 249061.0007 (n=5),0.3879 ± 0.2123 (n=5),0.1712 ± 0.0378 (n=5),0.1712 ± 0.0378 (n=5),391.5658 ± 81.9254 (n=5),0.3615 ± 0.0756 (n=5)
11,100,0.0001,100.0,0.5158 ± 0.3240 (n=5),0.0284 ± 0.0163 (n=5),135.2399 ± 37.0217 (n=5),0.1248 ± 0.0342 (n=5),10.5247 ± 3.1452 (n=5),10.5247 ± 3.1452 (n=5),32496.3781 ± 18061.7689 (n=5),0.0277 ± 0.0154 (n=5),0.1236 ± 0.0275 (n=5),0.1236 ± 0.0275 (n=5),168.9027 ± 47.0540 (n=5),0.1559 ± 0.0434 (n=5),0.0284 ± 0.0163 (n=5),135.2399 ± 37.0217 (n=5),0.1248 ± 0.0342 (n=5),10.5247 ± 3.1452 (n=5),10.5247 ± 3.1452 (n=5),32496.3781 ± 18061.7689 (n=5),0.0277 ± 0.0154 (n=5),0.1236 ± 0.0275 (n=5),0.1236 ± 0.0275 (n=5),168.9027 ± 47.0540 (n=5),0.1559 ± 0.0434 (n=5),182.2914 ± 49.7012 (n=5),0.1683 ± 0.0459 (n=5),8.0722 ± 2.2005 (n=5),8.0722 ± 2.2005 (n=5),449500.2594 ± 280348.7682 (n=5),0.3831 ± 0.2389 (n=5),0.1341 ± 0.0286 (n=5),0.1341 ± 0.0286 (n=5),399.4478 ± 111.0080 (n=5),0.3688 ± 0.1025 (n=5),0.5158 ± 0.3240 (n=5),182.2914 ± 49.7012 (n=5),0.1683 ± 0.0459 (n=5),8.0722 ± 2.2005 (n=5),8.0722 ± 2.2005 (n=5),449500.2594 ± 280348.7682 (n=5),0.3831 ± 0.2389 (n=5),0.1341 ± 0.0286 (n=5),0.1341 ± 0.0286 (n=5),399.4478 ± 111.0080 (n=5),0.3688 ± 0.1025 (n=5)
5,10,0.0001,10.0,0.6455 ± 0.3076 (n=5),0.0679 ± 0.0601 (n=5),194.6752 ± 76.3781 (n=5),0.1797 ± 0.0705 (n=5),12.5640 ± 4.2246 (n=5),12.5640 ± 4.2246 (n=5),75063.0152 ± 64052.5619 (n=5),0.0640 ± 0.0546 (n=5),0.1115 ± 0.0317 (n=5),0.1115 ± 0.0317 (n=5),249.8030 ± 97.2397 (n=5),0.2306 ± 0.0898 (n=5),0.0679 ± 0.0601 (n=5),194.6752 ± 76.3781 (n=5),0.1797 ± 0.0705 (n=5),12.5640 ± 4.2246 (n=5),12.5640 ± 4.2246 (n=5),75063.0152 ± 64052.5619 (n=5),0.0640 ± 0.0546 (n=5),0.1115 ± 0.0317 (n=5),0.1115 ± 0.0317 (n=5),249.8030 ± 97.2397 (n=5),0.2306 ± 0.0898 (n=5),236.7103 ± 87.9209 (n=5),0.2185 ± 0.0812 (n=5),13.7249 ± 8.2321 (n=5),13.7249 ± 8.2321 (n=5),582568.9313 ± 280214.2564 (n=5),0.4965 ± 0.2388 (n=5),0.1229 ± 0.0314 (n=5),0.1229 ± 0.0314 (n=5),494.3363 ± 142.7053 (n=5),0.4564 ± 0.1317 (n=5),0.6453 ± 0.3079 (n=5),238.9122 ± 85.9958 (n=5),0.2206 ± 0.0794 (n=5),13.9266 ± 8.1407 (n=5),13.9266 ± 8.1407 (n=5),582603.3750 ± 280169.1637 (n=5),0.4965 ± 0.2388 (n=5),0.1216 ± 0.0303 (n=5),0.1216 ± 0.0303 (n=5),496.4103 ± 140.3629 (n=5),0.4583 ± 0.1296 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.statistical_models_wrapper.StatisticalBaselineWrapper (linear) on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.seq_len,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
0,1,0.0010,1.0,19.7003 ± 24.7142 (n=5),0.3216 ± 0.1614 (n=5),417.9388 ± 107.8377 (n=5),0.3858 ± 0.0996 (n=5),35.4759 ± 16.7702 (n=5),35.4759 ± 16.7702 (n=5),324925.1547 ± 154032.0482 (n=5),0.2769 ± 0.1313 (n=5),0.0550 ± 0.0140 (n=5),0.0550 ± 0.0140 (n=5),527.4837 ± 137.1559 (n=5),0.4870 ± 0.1266 (n=5),0.3216 ± 0.1614 (n=5),417.9388 ± 107.8377 (n=5),0.3858 ± 0.0996 (n=5),35.4759 ± 16.7702 (n=5),35.4759 ± 16.7702 (n=5),324925.1547 ± 154032.0482 (n=5),0.2769 ± 0.1313 (n=5),0.0550 ± 0.0140 (n=5),0.0550 ± 0.0140 (n=5),527.4837 ± 137.1559 (n=5),0.4870 ± 0.1266 (n=5),494.2961 ± 106.5868 (n=5),0.4563 ± 0.0984 (n=5),24.8409 ± 8.6942 (n=5),24.8409 ± 8.6942 (n=5),17428995.4000 ± 21807867.8288 (n=5),14.8535 ± 18.5853 (n=5),0.0670 ± 0.0193 (n=5),0.0670 ± 0.0193 (n=5),1765.1415 ± 1018.4953 (n=5),1.6295 ± 0.9402 (n=5),18.6284 ± 24.2451 (n=5),574.6799 ± 163.9851 (n=5),0.5305 ± 0.1514 (n=5),34.4862 ± 15.7397 (n=5),34.4861 ± 15.7397 (n=5),16499097.1000 ± 21403616.1701 (n=5),14.0610 ± 18.2408 (n=5),0.0597 ± 0.0181 (n=5),0.0597 ± 0.0181 (n=5),1732.5736 ± 1124.6968 (n=5),1.5994 ± 1.0383 (n=5)
2,1,0.0001,1.0,44.5721 ± 44.1234 (n=5),4.0791 ± 5.3135 (n=5),1536.0023 ± 1417.5653 (n=5),1.4180 ± 1.3086 (n=5),96.3009 ± 66.0109 (n=5),96.3009 ± 66.0109 (n=5),4640612.1188 ± 6024748.0912 (n=5),3.9549 ± 5.1345 (n=5),0.0279 ± 0.0252 (n=5),0.0279 ± 0.0252 (n=5),1660.1187 ± 1418.6836 (n=5),1.5326 ± 1.3097 (n=5),4.0791 ± 5.3135 (n=5),1536.0023 ± 1417.5653 (n=5),1.4180 ± 1.3086 (n=5),96.3009 ± 66.0109 (n=5),96.3009 ± 66.0109 (n=5),4640612.1188 ± 6024748.0912 (n=5),3.9549 ± 5.1345 (n=5),0.0279 ± 0.0252 (n=5),0.0279 ± 0.0252 (n=5),1660.1187 ± 1418.6836 (n=5),1.5326 ± 1.3097 (n=5),1445.8746 ± 1130.8219 (n=5),1.3348 ± 1.0439 (n=5),65.4750 ± 29.8400 (n=5),65.4750 ± 29.8400 (n=5),40117152.1812 ± 39804932.9676 (n=5),34.1890 ± 33.9229 (n=5),0.0300 ± 0.0255 (n=5),0.0300 ± 0.0255 (n=5),3128.7685 ± 2315.9489 (n=5),2.8884 ± 2.1380 (n=5),44.1803 ± 43.7122 (n=5),1767.4689 ± 1537.7222 (n=5),1.6317 ± 1.4196 (n=5),81.2994 ± 48.1506 (n=5),81.2994 ± 48.1506 (n=5),40233524.2188 ± 39954209.2529 (n=5),34.2881 ± 34.0501 (n=5),0.0291 ± 0.0262 (n=5),0.0291 ± 0.0262 (n=5),3352.1283 ± 2581.6687 (n=5),3.0946 ± 2.3833 (n=5)
1,1,0.0005,1.0,46.2265 ± 45.4010 (n=5),3.7774 ± 4.9039 (n=5),1472.8694 ± 1359.3243 (n=5),1.3597 ± 1.2549 (n=5),91.5271 ± 62.4167 (n=5),91.5271 ± 62.4167 (n=5),4299998.7313 ± 5561258.1543 (n=5),3.6646 ± 4.7395 (n=5),0.0287 ± 0.0263 (n=5),0.0287 ± 0.0263 (n=5),1596.9728 ± 1361.4182 (n=5),1.4743 ± 1.2568 (n=5),3.7774 ± 4.9039 (n=5),1472.8694 ± 1359.3243 (n=5),1.3597 ± 1.2549 (n=5),91.5271 ± 62.4167 (n=5),91.5271 ± 62.4167 (n=5),4299998.7313 ± 5561258.1543 (n=5),3.6646 ± 4.7395 (n=5),0.0287 ± 0.0263 (n=5),0.0287 ± 0.0263 (n=5),1596.9728 ± 1361.4182 (n=5),1.4743 ± 1.2568 (n=5),838.5510 ± 462.3521 (n=5),0.7741 ± 0.4268 (n=5),40.7542 ± 17.6707 (n=5),40.7542 ± 17.6707 (n=5),40992721.8375 ± 40277672.1885 (n=5),34.9352 ± 34.3258 (n=5),0.0436 ± 0.0122 (n=5),0.0436 ± 0.0122 (n=5),2740.7376 ± 1872.3706 (n=5),2.5301 ± 1.7285 (n=5),44.1901 ± 43.7457 (n=5),1704.7104 ± 1482.5539 (n=5),1.5737 ± 1.3686 (n=5),77.8492 ± 45.9954 (n=5),77.8492 ± 45.9954 (n=5),40157508.9438 ± 39882362.6423 (n=5),34.2234 ± 33.9889 (n=5),0.0308 ± 0.0283 (n=5),0.0308 ± 0.0283 (n=5),3309.9976 ± 2544.7016 (n=5),3.0557 ± 2.3492 (n=5)
4,10,0.0005,10.0,493.1556 ± 248.4080 (n=5),3.4106 ± 2.8200 (n=5),1300.2638 ± 508.1093 (n=5),1.2004 ± 0.4691 (n=5),121.0303 ± 86.4326 (n=5),121.0303 ± 86.4326 (n=5),3412727.8125 ± 2619198.5030 (n=5),2.9084 ± 2.2322 (n=5),0.0188 ± 0.0074 (n=5),0.0188 ± 0.0074 (n=5),1665.3921 ± 612.3210 (n=5),1.5374 ± 0.5653 (n=5),3.4106 ± 2.8200 (n=5),1300.2638 ± 508.1093 (n=5),1.2004 ± 0.4691 (n=5),121.0303 ± 86.4326 (n=5),121.0303 ± 86.4326 (n=5),3412727.8125 ± 2619198.5030 (n=5),2.9084 ± 2.2322 (n=5),0.0188 ± 0.0074 (n=5),0.0188 ± 0.0074 (n=5),1665.3921 ± 612.3210 (n=5),1.5374 ± 0.5653 (n=5),2309.1333 ± 455.8261 (n=5),2.1317 ± 0.4208 (n=5),78.6807 ± 20.3611 (n=5),78.6807 ± 20.3611 (n=5),434634403.2000 ± 218792987.2258 (n=5),370.4076 ± 186.4615 (n=5),0.0250 ± 0.0054 (n=5),0.0250 ± 0.0054 (n=5),9354.1512 ± 2014.0474 (n=5),8.6354 ± 1.8593 (n=5),465.9919 ± 276.4451 (n=5),2549.2251 ± 429.3727 (n=5),2.3533 ± 0.3964 (n=5),100.8232 ± 37.5576 (n=5),100.8232 ± 37.5576 (n=5),410899862.4000 ± 243294694.2410 (n=5),350.1804 ± 207.3426 (n=5),0.0212 ± 0.0075 (n=5),0.0212 ± 0.0075 (n=5),9240.2802 ± 2205.7838 (n=5),8.5303 ± 2.0363 (n=5)
3,10,0.0010,10.0,498.5383 ± 247.5624 (n=5),3.7319 ± 2.8651 (n=5),1382.3739 ± 582.1845 (n=5),1.2762 ± 0.5375 (n=5),128.5504 ± 88.9158 (n=5),128.5504 ± 88.9158 (n=5),3785672.1875 ± 2796497.1313 (n=5),3.2263 ± 2.3833 (n=5),0.0178 ± 0.0089 (n=5),0.0178 ± 0.0089 (n=5),1748.4572 ± 688.1042 (n=5),1.6141 ± 0.6352 (n=5),3.7319 ± 2.8651 (n=5),1382.3739 ± 582.1845 (n=5),1.2762 ± 0.5375 (n=5),128.5504 ± 88.9158 (n=5),128.5504 ± 88.9158 (n=5),3785672.1875 ± 2796497.1313 (n=5),3.2263 ± 2.3833 (n=5),0.0178 ± 0.0089 (n=5),0.0178 ± 0.0089 (n=5),1748.4572 ± 688.1042 (n=5),1.6141 ± 0.6352 (n=5),2196.8107 ± 448.8851 (n=5),2.0280 ± 0.4144 (n=5),68.5404 ± 16.4290 (n=5),68.5404 ± 16.4290 (n=5),439309820.8000 ± 218054857.9613 (n=5),374.3922 ± 185.8325 (n=5),0.0280 ± 0.0053 (n=5),0.0280 ± 0.0053 (n=5),9288.8043 ± 2001.5062 (n=5),8.5751 ± 1.8477 (n=5),465.5906 ± 273.1913 (n=5),2628.3536 ± 521.8055 (n=5),2.4264 ± 0.4817 (n=5),106.6694 ± 44.4305 (n=5),106.6694 ± 44.4305 (n=5),410608627.2000 ± 240419959.2749 (n=5),349.9322 ± 204.8927 (n=5),0.0199 ± 0.0092 (n=5),0.0199 ± 0.0092 (n=5),9307.0712 ± 2177.3483 (n=5),8.5919 ± 2.0100 (n=5)
5,10,0.0001,10.0,549.8941 ± 395.5674 (n=5),6.0080 ± 2.9020 (n=5),1891.6947 ± 594.0723 (n=5),1.7463 ± 0.5484 (n=5),160.2141 ± 70.4081 (n=5),160.2141 ± 70.4081 (n=5),6152692.5000 ± 2868678.5054 (n=5),5.2435 ± 2.4448 (n=5),0.0121 ± 0.0084 (n=5),0.0121 ± 0.0084 (n=5),2318.2609 ± 589.5084 (n=5),2.1401 ± 0.5442 (n=5),6.0080 ± 2.9020 (n=5),1891.6947 ± 594.0723 (n=5),1.7463 ± 0.5484 (n=5),160.2141 ± 70.4081 (n=5),160.2141 ± 70.4081 (n=5),6152692.5000 ± 2868678.5054 (n=5),5.2435 ± 2.4448 (n=5),0.0121 ± 0.0084 (n=5),0.0121 ± 0.0084 (n=5),2318.2609 ± 589.5084 (n=5),2.1401 ± 0.5442 (n=5),2822.9235 ± 742.6112 (n=5),2.6060 ± 0.6856 (n=5),114.1125 ± 25.1562 (n=5),114.1125 ± 25.1562 (n=5),484932902.4000 ± 348583201.4880 (n=5),413.2734 ± 297.0724 (n=5),0.0183 ± 0.0054 (n=5),0.0183 ± 0.0054 (n=5),10023.4050 ± 3221.9568 (n=5),9.2532 ± 2.9744 (n=5),542.8161 ± 402.7115 (n=5),3215.9235 ± 793.9671 (n=5),2.9688 ± 0.7330 (n=5),134.2618 ± 31.8577 (n=5),134.2618 ± 31.8577 (n=5),479063136.0000 ± 354764846.8334 (n=5),408.2711 ± 302.3405 (n=5),0.0128 ± 0.0075 (n=5),0.0128 ± 0.0075 (n=5),10237.7012 ± 3284.2147 (n=5),9.4511 ± 3.0319 (n=5)
8,50,0.0001,50.0,2158.4633 ± 1152.3669 (n=5),32.3389 ± 33.1581 (n=5),4381.4331 ± 2652.5868 (n=5),4.0448 ± 2.4488 (n=5),321.5570 ± 161.1932 (n=5),321.5570 ± 161.1932 (n=5),36241231.6000 ± 40008850.8436 (n=5),30.8858 ± 34.0967 (n=5),0.0053 ± 0.0025 (n=5),0.0053 ± 0.0025 (n=5),5191.7345 ± 2724.2119 (n=5),4.7928 ± 2.5149 (n=5),32.3389 ± 33.1581 (n=5),4381.4331 ± 2652.5868 (n=5),4.0448 ± 2.4488 (n=5),321.5570 ± 161.1932 (n=5),321.5570 ± 161.1932 (n=5),36241231.6000 ± 40008850.8436 (n=5),30.8858 ± 34.0967 (n=5),0.0053 ± 0.0025 (n=5),0.0053 ± 0.0025 (n=5),5191.7345 ± 2724.2119 (n=5),4.7928 ± 2.5149 (n=5),6460.0639 ± 1010.5063 (n=5),5.9637 ± 0.9329 (n=5),219.0702 ± 51.7723 (n=5),219.0702 ± 51.7723 (n=5),1883624691.2000 ± 1002511359.6631 (n=5),1605.2779 ± 854.3682 (n=5),0.0066 ± 0.0023 (n=5),0.0066 ± 0.0023 (n=5),20695.1859 ± 4376.7502 (n=5),19.1050 ± 4.0404 (n=5),2137.7351 ± 1147.2050 (n=5),7387.0230 ± 2804.0263 (n=5),6.8194 ± 2.5886 (n=5),273.3813 ± 144.0670 (n=5),273.3813 ± 144.0670 (n=5),1869725324.8000 ± 998863674.8155 (n=5),1593.4325 ± 851.2595 (n=5),0.0060 ± 0.0027 (n=5),0.0060 ± 0.0027 (n=5),21444.7645 ± 5156.5863 (n=5),19.7970 ± 4.7604 (n=5)
7,50,0.0005,50.0,2199.7993 ± 1160.7346 (n=5),20.2637 ± 20.0291 (n=5),3400.7156 ± 2009.6205 (n=5),3.1394 ± 1.8552 (n=5),256.9579 ± 147.6849 (n=5),256.9579 ± 147.6849 (n=5),22589764.8000 ± 23157461.6154 (n=5),19.2516 ± 19.7354 (n=5),0.0067 ± 0.0033 (n=5),0.0067 ± 0.0033 (n=5),4090.2020 ± 2221.1286 (n=5),3.7759 ± 2.0505 (n=5),20.2637 ± 20.0291 (n=5),3400.7156 ± 2009.6205 (n=5),3.1394 ± 1.8552 (n=5),256.9579 ± 147.6849 (n=5),256.9579 ± 147.6849 (n=5),22589764.8000 ± 23157461.6154 (n=5),19.2516 ± 19.7354 (n=5),0.0067 ± 0.0033 (n=5),0.0067 ± 0.0033 (n=5),4090.2020 ± 2221.1286 (n=5),3.7759 ± 2.0505 (n=5),5494.0004 ± 942.6349 (n=5),5.0719 ± 0.8702 (n=5),160.8582 ± 56.8738 (n=5),160.8582 ± 56.8738 (n=5),1917602521.6000 ± 1010102312.2636 (n=5),1634.2346 ± 860.8374 (n=5),0.0093 ± 0.0037 (n=5),0.0093 ± 0.0037 (n=5),19925.3066 ± 4393.1755 (n=5),18.3943 ± 4.0556 (n=5),2088.2365 ± 1124.1470 (n=5),6362.8303 ± 2106.4237 (n=5),5.8739 ± 1.9446 (n=5),210.4152 ± 118.1220 (n=5),210.4152 ± 118.1220 (n=5),1823535808.0000 ± 978051602.7374 (n=5),1554.0685 ± 833.5229 (n=5),0.0080 ± 0.0040 (n=5),0.0080 ± 0.0040 (n=5),20335.5590 ± 4668.5586 (n=5),18.7730 ± 4.3098 (n=5)
6,50,0.0010,50.0,2244.0759 ± 1231.2225 (n=5),16.4482 ± 15.1949 (n=5),2974.8939 ± 1576.4529 (n=5),2.7463 ± 1.4553 (n=5),243.0123 ± 150.5905 (n=5),243.0123 ± 150.5905 (n=5),17462692.0000 ± 16031383.0994 (n=5),14.8822 ± 13.6624 (n=5),0.0079 ± 0.0035 (n=5),0.0079 ± 0.0035 (n=5),3648.3411 ± 1841.9725 (n=5),3.3680 ± 1.7004 (n=5),16.4482 ± 15.1949 (n=5),2974.8939 ± 1576.4529 (n=5),2.7463 ± 1.4553 (n=5),243.0123 ± 150.5905 (n=5),243.0123 ± 150.5905 (n=5),17462692.0000 ± 16031383.0994 (n=5),14.8822 ± 13.6624 (n=5),0.0079 ± 0.0035 (n=5),0.0079 ± 0.0035 (n=5),3648.3411 ± 1841.9725 (n=5),3.3680 ± 1.7004 (n=5),5234.3288 ± 1114.8396 (n=5),4.8321 ± 1.0292 (n=5),145.7196 ± 56.6597 (n=5),145.7196 ± 56.6597 (n=5),1955647680.0000 ± 1071887145.1885 (n=5),1666.6579 ± 913.4924 (n=5),0.0110 ± 0.0043 (n=5),0.0110 ± 0.0043 (n=5),19768.2264 ± 4915.5303 (n=5),18.2493 ± 4.5378 (n=5),2067.9582 ± 1151.3686 (n=5),5907.3960 ± 1665.0067 (n=5),5.4535 ± 1.5371 (n=5),187.5554 ± 98.6585 (n=5),187.5554 ± 98.6585 (n=5),1804566656.0000 ± 1001641235.1804 (n=5),1537.9024 ± 853.6268 (n=5),0.0098 ± 0.0043 (n=5),0.0098 ± 0.0043 (n=5),19695.7299 ± 4597.7988 (n=5),18.1823 ± 4.2445 (n=5)
11,100,0.0001,100.0,2449.8937 ± 642.4801 (n=5),71.3437 ± 44.8187 (n=5),6297.4775 ± 1782.5844 (n=5),5.8136 ± 1.6456 (n=5),601.5129 ± 245.4431 (n=5),601.5129 ± 245.4431 (n=5),69750724.0000 ± 40779144.0073 (n=5),59.4435 ± 34.7531 (n=5),0.0022 ± 0.0008 (n=5),0.0022 ± 0.0008 (n=5),7726.4398 ± 1845.1740 (n=5),7.1328 ± 1.7034 (n=5),71.3437 ± 44.8187 (n=5),6297.4775 ± 1782.5844 (n=5),5.8136 ± 1.6456 (n=5),601.5129 ± 245.4431 (n=5),601.5129 ± 245.4431 (n=5),69750724.0000 ± 40779144.0073 (n=5),59.4435 ± 34.7531 (n=5),0.0022 ± 0.0008 (n=5),0.0022 ± 0.0008 (n=5),7726.4398 ± 1845.1740 (n=5),7.1328 ± 1.7034 (n=5),9207.2640 ± 1935.2652 (n=5),8.4998 ± 1.7866 (n=5),442.9372 ± 161.8094 (n=5),442.9372 ± 161.8095 (n=5),2111684505.6000 ± 553442072.0423 (n=5),1799.6371 ± 471.6590 (n=5),0.0034 ± 0.0013 (n=5),0.0034 ± 0.0013 (n=5),24150.8770 ± 3279.7464 (n=5),22.2952 ± 3.0277 (n=5),2439.7983 ± 641.1154 (n=5),9600.1167 ± 2358.9832 (n=5),8.8625 ± 2.1777 (n=5),463.5838 ± 184.7143 (n=5),463.5838 ± 184.7143 (n=5),2105108505.6000 ± 553272020.5213 (n=5),1794.0326 ± 471.5139 (n=5),0.0035 ± 0.0014 (n=5),0.0035 ± 0.0014 (n=5),24400.6738 ± 3456.2557 (n=5),22.5258 ± 3.1907 (n=5)
10,100,0.0005,100.0,2494.1428 ± 658.8474 (n=5),75.8352 ± 45.8632 (n=5),6413.0419 ± 1671.7737 (n=5),5.9203 ± 1.5433 (n=5),643.7905 ± 272.8559 (n=5),643.7905 ± 272.8559 (n=5),73230863.2000 ± 40568350.1000 (n=5),62.4094 ± 34.5735 (n=5),0.0026 ± 0.0007 (n=5),0.0026 ± 0.0007 (n=5),7882.4042 ± 1766.7299 (n=5),7.2767 ± 1.6310 (n=5),75.8352 ± 45.8632 (n=5),6413.0419 ± 1671.7737 (n=5),5.9203 ± 1.5433 (n=5),643.7905 ± 272.8559 (n=5),643.7905 ± 272.8559 (n=5),73230863.2000 ± 40568350.1000 (n=5),62.4094 ± 34.5735 (n=5),0.0026 ± 0.0007 (n=5),0.0026 ± 0.0007 (n=5),7882.4042 ± 1766.7299 (n=5),7.2767 ± 1.6310 (n=5),8396.1014 ± 1069.7409 (n=5),7.7510 ± 0.9875 (n=5),383.7408 ± 93.5311 (n=5),383.7408 ± 93.5311 (n=5),2146252211.2000 ± 566116960.4660 (n=5),1829.0966 ± 482.4608 (n=5),0.0037 ± 0.0010 (n=5),0.0037 ± 0.0010 (n=5),23767.2293 ± 3064.3971 (n=5),21.9410 ± 2.8289 (n=5),2431.8531 ± 638.7757 (n=5),9706.3257 ± 2249.8919 (n=5),8.9605 ± 2.0770 (n=5),480.8551 ± 190.0656 (n=5),480.8551 ± 190.0656 (n=5),2098014105.6000 ± 550945714.3926 (n=5),1787.9866 ± 469.5315 (n=5),0.0029 ± 0.0012 (n=5),0.0029 ± 0.0012 (n=5),24404.7195 ± 3381.5486 (n=5),22.5295 ± 3.1217 (n=5)
9,100,0.0010,100.0,2527.7535 ± 688.9545 (n=5),81.0798 ± 50.9256 (n=5),6391.2734 ± 1503.4937 (n=5),5.9002 ± 1.3880 (n=5),705.8422 ± 337.9407 (n=5),705.8422 ± 337.9407 (n=5),76263779.2000 ± 42996236.5607 (n=5),64.9941 ± 36.6426 (n=5),0.0026 ± 0.0008 (n=5),0.0026 ± 0.0008 (n=5),7960.3057 ± 1728.4524 (n=5),7.3487 ± 1.5956 (n=5),81.0798 ± 50.9256 (n=5),6391.2734 ± 1503.4937 (n=5),5.9002 ± 1.3880 (n=5),705.8422 ± 337.9407 (n=5),705.8422 ± 337.9407 (n=5),76263779.2000 ± 42996236.5607 (n=5),64.9941 ± 36.6426 (n=5),0.0026 ± 0.0008 (n=5),0.0026 ± 0.0008 (n=5),7960.3057 ± 1728.4524 (n=5),7.3487 ± 1.5956 (n=5),8021.3120 ± 792.4121 (n=5),7.4050 ± 0.7315 (n=5),357.4337 ± 70.0777 (n=5),357.4337 ± 70.0777 (n=5),2173678617.6000 ± 591151628.2811 (n=5),1852.4701 ± 503.7961 (n=5),0.0039 ± 0.0003 (n=5),0.0039 ± 0.0003 (n=5),23591.4723 ± 3029.9541 (n=5),21.7788 ± 2.7971 (n=5),2423.3880 ± 635.2010 (n=5),9645.4400 ± 2034.0950 (n=5),8.9043 ± 1.8778 (n=5),491.1902 ± 219.3110 (n=5),491.1902 ± 219.3110 (n=5),2089084032.0000 ± 547141119.7188 (n=5),1780.3762 ± 466.2890 (n=5),0.0034 ± 0.0006 (n=5),0.0034 ± 0.0006 (n=5),24318.1703 ± 3295.2263 (n=5),22.4496 ± 3.0420 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> baselines.timeseries_transformer_model.Timeseries_Transformer_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,model.transformer_args.seq_len,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
8,50,0.0001,50.0,0.0089 ± 0.0038 (n=5),0.0040 ± 0.0007 (n=5),63.1397 ± 5.7433 (n=5),0.0583 ± 0.0053 (n=5),4.1653 ± 0.1403 (n=5),4.1653 ± 0.1403 (n=5),6396.3324 ± 1336.6113 (n=5),0.0055 ± 0.0011 (n=5),0.2253 ± 0.0121 (n=5),0.2253 ± 0.0121 (n=5),73.5311 ± 7.1928 (n=5),0.0679 ± 0.0066 (n=5),0.0040 ± 0.0007 (n=5),63.1397 ± 5.7433 (n=5),0.0583 ± 0.0053 (n=5),4.1653 ± 0.1403 (n=5),4.1653 ± 0.1403 (n=5),6396.3324 ± 1336.6113 (n=5),0.0055 ± 0.0011 (n=5),0.2253 ± 0.0121 (n=5),0.2253 ± 0.0121 (n=5),73.5311 ± 7.1928 (n=5),0.0679 ± 0.0066 (n=5),57.7204 ± 3.3994 (n=5),0.0533 ± 0.0031 (n=5),3.5900 ± 0.3197 (n=5),3.5900 ± 0.3197 (n=5),9658.9764 ± 3350.4078 (n=5),0.0082 ± 0.0029 (n=5),0.2773 ± 0.0087 (n=5),0.2773 ± 0.0087 (n=5),86.0128 ± 10.3297 (n=5),0.0794 ± 0.0095 (n=5),0.0056 ± 0.0012 (n=5),59.3318 ± 3.9944 (n=5),0.0548 ± 0.0037 (n=5),3.2798 ± 0.4288 (n=5),3.2798 ± 0.4288 (n=5),6885.3126 ± 1282.6855 (n=5),0.0059 ± 0.0011 (n=5),0.2710 ± 0.0093 (n=5),0.2710 ± 0.0093 (n=5),79.6011 ± 7.1981 (n=5),0.0735 ± 0.0066 (n=5)
5,10,0.0001,10.0,0.0093 ± 0.0018 (n=5),0.0051 ± 0.0004 (n=5),70.0386 ± 2.5280 (n=5),0.0647 ± 0.0023 (n=5),4.3819 ± 0.2998 (n=5),4.3819 ± 0.2998 (n=5),7820.2930 ± 649.3859 (n=5),0.0067 ± 0.0006 (n=5),0.2265 ± 0.0056 (n=5),0.2265 ± 0.0056 (n=5),82.0641 ± 3.3824 (n=5),0.0758 ± 0.0031 (n=5),0.0051 ± 0.0004 (n=5),70.0386 ± 2.5280 (n=5),0.0647 ± 0.0023 (n=5),4.3819 ± 0.2998 (n=5),4.3819 ± 0.2998 (n=5),7820.2930 ± 649.3859 (n=5),0.0067 ± 0.0006 (n=5),0.2265 ± 0.0056 (n=5),0.2265 ± 0.0056 (n=5),82.0641 ± 3.3824 (n=5),0.0758 ± 0.0031 (n=5),63.5521 ± 1.3508 (n=5),0.0587 ± 0.0012 (n=5),3.4146 ± 0.1556 (n=5),3.4146 ± 0.1556 (n=5),10207.9910 ± 1431.5192 (n=5),0.0087 ± 0.0012 (n=5),0.2710 ± 0.0042 (n=5),0.2710 ± 0.0042 (n=5),92.0118 ± 4.2245 (n=5),0.0849 ± 0.0039 (n=5),0.0065 ± 0.0008 (n=5),65.1324 ± 1.4367 (n=5),0.0601 ± 0.0013 (n=5),3.2267 ± 0.2490 (n=5),3.2267 ± 0.2490 (n=5),8057.8392 ± 717.8036 (n=5),0.0069 ± 0.0006 (n=5),0.2717 ± 0.0047 (n=5),0.2717 ± 0.0047 (n=5),87.0507 ± 3.2005 (n=5),0.0804 ± 0.0030 (n=5)
3,10,0.0010,10.0,0.0103 ± 0.0033 (n=5),0.0052 ± 0.0013 (n=5),69.1587 ± 9.7220 (n=5),0.0638 ± 0.0090 (n=5),3.7874 ± 0.2785 (n=5),3.7874 ± 0.2785 (n=5),7884.3729 ± 1912.9650 (n=5),0.0067 ± 0.0016 (n=5),0.2321 ± 0.0254 (n=5),0.2321 ± 0.0254 (n=5),81.9057 ± 11.6368 (n=5),0.0756 ± 0.0107 (n=5),0.0052 ± 0.0013 (n=5),69.1587 ± 9.7220 (n=5),0.0638 ± 0.0090 (n=5),3.7874 ± 0.2785 (n=5),3.7874 ± 0.2785 (n=5),7884.3729 ± 1912.9650 (n=5),0.0067 ± 0.0016 (n=5),0.2321 ± 0.0254 (n=5),0.2321 ± 0.0254 (n=5),81.9057 ± 11.6368 (n=5),0.0756 ± 0.0107 (n=5),57.1252 ± 4.5563 (n=5),0.0527 ± 0.0042 (n=5),2.6754 ± 0.2522 (n=5),2.6754 ± 0.2522 (n=5),10568.7450 ± 2977.5895 (n=5),0.0090 ± 0.0025 (n=5),0.2876 ± 0.0103 (n=5),0.2876 ± 0.0103 (n=5),88.5040 ± 9.1495 (n=5),0.0817 ± 0.0084 (n=5),0.0062 ± 0.0011 (n=5),64.6628 ± 7.1605 (n=5),0.0597 ± 0.0066 (n=5),2.9564 ± 0.2935 (n=5),2.9564 ± 0.2935 (n=5),7766.5893 ± 1366.4463 (n=5),0.0066 ± 0.0012 (n=5),0.2791 ± 0.0075 (n=5),0.2791 ± 0.0075 (n=5),85.6895 ± 8.3467 (n=5),0.0791 ± 0.0077 (n=5)
4,10,0.0005,10.0,0.0109 ± 0.0048 (n=5),0.0049 ± 0.0014 (n=5),68.0589 ± 10.8041 (n=5),0.0628 ± 0.0100 (n=5),3.9745 ± 0.6506 (n=5),3.9745 ± 0.6506 (n=5),7593.6073 ± 2170.8856 (n=5),0.0065 ± 0.0019 (n=5),0.2315 ± 0.0262 (n=5),0.2315 ± 0.0262 (n=5),79.9963 ± 12.6897 (n=5),0.0738 ± 0.0117 (n=5),0.0049 ± 0.0014 (n=5),68.0589 ± 10.8041 (n=5),0.0628 ± 0.0100 (n=5),3.9745 ± 0.6506 (n=5),3.9745 ± 0.6506 (n=5),7593.6073 ± 2170.8856 (n=5),0.0065 ± 0.0019 (n=5),0.2315 ± 0.0262 (n=5),0.2315 ± 0.0262 (n=5),79.9963 ± 12.6897 (n=5),0.0738 ± 0.0117 (n=5),63.7925 ± 11.1855 (n=5),0.0589 ± 0.0103 (n=5),3.2473 ± 0.7134 (n=5),3.2473 ± 0.7134 (n=5),11962.9666 ± 4971.2505 (n=5),0.0102 ± 0.0042 (n=5),0.2580 ± 0.0354 (n=5),0.2580 ± 0.0354 (n=5),94.5779 ± 16.8892 (n=5),0.0873 ± 0.0156 (n=5),0.0059 ± 0.0014 (n=5),63.3401 ± 8.2789 (n=5),0.0585 ± 0.0076 (n=5),2.9948 ± 0.4671 (n=5),2.9948 ± 0.4671 (n=5),7432.3214 ± 1791.4784 (n=5),0.0063 ± 0.0015 (n=5),0.2753 ± 0.0109 (n=5),0.2753 ± 0.0109 (n=5),83.7830 ± 10.4472 (n=5),0.0773 ± 0.0096 (n=5)
11,100,0.0001,100.0,0.0121 ± 0.0086 (n=5),0.0042 ± 0.0013 (n=5),63.3256 ± 7.8165 (n=5),0.0585 ± 0.0072 (n=5),4.6827 ± 0.5611 (n=5),4.6827 ± 0.5611 (n=5),6482.5881 ± 1556.8411 (n=5),0.0055 ± 0.0013 (n=5),0.2119 ± 0.0186 (n=5),0.2119 ± 0.0186 (n=5),74.3214 ± 10.4347 (n=5),0.0686 ± 0.0096 (n=5),0.0042 ± 0.0013 (n=5),63.3256 ± 7.8165 (n=5),0.0585 ± 0.0072 (n=5),4.6827 ± 0.5611 (n=5),4.6827 ± 0.5611 (n=5),6482.5881 ± 1556.8411 (n=5),0.0055 ± 0.0013 (n=5),0.2119 ± 0.0186 (n=5),0.2119 ± 0.0186 (n=5),74.3214 ± 10.4347 (n=5),0.0686 ± 0.0096 (n=5),57.7260 ± 8.5762 (n=5),0.0533 ± 0.0079 (n=5),3.6405 ± 0.2951 (n=5),3.6405 ± 0.2951 (n=5),12368.5812 ± 7587.7963 (n=5),0.0105 ± 0.0065 (n=5),0.2762 ± 0.0137 (n=5),0.2762 ± 0.0137 (n=5),90.1409 ± 21.2225 (n=5),0.0832 ± 0.0196 (n=5),0.0079 ± 0.0069 (n=5),60.6006 ± 12.7221 (n=5),0.0559 ± 0.0117 (n=5),3.8083 ± 0.8227 (n=5),3.8083 ± 0.8227 (n=5),8868.0595 ± 6341.6781 (n=5),0.0076 ± 0.0054 (n=5),0.2627 ± 0.0257 (n=5),0.2627 ± 0.0257 (n=5),84.1963 ± 24.0124 (n=5),0.0777 ± 0.0222 (n=5)
2,1,0.0001,1.0,0.0121 ± 0.0010 (n=5),0.0086 ± 0.0004 (n=5),81.7882 ± 2.1453 (n=5),0.0755 ± 0.0020 (n=5),4.5864 ± 0.3051 (n=5),4.5864 ± 0.3051 (n=5),10802.1717 ± 429.1065 (n=5),0.0092 ± 0.0004 (n=5),0.2013 ± 0.0059 (n=5),0.2013 ± 0.0059 (n=5),102.1143 ± 2.1192 (n=5),0.0943 ± 0.0020 (n=5),0.0086 ± 0.0004 (n=5),81.7882 ± 2.1453 (n=5),0.0755 ± 0.0020 (n=5),4.5864 ± 0.3051 (n=5),4.5864 ± 0.3051 (n=5),10802.1717 ± 429.1065 (n=5),0.0092 ± 0.0004 (n=5),0.2013 ± 0.0059 (n=5),0.2013 ± 0.0059 (n=5),102.1143 ± 2.1192 (n=5),0.0943 ± 0.0020 (n=5),77.1478 ± 2.1264 (n=5),0.0712 ± 0.0020 (n=5),3.7404 ± 0.3033 (n=5),3.7404 ± 0.3033 (n=5),13780.5764 ± 995.4015 (n=5),0.0117 ± 0.0008 (n=5),0.2564 ± 0.0064 (n=5),0.2564 ± 0.0064 (n=5),112.1386 ± 2.9088 (n=5),0.1035 ± 0.0027 (n=5),0.0099 ± 0.0005 (n=5),82.0067 ± 3.2294 (n=5),0.0757 ± 0.0030 (n=5),4.1078 ± 0.4841 (n=5),4.1078 ± 0.4841 (n=5),11831.5354 ± 572.2858 (n=5),0.0101 ± 0.0005 (n=5),0.2336 ± 0.0112 (n=5),0.2336 ± 0.0112 (n=5),107.7928 ± 2.6564 (n=5),0.0995 ± 0.0025 (n=5)
0,1,0.0010,1.0,0.0158 ± 0.0060 (n=5),0.0082 ± 0.0026 (n=5),79.4987 ± 14.0330 (n=5),0.0734 ± 0.0130 (n=5),4.6295 ± 0.9603 (n=5),4.6295 ± 0.9603 (n=5),10198.1456 ± 2739.1581 (n=5),0.0087 ± 0.0023 (n=5),0.2111 ± 0.0349 (n=5),0.2111 ± 0.0349 (n=5),98.3834 ± 16.9452 (n=5),0.0908 ± 0.0156 (n=5),0.0082 ± 0.0026 (n=5),79.4987 ± 14.0330 (n=5),0.0734 ± 0.0130 (n=5),4.6295 ± 0.9603 (n=5),4.6295 ± 0.9603 (n=5),10198.1456 ± 2739.1581 (n=5),0.0087 ± 0.0023 (n=5),0.2111 ± 0.0349 (n=5),0.2111 ± 0.0349 (n=5),98.3834 ± 16.9452 (n=5),0.0908 ± 0.0156 (n=5),69.3834 ± 7.7115 (n=5),0.0641 ± 0.0071 (n=5),3.0259 ± 0.3084 (n=5),3.0259 ± 0.3084 (n=5),16011.2872 ± 5365.6106 (n=5),0.0136 ± 0.0046 (n=5),0.2636 ± 0.0086 (n=5),0.2636 ± 0.0086 (n=5),109.5944 ± 16.9351 (n=5),0.1012 ± 0.0156 (n=5),0.0098 ± 0.0021 (n=5),81.2861 ± 15.2991 (n=5),0.0750 ± 0.0141 (n=5),4.4859 ± 1.2265 (n=5),4.4859 ± 1.2265 (n=5),11570.8092 ± 2660.5592 (n=5),0.0099 ± 0.0023 (n=5),0.2299 ± 0.0340 (n=5),0.2299 ± 0.0340 (n=5),105.6112 ± 14.9657 (n=5),0.0975 ± 0.0138 (n=5)
10,100,0.0005,100.0,0.0177 ± 0.0089 (n=5),0.0040 ± 0.0012 (n=5),61.1818 ± 7.2988 (n=5),0.0565 ± 0.0067 (n=5),4.3621 ± 0.7491 (n=5),4.3621 ± 0.7491 (n=5),6052.8375 ± 1349.7980 (n=5),0.0052 ± 0.0012 (n=5),0.2218 ± 0.0172 (n=5),0.2218 ± 0.0172 (n=5),72.3943 ± 9.3382 (n=5),0.0668 ± 0.0086 (n=5),0.0040 ± 0.0012 (n=5),61.1818 ± 7.2988 (n=5),0.0565 ± 0.0067 (n=5),4.3621 ± 0.7491 (n=5),4.3621 ± 0.7491 (n=5),6052.8375 ± 1349.7980 (n=5),0.0052 ± 0.0012 (n=5),0.2218 ± 0.0172 (n=5),0.2218 ± 0.0172 (n=5),72.3943 ± 9.3382 (n=5),0.0668 ± 0.0086 (n=5),57.6228 ± 3.5905 (n=5),0.0532 ± 0.0033 (n=5),3.3945 ± 0.2409 (n=5),3.3945 ± 0.2409 (n=5),16729.4146 ± 7432.5768 (n=5),0.0143 ± 0.0063 (n=5),0.2705 ± 0.0195 (n=5),0.2705 ± 0.0195 (n=5),96.5172 ± 15.3610 (n=5),0.0891 ± 0.0142 (n=5),0.0063 ± 0.0045 (n=5),59.1910 ± 11.0020 (n=5),0.0546 ± 0.0102 (n=5),3.4413 ± 0.9190 (n=5),3.4413 ± 0.9190 (n=5),7300.9401 ± 4207.4581 (n=5),0.0062 ± 0.0036 (n=5),0.2640 ± 0.0222 (n=5),0.2640 ± 0.0222 (n=5),79.5972 ± 18.8657 (n=5),0.0735 ± 0.0174 (n=5)
7,50,0.0005,50.0,0.0188 ± 0.0103 (n=5),0.0051 ± 0.0014 (n=5),68.7524 ± 6.5850 (n=5),0.0635 ± 0.0061 (n=5),4.1881 ± 0.9708 (n=5),4.1881 ± 0.9708 (n=5),7483.9557 ± 1437.6896 (n=5),0.0064 ± 0.0012 (n=5),0.2161 ± 0.0166 (n=5),0.2161 ± 0.0166 (n=5),81.2875 ± 8.8131 (n=5),0.0750 ± 0.0081 (n=5),0.0051 ± 0.0014 (n=5),68.7524 ± 6.5850 (n=5),0.0635 ± 0.0061 (n=5),4.1881 ± 0.9708 (n=5),4.1881 ± 0.9708 (n=5),7483.9557 ± 1437.6896 (n=5),0.0064 ± 0.0012 (n=5),0.2161 ± 0.0166 (n=5),0.2161 ± 0.0166 (n=5),81.2875 ± 8.8131 (n=5),0.0750 ± 0.0081 (n=5),63.9298 ± 7.9536 (n=5),0.0590 ± 0.0073 (n=5),3.4466 ± 0.4017 (n=5),3.4466 ± 0.4017 (n=5),18446.2678 ± 9050.9706 (n=5),0.0157 ± 0.0077 (n=5),0.2752 ± 0.0202 (n=5),0.2752 ± 0.0202 (n=5),105.1897 ± 17.4503 (n=5),0.0971 ± 0.0161 (n=5),0.0071 ± 0.0043 (n=5),66.5562 ± 11.3426 (n=5),0.0614 ± 0.0105 (n=5),3.4565 ± 1.1051 (n=5),3.4565 ± 1.1051 (n=5),8509.0149 ± 4251.9635 (n=5),0.0073 ± 0.0036 (n=5),0.2565 ± 0.0249 (n=5),0.2565 ± 0.0249 (n=5),87.7510 ± 19.0200 (n=5),0.0810 ± 0.0176 (n=5)
1,1,0.0005,1.0,0.0196 ± 0.0041 (n=5),0.0093 ± 0.0006 (n=5),84.8660 ± 3.1953 (n=5),0.0783 ± 0.0029 (n=5),4.8585 ± 0.6684 (n=5),4.8585 ± 0.6684 (n=5),11314.5047 ± 503.0885 (n=5),0.0096 ± 0.0004 (n=5),0.1977 ± 0.0054 (n=5),0.1977 ± 0.0054 (n=5),105.3106 ± 2.6350 (n=5),0.0972 ± 0.0024 (n=5),0.0093 ± 0.0006 (n=5),84.8660 ± 3.1953 (n=5),0.0783 ± 0.0029 (n=5),4.8585 ± 0.6684 (n=5),4.8585 ± 0.6684 (n=5),11314.5047 ± 503.0885 (n=5),0.0096 ± 0.0004 (n=5),0.1977 ± 0.0054 (n=5),0.1977 ± 0.0054 (n=5),105.3106 ± 2.6350 (n=5),0.0972 ± 0.0024 (n=5),75.5024 ± 1.5152 (n=5),0.0697 ± 0.0014 (n=5),3.7396 ± 0.4293 (n=5),3.7396 ± 0.4293 (n=5),20194.0504 ± 3257.3724 (n=5),0.0172 ± 0.0028 (n=5),0.2609 ± 0.0084 (n=5),0.2609 ± 0.0084 (n=5),123.2165 ± 5.5651 (n=5),0.1137 ± 0.0051 (n=5),0.0105 ± 0.0005 (n=5),86.9343 ± 3.8065 (n=5),0.0803 ± 0.0035 (n=5),4.7126 ± 0.7581 (n=5),4.7126 ± 0.7581 (n=5),12523.3908 ± 555.1493 (n=5),0.0107 ± 0.0005 (n=5),0.2185 ± 0.0094 (n=5),0.2185 ± 0.0094 (n=5),111.1867 ± 2.4979 (n=5),0.1026 ± 0.0023 (n=5)
6,50,0.0010,50.0,0.0215 ± 0.0117 (n=5),0.0045 ± 0.0005 (n=5),66.7586 ± 2.3610 (n=5),0.0616 ± 0.0022 (n=5),4.0980 ± 0.2668 (n=5),4.0980 ± 0.2668 (n=5),7291.3593 ± 512.3665 (n=5),0.0062 ± 0.0004 (n=5),0.2234 ± 0.0094 (n=5),0.2234 ± 0.0094 (n=5),77.6596 ± 3.6455 (n=5),0.0717 ± 0.0034 (n=5),0.0045 ± 0.0005 (n=5),66.7586 ± 2.3610 (n=5),0.0616 ± 0.0022 (n=5),4.0980 ± 0.2668 (n=5),4.0980 ± 0.2668 (n=5),7291.3593 ± 512.3665 (n=5),0.0062 ± 0.0004 (n=5),0.2234 ± 0.0094 (n=5),0.2234 ± 0.0094 (n=5),77.6596 ± 3.6455 (n=5),0.0717 ± 0.0034 (n=5),60.7164 ± 3.6630 (n=5),0.0561 ± 0.0034 (n=5),3.0312 ± 0.1943 (n=5),3.0312 ± 0.1943 (n=5),20231.2912 ± 9813.9326 (n=5),0.0172 ± 0.0084 (n=5),0.2726 ± 0.0341 (n=5),0.2726 ± 0.0341 (n=5),104.3821 ± 13.8004 (n=5),0.0964 ± 0.0127 (n=5),0.0055 ± 0.0014 (n=5),60.9238 ± 4.3108 (n=5),0.0562 ± 0.0040 (n=5),2.9866 ± 0.2983 (n=5),2.9866 ± 0.2983 (n=5),7055.8521 ± 1206.2187 (n=5),0.0060 ± 0.0010 (n=5),0.2679 ± 0.0097 (n=5),0.2679 ± 0.0097 (n=5),80.6656 ± 6.8617 (n=5),0.0745 ± 0.0063 (n=5)
9,100,0.0010,100.0,0.0215 ± 0.0169 (n=5),0.0037 ± 0.0017 (n=5),57.6774 ± 14.9207 (n=5),0.0532 ± 0.0138 (n=5),3.9485 ± 1.3842 (n=5),3.9485 ± 1.3842 (n=5),5524.7367 ± 2624.4623 (n=5),0.0047 ± 0.0022 (n=5),0.2300 ± 0.0414 (n=5),0.2300 ± 0.0414 (n=5),67.9406 ± 16.9083 (n=5),0.0627 ± 0.0156 (n=5),0.0037 ± 0.0017 (n=5),57.6774 ± 14.9207 (n=5),0.0532 ± 0.0138 (n=5),3.9485 ± 1.3842 (n=5),3.9485 ± 1.3842 (n=5),5524.7367 ± 2624.4623 (n=5),0.0047 ± 0.0022 (n=5),0.2300 ± 0.0414 (n=5),0.2300 ± 0.0414 (n=5),67.9406 ± 16.9083 (n=5),0.0627 ± 0.0156 (n=5),59.2834 ± 9.2536 (n=5),0.0547 ± 0.0085 (n=5),3.2252 ± 0.4711 (n=5),3.2252 ± 0.4711 (n=5),20166.9000 ± 14575.6112 (n=5),0.0172 ± 0.0124 (n=5),0.2466 ± 0.0429 (n=5),0.2466 ± 0.0429 (n=5),101.0179 ± 24.0323 (n=5),0.0933 ± 0.0222 (n=5),0.0049 ± 0.0035 (n=5),56.1379 ± 14.2750 (n=5),0.0518 ± 0.0132 (n=5),3.3565 ± 1.3698 (n=5),3.3565 ± 1.3698 (n=5),6062.6869 ± 3674.8965 (n=5),0.0052 ± 0.0031 (n=5),0.2684 ± 0.0360 (n=5),0.2684 ± 0.0360 (n=5),72.5799 ± 21.4290 (n=5),0.0670 ± 0.0198 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,task_definition.stride_train,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
0,1,1,-,1.0000 ± 0.0000 (n=1),41.7993 ± 0.0000 (n=1),0.0386 ± 0.0000 (n=1),1.4071 ± 0.0000 (n=1),1.4071 ± 0.0000 (n=1),2861.7988 ± 0.0000 (n=1),0.0024 ± 0.0000 (n=1),0.2451 ± 0.0000 (n=1),0.2451 ± 0.0000 (n=1),52.7592 ± 0.0000 (n=1),0.0487 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,5,1,-,1.0000 ± 0.0000 (n=1),41.7673 ± 0.0000 (n=1),0.0386 ± 0.0000 (n=1),2.1174 ± 0.0000 (n=1),2.1174 ± 0.0000 (n=1),2941.9949 ± 0.0000 (n=1),0.0025 ± 0.0000 (n=1),0.2910 ± 0.0000 (n=1),0.2910 ± 0.0000 (n=1),52.3130 ± 0.0000 (n=1),0.0483 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,10,5,-,1.0000 ± 0.0000 (n=1),48.7525 ± 0.0000 (n=1),0.0450 ± 0.0000 (n=1),2.7551 ± 0.0000 (n=1),2.7551 ± 0.0000 (n=1),4052.2131 ± 0.0000 (n=1),0.0035 ± 0.0000 (n=1),0.2799 ± 0.0000 (n=1),0.2799 ± 0.0000 (n=1),59.1192 ± 0.0000 (n=1),0.0546 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3,20,5,-,1.0000 ± 0.0000 (n=1),48.1991 ± 0.0000 (n=1),0.0445 ± 0.0000 (n=1),3.0071 ± 0.0000 (n=1),3.0071 ± 0.0000 (n=1),3802.6609 ± 0.0000 (n=1),0.0032 ± 0.0000 (n=1),0.2700 ± 0.0000 (n=1),0.2700 ± 0.0000 (n=1),57.5949 ± 0.0000 (n=1),0.0532 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,50,50,-,1.0000 ± 0.0000 (n=1),72.5398 ± 0.0000 (n=1),0.0670 ± 0.0000 (n=1),6.9988 ± 0.0000 (n=1),6.9988 ± 0.0000 (n=1),8562.4521 ± 0.0000 (n=1),0.0073 ± 0.0000 (n=1),0.1970 ± 0.0000 (n=1),0.1970 ± 0.0000 (n=1),86.9495 ± 0.0000 (n=1),0.0803 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
5,100,100,-,1.0000 ± 0.0000 (n=1),103.5101 ± 0.0000 (n=1),0.0956 ± 0.0000 (n=1),9.8268 ± 0.0000 (n=1),9.8268 ± 0.0000 (n=1),16679.6074 ± 0.0000 (n=1),0.0142 ± 0.0000 (n=1),0.1143 ± 0.0000 (n=1),0.1143 ± 0.0000 (n=1),119.5650 ± 0.0000 (n=1),0.1104 ± 0.0000 (n=1),-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

>>> baselines.lstm_model.LSTM_Forecaster on NB14
    (Sorted by optimization target: val/loss)

,task_definition.seq_len,optimization.lr,val/loss,test/loss,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_denormalized_mean,val/rmse_normalized_mean,val_best_rerun/loss,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
9,100,0.0010,0.0019 ± 0.0002 (n=5),0.0019 ± 0.0002 (n=5),41.2270 ± 2.1486 (n=5),0.0381 ± 0.0020 (n=5),2.6186 ± 0.1395 (n=5),2.6186 ± 0.1395 (n=5),2877.2120 ± 321.5396 (n=5),0.0025 ± 0.0003 (n=5),0.2547 ± 0.0155 (n=5),0.2547 ± 0.0155 (n=5),49.9535 ± 2.3129 (n=5),0.0461 ± 0.0021 (n=5),0.0019 ± 0.0002 (n=5),41.2270 ± 2.1486 (n=5),0.0381 ± 0.0020 (n=5),2.6186 ± 0.1395 (n=5),2.6186 ± 0.1395 (n=5),2877.2120 ± 321.5396 (n=5),0.0025 ± 0.0003 (n=5),0.2547 ± 0.0155 (n=5),0.2547 ± 0.0155 (n=5),49.9535 ± 2.3129 (n=5),0.0461 ± 0.0021 (n=5),37.8514 ± 2.7414 (n=5),0.0349 ± 0.0025 (n=5),2.1897 ± 0.2090 (n=5),2.1897 ± 0.2090 (n=5),2873.5661 ± 306.9954 (n=5),0.0024 ± 0.0003 (n=5),0.3174 ± 0.0240 (n=5),0.3174 ± 0.0240 (n=5),46.9656 ± 3.8908 (n=5),0.0434 ± 0.0036 (n=5),0.0017 ± 0.0001 (n=5),35.7047 ± 1.1237 (n=5),0.0330 ± 0.0010 (n=5),2.1263 ± 0.1063 (n=5),2.1263 ± 0.1063 (n=5),2460.7995 ± 88.0099 (n=5),0.0021 ± 0.0001 (n=5),0.3514 ± 0.0081 (n=5),0.3514 ± 0.0081 (n=5),44.6926 ± 1.9828 (n=5),0.0413 ± 0.0018 (n=5)
10,100,0.0005,0.0020 ± 0.0001 (n=5),0.0020 ± 0.0003 (n=5),43.0109 ± 1.7850 (n=5),0.0397 ± 0.0016 (n=5),2.9748 ± 0.4641 (n=5),2.9748 ± 0.4641 (n=5),3114.9517 ± 307.8053 (n=5),0.0027 ± 0.0003 (n=5),0.2487 ± 0.0309 (n=5),0.2487 ± 0.0309 (n=5),51.8657 ± 3.0145 (n=5),0.0479 ± 0.0028 (n=5),0.0020 ± 0.0003 (n=5),43.0109 ± 1.7850 (n=5),0.0397 ± 0.0016 (n=5),2.9748 ± 0.4641 (n=5),2.9748 ± 0.4641 (n=5),3114.9517 ± 307.8053 (n=5),0.0027 ± 0.0003 (n=5),0.2487 ± 0.0309 (n=5),0.2487 ± 0.0309 (n=5),51.8657 ± 3.0145 (n=5),0.0479 ± 0.0028 (n=5),40.3497 ± 2.0700 (n=5),0.0372 ± 0.0019 (n=5),2.2622 ± 0.1026 (n=5),2.2622 ± 0.1026 (n=5),3122.5395 ± 235.7783 (n=5),0.0027 ± 0.0002 (n=5),0.3234 ± 0.0142 (n=5),0.3234 ± 0.0142 (n=5),49.9243 ± 2.3629 (n=5),0.0461 ± 0.0022 (n=5),0.0018 ± 0.0002 (n=5),38.3474 ± 2.3482 (n=5),0.0354 ± 0.0022 (n=5),2.3891 ± 0.2242 (n=5),2.3891 ± 0.2242 (n=5),2643.0551 ± 256.7642 (n=5),0.0023 ± 0.0002 (n=5),0.3283 ± 0.0214 (n=5),0.3283 ± 0.0214 (n=5),47.3626 ± 2.9052 (n=5),0.0437 ± 0.0027 (n=5)
6,50,0.0010,0.0024 ± 0.0004 (n=5),0.0020 ± 0.0002 (n=5),42.5443 ± 3.0809 (n=5),0.0393 ± 0.0028 (n=5),2.2734 ± 0.4509 (n=5),2.2734 ± 0.4509 (n=5),3011.6648 ± 367.6247 (n=5),0.0026 ± 0.0003 (n=5),0.2624 ± 0.0182 (n=5),0.2624 ± 0.0182 (n=5),51.3197 ± 3.1110 (n=5),0.0474 ± 0.0029 (n=5),0.0020 ± 0.0002 (n=5),42.5443 ± 3.0809 (n=5),0.0393 ± 0.0028 (n=5),2.2734 ± 0.4509 (n=5),2.2734 ± 0.4509 (n=5),3011.6648 ± 367.6247 (n=5),0.0026 ± 0.0003 (n=5),0.2624 ± 0.0182 (n=5),0.2624 ± 0.0182 (n=5),51.3197 ± 3.1110 (n=5),0.0474 ± 0.0029 (n=5),39.4864 ± 4.2683 (n=5),0.0365 ± 0.0039 (n=5),2.0105 ± 0.3193 (n=5),2.0105 ± 0.3193 (n=5),3244.5389 ± 663.8812 (n=5),0.0028 ± 0.0006 (n=5),0.3287 ± 0.0194 (n=5),0.3287 ± 0.0194 (n=5),51.7889 ± 6.4494 (n=5),0.0478 ± 0.0060 (n=5),0.0020 ± 0.0005 (n=5),37.7947 ± 4.8832 (n=5),0.0349 ± 0.0045 (n=5),1.8968 ± 0.2446 (n=5),1.8968 ± 0.2446 (n=5),2696.7386 ± 631.6557 (n=5),0.0023 ± 0.0005 (n=5),0.3387 ± 0.0295 (n=5),0.3387 ± 0.0295 (n=5),48.9677 ± 6.6049 (n=5),0.0452 ± 0.0061 (n=5)
3,10,0.0010,0.0026 ± 0.0004 (n=5),0.0024 ± 0.0001 (n=5),45.6430 ± 1.5366 (n=5),0.0421 ± 0.0014 (n=5),2.3557 ± 0.1571 (n=5),2.3557 ± 0.1571 (n=5),3547.8737 ± 234.9562 (n=5),0.0030 ± 0.0002 (n=5),0.2877 ± 0.0152 (n=5),0.2877 ± 0.0152 (n=5),56.3588 ± 1.2569 (n=5),0.0520 ± 0.0012 (n=5),0.0024 ± 0.0001 (n=5),45.6430 ± 1.5366 (n=5),0.0421 ± 0.0014 (n=5),2.3557 ± 0.1571 (n=5),2.3557 ± 0.1571 (n=5),3547.8737 ± 234.9562 (n=5),0.0030 ± 0.0002 (n=5),0.2877 ± 0.0152 (n=5),0.2877 ± 0.0152 (n=5),56.3588 ± 1.2569 (n=5),0.0520 ± 0.0012 (n=5),42.1283 ± 2.4391 (n=5),0.0389 ± 0.0023 (n=5),1.8042 ± 0.0605 (n=5),1.8042 ± 0.0605 (n=5),3523.3232 ± 444.9635 (n=5),0.0030 ± 0.0004 (n=5),0.3288 ± 0.0171 (n=5),0.3288 ± 0.0171 (n=5),56.1463 ± 3.7667 (n=5),0.0518 ± 0.0035 (n=5),0.0024 ± 0.0003 (n=5),40.4469 ± 1.5434 (n=5),0.0373 ± 0.0014 (n=5),1.8288 ± 0.0616 (n=5),1.8288 ± 0.0616 (n=5),3168.9193 ± 296.8941 (n=5),0.0027 ± 0.0003 (n=5),0.3496 ± 0.0117 (n=5),0.3496 ± 0.0117 (n=5),54.2844 ± 3.3091 (n=5),0.0501 ± 0.0031 (n=5)
11,100,0.0001,0.0027 ± 0.0004 (n=5),0.0021 ± 0.0003 (n=5),46.7148 ± 3.9196 (n=5),0.0431 ± 0.0036 (n=5),3.4069 ± 0.5323 (n=5),3.4069 ± 0.5323 (n=5),3400.0366 ± 508.8981 (n=5),0.0029 ± 0.0004 (n=5),0.2510 ± 0.0264 (n=5),0.2510 ± 0.0264 (n=5),54.0736 ± 3.4793 (n=5),0.0499 ± 0.0032 (n=5),0.0021 ± 0.0003 (n=5),46.7148 ± 3.9196 (n=5),0.0431 ± 0.0036 (n=5),3.4069 ± 0.5323 (n=5),3.4069 ± 0.5323 (n=5),3400.0366 ± 508.8981 (n=5),0.0029 ± 0.0004 (n=5),0.2510 ± 0.0264 (n=5),0.2510 ± 0.0264 (n=5),54.0736 ± 3.4793 (n=5),0.0499 ± 0.0032 (n=5),48.9818 ± 5.8436 (n=5),0.0452 ± 0.0054 (n=5),3.1137 ± 0.4319 (n=5),3.1137 ± 0.4319 (n=5),3989.5886 ± 788.5064 (n=5),0.0034 ± 0.0007 (n=5),0.2608 ± 0.0417 (n=5),0.2608 ± 0.0417 (n=5),57.8764 ± 5.0322 (n=5),0.0534 ± 0.0046 (n=5),0.0024 ± 0.0002 (n=5),46.0132 ± 1.9628 (n=5),0.0425 ± 0.0018 (n=5),3.0416 ± 0.4615 (n=5),3.0416 ± 0.4615 (n=5),3312.7006 ± 177.7939 (n=5),0.0028 ± 0.0002 (n=5),0.2694 ± 0.0269 (n=5),0.2694 ± 0.0269 (n=5),54.8474 ± 2.3348 (n=5),0.0506 ± 0.0022 (n=5)
7,50,0.0005,0.0028 ± 0.0006 (n=5),0.0022 ± 0.0003 (n=5),45.5841 ± 2.3096 (n=5),0.0421 ± 0.0021 (n=5),2.7652 ± 0.6614 (n=5),2.7652 ± 0.6614 (n=5),3473.4902 ± 421.9843 (n=5),0.0030 ± 0.0004 (n=5),0.2755 ± 0.0151 (n=5),0.2755 ± 0.0151 (n=5),54.7119 ± 2.6130 (n=5),0.0505 ± 0.0024 (n=5),0.0022 ± 0.0003 (n=5),45.5841 ± 2.3096 (n=5),0.0421 ± 0.0021 (n=5),2.7652 ± 0.6614 (n=5),2.7652 ± 0.6614 (n=5),3473.4902 ± 421.9843 (n=5),0.0030 ± 0.0004 (n=5),0.2755 ± 0.0151 (n=5),0.2755 ± 0.0151 (n=5),54.7119 ± 2.6130 (n=5),0.0505 ± 0.0024 (n=5),43.5070 ± 8.1515 (n=5),0.0402 ± 0.0075 (n=5),2.3282 ± 0.6650 (n=5),2.3282 ± 0.6650 (n=5),3747.5331 ± 1090.2054 (n=5),0.0032 ± 0.0009 (n=5),0.3010 ± 0.0487 (n=5),0.3010 ± 0.0487 (n=5),56.7559 ± 8.2493 (n=5),0.0524 ± 0.0076 (n=5),0.0025 ± 0.0003 (n=5),40.8157 ± 5.0359 (n=5),0.0377 ± 0.0046 (n=5),2.3208 ± 0.6864 (n=5),2.3208 ± 0.6864 (n=5),3165.2777 ± 448.4033 (n=5),0.0027 ± 0.0004 (n=5),0.3275 ± 0.0320 (n=5),0.3275 ± 0.0320 (n=5),53.8724 ± 4.5919 (n=5),0.0497 ± 0.0042 (n=5)
4,10,0.0005,0.0028 ± 0.0002 (n=5),0.0025 ± 0.0001 (n=5),47.6559 ± 1.7201 (n=5),0.0440 ± 0.0016 (n=5),2.4682 ± 0.3354 (n=5),2.4682 ± 0.3354 (n=5),3959.7081 ± 278.8141 (n=5),0.0034 ± 0.0002 (n=5),0.2870 ± 0.0134 (n=5),0.2870 ± 0.0134 (n=5),58.0649 ± 1.8679 (n=5),0.0536 ± 0.0017 (n=5),0.0025 ± 0.0001 (n=5),47.6559 ± 1.7201 (n=5),0.0440 ± 0.0016 (n=5),2.4682 ± 0.3354 (n=5),2.4682 ± 0.3354 (n=5),3959.7081 ± 278.8141 (n=5),0.0034 ± 0.0002 (n=5),0.2870 ± 0.0134 (n=5),0.2870 ± 0.0134 (n=5),58.0649 ± 1.8679 (n=5),0.0536 ± 0.0017 (n=5),45.5801 ± 2.2411 (n=5),0.0421 ± 0.0021 (n=5),2.0499 ± 0.0932 (n=5),2.0499 ± 0.0932 (n=5),3914.1493 ± 322.7110 (n=5),0.0033 ± 0.0003 (n=5),0.3028 ± 0.0240 (n=5),0.3028 ± 0.0240 (n=5),59.4393 ± 2.1570 (n=5),0.0549 ± 0.0020 (n=5),0.0026 ± 0.0001 (n=5),42.2881 ± 1.1645 (n=5),0.0390 ± 0.0011 (n=5),1.9866 ± 0.2829 (n=5),1.9866 ± 0.2829 (n=5),3367.4301 ± 105.1806 (n=5),0.0029 ± 0.0001 (n=5),0.3372 ± 0.0119 (n=5),0.3372 ± 0.0119 (n=5),56.4119 ± 0.9322 (n=5),0.0521 ± 0.0009 (n=5)
8,50,0.0001,0.0034 ± 0.0002 (n=5),0.0023 ± 0.0002 (n=5),47.8228 ± 1.8156 (n=5),0.0441 ± 0.0017 (n=5),3.5388 ± 0.1167 (n=5),3.5388 ± 0.1167 (n=5),3628.3738 ± 378.1536 (n=5),0.0031 ± 0.0003 (n=5),0.2739 ± 0.0097 (n=5),0.2739 ± 0.0097 (n=5),55.5074 ± 1.9660 (n=5),0.0512 ± 0.0018 (n=5),0.0023 ± 0.0002 (n=5),47.8228 ± 1.8156 (n=5),0.0441 ± 0.0017 (n=5),3.5388 ± 0.1167 (n=5),3.5388 ± 0.1167 (n=5),3628.3738 ± 378.1536 (n=5),0.0031 ± 0.0003 (n=5),0.2739 ± 0.0097 (n=5),0.2739 ± 0.0097 (n=5),55.5074 ± 1.9660 (n=5),0.0512 ± 0.0018 (n=5),52.1036 ± 2.9386 (n=5),0.0481 ± 0.0027 (n=5),3.1153 ± 0.1398 (n=5),3.1153 ± 0.1398 (n=5),4530.8512 ± 434.9815 (n=5),0.0039 ± 0.0004 (n=5),0.2437 ± 0.0160 (n=5),0.2437 ± 0.0160 (n=5),64.4946 ± 2.6842 (n=5),0.0595 ± 0.0025 (n=5),0.0031 ± 0.0001 (n=5),48.6517 ± 1.2839 (n=5),0.0449 ± 0.0012 (n=5),3.1278 ± 0.0935 (n=5),3.1278 ± 0.0935 (n=5),3866.1421 ± 209.0474 (n=5),0.0033 ± 0.0002 (n=5),0.2608 ± 0.0118 (n=5),0.2608 ± 0.0118 (n=5),60.7319 ± 1.5333 (n=5),0.0561 ± 0.0014 (n=5)
5,10,0.0001,0.0038 ± 0.0004 (n=5),0.0031 ± 0.0002 (n=5),54.9587 ± 2.2877 (n=5),0.0507 ± 0.0021 (n=5),3.3460 ± 0.2505 (n=5),3.3460 ± 0.2505 (n=5),5116.9981 ± 399.6914 (n=5),0.0044 ± 0.0003 (n=5),0.2772 ± 0.0059 (n=5),0.2772 ± 0.0059 (n=5),64.4019 ± 2.4657 (n=5),0.0595 ± 0.0023 (n=5),0.0031 ± 0.0002 (n=5),54.9587 ± 2.2877 (n=5),0.0507 ± 0.0021 (n=5),3.3460 ± 0.2505 (n=5),3.3460 ± 0.2505 (n=5),5116.9981 ± 399.6914 (n=5),0.0044 ± 0.0003 (n=5),0.2772 ± 0.0059 (n=5),0.2772 ± 0.0059 (n=5),64.4019 ± 2.4657 (n=5),0.0595 ± 0.0023 (n=5),55.0805 ± 2.4895 (n=5),0.0508 ± 0.0023 (n=5),2.7185 ± 0.3552 (n=5),2.7185 ± 0.3552 (n=5),5173.4199 ± 546.8574 (n=5),0.0044 ± 0.0005 (n=5),0.2627 ± 0.0102 (n=5),0.2627 ± 0.0102 (n=5),69.3902 ± 3.3514 (n=5),0.0641 ± 0.0031 (n=5),0.0036 ± 0.0003 (n=5),52.9297 ± 1.6023 (n=5),0.0489 ± 0.0015 (n=5),2.6875 ± 0.3178 (n=5),2.6875 ± 0.3178 (n=5),4811.1587 ± 353.7309 (n=5),0.0041 ± 0.0003 (n=5),0.2794 ± 0.0073 (n=5),0.2794 ± 0.0073 (n=5),67.6784 ± 2.4756 (n=5),0.0625 ± 0.0023 (n=5)
0,1,0.0010,0.0048 ± 0.0003 (n=5),0.0041 ± 0.0000 (n=5),57.1946 ± 0.6329 (n=5),0.0528 ± 0.0006 (n=5),3.8398 ± 0.1188 (n=5),3.8398 ± 0.1188 (n=5),5712.1804 ± 106.7833 (n=5),0.0049 ± 0.0001 (n=5),0.2726 ± 0.0054 (n=5),0.2726 ± 0.0054 (n=5),71.6815 ± 0.6223 (n=5),0.0662 ± 0.0006 (n=5),0.0041 ± 0.0000 (n=5),57.1946 ± 0.6329 (n=5),0.0528 ± 0.0006 (n=5),3.8398 ± 0.1188 (n=5),3.8398 ± 0.1188 (n=5),5712.1804 ± 106.7833 (n=5),0.0049 ± 0.0001 (n=5),0.2726 ± 0.0054 (n=5),0.2726 ± 0.0054 (n=5),71.6815 ± 0.6223 (n=5),0.0662 ± 0.0006 (n=5),59.2286 ± 1.3096 (n=5),0.0547 ± 0.0012 (n=5),3.3398 ± 0.3192 (n=5),3.3398 ± 0.3192 (n=5),6140.3178 ± 281.8503 (n=5),0.0052 ± 0.0002 (n=5),0.2565 ± 0.0074 (n=5),0.2565 ± 0.0074 (n=5),76.7408 ± 1.8415 (n=5),0.0708 ± 0.0017 (n=5),0.0044 ± 0.0002 (n=5),56.5955 ± 1.0029 (n=5),0.0522 ± 0.0009 (n=5),3.5340 ± 0.1223 (n=5),3.5340 ± 0.1223 (n=5),5400.5054 ± 198.2211 (n=5),0.0046 ± 0.0002 (n=5),0.2731 ± 0.0090 (n=5),0.2731 ± 0.0090 (n=5),72.4033 ± 1.4057 (n=5),0.0668 ± 0.0013 (n=5)
1,1,0.0005,0.0049 ± 0.0001 (n=5),0.0043 ± 0.0001 (n=5),58.1375 ± 0.9159 (n=5),0.0537 ± 0.0008 (n=5),3.9365 ± 0.1628 (n=5),3.9365 ± 0.1628 (n=5),5880.7251 ± 175.3646 (n=5),0.0050 ± 0.0001 (n=5),0.2670 ± 0.0080 (n=5),0.2670 ± 0.0080 (n=5),72.9672 ± 1.1627 (n=5),0.0674 ± 0.0011 (n=5),0.0043 ± 0.0001 (n=5),58.1375 ± 0.9159 (n=5),0.0537 ± 0.0008 (n=5),3.9365 ± 0.1628 (n=5),3.9365 ± 0.1628 (n=5),5880.7251 ± 175.3646 (n=5),0.0050 ± 0.0001 (n=5),0.2670 ± 0.0080 (n=5),0.2670 ± 0.0080 (n=5),72.9672 ± 1.1627 (n=5),0.0674 ± 0.0011 (n=5),61.2089 ± 1.2303 (n=5),0.0565 ± 0.0011 (n=5),3.7457 ± 0.2220 (n=5),3.7457 ± 0.2220 (n=5),6298.5618 ± 165.3872 (n=5),0.0054 ± 0.0001 (n=5),0.2464 ± 0.0075 (n=5),0.2464 ± 0.0075 (n=5),77.6342 ± 0.9232 (n=5),0.0717 ± 0.0009 (n=5),0.0046 ± 0.0001 (n=5),57.8790 ± 1.1428 (n=5),0.0534 ± 0.0011 (n=5),3.6589 ± 0.1425 (n=5),3.6589 ± 0.1425 (n=5),5685.0148 ± 176.5739 (n=5),0.0048 ± 0.0002 (n=5),0.2665 ± 0.0111 (n=5),0.2665 ± 0.0111 (n=5),74.4114 ± 1.2235 (n=5),0.0687 ± 0.0011 (n=5)
2,1,0.0001,0.0053 ± 0.0002 (n=5),0.0049 ± 0.0002 (n=5),62.4996 ± 1.2808 (n=5),0.0577 ± 0.0012 (n=5),4.6452 ± 0.1970 (n=5),4.6452 ± 0.1970 (n=5),6714.4655 ± 265.1728 (n=5),0.0057 ± 0.0002 (n=5),0.2487 ± 0.0063 (n=5),0.2487 ± 0.0063 (n=5),78.3865 ± 1.6670 (n=5),0.0724 ± 0.0015 (n=5),0.0049 ± 0.0002 (n=5),62.4996 ± 1.2808 (n=5),0.0577 ± 0.0012 (n=5),4.6452 ± 0.1970 (n=5),4.6452 ± 0.1970 (n=5),6714.4655 ± 265.1728 (n=5),0.0057 ± 0.0002 (n=5),0.2487 ± 0.0063 (n=5),0.2487 ± 0.0063 (n=5),78.3865 ± 1.6670 (n=5),0.0724 ± 0.0015 (n=5),63.1340 ± 0.7206 (n=5),0.0583 ± 0.0007 (n=5),3.9147 ± 0.0956 (n=5),3.9147 ± 0.0956 (n=5),6800.4195 ± 272.5768 (n=5),0.0058 ± 0.0002 (n=5),0.2457 ± 0.0043 (n=5),0.2457 ± 0.0043 (n=5),80.9662 ± 1.5649 (n=5),0.0747 ± 0.0014 (n=5),0.0052 ± 0.0002 (n=5),61.2984 ± 0.8992 (n=5),0.0566 ± 0.0008 (n=5),3.8250 ± 0.1085 (n=5),3.8250 ± 0.1085 (n=5),6483.7546 ± 293.8289 (n=5),0.0055 ± 0.0003 (n=5),0.2594 ± 0.0074 (n=5),0.2594 ± 0.0074 (n=5),79.4744 ± 1.7391 (n=5),0.0734 ± 0.0016 (n=5)
12,150,0.0010,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13,150,0.0005,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
14,150,0.0001,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

📊 Full Summary Table:

Dataset                                                              NB14                                                                                                            \
Metric                                                          test/loss test/mae_denormalized_mean test/mae_normalized_mean test/mape_denormalized_mean test/mape_normalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster  0.0018 ± 0.0003 (n=5)     41.8399 ± 3.6838 (n=5)    0.0386 ± 0.0034 (n=5)       2.8595 ± 0.4221 (n=5)     2.8595 ± 0.4221 (n=5)
baselines.lstm_model.LSTM_Forecaster                0.0019 ± 0.0002 (n=5)     41.2270 ± 2.1486 (n=5)    0.0381 ± 0.0020 (n=5)       2.6186 ± 0.1395 (n=5)     2.6186 ± 0.1395 (n=5)
baselines.patchtst_model.PatchTST_Forecaster        0.0045 ± 0.0000 (n=5)     65.8630 ± 0.6700 (n=5)    0.0608 ± 0.0006 (n=5)       3.5010 ± 0.2680 (n=5)     3.5010 ± 0.2680 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...  0.0053 ± 0.0017 (n=5)     68.0611 ± 8.7032 (n=5)    0.0628 ± 0.0080 (n=5)       5.6071 ± 2.1299 (n=5)     5.6071 ± 2.1299 (n=5)
baselines.tide_model.TiDE_Forecaster                0.0014 ± 0.0002 (n=5)     36.3731 ± 1.1665 (n=5)    0.0336 ± 0.0011 (n=5)       2.6982 ± 0.4399 (n=5)     2.6982 ± 0.4399 (n=5)
baselines.timeseries_transformer_model.Timeseri...  0.0040 ± 0.0007 (n=5)     63.1397 ± 5.7433 (n=5)    0.0583 ± 0.0053 (n=5)       4.1653 ± 0.1403 (n=5)     4.1653 ± 0.1403 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper          0.0131 ± 0.0059 (n=5)    98.9557 ± 15.4816 (n=5)    0.0914 ± 0.0143 (n=5)       6.1727 ± 1.1110 (n=5)     6.1727 ± 1.1110 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...  1.0000 ± 0.0000 (n=1)     41.7993 ± 0.0000 (n=1)    0.0386 ± 0.0000 (n=1)       1.4071 ± 0.0000 (n=1)     1.4071 ± 0.0000 (n=1)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...  1.0000 ± 0.0000 (n=1)     41.7476 ± 0.0000 (n=1)    0.0385 ± 0.0000 (n=1)       1.4111 ± 0.0000 (n=1)     1.4111 ± 0.0000 (n=1)
model.wrappers.mlp_wrapper.MLPWrapper               0.0510 ± 0.0571 (n=5)   161.9690 ± 96.3975 (n=5)    0.1495 ± 0.0890 (n=5)       9.7809 ± 4.6053 (n=5)     9.7809 ± 4.6053 (n=5)
model.wrappers.statistical_models_wrapper.Stati...  0.0260 ± 0.0000 (n=5)    130.1766 ± 0.0116 (n=5)    0.1202 ± 0.0000 (n=5)       0.9991 ± 0.0005 (n=5)     0.9991 ± 0.0005 (n=5)
model.wrappers.statistical_models_wrapper.Stati...  0.3216 ± 0.1614 (n=5)  417.9388 ± 107.8377 (n=5)    0.3858 ± 0.0996 (n=5)     35.4759 ± 16.7702 (n=5)   35.4759 ± 16.7702 (n=5)

Dataset                                                                                                                                                                       \
Metric                                                   test/mse_denormalized_mean test/mse_normalized_mean test/phm_score_denormalized_mean test/phm_score_normalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster       3142.0465 ± 806.7998 (n=5)    0.0027 ± 0.0007 (n=5)            0.3083 ± 0.0163 (n=5)          0.3083 ± 0.0163 (n=5)
baselines.lstm_model.LSTM_Forecaster                     2877.2120 ± 321.5396 (n=5)    0.0025 ± 0.0003 (n=5)            0.2547 ± 0.0155 (n=5)          0.2547 ± 0.0155 (n=5)
baselines.patchtst_model.PatchTST_Forecaster             7089.4036 ± 213.7164 (n=5)    0.0060 ± 0.0002 (n=5)            0.2349 ± 0.0028 (n=5)          0.2349 ± 0.0028 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...      7230.2074 ± 1637.3606 (n=5)    0.0062 ± 0.0014 (n=5)            0.2029 ± 0.0310 (n=5)          0.2029 ± 0.0310 (n=5)
baselines.tide_model.TiDE_Forecaster                     2174.5901 ± 157.9304 (n=5)    0.0019 ± 0.0001 (n=5)            0.2949 ± 0.0297 (n=5)          0.2949 ± 0.0297 (n=5)
baselines.timeseries_transformer_model.Timeseri...      6396.3324 ± 1336.6113 (n=5)    0.0055 ± 0.0011 (n=5)            0.2253 ± 0.0121 (n=5)          0.2253 ± 0.0121 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper             15644.7350 ± 6266.1642 (n=5)    0.0133 ± 0.0053 (n=5)            0.1759 ± 0.0179 (n=5)          0.1759 ± 0.0179 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...         2861.7988 ± 0.0000 (n=1)    0.0024 ± 0.0000 (n=1)            0.2451 ± 0.0000 (n=1)          0.2451 ± 0.0000 (n=1)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...         2862.3887 ± 0.0000 (n=1)    0.0024 ± 0.0000 (n=1)            0.2363 ± 0.0000 (n=1)          0.2363 ± 0.0000 (n=1)
model.wrappers.mlp_wrapper.MLPWrapper                 59727.6617 ± 67912.0565 (n=5)    0.0509 ± 0.0579 (n=5)            0.1447 ± 0.0603 (n=5)          0.1447 ± 0.0603 (n=5)
model.wrappers.statistical_models_wrapper.Stati...        26790.7039 ± 3.2606 (n=5)    0.0228 ± 0.0000 (n=5)            0.0313 ± 0.0001 (n=5)          0.0313 ± 0.0001 (n=5)
model.wrappers.statistical_models_wrapper.Stati...  324925.1547 ± 154032.0482 (n=5)    0.2769 ± 0.1313 (n=5)            0.0550 ± 0.0140 (n=5)          0.0550 ± 0.0140 (n=5)

Dataset                                                                                                                                                                \
Metric                                             test/rmse_denormalized_mean test/rmse_normalized_mean   test_best_rerun/loss test_best_rerun/mae_denormalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster      49.4970 ± 4.0689 (n=5)     0.0457 ± 0.0038 (n=5)  0.0018 ± 0.0003 (n=5)                41.8399 ± 3.6838 (n=5)
baselines.lstm_model.LSTM_Forecaster                    49.9535 ± 2.3129 (n=5)     0.0461 ± 0.0021 (n=5)  0.0019 ± 0.0002 (n=5)                41.2270 ± 2.1486 (n=5)
baselines.patchtst_model.PatchTST_Forecaster            77.5613 ± 0.5809 (n=5)     0.0716 ± 0.0005 (n=5)  0.0045 ± 0.0000 (n=5)                65.8630 ± 0.6700 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...      80.1586 ± 9.8126 (n=5)     0.0740 ± 0.0091 (n=5)  0.0053 ± 0.0017 (n=5)                68.0611 ± 8.7032 (n=5)
baselines.tide_model.TiDE_Forecaster                    42.7440 ± 1.6112 (n=5)     0.0395 ± 0.0015 (n=5)  0.0014 ± 0.0002 (n=5)                36.3731 ± 1.1665 (n=5)
baselines.timeseries_transformer_model.Timeseri...      73.5311 ± 7.1928 (n=5)     0.0679 ± 0.0066 (n=5)  0.0040 ± 0.0007 (n=5)                63.1397 ± 5.7433 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper            122.1711 ± 22.0143 (n=5)     0.1128 ± 0.0203 (n=5)  0.0131 ± 0.0059 (n=5)               98.9557 ± 15.4816 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...      52.7592 ± 0.0000 (n=1)     0.0487 ± 0.0000 (n=1)     nan ± 0.0000 (n=0)                    nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...      52.6333 ± 0.0000 (n=1)     0.0486 ± 0.0000 (n=1)     nan ± 0.0000 (n=0)                    nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                209.2534 ± 119.6525 (n=5)     0.1932 ± 0.1105 (n=5)  0.0510 ± 0.0571 (n=5)              161.9690 ± 96.3975 (n=5)
model.wrappers.statistical_models_wrapper.Stati...     160.4152 ± 0.0102 (n=5)     0.1481 ± 0.0000 (n=5)  0.0260 ± 0.0000 (n=5)               130.1766 ± 0.0116 (n=5)
model.wrappers.statistical_models_wrapper.Stati...   527.4837 ± 137.1559 (n=5)     0.4870 ± 0.1266 (n=5)  0.3216 ± 0.1614 (n=5)             417.9388 ± 107.8377 (n=5)

Dataset                                                                                                                                                             \
Metric                                             test_best_rerun/mae_normalized_mean test_best_rerun/mape_denormalized_mean test_best_rerun/mape_normalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster               0.0386 ± 0.0034 (n=5)                  2.8595 ± 0.4221 (n=5)                2.8595 ± 0.4221 (n=5)
baselines.lstm_model.LSTM_Forecaster                             0.0381 ± 0.0020 (n=5)                  2.6186 ± 0.1395 (n=5)                2.6186 ± 0.1395 (n=5)
baselines.patchtst_model.PatchTST_Forecaster                     0.0608 ± 0.0006 (n=5)                  3.5010 ± 0.2680 (n=5)                3.5010 ± 0.2680 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...               0.0628 ± 0.0080 (n=5)                  5.6071 ± 2.1299 (n=5)                5.6071 ± 2.1299 (n=5)
baselines.tide_model.TiDE_Forecaster                             0.0336 ± 0.0011 (n=5)                  2.6982 ± 0.4399 (n=5)                2.6982 ± 0.4399 (n=5)
baselines.timeseries_transformer_model.Timeseri...               0.0583 ± 0.0053 (n=5)                  4.1653 ± 0.1403 (n=5)                4.1653 ± 0.1403 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper                       0.0914 ± 0.0143 (n=5)                  6.1727 ± 1.1110 (n=5)                6.1727 ± 1.1110 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...                  nan ± 0.0000 (n=0)                     nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...                  nan ± 0.0000 (n=0)                     nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                            0.1495 ± 0.0890 (n=5)                  9.7809 ± 4.6053 (n=5)                9.7809 ± 4.6053 (n=5)
model.wrappers.statistical_models_wrapper.Stati...               0.1202 ± 0.0000 (n=5)                  0.9991 ± 0.0005 (n=5)                0.9991 ± 0.0005 (n=5)
model.wrappers.statistical_models_wrapper.Stati...               0.3858 ± 0.0996 (n=5)                35.4759 ± 16.7702 (n=5)              35.4759 ± 16.7702 (n=5)

Dataset                                                                                                                                                                   \
Metric                                             test_best_rerun/mse_denormalized_mean test_best_rerun/mse_normalized_mean test_best_rerun/phm_score_denormalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster            3142.0465 ± 806.7998 (n=5)               0.0027 ± 0.0007 (n=5)                       0.3083 ± 0.0163 (n=5)
baselines.lstm_model.LSTM_Forecaster                          2877.2120 ± 321.5396 (n=5)               0.0025 ± 0.0003 (n=5)                       0.2547 ± 0.0155 (n=5)
baselines.patchtst_model.PatchTST_Forecaster                  7089.4036 ± 213.7164 (n=5)               0.0060 ± 0.0002 (n=5)                       0.2349 ± 0.0028 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...           7230.2074 ± 1637.3606 (n=5)               0.0062 ± 0.0014 (n=5)                       0.2029 ± 0.0310 (n=5)
baselines.tide_model.TiDE_Forecaster                          2174.5901 ± 157.9304 (n=5)               0.0019 ± 0.0001 (n=5)                       0.2949 ± 0.0297 (n=5)
baselines.timeseries_transformer_model.Timeseri...           6396.3324 ± 1336.6113 (n=5)               0.0055 ± 0.0011 (n=5)                       0.2253 ± 0.0121 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper                  15644.7350 ± 6266.1642 (n=5)               0.0133 ± 0.0053 (n=5)                       0.1759 ± 0.0179 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...                    nan ± 0.0000 (n=0)                  nan ± 0.0000 (n=0)                          nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...                    nan ± 0.0000 (n=0)                  nan ± 0.0000 (n=0)                          nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                      59727.6617 ± 67912.0565 (n=5)               0.0509 ± 0.0579 (n=5)                       0.1447 ± 0.0603 (n=5)
model.wrappers.statistical_models_wrapper.Stati...             26790.7039 ± 3.2606 (n=5)               0.0228 ± 0.0000 (n=5)                       0.0313 ± 0.0001 (n=5)
model.wrappers.statistical_models_wrapper.Stati...       324925.1547 ± 154032.0482 (n=5)               0.2769 ± 0.1313 (n=5)                       0.0550 ± 0.0140 (n=5)

Dataset                                                                                                                                                                                            \
Metric                                             test_best_rerun/phm_score_normalized_mean test_best_rerun/rmse_denormalized_mean test_best_rerun/rmse_normalized_mean                 val/loss
Model
baselines.crossformer_model.Crossformer_Forecaster                     0.3083 ± 0.0163 (n=5)                 49.4970 ± 4.0689 (n=5)                0.0457 ± 0.0038 (n=5)    0.0018 ± 0.0003 (n=5)
baselines.lstm_model.LSTM_Forecaster                                   0.2547 ± 0.0155 (n=5)                 49.9535 ± 2.3129 (n=5)                0.0461 ± 0.0021 (n=5)    0.0019 ± 0.0002 (n=5)
baselines.patchtst_model.PatchTST_Forecaster                           0.2349 ± 0.0028 (n=5)                 77.5613 ± 0.5809 (n=5)                0.0716 ± 0.0005 (n=5)    0.0043 ± 0.0001 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...                     0.2029 ± 0.0310 (n=5)                 80.1586 ± 9.8126 (n=5)                0.0740 ± 0.0091 (n=5)    1.0792 ± 0.5181 (n=5)
baselines.tide_model.TiDE_Forecaster                                   0.2949 ± 0.0297 (n=5)                 42.7440 ± 1.6112 (n=5)                0.0395 ± 0.0015 (n=5)    0.0019 ± 0.0006 (n=5)
baselines.timeseries_transformer_model.Timeseri...                     0.2253 ± 0.0121 (n=5)                 73.5311 ± 7.1928 (n=5)                0.0679 ± 0.0066 (n=5)    0.0089 ± 0.0038 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper                             0.1759 ± 0.0179 (n=5)               122.1711 ± 22.0143 (n=5)                0.1128 ± 0.0203 (n=5)    0.0949 ± 0.1182 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...                        nan ± 0.0000 (n=0)                     nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...                        nan ± 0.0000 (n=0)                     nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                                  0.1447 ± 0.0603 (n=5)              209.2534 ± 119.6525 (n=5)                0.1932 ± 0.1105 (n=5)    0.2057 ± 0.2304 (n=5)
model.wrappers.statistical_models_wrapper.Stati...                     0.0313 ± 0.0001 (n=5)                160.4152 ± 0.0102 (n=5)                0.1481 ± 0.0000 (n=5)    0.0508 ± 0.0457 (n=5)
model.wrappers.statistical_models_wrapper.Stati...                     0.0550 ± 0.0140 (n=5)              527.4837 ± 137.1559 (n=5)                0.4870 ± 0.1266 (n=5)  19.7003 ± 24.7142 (n=5)

Dataset                                                                                                                                                                                         \
Metric                                              val/mae_denormalized_mean val/mae_normalized_mean val/mape_denormalized_mean val/mape_normalized_mean            val/mse_denormalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster     37.7371 ± 4.6903 (n=5)   0.0348 ± 0.0043 (n=5)      2.1162 ± 0.3232 (n=5)    2.1162 ± 0.3232 (n=5)           2503.3202 ± 528.8147 (n=5)
baselines.lstm_model.LSTM_Forecaster                   37.8514 ± 2.7414 (n=5)   0.0349 ± 0.0025 (n=5)      2.1897 ± 0.2090 (n=5)    2.1897 ± 0.2090 (n=5)           2873.5661 ± 306.9954 (n=5)
baselines.patchtst_model.PatchTST_Forecaster           59.3844 ± 0.9261 (n=5)   0.0548 ± 0.0009 (n=5)      2.7441 ± 0.1956 (n=5)    2.7441 ± 0.1956 (n=5)           5637.7305 ± 236.8623 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...   133.9338 ± 26.8927 (n=5)   0.1236 ± 0.0248 (n=5)      4.3979 ± 0.6118 (n=5)    4.3979 ± 0.6118 (n=5)      926752.0938 ± 444094.9471 (n=5)
baselines.tide_model.TiDE_Forecaster                   39.3759 ± 5.0496 (n=5)   0.0364 ± 0.0047 (n=5)      2.3988 ± 0.2799 (n=5)    2.3988 ± 0.2799 (n=5)           2648.1651 ± 759.5156 (n=5)
baselines.timeseries_transformer_model.Timeseri...     57.7204 ± 3.3994 (n=5)   0.0533 ± 0.0031 (n=5)      3.5900 ± 0.3197 (n=5)    3.5900 ± 0.3197 (n=5)          9658.9764 ± 3350.4078 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper           105.7017 ± 18.6495 (n=5)   0.0976 ± 0.0172 (n=5)      5.9408 ± 1.4956 (n=5)    5.9408 ± 1.4956 (n=5)       87644.9619 ± 104535.4546 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...         nan ± 0.0000 (n=0)      nan ± 0.0000 (n=0)         nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...         nan ± 0.0000 (n=0)      nan ± 0.0000 (n=0)         nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)                   nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                163.7118 ± 81.1831 (n=5)   0.1511 ± 0.0749 (n=5)     11.4112 ± 6.4508 (n=5)   11.4112 ± 6.4508 (n=5)      191302.3578 ± 211946.3189 (n=5)
model.wrappers.statistical_models_wrapper.Stati...    149.6378 ± 1.5809 (n=5)   0.1381 ± 0.0015 (n=5)      1.0014 ± 0.0039 (n=5)    1.0014 ± 0.0039 (n=5)        51613.6133 ± 39217.9905 (n=5)
model.wrappers.statistical_models_wrapper.Stati...  494.2961 ± 106.5868 (n=5)   0.4563 ± 0.0984 (n=5)     24.8409 ± 8.6942 (n=5)   24.8409 ± 8.6942 (n=5)  17428995.4000 ± 21807867.8288 (n=5)

Dataset                                                                                                                                                                                          \
Metric                                              val/mse_normalized_mean val/phm_score_denormalized_mean val/phm_score_normalized_mean   val/rmse_denormalized_mean val/rmse_normalized_mean
Model
baselines.crossformer_model.Crossformer_Forecaster    0.0021 ± 0.0005 (n=5)           0.3082 ± 0.0429 (n=5)         0.3082 ± 0.0429 (n=5)       47.1271 ± 5.0668 (n=5)    0.0435 ± 0.0047 (n=5)
baselines.lstm_model.LSTM_Forecaster                  0.0024 ± 0.0003 (n=5)           0.3174 ± 0.0240 (n=5)         0.3174 ± 0.0240 (n=5)       46.9656 ± 3.8908 (n=5)    0.0434 ± 0.0036 (n=5)
baselines.patchtst_model.PatchTST_Forecaster          0.0048 ± 0.0002 (n=5)           0.2665 ± 0.0055 (n=5)         0.2665 ± 0.0055 (n=5)       73.9168 ± 1.2187 (n=5)    0.0682 ± 0.0011 (n=5)
baselines.spacetimeformer_model.Spacetimeformer...    0.7898 ± 0.3785 (n=5)           0.2836 ± 0.0281 (n=5)         0.2836 ± 0.0281 (n=5)    434.6919 ± 109.0902 (n=5)    0.4013 ± 0.1007 (n=5)
baselines.tide_model.TiDE_Forecaster                  0.0023 ± 0.0006 (n=5)           0.3068 ± 0.0365 (n=5)         0.3068 ± 0.0365 (n=5)       47.9501 ± 6.5718 (n=5)    0.0443 ± 0.0061 (n=5)
baselines.timeseries_transformer_model.Timeseri...    0.0082 ± 0.0029 (n=5)           0.2773 ± 0.0087 (n=5)         0.2773 ± 0.0087 (n=5)      86.0128 ± 10.3297 (n=5)    0.0794 ± 0.0095 (n=5)
model.wrappers.cnn1d_wrapper.CNN1D_Wrapper            0.0747 ± 0.0891 (n=5)           0.2046 ± 0.0213 (n=5)         0.2046 ± 0.0213 (n=5)     192.4116 ± 78.5082 (n=5)    0.1776 ± 0.0725 (n=5)
model.wrappers.fit_predict_tabdpt_wrapper.FitPr...       nan ± 0.0000 (n=0)              nan ± 0.0000 (n=0)            nan ± 0.0000 (n=0)           nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)
model.wrappers.fit_predict_tabpfn_wrapper.FitPr...       nan ± 0.0000 (n=0)              nan ± 0.0000 (n=0)            nan ± 0.0000 (n=0)           nan ± 0.0000 (n=0)       nan ± 0.0000 (n=0)
model.wrappers.mlp_wrapper.MLPWrapper                 0.1630 ± 0.1806 (n=5)           0.1680 ± 0.0632 (n=5)         0.1680 ± 0.0632 (n=5)    301.2852 ± 156.1535 (n=5)    0.2781 ± 0.1442 (n=5)
model.wrappers.statistical_models_wrapper.Stati...    0.0440 ± 0.0334 (n=5)           0.0313 ± 0.0000 (n=5)         0.0313 ± 0.0000 (n=5)     202.2958 ± 42.9449 (n=5)    0.1868 ± 0.0396 (n=5)

In [2]:
# 1. Access the raw data for the specific model and dataset
model_key = "picid.baselines.spacetimeformer_model.Spacetimeformer_Forecaster"
dataset_key = "NB14"

# This DF contains all runs for this model before aggregation
df_subset = all_results[dataset_key][model_key]["non_aggregated_df"]

In [5]:
[i for i in list(df_subset.columns) if "datasource" in i]

['datasource._target_',
 'datasource.data_dir',
 'datasource.data_name',
 'datasource.task_mode']

In [22]:
# 1. Access the raw data for the specific model and dataset
model_key = "picid.baselines.spacetimeformer_model.Spacetimeformer_Forecaster"
dataset_key = "UNIBO21"

# This DF contains all runs for this model before aggregation
df_subset = all_results[dataset_key][model_key]["non_aggregated_df"]

# 2. Filter for ONE specific configuration that shows count=15
# (Based on your screenshot: lr=0.0001, seq_len=10, batch_size=16)
mask = (
    (df_subset["optimization.lr"] == 0.0001)
    & (df_subset["task_definition.seq_len"] == 10)
    & (df_subset["datamodule.train_batch_size"] == 16)
)
group_runs = df_subset[mask]

# 3. Display identifiers to spot the duplicates
# 'created_at' will show you if these runs are from different times/days
cols_to_inspect = [
    "run_name",
    "id",
    "created_at",
    "seed",
    "datasource.parameters.data_seed",
]
valid_cols = [c for c in cols_to_inspect if c in group_runs.columns]

print(f"Found {len(group_runs)} runs for this configuration (Expected 5).")
print("Listing all runs in this group:")
# display(group_runs[valid_cols].sort_values('created_at'))

Found 5 runs for this configuration (Expected 5).
Listing all runs in this group:

In [ ]:
df_subset

\begin{tabular}{ll}
\toprule
 & 0 \\
\midrule
AvgTime/train_batch_mean & 0.020657 \\
AvgTime/train_batch_std & 0.005162 \\
AvgTime/train_epoch_mean & 11.607952 \\
AvgTime/train_epoch_std & 0.450640 \\
AvgTime/val_batch_mean & 0.008616 \\
AvgTime/val_batch_std & 0.000965 \\
AvgTime/val_epoch_mean & 0.036777 \\
AvgTime/val_epoch_std & 0.002732 \\
_runtime & 306 \\
_step & 490 \\
_timestamp & 1769624335.062802 \\
epoch & 25 \\
lr-AdamW & 0.000902 \\
plots/test/pred_vs_target_unit_10 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_10_478_79be3a6b41f2384b3f28.plotly.json', 'sha256': '79be3a6b41f2384b3f284f3a04ea9ec558be424cd78f12632c04666c0f8665d2', 'size': 29913} \\
plots/test/pred_vs_target_unit_11 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_11_485_aa7b2f092bbec702f9dc.plotly.json', 'sha256': 'aa7b2f092bbec702f9dcde687afc921f046ea5c1f5c4e71eeb175f1442ced9cc', 'size': 29299} \\
plots/test/pred_vs_target_unit_13 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_13_486_49d1987c908151f2756b.plotly.json', 'sha256': '49d1987c908151f2756bb4ffe8bf2a7f2d10d578acd8ea5f3c2931e1877be67c', 'size': 22408} \\
plots/test/pred_vs_target_unit_16 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_16_479_f9e75831bab8e3c6bbef.plotly.json', 'sha256': 'f9e75831bab8e3c6bbefccdf61cfca436d6a80214345c68907a34324b0026b97', 'size': 23488} \\
plots/test/pred_vs_target_unit_2 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_2_477_6dc834a7a523c6cad013.plotly.json', 'sha256': '6dc834a7a523c6cad0130107a3695d8d6a3697e8b3f8e54844ef1925fb2d2846', 'size': 24081} \\
plots/test/pred_vs_target_unit_3 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_3_483_8b11ea8a99fae3fef442.plotly.json', 'sha256': '8b11ea8a99fae3fef442598b0722da4fe0f21ae1f4724b49d8d1aad80f959293', 'size': 24794} \\
plots/test/pred_vs_target_unit_39 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_39_487_1a9dcfc1321d44ef717a.plotly.json', 'sha256': '1a9dcfc1321d44ef717ad6c9a3599d994a8149beb504adae7bce0771958f2d9f', 'size': 37113} \\
plots/test/pred_vs_target_unit_41 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_41_488_0de776126748ac01a2b2.plotly.json', 'sha256': '0de776126748ac01a2b2f2cbc0bc516adadbaf934004c43986a81aebdd462b96', 'size': 15238} \\
plots/test/pred_vs_target_unit_42 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_42_480_0c0254105ebeb56a1efe.plotly.json', 'sha256': '0c0254105ebeb56a1efe9a57ce75fc634d31477bdd3e0b968fd604f56eca22f5', 'size': 54508} \\
plots/test/pred_vs_target_unit_44 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_44_489_b2a649da357c75bc2cc7.plotly.json', 'sha256': 'b2a649da357c75bc2cc7cd11a1765f71c39854e87d72c706deef1c3c389c09f8', 'size': 54244} \\
plots/test/pred_vs_target_unit_51 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_51_481_7c25dcfbd2e748ec2d4a.plotly.json', 'sha256': '7c25dcfbd2e748ec2d4a3fc6caf1a4f6510f7bbfdccffaa8400c7be677816b6f', 'size': 38339} \\
plots/test/pred_vs_target_unit_6 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_6_484_50b61aae8f2050981541.plotly.json', 'sha256': '50b61aae8f2050981541b9ee379a3861eb91d3b8f32a632ad322fa15ce63b1a8', 'size': 42140} \\
plots/val/pred_vs_target_unit_10 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_10_462_7d940481f0d6b9407246.plotly.json', 'sha256': '7d940481f0d6b94072468639839994882312de614f34253e20966fec0013d66a', 'size': 30258} \\
plots/val/pred_vs_target_unit_16 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_16_463_df70b3bab00f499c7663.plotly.json', 'sha256': 'df70b3bab00f499c7663461540266aa9b4e659375ebf79cc98913c94fdd8fc52', 'size': 23798} \\
plots/val/pred_vs_target_unit_2 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_2_461_6164449c8394864db36f.plotly.json', 'sha256': '6164449c8394864db36f13311f4e6e303ff70236987aa8c447ac638fd3431cb3', 'size': 24268} \\
plots/val/pred_vs_target_unit_42 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_42_464_fd2f58af50f83e195ad3.plotly.json', 'sha256': 'fd2f58af50f83e195ad382ca75503e955f64d7ebb58f049719aea2041edf7ec9', 'size': 55046} \\
plots/val/pred_vs_target_unit_51 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_51_465_2ec954e10c652ef899d1.plotly.json', 'sha256': '2ec954e10c652ef899d1fec073548df4afe163d1e1027c493a600e6b062763ea', 'size': 38450} \\
test/loss & 0.021859 \\
test/mae_11_denormalized & 18.546143 \\
test/mae_11_normalized & 0.037676 \\
test/mae_13_denormalized & 23.699884 \\
test/mae_13_normalized & 0.048145 \\
test/mae_39_denormalized & 111.109581 \\
test/mae_39_normalized & 0.225714 \\
test/mae_3_denormalized & 28.114170 \\
test/mae_3_normalized & 0.057113 \\
test/mae_41_denormalized & 54.811863 \\
test/mae_41_normalized & 0.111348 \\
test/mae_44_denormalized & 37.308807 \\
test/mae_44_normalized & 0.075791 \\
test/mae_6_denormalized & 56.545311 \\
test/mae_6_normalized & 0.114869 \\
test/mae_denormalized_mean & 47.162254 \\
test/mae_normalized_mean & 0.095808 \\
test/mape_11_denormalized & 0.885242 \\
test/mape_11_normalized & 0.885242 \\
test/mape_13_denormalized & 1.702330 \\
test/mape_13_normalized & 1.702330 \\
test/mape_39_denormalized & 0.570063 \\
test/mape_39_normalized & 0.570063 \\
test/mape_3_denormalized & 1.206405 \\
test/mape_3_normalized & 1.206405 \\
test/mape_41_denormalized & 4.268859 \\
test/mape_41_normalized & 4.268860 \\
test/mape_44_denormalized & 0.956341 \\
test/mape_44_normalized & 0.956341 \\
test/mape_6_denormalized & 0.548364 \\
test/mape_6_normalized & 0.548364 \\
test/mape_denormalized_mean & 1.448229 \\
test/mape_normalized_mean & 1.448229 \\
test/mse_11_denormalized & 562.209045 \\
test/mse_11_normalized & 0.002320 \\
test/mse_13_denormalized & 656.934753 \\
test/mse_13_normalized & 0.002711 \\
test/mse_39_denormalized & 16500.416016 \\
test/mse_39_normalized & 0.068094 \\
test/mse_3_denormalized & 1149.456665 \\
test/mse_3_normalized & 0.004744 \\
test/mse_41_denormalized & 4725.065430 \\
test/mse_41_normalized & 0.019499 \\
test/mse_44_denormalized & 4240.558594 \\
test/mse_44_normalized & 0.017500 \\
test/mse_6_denormalized & 5640.681641 \\
test/mse_6_normalized & 0.023278 \\
test/mse_denormalized_mean & 4782.188965 \\
test/mse_normalized_mean & 0.019735 \\
test/phm_score_11_denormalized & 0.072037 \\
test/phm_score_11_normalized & 0.072037 \\
test/phm_score_13_denormalized & 0.081722 \\
test/phm_score_13_normalized & 0.081722 \\
test/phm_score_39_denormalized & 0.178090 \\
test/phm_score_39_normalized & 0.178090 \\
test/phm_score_3_denormalized & 0.087105 \\
test/phm_score_3_normalized & 0.087105 \\
test/phm_score_41_denormalized & 0.159254 \\
test/phm_score_41_normalized & 0.159254 \\
test/phm_score_44_denormalized & 0.056520 \\
test/phm_score_44_normalized & 0.056520 \\
test/phm_score_6_denormalized & 0.156937 \\
test/phm_score_6_normalized & 0.156937 \\
test/phm_score_denormalized_mean & 0.113095 \\
test/phm_score_normalized_mean & 0.113095 \\
test/rmse_11_denormalized & 23.710949 \\
test/rmse_11_normalized & 0.048168 \\
test/rmse_13_denormalized & 25.630737 \\
test/rmse_13_normalized & 0.052068 \\
test/rmse_39_denormalized & 128.453949 \\
test/rmse_39_normalized & 0.260948 \\
test/rmse_3_denormalized & 33.903637 \\
test/rmse_3_normalized & 0.068874 \\
test/rmse_41_denormalized & 68.739113 \\
test/rmse_41_normalized & 0.139640 \\
test/rmse_44_denormalized & 65.119568 \\
test/rmse_44_normalized & 0.132287 \\
test/rmse_6_denormalized & 75.104469 \\
test/rmse_6_normalized & 0.152571 \\
test/rmse_denormalized_mean & 60.094631 \\
test/rmse_normalized_mean & 0.122080 \\
test_best_rerun/loss & 0.021859 \\
test_best_rerun/mae_11_denormalized & 18.546143 \\
test_best_rerun/mae_11_normalized & 0.037676 \\
test_best_rerun/mae_13_denormalized & 23.699884 \\
test_best_rerun/mae_13_normalized & 0.048145 \\
test_best_rerun/mae_39_denormalized & 111.109581 \\
test_best_rerun/mae_39_normalized & 0.225714 \\
test_best_rerun/mae_3_denormalized & 28.114170 \\
test_best_rerun/mae_3_normalized & 0.057113 \\
test_best_rerun/mae_41_denormalized & 54.811863 \\
test_best_rerun/mae_41_normalized & 0.111348 \\
test_best_rerun/mae_44_denormalized & 37.308807 \\
test_best_rerun/mae_44_normalized & 0.075791 \\
test_best_rerun/mae_6_denormalized & 56.545311 \\
test_best_rerun/mae_6_normalized & 0.114869 \\
test_best_rerun/mae_denormalized_mean & 47.162254 \\
test_best_rerun/mae_normalized_mean & 0.095808 \\
test_best_rerun/mape_11_denormalized & 0.885242 \\
test_best_rerun/mape_11_normalized & 0.885242 \\
test_best_rerun/mape_13_denormalized & 1.702330 \\
test_best_rerun/mape_13_normalized & 1.702330 \\
test_best_rerun/mape_39_denormalized & 0.570063 \\
test_best_rerun/mape_39_normalized & 0.570063 \\
test_best_rerun/mape_3_denormalized & 1.206405 \\
test_best_rerun/mape_3_normalized & 1.206405 \\
test_best_rerun/mape_41_denormalized & 4.268859 \\
test_best_rerun/mape_41_normalized & 4.268860 \\
test_best_rerun/mape_44_denormalized & 0.956341 \\
test_best_rerun/mape_44_normalized & 0.956341 \\
test_best_rerun/mape_6_denormalized & 0.548364 \\
test_best_rerun/mape_6_normalized & 0.548364 \\
test_best_rerun/mape_denormalized_mean & 1.448229 \\
test_best_rerun/mape_normalized_mean & 1.448229 \\
test_best_rerun/mse_11_denormalized & 562.209045 \\
test_best_rerun/mse_11_normalized & 0.002320 \\
test_best_rerun/mse_13_denormalized & 656.934753 \\
test_best_rerun/mse_13_normalized & 0.002711 \\
test_best_rerun/mse_39_denormalized & 16500.416016 \\
test_best_rerun/mse_39_normalized & 0.068094 \\
test_best_rerun/mse_3_denormalized & 1149.456665 \\
test_best_rerun/mse_3_normalized & 0.004744 \\
test_best_rerun/mse_41_denormalized & 4725.065430 \\
test_best_rerun/mse_41_normalized & 0.019499 \\
test_best_rerun/mse_44_denormalized & 4240.558594 \\
test_best_rerun/mse_44_normalized & 0.017500 \\
test_best_rerun/mse_6_denormalized & 5640.681641 \\
test_best_rerun/mse_6_normalized & 0.023278 \\
test_best_rerun/mse_denormalized_mean & 4782.188965 \\
test_best_rerun/mse_normalized_mean & 0.019735 \\
test_best_rerun/phm_score_11_denormalized & 0.072037 \\
test_best_rerun/phm_score_11_normalized & 0.072037 \\
test_best_rerun/phm_score_13_denormalized & 0.081722 \\
test_best_rerun/phm_score_13_normalized & 0.081722 \\
test_best_rerun/phm_score_39_denormalized & 0.178090 \\
test_best_rerun/phm_score_39_normalized & 0.178090 \\
test_best_rerun/phm_score_3_denormalized & 0.087105 \\
test_best_rerun/phm_score_3_normalized & 0.087105 \\
test_best_rerun/phm_score_41_denormalized & 0.159254 \\
test_best_rerun/phm_score_41_normalized & 0.159254 \\
test_best_rerun/phm_score_44_denormalized & 0.056520 \\
test_best_rerun/phm_score_44_normalized & 0.056520 \\
test_best_rerun/phm_score_6_denormalized & 0.156937 \\
test_best_rerun/phm_score_6_normalized & 0.156937 \\
test_best_rerun/phm_score_denormalized_mean & 0.113095 \\
test_best_rerun/phm_score_normalized_mean & 0.113095 \\
test_best_rerun/rmse_11_denormalized & 23.710949 \\
test_best_rerun/rmse_11_normalized & 0.048168 \\
test_best_rerun/rmse_13_denormalized & 25.630737 \\
test_best_rerun/rmse_13_normalized & 0.052068 \\
test_best_rerun/rmse_39_denormalized & 128.453949 \\
test_best_rerun/rmse_39_normalized & 0.260948 \\
test_best_rerun/rmse_3_denormalized & 33.903637 \\
test_best_rerun/rmse_3_normalized & 0.068874 \\
test_best_rerun/rmse_41_denormalized & 68.739113 \\
test_best_rerun/rmse_41_normalized & 0.139640 \\
test_best_rerun/rmse_44_denormalized & 65.119568 \\
test_best_rerun/rmse_44_normalized & 0.132287 \\
test_best_rerun/rmse_6_denormalized & 75.104469 \\
test_best_rerun/rmse_6_normalized & 0.152571 \\
test_best_rerun/rmse_denormalized_mean & 60.094631 \\
test_best_rerun/rmse_normalized_mean & 0.122080 \\
train/loss_epoch & 0.010704 \\
train/loss_step & 0.003716 \\
trainer/global_step & 13425 \\
val/loss & 0.028202 \\
val/mae_10_denormalized & 28.014641 \\
val/mae_10_normalized & 0.056910 \\
val/mae_16_denormalized & 33.018032 \\
val/mae_16_normalized & 0.067075 \\
val/mae_2_denormalized & 32.433949 \\
val/mae_2_normalized & 0.065888 \\
val/mae_42_denormalized & 64.206894 \\
val/mae_42_normalized & 0.130433 \\
val/mae_51_denormalized & 54.071411 \\
val/mae_51_normalized & 0.109844 \\
val/mae_denormalized_mean & 42.348988 \\
val/mae_normalized_mean & 0.086030 \\
val/mape_10_denormalized & 1.720226 \\
val/mape_10_normalized & 1.720226 \\
val/mape_16_denormalized & 0.957835 \\
val/mape_16_normalized & 0.957835 \\
val/mape_2_denormalized & 0.826357 \\
val/mape_2_normalized & 0.826357 \\
val/mape_42_denormalized & 0.808630 \\
val/mape_42_normalized & 0.808630 \\
val/mape_51_denormalized & 1.048445 \\
val/mape_51_normalized & 1.048445 \\
val/mape_denormalized_mean & 1.072299 \\
val/mape_normalized_mean & 1.072299 \\
val/mse_10_denormalized & 1459.913086 \\
val/mse_10_normalized & 0.006025 \\
val/mse_16_denormalized & 2472.047852 \\
val/mse_16_normalized & 0.010202 \\
val/mse_2_denormalized & 2276.131104 \\
val/mse_2_normalized & 0.009393 \\
val/mse_42_denormalized & 13946.560547 \\
val/mse_42_normalized & 0.057555 \\
val/mse_51_denormalized & 4194.742188 \\
val/mse_51_normalized & 0.017311 \\
val/mse_denormalized_mean & 4869.878906 \\
val/mse_normalized_mean & 0.020097 \\
val/phm_score_10_denormalized & 0.013500 \\
val/phm_score_10_normalized & 0.013500 \\
val/phm_score_16_denormalized & 0.018126 \\
val/phm_score_16_normalized & 0.018126 \\
val/phm_score_2_denormalized & 0.082461 \\
val/phm_score_2_normalized & 0.082461 \\
val/phm_score_42_denormalized & 0.034890 \\
val/phm_score_42_normalized & 0.034890 \\
val/phm_score_51_denormalized & 0.236461 \\
val/phm_score_51_normalized & 0.236461 \\
val/phm_score_denormalized_mean & 0.077088 \\
val/phm_score_normalized_mean & 0.077088 \\
val/rmse_10_denormalized & 38.208809 \\
val/rmse_10_normalized & 0.077619 \\
val/rmse_16_denormalized & 49.719692 \\
val/rmse_16_normalized & 0.101003 \\
val/rmse_2_denormalized & 47.708817 \\
val/rmse_2_normalized & 0.096918 \\
val/rmse_42_denormalized & 118.095558 \\
val/rmse_42_normalized & 0.239906 \\
val/rmse_51_denormalized & 64.766830 \\
val/rmse_51_normalized & 0.131571 \\
val/rmse_denormalized_mean & 63.699940 \\
val/rmse_normalized_mean & 0.129404 \\
d_x & 72 \\
d_ff & 128 \\
d_yc & 0 \\
d_yt & 1 \\
loss & mse \\
norm & batch \\
seed & 72 \\
tags & ['dev'] \\
test & True \\
train & True \\
head_f & linear \\
base_lr & 0.001000 \\
d_model & 128 \\
n_heads & 7 \\
verbose & True \\
d_layers & 3 \\
d_values & 50 \\
e_layers & 2 \\
exp_name & unibo/prognostics/combined/stf \\
mask_y_c & False \\
metadata & {'lightning_model': True} \\
use_time & True \\

In [19]:
print(df_subset.iloc[0].to_latex())

\begin{tabular}{ll}
\toprule
 & 30 \\
\midrule
AvgTime/train_batch_mean & 0.024092 \\
AvgTime/train_batch_std & 0.006863 \\
AvgTime/train_epoch_mean & 12.582578 \\
AvgTime/train_epoch_std & 1.215955 \\
AvgTime/val_batch_mean & 0.018669 \\
AvgTime/val_batch_std & 0.008642 \\
AvgTime/val_epoch_mean & 0.073752 \\
AvgTime/val_epoch_std & 0.012027 \\
_runtime & 1358 \\
_step & 1918 \\
_timestamp & 1762901279.126953 \\
epoch & 100 \\
lr-Adam & NaN \\
plots/test/pred_vs_target_unit_10 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_10_1906_ce34dedb41d76ea75180.plotly.json', 'sha256': 'ce34dedb41d76ea75180778ff341f8960afc2147b56aaece910ba30348b5591a', 'size': 28982} \\
plots/test/pred_vs_target_unit_11 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_11_1913_09482285d5caa3b46983.plotly.json', 'sha256': '09482285d5caa3b469839a8d5678ab7aeeee53c83d349bc317ef18a2e1c4c76e', 'size': 28379} \\
plots/test/pred_vs_target_unit_13 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_13_1914_35b4d458ee638d8d385f.plotly.json', 'sha256': '35b4d458ee638d8d385f2489306584921833b57149c9fcba6bd9e67ff47c822b', 'size': 21554} \\
plots/test/pred_vs_target_unit_16 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_16_1907_ce266ab035a63633692a.plotly.json', 'sha256': 'ce266ab035a63633692a4115a589c4db220d399fd269f467ce185da19c51766c', 'size': 22598} \\
plots/test/pred_vs_target_unit_2 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_2_1905_e92a138b0b81e696f46f.plotly.json', 'sha256': 'e92a138b0b81e696f46ff215a68b8fcd7c5e8128dd550f157869815c9161d4de', 'size': 23241} \\
plots/test/pred_vs_target_unit_3 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_3_1911_2f5a21e691596f5151ee.plotly.json', 'sha256': '2f5a21e691596f5151ee0d62c688612bfc5ecdf0c936567f21f829f30116217a', 'size': 23915} \\
plots/test/pred_vs_target_unit_39 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_39_1915_f02d856406675a7df9e8.plotly.json', 'sha256': 'f02d856406675a7df9e849aac76218e84d5f543b572c673f5ab903e08cc0d3ed', 'size': 36257} \\
plots/test/pred_vs_target_unit_41 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_41_1916_9278a60c3dbc4f1f99fd.plotly.json', 'sha256': '9278a60c3dbc4f1f99fd12a560108182559f724ee4f24aada2c1a814eda8dac5', 'size': 14432} \\
plots/test/pred_vs_target_unit_42 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_42_1908_1acd4003e85c66750e46.plotly.json', 'sha256': '1acd4003e85c66750e4625bc2f5d9444d63bae887fd047d11550d33aa6b2f0fa', 'size': 53470} \\
plots/test/pred_vs_target_unit_44 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_44_1917_5e24f0cbaf20e63e7b9e.plotly.json', 'sha256': '5e24f0cbaf20e63e7b9ea5eef571fbf8432ebfa41f1d16a474c748139923c271', 'size': 52967} \\
plots/test/pred_vs_target_unit_51 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_51_1909_7c31413a20e917ecb55c.plotly.json', 'sha256': '7c31413a20e917ecb55cc4dff746ad789da85beacac75df2ee35bbf0594391a7', 'size': 37537} \\
plots/test/pred_vs_target_unit_6 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/test/pred_vs_target_unit_6_1912_777497531ba87bc147c0.plotly.json', 'sha256': '777497531ba87bc147c0b145a46d970132b905079056a1b5141298294d0a5b7a', 'size': 41221} \\
plots/val/pred_vs_target_unit_10 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_10_1890_7b9196d8d0b26dbbe4f6.plotly.json', 'sha256': '7b9196d8d0b26dbbe4f63e235f7a545b4d05277463a92faaa3d9fc4be3fab930', 'size': 29510} \\
plots/val/pred_vs_target_unit_16 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_16_1891_f522c721271e622db04b.plotly.json', 'sha256': 'f522c721271e622db04b9e144b13d15bfe7c45397c044e10b0e6489bcf089331', 'size': 22949} \\
plots/val/pred_vs_target_unit_2 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_2_1889_662158fe3b70a65b4b71.plotly.json', 'sha256': '662158fe3b70a65b4b714cba8de32e6843e863183ab01707c29c079ef9f01cb1', 'size': 23344} \\
plots/val/pred_vs_target_unit_42 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_42_1892_c3072de8904e5cb425b9.plotly.json', 'sha256': 'c3072de8904e5cb425b9f66427b3d5416284b2e07418b633b8c5e948c56ae8d1', 'size': 54034} \\
plots/val/pred_vs_target_unit_51 & {'_type': 'plotly-file', 'path': 'media/plotly/plots/val/pred_vs_target_unit_51_1893_a91e3bb2011340c5bf37.plotly.json', 'sha256': 'a91e3bb2011340c5bf3768face9edde1b820065ebc2580004181daf24c5f1199', 'size': 37615} \\
test/loss & 0.023967 \\
test/mae_mean & 43.193264 \\
test/mape_mean & 1.728788 \\
test/mse_mean & 4746.603516 \\
test/phm_score_mean & 0.134455 \\
test/rmse_mean & 57.381641 \\
test_best_rerun/loss & 0.023967 \\
test_best_rerun/mae_mean & 43.193264 \\
test_best_rerun/mape_mean & 1.728788 \\
test_best_rerun/mse_mean & 4746.603516 \\
test_best_rerun/phm_score_mean & 0.134455 \\
test_best_rerun/rmse_mean & 57.381641 \\
train/loss_epoch & 0.000685 \\
train/loss_step & 0.000618 \\
train/mae_mean & 7.788931 \\
train/mape_mean & 0.401982 \\
train/mse_mean & 163.049347 \\
train/phm_score_mean & 0.219114 \\
train/rmse_mean & 12.364769 \\
trainer/global_step & 52300 \\
val/loss & 0.030273 \\
val/mae_mean & 42.442570 \\
val/mape_mean & 0.990072 \\
val/mse_mean & 6007.494629 \\
val/phm_score_mean & 0.107708 \\
val/rmse_mean & 59.091045 \\
val_best_rerun/loss & 0.014236 \\
val_best_rerun/mae_mean & 42.538048 \\
val_best_rerun/mape_mean & 2.022349 \\
val_best_rerun/mse_mean & 3138.406982 \\
val_best_rerun/phm_score_mean & 0.063100 \\
val_best_rerun/rmse_mean & 51.129303 \\
d_x & 72.000000 \\
d_ff & 128.000000 \\
d_yc & 0.000000 \\
d_yt & 1.000000 \\
loss & mse \\
seed & 72 \\
tags & ['dev'] \\
test & True \\
train & True \\
ts_in & NaN \\
device & NaN \\
factor & NaN \\
ts_out & NaN \\
d_model & 128.000000 \\
dropout & NaN \\
n_heads & 7.000000 \\
seg_len & NaN \\
verbose & True \\
baseline & NaN \\
e_layers & 2.000000 \\
exp_name & unibo/prognostics/statistics/stf \\
mask_y_c & False \\
metadata & {'lightning_model': True} \\
win_size & NaN \\
hydra_cfg & {'job': {'id': '???', 'num': '???', 'name': '${flat:${experiment_group}/${hydra:runtime.choices.experiment}}', 'chdir': None, 'config': {'override_dirname': {'kv_sep': '=', 'item_sep': ',', 'exclude_keys': []}}, 'env_copy': [], 'config_name': 'run.yaml', 'override_dirname': 'cache.preprocessing_file_lock_path=/tmp/picid_preprocess.lock,cache.use_cache_after_loading=True,cache.use_cache_after_transfroms=True,cache.use_preprocessing_file_lock=False,datamodule.test_batch_size=1024,datamodule.train_batch_size=16,datamodule.val_batch_size=1024,enable_progress_bar=False,experiment=unibo/prognostics/statistics/stf,experiment_group=statistics,logger.wandb.project=unibo_full,paths=runai,seed=72,trainer.check_val_every_n_epoch=1,trainer.devices=[0],trainer.max_epochs=100'}, 'run': {'dir': '${paths.artifacts_dir}/${experiment_group}/runs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}'}, 'help': {'footer': 'Powered by Hydra (https://hydra.cc)\nUse --hydra-help to view Hydra specific help\n', 'header': '${hydra.help.app_name} is powered by Hydra.\n', 'app_name': '${hydra.job.name}', 'template': '${hydra.help.header}\n== Configuration groups ==\nCompose your configuration from those groups (group=option)\n\n$APP_CONFIG_GROUPS\n\n== Config ==\nOverride anything in the config (foo.bar=value)\n\n$CONFIG\n\n${hydra.help.footer}\n'}, 'mode': 'RUN', 'sweep': {'dir': '${paths.artifacts_dir}/${experiment_group}/multiruns/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}', 'subdir': '${hydra.job.num}'}, 'runtime': {'cwd': '/mnt/imos-students/rtheiler/projects/_rundir/unibo-baselines', 'choices': {'loss': 'default', 'cache': 'default', 'debug': None, 'hydra': 'default', 'model': 'stf', 'paths': 'runai', 'logger': 'wandb', 'dataset': 'prognostics/rul_multiunit_dataset', 'trainer': 'default', 'callbacks': 'default', 'evaluator': 'per_unit', 'hydra/env': 'default', 'datamodule': 'base_datamodule', 'datasource': 'unibo21_bosello', 'experiment': 'unibo/prognostics/statistics/stf', 'hydra/help': 'default', 'transforms': 'battery/unibo/statistics', 'hydra/output': 'default', 'optimization': 'warmup_reduce_on_plateau', 'hydra/sweeper': 'basic', 'hparams_search': None, 'hydra/launcher': 'basic', 'hydra/callbacks': None, 'task_definition': 'prognostics/rul', 'hydra/hydra_help': 'default', 'hydra/job_logging': 'colorlog', 'hydra/hydra_logging': 'colorlog'}, 'version': '1.3.2', 'output_dir': '/workspace/experiments/2025-09-18_TabPHM/statistics/runs/statistics+unibo+prognostics+statistics+stf/2025-11-11_23-25-12', 'version_base': '1.3', 'config_sources': [{'path': 'hydra.conf', 'schema': 'pkg', 'provider': 'hydra'}, {'path': '/mnt/imos-students/rtheiler/projects/_rundir/unibo-baselines/configs', 'schema': 'file', 'provider': 'main'}, {'path': 'hydra_plugins.hydra_colorlog.conf', 'schema': 'pkg', 'provider': 'hydra-colorlog'}, {'path': '', 'schema': 'structured', 'provider': 'schema'}]}, 'sweeper': {'params': None, '_target_': 'hydra._internal.core_plugins.basic_sweeper.BasicSweeper', 'max_batch_size': None}, 'verbose': False, 'launcher': {'_target_': 'hydra._internal.core_plugins.basic_launcher.BasicLauncher'}, 'overrides': {'task': ['paths=runai', 'experiment=unibo/prognostics/statistics/stf', 'datamodule.train_batch_size=16', 'datamodule.val_batch_size=1024', 'datamodule.test_batch_size=1024', 'trainer.check_val_every_n_epoch=1', 'trainer.max_epochs=100', 'trainer.devices=[0]', 'logger.wandb.project=unibo_full', 'cache.use_cache_after_loading=True', 'cache.use_cache_after_transfroms=True', 'cache.use_preprocessing_file_lock=False', 'cache.preprocessing_file_lock_path=/tmp/picid_preprocess.lock', 'enable_progress_bar=False', 'experiment_group=statistics', 'seed=72'], 'hydra': ['hydra.mode=RUN']}, 'hydra_help': {'template': "Hydra (${hydra.runtime.version})\nSee https://hydra.cc for more info.\n\n== Flags ==\n$FLAGS_HELP\n\n== Configuration groups ==\nCompose your configuration from those groups (For example, append hydra/job_logging=disabled to command line)\n\n$HYDRA_CONFIG_GROUPS\n\nUse '--cfg hydra' to Show the Hydra config.\n", 'hydra_help': '???'}, 'searchpath': [], 'job_logging': {'root': {'level': 'INFO', 'handlers': ['console', 'file']}, 'version': 1, 'handlers': {'file': {'class': 'logging.FileHandler', 'filename': '${hydra.runtime.output_dir}/${experiment_group}.log', 'formatter': 'simple'}, 'console': {'class': 'logging.StreamHandler', 'stream': 'ext://sys.stdout', 'formatter': 'colorlog'}}, 'formatters': {'simple': {'format': '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'}, 'colorlog': {'()': 'colorlog.ColoredFormatter', 'format': '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s', 'log_colors': {'INFO': 'green', 'DEBUG': 'purple', 'ERROR': 'red', 'WARNING': 'yellow', 'CRITICAL': 'red'}}}, 'disable_existing_loggers': False}, 'hydra_logging': {'root': {'level': 'INFO', 'handlers': ['console']}, 'version': 1, 'handlers': {'console': {'class': 'logging.StreamHandler', 'stream': 'ext://sys.stdout', 'formatter': 'colorlog'}}, 'formatters': {'colorlog': {'()': 'colorlog.ColoredFormatter', 'format': '[%(cyan)s%(asctime)s%(reset)s][%(purple)sHYDRA%(reset)s] %(message)s'}}, 'disable_existing_loggers': False}, 'output_subdir': '.hydra'} \\
task_type & rul \\
use_revin & False \\

In [12]:
import pandas as pd

# 1. Isolate the specific group
target_model = "picid.baselines.spacetimeformer_model.Spacetimeformer_Forecaster"

# Update this mask to match the specific "duplicate" group you saw in your table
mask = (
    (df["model._target_"] == target_model)
    & (df["optimization.lr"] == 0.0001)
    & (df["task_definition.seq_len"] == 10)
    & (df["datamodule.train_batch_size"] == 16)
)
group_runs = df[mask].copy()

# 2. Find "Hidden Variables" (Robust to lists/dicts)
varying_cols = []

for col in group_runs.columns:
    try:
        # Standard check for hashable types (int, float, str)
        if group_runs[col].nunique() > 1:
            varying_cols.append(col)
    except TypeError:
        # Fallback for unhashable types (lists, dicts): Convert to string first
        if group_runs[col].astype(str).nunique() > 1:
            varying_cols.append(col)

# 3. Add identifiers for context
# 'created_at' or '_timestamp' is CRITICAL to see if these are old vs new runs
context_cols = ["run_name", "seed", "created_at", "_timestamp"]

for c in context_cols:
    if c in group_runs.columns and c not in varying_cols:
        varying_cols.insert(0, c)

# 4. Display sorted by Seed to compare side-by-side
print(f"Found {len(group_runs)} runs in this group.")
print("Showing ONLY columns that differ between these runs:")

if not varying_cols:
    print("No varying columns found! These rows are EXACT duplicates.")
else:
    display(
        group_runs[varying_cols]
        .sort_values(
            by=["seed", "created_at"] if "created_at" in group_runs else ["seed"]
        )
        .style.set_properties(**{"text-align": "left"})
    )

Found 0 runs in this group.
Showing ONLY columns that differ between these runs:

In [6]:
group_runs.sort_values(
    by=["seed", "created_at"] if "created_at" in group_runs else ["seed"]
)["val_best_rerun/rmse_denormalized_mean"]

25    85.029541
26    88.634254
27    85.144997
28    88.849060
29    93.493942
Name: val_best_rerun/rmse_denormalized_mean, dtype: float64

In [7]:
group_runs.sort_values(
    by=["seed", "created_at"] if "created_at" in group_runs else ["seed"]
)[[i for i in group_runs.columns if "val_best_rerun" in i]]

,val_best_rerun/loss,val_best_rerun/mae_15_denormalized,val_best_rerun/mae_15_normalized,val_best_rerun/mae_18_denormalized,val_best_rerun/mae_18_normalized,val_best_rerun/mae_23_denormalized,val_best_rerun/mae_23_normalized,val_best_rerun/mae_27_denormalized,val_best_rerun/mae_27_normalized,val_best_rerun/mae_5_denormalized,val_best_rerun/mae_5_normalized,val_best_rerun/mae_7_denormalized,val_best_rerun/mae_7_normalized,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_15_denormalized,val_best_rerun/mape_15_normalized,val_best_rerun/mape_18_denormalized,val_best_rerun/mape_18_normalized,val_best_rerun/mape_23_denormalized,val_best_rerun/mape_23_normalized,val_best_rerun/mape_27_denormalized,val_best_rerun/mape_27_normalized,val_best_rerun/mape_5_denormalized,val_best_rerun/mape_5_normalized,val_best_rerun/mape_7_denormalized,val_best_rerun/mape_7_normalized,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_15_denormalized,val_best_rerun/mse_15_normalized,val_best_rerun/mse_18_denormalized,val_best_rerun/mse_18_normalized,val_best_rerun/mse_23_denormalized,val_best_rerun/mse_23_normalized,val_best_rerun/mse_27_denormalized,val_best_rerun/mse_27_normalized,val_best_rerun/mse_5_denormalized,val_best_rerun/mse_5_normalized,val_best_rerun/mse_7_denormalized,val_best_rerun/mse_7_normalized,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_15_denormalized,val_best_rerun/phm_score_15_normalized,val_best_rerun/phm_score_18_denormalized,val_best_rerun/phm_score_18_normalized,val_best_rerun/phm_score_23_denormalized,val_best_rerun/phm_score_23_normalized,val_best_rerun/phm_score_27_denormalized,val_best_rerun/phm_score_27_normalized,val_best_rerun/phm_score_5_denormalized,val_best_rerun/phm_score_5_normalized,val_best_rerun/phm_score_7_denormalized,val_best_rerun/phm_score_7_normalized,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_15_denormalized,val_best_rerun/rmse_15_normalized,val_best_rerun/rmse_18_denormalized,val_best_rerun/rmse_18_normalized,val_best_rerun/rmse_23_denormalized,val_best_rerun/rmse_23_normalized,val_best_rerun/rmse_27_denormalized,val_best_rerun/rmse_27_normalized,val_best_rerun/rmse_5_denormalized,val_best_rerun/rmse_5_normalized,val_best_rerun/rmse_7_denormalized,val_best_rerun/rmse_7_normalized,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean
25,0.005646,44.671867,0.041239,36.080811,0.033308,104.976585,0.096910,92.057945,0.084984,60.715847,0.056051,66.602440,0.061485,67.517586,0.062330,1.934772,1.934772,1.588566,1.588566,3.528280,3.528280,6.192298,6.192297,3.645222,3.645222,3.017918,3.017918,3.317842,3.317842,3270.481201,0.002787,4703.015137,0.004008,14702.636719,0.012530,12116.985352,0.010326,5449.311523,0.004644,6282.075684,0.005354,7754.083984,0.006608,0.356089,0.356089,0.373114,0.373114,0.122099,0.122099,0.190011,0.190011,0.226884,0.226884,0.240738,0.240738,0.251489,0.251489,57.188122,0.052794,68.578537,0.063309,121.254425,0.111937,110.077179,0.101619,73.819450,0.068147,79.259544,0.073169,85.029541,0.078496
26,0.006057,38.695671,0.035722,41.855164,0.038639,122.995995,0.113545,103.576431,0.095618,72.726845,0.067139,62.672249,0.057857,73.753723,0.068087,3.003232,3.003231,2.394802,2.394802,3.774184,3.774184,6.207900,6.207900,5.217603,5.217603,3.536097,3.536097,4.022303,4.022303,2361.650146,0.002013,4285.586426,0.003652,18346.722656,0.015636,14237.776367,0.012134,7600.750488,0.006478,5744.092285,0.004895,8762.763672,0.007468,0.365468,0.365468,0.289375,0.289375,0.049095,0.049095,0.122567,0.122567,0.183412,0.183412,0.244611,0.244611,0.209088,0.209088,48.596813,0.044863,65.464394,0.060434,135.450073,0.125042,119.322151,0.110154,87.182281,0.080483,75.789787,0.069966,88.634254,0.081824
27,0.006139,49.166866,0.045389,46.119526,0.042576,81.977654,0.075679,75.429947,0.069634,62.865887,0.058035,80.776985,0.074570,66.056145,0.060981,1.610703,1.610703,1.022719,1.022719,3.391456,3.391456,4.716940,4.716940,3.599923,3.599923,2.357304,2.357304,2.783175,2.783174,3917.479248,0.003339,5903.969727,0.005032,9342.919922,0.007962,8128.094727,0.006927,6741.694824,0.005745,10510.426758,0.008957,7424.097656,0.006327,0.344411,0.344411,0.327104,0.327104,0.212333,0.212333,0.231627,0.231627,0.275526,0.275526,0.238537,0.238537,0.271590,0.271590,62.589771,0.057780,76.837296,0.070933,96.658783,0.089232,90.155945,0.083229,82.107826,0.075799,102.520370,0.094643,85.144997,0.078603
28,0.006123,34.707764,0.032041,47.404007,0.043762,115.920738,0.107014,114.194313,0.105420,76.915894,0.071006,57.000393,0.052621,74.357185,0.068644,2.585800,2.585800,2.000939,2.000939,3.824867,3.824867,6.266679,6.266680,5.505452,5.505452,2.510259,2.510259,3.782333,3.782333,1976.333862,0.001684,5192.150391,0.004425,16500.734375,0.014062,16570.966797,0.014122,7911.980957,0.006743,4963.063965,0.004230,8852.539062,0.007544,0.396334,0.396334,0.242997,0.242997,0.067296,0.067296,0.100483,0.100483,0.144475,0.144475,0.244809,0.244809,0.199399,0.199399,44.455978,0.041040,72.056580,0.066520,128.455185,0.118585,128.728271,0.118837,88.949318,0.082115,70.449013,0.065036,88.849060,0.082022
29,0.006941,26.649668,0.024602,42.282795,0.039034,127.263237,0.117485,111.299934,0.102748,77.672325,0.071704,69.260521,0.063939,75.738075,0.069919,1.513642,1.513642,0.642547,0.642547,4.839706,4.839706,6.799308,6.799308,5.831326,5.831326,2.495583,2.495583,3.687019,3.687019,1251.383667,0.001066,6234.289062,0.005313,20698.365234,0.017640,17048.935547,0.014530,7991.928223,0.006811,6854.653320,0.005842,10013.258789,0.008534,0.438574,0.438574,0.267118,0.267118,0.090438,0.090438,0.141612,0.141612,0.222506,0.222506,0.241109,0.241109,0.233559,0.233559,35.374901,0.032657,78.957512,0.072891,143.869263,0.132815,130.571579,0.120539,89.397583,0.082528,82.792831,0.076431,93.493942,0.086310

In [8]:
group_runs.sort_values(
    by=["seed", "created_at"] if "created_at" in group_runs else ["seed"]
)[[i for i in group_runs.columns if "test_best_rerun" in i]]

,test_best_rerun/loss,test_best_rerun/mae_16_denormalized,test_best_rerun/mae_16_normalized,test_best_rerun/mae_19_denormalized,test_best_rerun/mae_19_normalized,test_best_rerun/mae_24_denormalized,test_best_rerun/mae_24_normalized,test_best_rerun/mae_28_denormalized,test_best_rerun/mae_28_normalized,test_best_rerun/mae_6_denormalized,test_best_rerun/mae_6_normalized,test_best_rerun/mae_8_denormalized,test_best_rerun/mae_8_normalized,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_16_denormalized,test_best_rerun/mape_16_normalized,test_best_rerun/mape_19_denormalized,test_best_rerun/mape_19_normalized,test_best_rerun/mape_24_denormalized,test_best_rerun/mape_24_normalized,test_best_rerun/mape_28_denormalized,test_best_rerun/mape_28_normalized,test_best_rerun/mape_6_denormalized,test_best_rerun/mape_6_normalized,test_best_rerun/mape_8_denormalized,test_best_rerun/mape_8_normalized,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_16_denormalized,test_best_rerun/mse_16_normalized,test_best_rerun/mse_19_denormalized,test_best_rerun/mse_19_normalized,test_best_rerun/mse_24_denormalized,test_best_rerun/mse_24_normalized,test_best_rerun/mse_28_denormalized,test_best_rerun/mse_28_normalized,test_best_rerun/mse_6_denormalized,test_best_rerun/mse_6_normalized,test_best_rerun/mse_8_denormalized,test_best_rerun/mse_8_normalized,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_16_denormalized,test_best_rerun/phm_score_16_normalized,test_best_rerun/phm_score_19_denormalized,test_best_rerun/phm_score_19_normalized,test_best_rerun/phm_score_24_denormalized,test_best_rerun/phm_score_24_normalized,test_best_rerun/phm_score_28_denormalized,test_best_rerun/phm_score_28_normalized,test_best_rerun/phm_score_6_denormalized,test_best_rerun/phm_score_6_normalized,test_best_rerun/phm_score_8_denormalized,test_best_rerun/phm_score_8_normalized,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_16_denormalized,test_best_rerun/rmse_16_normalized,test_best_rerun/rmse_19_denormalized,test_best_rerun/rmse_19_normalized,test_best_rerun/rmse_24_denormalized,test_best_rerun/rmse_24_normalized,test_best_rerun/rmse_28_denormalized,test_best_rerun/rmse_28_normalized,test_best_rerun/rmse_6_denormalized,test_best_rerun/rmse_6_normalized,test_best_rerun/rmse_8_denormalized,test_best_rerun/rmse_8_normalized,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean
25,0.005065,30.792141,0.028426,30.798347,0.028432,87.903671,0.081149,81.827187,0.075540,128.666290,0.118780,59.390087,0.054827,69.896286,0.064526,1.651149,1.651149,4.698690,4.698690,3.989303,3.989303,4.889970,4.889970,5.925451,5.925451,2.817622,2.817622,3.995364,3.995364,1680.807007,0.001432,1605.695190,0.001368,10669.673828,0.009093,9461.178711,0.008063,18545.105469,0.015805,5336.435059,0.004548,7883.149902,0.006718,0.314925,0.314925,0.382616,0.382616,0.168841,0.168841,0.184514,0.184514,0.006502,0.006502,0.269012,0.269012,0.221069,0.221069,40.997646,0.037847,40.071125,0.036992,103.294113,0.095357,97.268585,0.089795,136.180420,0.125717,73.050903,0.067438,81.810463,0.075524
26,0.005970,38.689022,0.035716,33.813931,0.031216,96.416992,0.089008,84.515388,0.078021,156.255219,0.144249,57.150345,0.052759,77.806816,0.071828,2.553461,2.553461,6.677299,6.677299,4.178485,4.178485,4.508988,4.508988,6.977624,6.977624,3.346066,3.346066,4.706987,4.706987,2657.914551,0.002265,1772.029297,0.001510,12418.380859,0.010583,9471.228516,0.008072,27156.468750,0.023144,4989.267090,0.004252,9744.214844,0.008304,0.254609,0.254609,0.307770,0.307770,0.136200,0.136200,0.130625,0.130625,0.001642,0.001642,0.271274,0.271274,0.183687,0.183687,51.554966,0.047594,42.095478,0.038861,111.437790,0.102875,97.320236,0.089842,164.792206,0.152130,70.634743,0.065207,89.639236,0.082752
27,0.004513,26.860533,0.024797,39.791023,0.036734,77.042717,0.071123,67.267639,0.062099,71.619087,0.066116,71.577553,0.066078,59.026428,0.054491,1.189626,1.189626,2.865770,2.865770,3.560289,3.560289,3.680051,3.680051,5.033912,5.033912,2.644830,2.644830,3.162413,3.162413,1216.104858,0.001036,2437.869873,0.002078,7766.737305,0.006619,6506.324707,0.005545,7029.528320,0.005991,8963.466797,0.007639,5653.338379,0.004818,0.327169,0.327169,0.340780,0.340780,0.205759,0.205759,0.235921,0.235921,0.153812,0.153812,0.269420,0.269420,0.255477,0.255477,34.872696,0.032193,49.374790,0.045581,88.129097,0.081357,80.661797,0.074464,83.842285,0.077400,94.675591,0.087401,71.926041,0.066399
28,0.005817,37.847713,0.034940,39.058788,0.036058,91.219818,0.084211,92.227989,0.085141,150.486649,0.138924,50.829823,0.046924,76.945129,0.071033,2.219661,2.219661,5.773337,5.773337,4.064999,4.064999,4.470843,4.470843,7.070843,7.070843,2.688424,2.688424,4.381351,4.381351,2525.596191,0.002152,2382.248291,0.002030,11076.048828,0.009439,10579.828125,0.009016,25801.929688,0.021989,4232.704590,0.003607,9433.059570,0.008039,0.245673,0.245673,0.255327,0.255327,0.153280,0.153280,0.103411,0.103411,0.009864,0.009864,0.301932,0.301932,0.178248,0.178248,50.255310,0.046394,48.808281,0.045058,105.242805,0.097156,102.858292,0.094955,160.629791,0.148287,65.059235,0.060060,88.808952,0.081985
29,0.006596,39.326202,0.036304,32.211716,0.029737,112.206833,0.103585,101.405251,0.093613,145.811783,0.134608,60.085175,0.055468,81.841164,0.075553,1.391331,1.391331,0.819985,0.819985,5.240936,5.240936,5.625748,5.625748,8.083898,8.083899,2.957941,2.957941,4.019973,4.019973,2612.886963,0.002227,1511.900269,0.001288,16689.703125,0.014223,13806.716797,0.011766,23360.076172,0.019908,5526.227051,0.004710,10584.584961,0.009020,0.212016,0.212016,0.313070,0.313070,0.145670,0.145670,0.129899,0.129899,0.004754,0.004754,0.275867,0.275867,0.180213,0.180213,51.116405,0.047189,38.883163,0.035895,129.188629,0.119262,117.501984,0.108473,152.840027,0.141096,74.338600,0.068627,93.978134,0.086757