In [1]:
%reload_ext autoreload
%autoreload 2
# notebooks/result_processing.ipynb

# ---
# # Experiment Results Analysis
# This notebook orchestrates the loading, analysis, validation, and reporting 
# of experiment results logged to Weights & Biases.
# ---

# ## 1. Setup and Imports
# Import necessary libraries and custom modules. The `sys.path.append` line
# allows the notebook to find the custom `lmetk_report` package.
import sys
import pandas as pd
sys.path.append('..')

from lmetk_report.run_processor import load_runs_df
from lmetk_report.analysis import analyze_results
from lmetk_report.reporting import (
    create_summary_table,
    display_experiment_stats,
    display_performance_tables,
    display_hp_impact
)

# ---
# ## 2. Configuration
# Define all key parameters for the analysis in one place.
# ---
PROJECT_NAME = "01_2026_hsf15_valve_diagnostics_"
USER = "imos-buildingenergy-1"

# Metrics to extract
METRIC_PREFIXES = ["val/", "test/", "test_best_rerun/", "val_best_rerun/"]
REPORTING_METRICS = ["loss", "mse", "mae", "rmse", "f1", "accuracy"]

# --- NEW: Scientific Rigor Settings ---
# If defined, the analysis will DROP any configuration group that does not 
# contain exactly these seeds. Set to `None` to include all available data.

# Data seeds are set to None (Flexible mode)
REQUIRED_DATA_SEEDS = None      

# Model seeds are strictly enforced (Strict mode)
REQUIRED_MODEL_SEEDS = {72, 88, 101, 666, 226688}

# Columns to ignore if they vary within a group (avoids "Hidden Variation" warnings)
ADDITIONAL_IGNORED_COLS = ["gpu_id", "slurm_job_id"] 

# Configure pandas display options for better readability in the notebook.
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

# ---
# ## 3. Data Loading
# Fetch data from wandb (or a local cache) and prepare the initial DataFrame.
# The `load_runs_df` function handles all the complex cleaning and flattening.
# ---
print("🚀 Loading Run Data...")
df, config_columns, dropped_columns = load_runs_df(
    project_name=PROJECT_NAME, 
    user=USER
)
print(f"Loaded {len(df)} runs.")

# ---
# ## 4. Core Analysis
# Run the main analysis function. This now includes:
# 1. Grouping by Model + Hyperparameters
# 2. Strict Seed Validation (Filtering incomplete groups)
# 3. Hidden Variation Detection (Warning about silent bugs)
# 4. Aggregation & Best Model Selection
# ---
print("\n🔬 Analyzing Results & Validating Consistency...")

all_results = analyze_results(
    df=df,
    config_columns=config_columns,
    dropped_columns=dropped_columns,
    reporting_metrics=REPORTING_METRICS,
    metric_prefixes=METRIC_PREFIXES,
    # --- New Validation Arguments ---
    required_data_seeds=REQUIRED_DATA_SEEDS,
    required_model_seeds=REQUIRED_MODEL_SEEDS,
    additional_ignored_cols=ADDITIONAL_IGNORED_COLS
)

# ---
# ## 5. Reporting & Visualizations
# ---

# ### A. Experiment Statistics
# Shows how many configurations completed successfully and 
# confirms which seeds were actually found in the data.
display_experiment_stats(all_results)

# ### B. Performance Leaderboards
# Displays a separate, clean pivot table for every metric found (MSE, MAE, etc.).
display_performance_tables(all_results)

# ### C. Hyperparameter Impact Analysis
# Shows the top 10 configurations for each model, exposing exactly 
# which hyperparameters led to the best results.
display_hp_impact(all_results)

# ### D. Legacy Summary Table
# A single flattened table containing all metrics (useful for copying to Excel/LaTeX).
print("\n📊 Full Summary Table:")
summary_df = create_summary_table(all_results)
display(summary_df)

🚀 Loading Run Data...
Loaded 390 runs from cached file: csv_files/01_2026_hsf15_valve_diagnostics_.csv
Dropped 41 columns with >90% NaN values.
The columns were drropped: ['ckpt_path', 'pad_value', 'null_value', 'subset_seed', 'target_mask', 'profiler_cfg', 'subset_range', 'val_subset_ratio', 'optimizer_factory', 'scheduler_factory', 'test_subset_ratio', 'variable_emb_type', 'train_subset_ratio', 'optimization.scheduler.gamma', 'optimization.scheduler.step_size', 'model.device', 'model.n_jobs', 'model.fit_mode', 'model.random_state', 'model.yield_strategy', 'model.model_cache_path', 'model.yield_batch_size', 'model.ignore_pretraining_limits', 'dataset.task_type', 'datamodule.subset_seed', 'datamodule.val_subset_ratio', 'datamodule.test_subset_ratio', 'datamodule.train_subset_ratio', 'callbacks.early_stopping.stopping_threshold', 'callbacks.early_stopping.divergence_threshold', 'callbacks.early_stopping.check_on_train_epoch_end', 'callbacks.model_checkpoint.every_n_epochs', 'callbacks.model_checkpoint.every_n_train_steps', 'callbacks.model_checkpoint.train_time_interval', 'callbacks.model_checkpoint.save_on_train_epoch_end', 'evaluator.val.inverse_transform_name', 'evaluator.test.inverse_transform_name', 'evaluator.train.inverse_transform_name', 'evaluator._evaluator_defaults.inverse_transform_name', 'logger.wandb.anonymous', 'trainer.enable_checkpointing']
Dropped 60 columns based on name filters (e.g., 'paths.').
Loaded 390 runs.

🔬 Analyzing Results & Validating Consistency...

  [DATAFRAME MODIFICATION] Selecting Data for Analysis
    Reason: Isolating Model='lmetk.model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper' and Dataset='HSF15'
    Input Shape: (390, 274) -> Output Shape: (24, 274)
    Change: 366 rows dropped
  ------------------------------
Fallback: Switching optimization metric to 'test/loss' (found valid data).
  [Validator] NOTE: Strict filter on 'seed' removed all rows.
  [Validator] Fallback triggered: Ignoring seed filter for this model (assuming it does not use seeds).
Hyperparameters that vary for lmetk.model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper on HSF15:
task_definition.seq_len: [1, 5, 10, 20, 50, 100]
task_definition.stride_train: [1, 5, 50, 100]
---------
Warning: Optimization mode not found. Defaulting to 'min'.

  [DATAFRAME MODIFICATION] Selecting Data for Analysis
    Reason: Isolating Model='lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster' and Dataset='HSF15'
    Input Shape: (390, 274) -> Output Shape: (360, 274)
    Change: 30 rows dropped
  ------------------------------
  [WARNING] Hidden variation detected in 'evaluators'! (Varies within grouped config)
Hyperparameters that vary for lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster on HSF15:
optimization.lr: [0.001, 0.0005, 0.0001]
task_definition.seq_len: [1, 10, 50, 100]
datamodule.train_batch_size: [16, 512]
---------

  [DATAFRAME MODIFICATION] Selecting Data for Analysis
    Reason: Isolating Model='lmetk.model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper' and Dataset='HSF15'
    Input Shape: (390, 274) -> Output Shape: (6, 274)
    Change: 384 rows dropped
  ------------------------------
  [Validator] NOTE: Strict filter on 'seed' removed all rows.
  [Validator] Fallback triggered: Ignoring seed filter for this model (assuming it does not use seeds).
Hyperparameters that vary for lmetk.model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper on HSF15:
task_definition.seq_len: [1, 5, 10, 20, 50, 100]
task_definition.stride_train: [1, 5, 50, 100]
---------

========================================
  EXPERIMENT STATISTICS
========================================

========================================
  METRIC: test_best_rerunaccuracy
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.43 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: test_best_rerunf1
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.34 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: test_best_rerunloss
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.20 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: testaccuracy
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.43 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...  0.99 ± 0.00
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...   1.00 ± nan

========================================
  METRIC: testf1
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.34 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...  0.98 ± 0.00
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...   1.00 ± nan

========================================
  METRIC: testloss
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.20 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...  1.00 ± 0.00
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...   1.00 ± nan

========================================
  METRIC: val_best_rerunaccuracy
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.37 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: val_best_rerunf1
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.30 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: val_best_rerunloss
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.20 ± 0.00
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: valaccuracy
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.26 ± 0.06
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: valf1
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.18 ± 0.07
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  METRIC: valloss
========================================

Dataset                                                   HSF15
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  4.32 ± 8.16
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...    nan ± nan
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...    nan ± nan

========================================
  HYPERPARAMETER IMPACT ANALYSIS
========================================

>>> lmetk.model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper on HSF15
    (Sorted by test/loss)

,task_definition.seq_len,task_definition.stride_train,val/loss_mean,val/f1_mean,val/accuracy_mean,test/loss_mean,test/loss_std,test/loss_count,test/f1_mean,test/accuracy_mean,test_best_rerun/loss_mean,test_best_rerun/f1_mean,test_best_rerun/accuracy_mean,val_best_rerun/loss_mean,val_best_rerun/f1_mean,val_best_rerun/accuracy_mean
0,1,1,NaN,NaN,NaN,1.0,0.0,4,0.984628,0.988399,NaN,NaN,NaN,NaN,NaN,NaN
1,5,1,NaN,NaN,NaN,1.0,0.0,4,0.697180,0.754098,NaN,NaN,NaN,NaN,NaN,NaN
2,10,5,NaN,NaN,NaN,1.0,0.0,4,0.466209,0.547393,NaN,NaN,NaN,NaN,NaN,NaN
3,20,5,NaN,NaN,NaN,1.0,0.0,4,0.409042,0.501214,NaN,NaN,NaN,NaN,NaN,NaN
4,50,50,NaN,NaN,NaN,1.0,0.0,4,0.205032,0.429319,NaN,NaN,NaN,NaN,NaN,NaN
5,100,100,NaN,NaN,NaN,1.0,0.0,4,0.201551,0.463855,NaN,NaN,NaN,NaN,NaN,NaN

>>> lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster on HSF15
    (Sorted by test/loss)

,optimization.lr,task_definition.seq_len,datamodule.train_batch_size,val/loss_mean,val/f1_mean,val/accuracy_mean,test/loss_mean,test/loss_std,test/loss_count,test/f1_mean,test/accuracy_mean,test_best_rerun/loss_mean,test_best_rerun/f1_mean,test_best_rerun/accuracy_mean,val_best_rerun/loss_mean,val_best_rerun/f1_mean,val_best_rerun/accuracy_mean
23,0.0010,100,512,4.318756,0.179926,0.255859,0.199749,0.000000,3,0.336042,0.429429,0.199749,0.336042,0.429429,0.196014,0.298936,0.367188
14,0.0005,100,16,0.126165,0.157512,0.219531,0.215559,0.075234,15,0.309319,0.482282,0.215559,0.309319,0.482282,0.175776,0.321090,0.501563
12,0.0005,50,16,0.181811,0.202619,0.252288,0.255410,0.127806,15,0.389981,0.545692,0.255410,0.389981,0.545692,0.237603,0.410941,0.549020
22,0.0010,100,16,0.099765,0.183511,0.246875,0.355410,0.094761,15,0.357620,0.439039,0.355410,0.357620,0.439039,0.272880,0.364217,0.456250
20,0.0010,50,16,0.181432,0.207754,0.212418,0.366248,0.095998,15,0.316588,0.451697,0.366248,0.316588,0.451697,0.323324,0.329233,0.450980
16,0.0010,1,16,0.280105,0.157466,0.222723,0.550678,0.604585,15,0.364821,0.544753,0.550678,0.364821,0.544753,0.538057,0.365685,0.548732
2,0.0001,10,16,0.285344,0.163769,0.282081,0.601347,0.286348,15,0.273345,0.392908,0.601347,0.273345,0.392908,0.494233,0.280184,0.398266
6,0.0001,100,16,0.191509,0.172046,0.289844,0.658131,0.695045,15,0.296042,0.514715,0.658131,0.296042,0.514715,0.587058,0.292300,0.519531
10,0.0005,10,16,0.604938,0.206666,0.257225,0.894615,0.173484,15,0.340816,0.442553,0.894615,0.340816,0.442553,0.648330,0.356479,0.468786
15,0.0005,100,512,1.128910,0.184894,0.277344,1.286629,2.108980,5,0.241398,0.445646,1.286629,0.241398,0.445646,1.236629,0.279801,0.508594

>>> lmetk.model.wrappers.fit_predict_tabpfn_wrapper.FitPredictTabPFNWrapper on HSF15
    (Sorted by test/loss)

,task_definition.seq_len,task_definition.stride_train,val/loss_mean,val/f1_mean,val/accuracy_mean,test/loss_mean,test/loss_std,test/loss_count,test/f1_mean,test/accuracy_mean,test_best_rerun/loss_mean,test_best_rerun/f1_mean,test_best_rerun/accuracy_mean,val_best_rerun/loss_mean,val_best_rerun/f1_mean,val_best_rerun/accuracy_mean
0,1,1,NaN,NaN,NaN,1.0,NaN,1,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,5,1,NaN,NaN,NaN,1.0,NaN,1,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,10,5,NaN,NaN,NaN,1.0,NaN,1,0.996454,0.997630,NaN,NaN,NaN,NaN,NaN,NaN
3,20,5,NaN,NaN,NaN,1.0,NaN,1,0.982254,0.987864,NaN,NaN,NaN,NaN,NaN,NaN
4,50,50,NaN,NaN,NaN,1.0,NaN,1,0.168278,0.476440,NaN,NaN,NaN,NaN,NaN,NaN
5,100,100,NaN,NaN,NaN,1.0,NaN,1,0.164646,0.490964,NaN,NaN,NaN,NaN,NaN,NaN

📊 Full Summary Table:

Dataset                                                              HSF15                                                                                                                     \
Metric                                             test_best_rerunaccuracy      test_best_rerunf1    test_best_rerunloss           testaccuracy                 testf1               testloss
Model
lmetk.baselines.spacetimeformer_model.Spacetime...   0.4294 ± 0.0000 (n=3)  0.3360 ± 0.0000 (n=3)  0.1997 ± 0.0000 (n=3)  0.4294 ± 0.0000 (n=3)  0.3360 ± 0.0000 (n=3)  0.1997 ± 0.0000 (n=3)
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...         nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)  0.9884 ± 0.0000 (n=4)  0.9846 ± 0.0000 (n=4)  1.0000 ± 0.0000 (n=4)
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...         nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)     1.0000 ± nan (n=1)     1.0000 ± nan (n=1)     1.0000 ± nan (n=1)

Dataset
Metric                                             val_best_rerunaccuracy       val_best_rerunf1     val_best_rerunloss            valaccuracy                  valf1                valloss
Model
lmetk.baselines.spacetimeformer_model.Spacetime...  0.3672 ± 0.0000 (n=3)  0.2989 ± 0.0000 (n=3)  0.1960 ± 0.0000 (n=3)  0.2559 ± 0.0586 (n=4)  0.1799 ± 0.0720 (n=4)  4.3188 ± 8.1603 (n=4)
lmetk.model.wrappers.fit_predict_tabdpt_wrapper...        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)
lmetk.model.wrappers.fit_predict_tabpfn_wrapper...        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)        nan ± nan (n=0)

In [2]:
# 1. Access the raw data for the specific model and dataset
model_key = 'lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster'
dataset_key = 'HSF15'

# This DF contains all runs for this model before aggregation
df_subset = all_results[dataset_key][model_key]['non_aggregated_df']

# 2. Filter for ONE specific configuration that shows count=15
# (Based on your screenshot: lr=0.0001, seq_len=10, batch_size=16)
mask = (
    (df_subset['optimization.lr'] == 0.0001) & 
    (df_subset['task_definition.seq_len'] == 10) & 
    (df_subset['datamodule.train_batch_size'] == 16)
)
group_runs = df_subset[mask]

# 3. Display identifiers to spot the duplicates
# 'created_at' will show you if these runs are from different times/days
cols_to_inspect = ['run_name', 'id', 'created_at', 'seed', 'datasource.parameters.data_seed']
valid_cols = [c for c in cols_to_inspect if c in group_runs.columns]

print(f"Found {len(group_runs)} runs for this configuration (Expected 5).")
print("Listing all runs in this group:")
#display(group_runs[valid_cols].sort_values('created_at'))

Found 15 runs for this configuration (Expected 5).
Listing all runs in this group:

In [3]:
group_runs[valid_cols]

                                       run_name    seed
25   debug+hsf15+valve+diagnostics+stf_c0f10b13      72
26   debug+hsf15+valve+diagnostics+stf_59db61cb      88
27   debug+hsf15+valve+diagnostics+stf_0fe4497b     666
28   debug+hsf15+valve+diagnostics+stf_6102e251     101
29   debug+hsf15+valve+diagnostics+stf_15625fc5  226688
157  debug+hsf15+valve+diagnostics+stf_f1c2fe48      72
158  debug+hsf15+valve+diagnostics+stf_39782614      88
159  debug+hsf15+valve+diagnostics+stf_1722e80a     101
160  debug+hsf15+valve+diagnostics+stf_e4f83bb0     666
161  debug+hsf15+valve+diagnostics+stf_8178777e  226688
289  debug+hsf15+valve+diagnostics+stf_c0ccacd4      72
290  debug+hsf15+valve+diagnostics+stf_bd1c6e19      88
291  debug+hsf15+valve+diagnostics+stf_e6ec813d     101
292  debug+hsf15+valve+diagnostics+stf_dbaa3a0a     666
293  debug+hsf15+valve+diagnostics+stf_ed7626df  226688

In [ ]:
# 1. Isolate the specific group of 15 runs (from your screenshot)
# Adjust these values if you want to look at a different group
target_model = 'lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster'
mask = (
    (df['model._target_'] == target_model) &
    (df['optimization.lr'] == 0.0001) & 
    (df['task_definition.seq_len'] == 10) & 
    (df['datamodule.train_batch_size'] == 16)
)
group_runs = df[mask].copy()

# 2. Find "Hidden Variables"
# We calculate the number of unique values for EVERY column in this small group.
# If a column has > 1 unique value, it means it varies between these "duplicate" runs.
drop_cols = [] #"hydra_cfg", "_wandb", "metadata", "transforms", "evaluator.val.metric_names" 
# find all dict or list columns:
for col in group_runs:
    if group_runs[col].apply(lambda x: isinstance(x, (dict, list))).any():
        drop_cols.append(col)

group_runs.drop(columns=drop_cols, errors='ignore', inplace=True)

nunique = group_runs.nunique()
varying_cols = nunique[nunique > 1].index.tolist()

# 3. Add identifiers for context (if they aren't already varying)
context_cols = ['run_name', 'seed']
for c in context_cols:
    if c not in varying_cols and c in group_runs.columns:
        varying_cols.insert(0, c)

# 4. Display sorted by Seed
print(f"Found {len(group_runs)} runs in this group.")
print("Showing ONLY columns that differ between these runs:")

# Sort by seed to put duplicates next to each other
display(
    group_runs[varying_cols]
    .sort_values(by=['seed',])
    .style.set_properties(**{'text-align': 'left'})
)

Found 15 runs in this group.
Showing ONLY columns that differ between these runs:

KeyError: 'created_at'

In [ ]:


group_runs

,AvgTime/train_batch_mean,AvgTime/train_batch_std,AvgTime/train_epoch_mean,AvgTime/train_epoch_std,AvgTime/val_batch_mean,AvgTime/val_batch_std,AvgTime/val_epoch_mean,AvgTime/val_epoch_std,_runtime,_step,_timestamp,_wandb,epoch,lr-AdamW,test/accuracy,test/f1,test/loss,test/precision,test/recall,test_best_rerun/accuracy,test_best_rerun/f1,test_best_rerun/loss,test_best_rerun/precision,test_best_rerun/recall,train/loss_epoch,train/loss_step,trainer/global_step,val/accuracy,val/f1,val/loss,val/precision,val/recall,val_best_rerun/accuracy,val_best_rerun/f1,val_best_rerun/loss,val_best_rerun/precision,val_best_rerun/recall,d_x,d_ff,d_yc,d_yt,loss,norm,seed,tags,test,train,head_f,base_lr,d_model,n_heads,verbose,d_layers,d_values,e_layers,exp_name,mask_y_c,metadata,use_time,hydra_cfg,task_type,use_given,use_revin,use_space,activation,dropout_ff,evaluators,pin_memory,transforms,use_tt_dec,use_tt_enc,attn_factor,dropout_emb,dropout_qkv,max_seq_len,num_threads,num_workers,shuffle_val,use_val_dec,use_val_enc,embed_method,pos_emb_type,shuffle_test,time_emb_dim,linear_window,shuffle_train,time_emb_type,class_loss_imp,d_queries_keys,n_timefeatures,performer_relu,recon_loss_imp,use_final_norm,val_batch_size,flash_attention,local_self_attn,prefetch_factor,start_token_len,test_batch_size,attention_method,dropout_attn_out,experiment_group,global_self_attn,inverted_encoder,local_cross_attn,performer_kernel,train_batch_size,attn_time_windows,global_cross_attn,use_batch_sampler,model/params/total,timetable_emb_type,dropout_attn_matrix,enable_progress_bar,recon_mask_drop_seq,recon_mask_skip_all,use_seasonal_decomp,recon_mask_drop_full,linear_shared_weights,model/params/trainable,recon_mask_max_seq_len,scheduler_Loss_monitor,initial_downsample_convs,recon_mask_drop_standard,use_shifted_time_windows,performer_redraw_interval,intermediate_downsample_convs,run_name,optimization.lr,optimization.start_lr,optimization.optimizer.lr,optimization.optimizer._target_,optimization.optimizer.weight_decay,optimization.scheduler.factor,optimization.scheduler.init_lr,optimization.scheduler.peak_lr,optimization.scheduler._target_,optimization.scheduler.patience,optimization.scheduler.warmup_steps,datasource.fold,datasource._target_,datasource.cache_dir,datasource.data_name,datasource.task_mode,datasource.num_classes,datasource.auxiliary_tasks,task_definition.stride,task_definition.seq_len,task_definition.pred_len,task_definition.label_len,task_definition.task_type,task_definition.num_classes,task_definition.stride_train,task_definition.target_metric,task_definition.requires_training,task_definition.target_metric_mode,task_definition.model.data_requirements.input_tensors,model.d_x,model.d_ff,model.d_yc,model.d_yt,model.base_lr,model.d_model,model.n_heads,model._target_,model.d_layers,model.e_layers,model.task_type,model.use_revin,model.dropout_ff,model.dropout_emb,model.dropout_qkv,model.max_seq_len,model.pos_emb_type,model.time_emb_dim,model.time_emb_type,model.n_timefeatures,model.local_self_attn,model.start_token_len,model.global_self_attn,model.local_cross_attn,model.global_cross_attn,model.timetable_emb_type,model.dropout_attn_matrix,model.use_seasonal_decomp,model.metadata.lightning_model,dataset._target_,dataset._recursive_,dataset.dataset_cfg.stride,dataset.dataset_cfg.seq_len,dataset.dataset_cfg._target_,dataset.dataset_cfg.pred_len,dataset.dataset_cfg.label_len,dataset.dataset_cfg.task_type,datamodule._target_,datamodule.num_workers,datamodule.shuffle_val,datamodule.shuffle_test,datamodule.shuffle_train,datamodule.val_batch_size,datamodule.prefetch_factor,datamodule.test_batch_size,datamodule.train_batch_size,callbacks.model_timer._target_,callbacks.model_summary._target_,callbacks.model_summary.max_depth,callbacks.early_stopping.mode,callbacks.early_stopping.strict,callbacks.early_stopping.monitor,callbacks.early_stopping.verbose,callbacks.early_stopping._target_,callbacks.early_stopping.patience,callbacks.early_stopping.min_delta,callbacks.early_stopping.check_finite,callbacks.model_checkpoint.mode,callbacks.model_checkpoint.dirpath,callbacks.model_checkpoint.monitor,callbacks.model_checkpoint.verbose,callbacks.model_checkpoint._target_,callbacks.model_checkpoint.filename,callbacks.model_checkpoint.save_last,callbacks.model_checkpoint.save_top_k,callbacks.model_checkpoint.save_weights_only,callbacks.model_checkpoint.auto_insert_metric_name,callbacks.learning_rate_monitor._target_,callbacks.learning_rate_monitor.logging_interval,evaluator.val._target_,evaluator.val.task_mode,evaluator.val.num_classes,evaluator.val.metric_names,evaluator.val.save_predictions,evaluator.val.apply_inverse_scaling,evaluator.test._target_,evaluator.test.task_mode,evaluator.test.num_classes,evaluator.test.metric_names,evaluator.test.save_predictions,evaluator.test.apply_inverse_scaling,evaluator.train._target_,evaluator.train.task_mode,evaluator.train.num_classes,evaluator.train.metric_names,evaluator.train.save_predictions,evaluator.train.apply_inverse_scaling,evaluator._evaluator_defaults._target_,evaluator._evaluator_defaults.task_mode,evaluator._evaluator_defaults.num_classes,evaluator._evaluator_defaults.metric_names,evaluator._evaluator_defaults.save_predictions,evaluator._evaluator_defaults.apply_inverse_scaling,cache.use_cache_after_loading,cache.use_cache_after_transfroms,cache.use_preprocessing_file_lock,cache.preprocessing_file_lock_path,logger.wandb.id,logger.wandb.tags,logger.wandb.group,logger.wandb.entity,logger.wandb.prefix,logger.wandb.offline,logger.wandb.project,logger.wandb._target_,logger.wandb.job_type,logger.wandb.save_dir,logger.wandb.log_model,trainer.devices,trainer._target_,trainer.max_epochs,trainer.min_epochs,trainer.accelerator,trainer.deterministic,trainer.inference_mode,trainer.default_root_dir,trainer.check_val_every_n_epoch
25,0.019761,0.001484,1.818339,0.022622,0.018977,0.001300,0.034263,0.001614,39,98,1.769010e+09,{'runtime': 39},20.0,0.000095,0.463357,0.281525,0.469736,0.269328,0.304954,0.463357,0.281525,0.469736,0.269328,0.304954,0.248206,0.463041,1760,0.442197,0.234360,0.242445,0.478501,0.262380,0.476879,0.297236,0.406292,0.286229,0.319818,408.0,128.0,0.0,4.0,mse,batch,72,[dev],True,True,linear,0.001,128.0,7.0,True,3.0,50.0,2.0,hsf15/valve/diagnostics/stf,False,{'lightning_model': True},True,"{'job': {'id': '???', 'num': '???', 'name': '$...",fault_classification,True,False,True,gelu,0.2,{'train': <ClassificationEvaluator({'task_mode...,True,{'reshape_target': {'metadata': {'apply_to': '...,True,True,5.0,0.0,0.1,11.0,32,4,False,True,True,spatio-temporal,abs,False,12.0,0.0,True,linear,0.001,50.0,0.0,True,0.0,True,1024,True,full,10,0.0,1024,non-causual,0.0,debug,full,False,full,relu,16,1.0,full,True,3817278,linear,0.0,False,0.1,1.0,False,0.05,False,3817278,5.0,forecast_loss,0.0,0.2,True,1000.0,0.0,debug+hsf15+valve+diagnostics+stf_c0f10b13,0.0001,1.000000e-10,0.0001,torch.optim.AdamW,0,0.95,1.000000e-10,0.0001,lmetk.lr_scheduler.warmup_reduce_lr_on_plateau...,5.0,88.0,0,lmetk.data.datasources.phmd_hsf15.HSF15Loader,/workspace/datasets/phmd_cache,HSF15,valve,4,[],1,10,1,0,fault_classification,4,5,val/f1,True,max,"[features, fault_classification]",408.0,128.0,0.0,4.0,0.001,128.0,7.0,lmetk.baselines.spacetimeformer_model.Spacetim...,3.0,2.0,fault_classification,False,0.2,0.0,0.1,11.0,abs,12.0,linear,0.0,full,6.0,full,full,full,linear,0.0,False,True,lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1.0,10.0,lmetk.data.datasets.fault_classification_datas...,1.0,0.0,fault_classification,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,16,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,max,True,val/f1,True,lightning.pytorch.callbacks.EarlyStopping,15.0,0.0,True,max,/workspace/experiments/2025-09-18_TabPHM/debug...,val/f1,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.8f},False,1.0,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,True,True,False,/tmp/lmetk_preprocess.lock,debug+hsf15+valve+diagnostics+stf_1216c188,[],,imos-buildingenergy-1,,False,01_2026_hsf15_valve_diagnostics_,lightning.pytorch.loggers.wandb.WandbLogger,,/workspace/experiments/2025-09-18_TabPHM/debug...,False,[0],lightning.pytorch.trainer.Trainer,100,1,gpu,False,False,/workspace/experiments/2025-09-18_TabPHM/debug...,1
26,0.021151,0.002395,2.067571,0.022736,0.024875,0.000520,0.039455,0.000484,48,112,1.769010e+09,{'runtime': 48},23.0,0.000090,0.219858,0.213852,0.274057,0.248228,0.234868,0.219858,0.213852,0.274057,0.248228,0.234868,0.150603,0.088569,2024,0.127168,0.108081,0.280657,0.337105,0.186798,0.187861,0.187013,0.198503,0.229982,0.205894,408.0,128.0,0.0,4.0,mse,batch,88,[dev],True,True,linear,0.001,128.0,7.0,True,3.0,50.0,2.0,hsf15/valve/diagnostics/stf,False,{'lightning_model': True},True,"{'job': {'id': '???', 'num': '???', 'name': '$...",fault_classification,True,False,True,gelu,0.2,{'train': <ClassificationEvaluator({'task_mode...,True,{'reshape_target': {'metadata': {'apply_to': '...,True,True,5.0,0.0,0.1,11.0,32,4,False,True,True,spatio-temporal,abs,False,12.0,0.0,True,linear,0.001,50.0,0.0,True,0.0,True,1024,True,full,10,0.0,1024,non-causual,0.0,debug,full,False,full,relu,16,1.0,full,True,3817278,linear,0.0,False,0.1,1.0,False,0.05,False,3817278,5.0,forecast_loss,0.0,0.2,True,1000.0,0.0,debug+hsf15+valve+diagnostics+stf_59db61cb,0.0001,1.000000e-10,0.0001,torch.optim.AdamW,0,0.95,1.000000e-10,0.0001,lmetk.lr_scheduler.warmup_reduce_lr_on_plateau...,5.0,88.0,0,lmetk.data.datasources.phmd_hsf15.HSF15Loader,/workspace/datasets/phmd_cache,HSF15,valve,4,[],1,10,1,0,fault_classification,4,5,val/f1,True,max,"[features, fault_classification]",408.0,128.0,0.0,4.0,0.001,128.0,7.0,lmetk.baselines.spacetimeformer_model.Spacetim...,3.0,2.0,fault_classification,False,0.2,0.0,0.1,11.0,abs,12.0,linear,0.0,full,6.0,full,full,full,linear,0.0,False,True,lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1.0,10.0,lmetk.data.datasets.fault_classification_datas...,1.0,0.0,fault_classification,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,16,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,max,True,val/f1,True,lightning.pytorch.callbacks.EarlyStopping,15.0,0.0,True,max,/workspace/experiments/2025-09-18_TabPHM/debug...,val/f1,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.8f},False,1.0,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,True,True,False,/tmp/lmetk_preprocess.lock,debug+hsf15+valve+diagnostics+stf_60e8514d,[],,imos-buildingenergy-1,,False,01_2026_hsf15_valve_diagnostics_,lightning.pytorch.loggers.wandb.WandbLogger,,/workspace/experiments/2025-09-18_TabPHM/debug...,False,[0],lightning.pytorch.trainer.Trainer,100,1,gpu,False,False,/workspace/experiments/2025-09-18_TabPHM/debug...,1
27,0.019180,0.002118,1.749590,0.153308,0.018476,0.003346,0.033736,0.003705,112,293,1.769010e+09,{'runtime': 112},61.0,0.000063,0.425532,0.305019,0.586460,0.307267,0.309159,0.425532,0.305019,0.586460,0.307267,0.309159,0.047995,0.029073,5368,0.303468,0.199114,0.258837,0.209594,0.206897,0.462428,0.326771,0.395221,0.345027,0.329691,408.0,128.0,0.0,4.0,mse,batch,666,[dev],True,True,linear,0.001,128.0,7.0,True,3.0,50.0,2.0,hsf15/valve/diagnostics/stf,False,{'lightning_model': True},True,"{'job': {'id': '???', 'num': '???', 'name': '$...",fault_classification,True,False,True,gelu,0.2,{'train': <ClassificationEvaluator({'task_mode...,True,{'reshape_target': {'metadata': {'apply_to': '...,True,True,5.0,0.0,0.1,11.0,32,4,False,True,True,spatio-temporal,abs,False,12.0,0.0,True,linear,0.001,50.0,0.0,True,0.0,True,1024,True,full,10,0.0,1024,non-causual,0.0,debug,full,False,full,relu,16,1.0,full,True,3817278,linear,0.0,False,0.1,1.0,False,0.05,False,3817278,5.0,forecast_loss,0.0,0.2,True,1000.0,0.0,debug+hsf15+valve+diagnostics+stf_0fe4497b,0.0001,1.000000e-10,0.0001,torch.optim.AdamW,0,0.95,1.000000e-10,0.0001,lmetk.lr_scheduler.warmup_reduce_lr_on_plateau...,5.0,88.0,0,lmetk.data.datasources.phmd_hsf15.HSF15Loader,/workspace/datasets/phmd_cache,HSF15,valve,4,[],1,10,1,0,fault_classification,4,5,val/f1,True,max,"[features, fault_classification]",408.0,128.0,0.0,4.0,0.001,128.0,7.0,lmetk.baselines.spacetimeformer_model.Spacetim...,3.0,2.0,fault_classification,False,0.2,0.0,0.1,11.0,abs,12.0,linear,0.0,full,6.0,full,full,full,linear,0.0,False,True,lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1.0,10.0,lmetk.data.datasets.fault_classification_datas...,1.0,0.0,fault_classification,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,16,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,max,True,val/f1,True,lightning.pytorch.callbacks.EarlyStopping,15.0,0.0,True,max,/workspace/experiments/2025-09-18_TabPHM/debug...,val/f1,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.8f},False,1.0,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,True,True,False,/tmp/lmetk_preprocess.lock,debug+hsf15+valve+diagnostics+stf_a3da6f3d,[],,imos-buildingenergy-1,,False,01_2026_hsf15_valve_diagnostics_,lightning.pytorch.loggers.wandb.WandbLogger,,/workspace/experiments/2025-09-18_TabPHM/debug...,False,[0],lightning.pytorch.trainer.Trainer,100,1,gpu,False,False,/workspace/experiments/2025-09-18_TabPHM/debug...,1
28,0.022630,0.002207,2.063235,0.024804,0.023402,0.002938,0.036872,0.002993,40,88,1.769010e+09,{'runtime': 40},18.0,0.000090,0.342790,0.299893,1.108190,0.312412,0.330719,0.342790,0.299893,1.108190,0.312412,0.330719,0.280735,0.193333,1584,0.462428,0.199617,0.266452,0.324332,0.249699,0.352601,0.309120,0.924604,0.326148,0.331596,408.0,128.0,0.0,4.0,mse,batch,101,[dev],True,True,linear,0.001,128.0,7.0,True,3.0,50.0,2.0,hsf15/valve/diagnostics/stf,False,{'lightning_model': True},True,"{'job': {'id': '???', 'num': '???', 'name': '$...",fault_classification,True,False,True,gelu,0.2,{'train': <ClassificationEvaluator({'task_mode...,True,{'reshape_target': {'metadata': {'apply_to': '...,True,True,5.0,0.0,0.1,11.0,32,4,False,True,True,spatio-temporal,abs,False,12.0,0.0,True,linear,0.001,50.0,0.0,True,0.0,True,1024,True,full,10,0.0,1024,non-causual,0.0,debug,full,False,full,relu,16,1.0,full,True,3817278,linear,0.0,False,0.1,1.0,False,0.05,False,3817278,5.0,forecast_loss,0.0,0.2,True,1000.0,0.0,debug+hsf15+valve+diagnostics+stf_6102e251,0.0001,1.000000e-10,0.0001,torch.optim.AdamW,0,0.95,1.000000e-10,0.0001,lmetk.lr_scheduler.warmup_reduce_lr_on_plateau...,5.0,88.0,0,lmetk.data.datasources.phmd_hsf15.HSF15Loader,/workspace/datasets/phmd_cache,HSF15,valve,4,[],1,10,1,0,fault_classification,4,5,val/f1,True,max,"[features, fault_classification]",408.0,128.0,0.0,4.0,0.001,128.0,7.0,lmetk.baselines.spacetimeformer_model.Spacetim...,3.0,2.0,fault_classification,False,0.2,0.0,0.1,11.0,abs,12.0,linear,0.0,full,6.0,full,full,full,linear,0.0,False,True,lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1.0,10.0,lmetk.data.datasets.fault_classification_datas...,1.0,0.0,fault_classification,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,16,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,max,True,val/f1,True,lightning.pytorch.callbacks.EarlyStopping,15.0,0.0,True,max,/workspace/experiments/2025-09-18_TabPHM/debug...,val/f1,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.8f},False,1.0,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",True,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,lmetk.evaluator.classification.ClassificationE...,valve,4,"[f1, accuracy, precision, recall]",False,False,True,True,False,/tmp/lmetk_preprocess.lock,debug+hsf15+valve+diagnostics+stf_4ffce7e8,[],,imos-buildingenergy-1,,False,01_2026_hsf15_valve_diagnostics_,lightning.pytorch.loggers.wandb.WandbLogger,,/workspace/experiments/2025-09-18_TabPHM/debug...,False,[0],lightning.pytorch.trainer.Trainer,100,1,gpu,False,False,/workspace/experiments/2025-09-18_TabPHM/debug...,1

In [ ]:
hydra_cfg, hydra_cfg

In [2]:
for key in all_results.keys():
    print(f"Dataset key: {key}")
    for key_2 in all_results[key].keys():
        print(f"  Model key: {key_2}")
        for sub_key in all_results[key][key_2].keys():
            #if pd data frame then display the head only
            if isinstance(all_results[key][key_2][sub_key], pd.DataFrame):
                print(f"    {sub_key}:")
                display(all_results[key][key_2][sub_key].head(2))
            # if dict proceed with keys 
            elif isinstance(all_results[key][key_2][sub_key], dict):
                # same for inside dict and repeat
                for inner_key in all_results[key][key_2][sub_key].keys():
                    # print the 
                    if isinstance(all_results[key][key_2][sub_key][inner_key], pd.DataFrame):
                        print(f"   {sub_key}   {inner_key}:")
                        display(all_results[key][key_2][sub_key][inner_key].head(2))
                    else:
                        print(f" {sub_key}     {inner_key}: {all_results[key][key_2][sub_key][inner_key]}")
                
            else:
                print(f"    {sub_key}: {all_results[key][key_2][sub_key]}")

Dataset key: NB14
  Model key: lmetk.baselines.spacetimeformer_model.Spacetimeformer_Forecaster
 best_hyperparameters     task_definition.seq_len: 10
 best_hyperparameters     model.max_seq_len: 11.0
 best_hyperparameters     dataset.dataset_cfg.seq_len: 10.0
 best_hyperparameters     datamodule.train_batch_size: 16
 best_hyperparameters     run_names: ['debug+nb14+prognostics+combined+stf_61a9cc80', 'debug+nb14+prognostics+combined+stf_d0831fd2', 'debug+nb14+prognostics+combined+stf_dec7c232', 'debug+nb14+prognostics+combined+stf_b7d718c4', 'debug+nb14+prognostics+combined+stf_efaff768', 'debug+nb14+prognostics+combined+stf_9d450055', 'debug+nb14+prognostics+combined+stf_0de9df77', 'debug+nb14+prognostics+combined+stf_cbd4c0be', 'debug+nb14+prognostics+combined+stf_881aa4df', 'debug+nb14+prognostics+combined+stf_341fa4f1', 'debug+nb14+prognostics+combined+stf_d6dfad92', 'debug+nb14+prognostics+combined+stf_f0e15a8a', 'debug+nb14+prognostics+combined+stf_6b42d1d8', 'debug+nb14+prognostics+combined+stf_2fdff258', 'debug+nb14+prognostics+combined+stf_e07eaf8f', 'debug+nb14+prognostics+combined+stf_f2a12d63', 'debug+nb14+prognostics+combined+stf_66d13a9d', 'debug+nb14+prognostics+combined+stf_d66d985f', 'debug+nb14+prognostics+combined+stf_298da075', 'debug+nb14+prognostics+combined+stf_c4506914', 'debug+nb14+prognostics+combined+stf_451edaeb', 'debug+nb14+prognostics+combined+stf_d4047020', 'debug+nb14+prognostics+combined+stf_cc06e8f5', 'debug+nb14+prognostics+combined+stf_96bafcb9', 'debug+nb14+prognostics+combined+stf_f4ddb645', 'debug+nb14+prognostics+combined+stf_836cb9c2', 'debug+nb14+prognostics+combined+stf_b0260595', 'debug+nb14+prognostics+combined+stf_0e1daffb', 'debug+nb14+prognostics+combined+stf_884b52c8', 'debug+nb14+prognostics+combined+stf_11eb49ce', 'debug+nb14+prognostics+combined+stf_46ec0f30', 'debug+nb14+prognostics+combined+stf_61fb0f92', 'debug+nb14+prognostics+combined+stf_9a52eb65', 'debug+nb14+prognostics+combined+stf_d3aff102', 'debug+nb14+prognostics+combined+stf_3f47dafb', 'debug+nb14+prognostics+combined+stf_bdd40827', 'debug+nb14+prognostics+combined+stf_96f7f55f', 'debug+nb14+prognostics+combined+stf_963e7e67', 'debug+nb14+prognostics+combined+stf_c29aaa0d', 'debug+nb14+prognostics+combined+stf_6f1041b1', 'debug+nb14+prognostics+combined+stf_9f13b45a', 'debug+nb14+prognostics+combined+stf_cf9f4910', 'debug+nb14+prognostics+combined+stf_227c2f31', 'debug+nb14+prognostics+combined+stf_9a852042', 'debug+nb14+prognostics+combined+stf_331eeb56']
 best_performance     optimized_on: {'metric': 'val/loss', 'strategy': 'min'}
 best_performance     metrics: defaultdict(<class 'dict'>, {'loss': {'val': {'mean': np.float64(0.9274582734124528), 'std': np.float64(1.5698329166167213), 'count': np.int64(45)}, 'test': {'mean': np.float64(0.004994412006940259), 'std': np.float64(0.0027297318769980115), 'count': np.int64(43)}, 'test_best_rerun': {'mean': np.float64(0.004892968660634425), 'std': np.float64(0.002709062271099271), 'count': np.int64(45)}, 'val_best_rerun': {'mean': np.float64(0.022713633996318094), 'std': np.float64(0.036451185815955967), 'count': np.int64(16)}}})
    best_run_names: ['debug+nb14+prognostics+combined+stf_61a9cc80', 'debug+nb14+prognostics+combined+stf_d0831fd2', 'debug+nb14+prognostics+combined+stf_dec7c232', 'debug+nb14+prognostics+combined+stf_b7d718c4', 'debug+nb14+prognostics+combined+stf_efaff768', 'debug+nb14+prognostics+combined+stf_9d450055', 'debug+nb14+prognostics+combined+stf_0de9df77', 'debug+nb14+prognostics+combined+stf_cbd4c0be', 'debug+nb14+prognostics+combined+stf_881aa4df', 'debug+nb14+prognostics+combined+stf_341fa4f1', 'debug+nb14+prognostics+combined+stf_d6dfad92', 'debug+nb14+prognostics+combined+stf_f0e15a8a', 'debug+nb14+prognostics+combined+stf_6b42d1d8', 'debug+nb14+prognostics+combined+stf_2fdff258', 'debug+nb14+prognostics+combined+stf_e07eaf8f', 'debug+nb14+prognostics+combined+stf_f2a12d63', 'debug+nb14+prognostics+combined+stf_66d13a9d', 'debug+nb14+prognostics+combined+stf_d66d985f', 'debug+nb14+prognostics+combined+stf_298da075', 'debug+nb14+prognostics+combined+stf_c4506914', 'debug+nb14+prognostics+combined+stf_451edaeb', 'debug+nb14+prognostics+combined+stf_d4047020', 'debug+nb14+prognostics+combined+stf_cc06e8f5', 'debug+nb14+prognostics+combined+stf_96bafcb9', 'debug+nb14+prognostics+combined+stf_f4ddb645', 'debug+nb14+prognostics+combined+stf_836cb9c2', 'debug+nb14+prognostics+combined+stf_b0260595', 'debug+nb14+prognostics+combined+stf_0e1daffb', 'debug+nb14+prognostics+combined+stf_884b52c8', 'debug+nb14+prognostics+combined+stf_11eb49ce', 'debug+nb14+prognostics+combined+stf_46ec0f30', 'debug+nb14+prognostics+combined+stf_61fb0f92', 'debug+nb14+prognostics+combined+stf_9a52eb65', 'debug+nb14+prognostics+combined+stf_d3aff102', 'debug+nb14+prognostics+combined+stf_3f47dafb', 'debug+nb14+prognostics+combined+stf_bdd40827', 'debug+nb14+prognostics+combined+stf_96f7f55f', 'debug+nb14+prognostics+combined+stf_963e7e67', 'debug+nb14+prognostics+combined+stf_c29aaa0d', 'debug+nb14+prognostics+combined+stf_6f1041b1', 'debug+nb14+prognostics+combined+stf_9f13b45a', 'debug+nb14+prognostics+combined+stf_cf9f4910', 'debug+nb14+prognostics+combined+stf_227c2f31', 'debug+nb14+prognostics+combined+stf_9a852042', 'debug+nb14+prognostics+combined+stf_331eeb56']
    best_checkpoint_path: /workspace/experiments/2025-09-18_TabPHM/debug/runs/debug+nb14+prognostics+combined+stf/2026-01-21_16-19-56/checkpoints/checkpoints
 avg_epoch_time     mean: 7.974187340241309
 avg_epoch_time     std: 5.655792701482458
 avg_runtime     mean: 178.55113636363637
 avg_runtime     std: 154.46849483354492
    sorted_aggregated_results:

                                               Model task_definition.seq_len model.max_seq_len dataset.dataset_cfg.seq_len datamodule.train_batch_size  val/loss                 test/loss            \
                                                                                                                                                            mean       std count      mean       std
2  lmetk.baselines.spacetimeformer_model.Spacetim...                      10              11.0                        10.0                          16  0.927458  1.569833    45  0.004994  0.002730
7  lmetk.baselines.spacetimeformer_model.Spacetim...                     100             101.0                       100.0                         512  3.923929  4.241883    31  0.007404  0.003877

        test_best_rerun/loss                 val_best_rerun/loss                                                           run_name
  count                 mean       std count                mean       std count                                               list
2    43             0.004893  0.002709    45            0.022714  0.036451    16  [debug+nb14+prognostics+combined+stf_61a9cc80,...
7    30             0.007377  0.003814    31            0.012309  0.004241     7  [debug+nb14+prognostics+combined+stf_98e72e62,...

    non_aggregated_df:

,AvgTime/train_batch_mean,AvgTime/train_batch_std,AvgTime/train_epoch_mean,AvgTime/train_epoch_std,AvgTime/val_batch_mean,AvgTime/val_batch_std,AvgTime/val_epoch_mean,AvgTime/val_epoch_std,_runtime,_step,_timestamp,_wandb,epoch,lr-AdamW,plots/test/pred_vs_target_unit_15,plots/test/pred_vs_target_unit_16,plots/test/pred_vs_target_unit_18,plots/test/pred_vs_target_unit_19,plots/test/pred_vs_target_unit_23,plots/test/pred_vs_target_unit_24,plots/test/pred_vs_target_unit_27,plots/test/pred_vs_target_unit_28,plots/test/pred_vs_target_unit_5,plots/test/pred_vs_target_unit_6,plots/test/pred_vs_target_unit_7,plots/test/pred_vs_target_unit_8,plots/val/pred_vs_target_unit_15,plots/val/pred_vs_target_unit_18,plots/val/pred_vs_target_unit_23,plots/val/pred_vs_target_unit_27,plots/val/pred_vs_target_unit_5,plots/val/pred_vs_target_unit_7,test/loss,test/mae_16_denormalized,test/mae_16_normalized,test/mae_19_denormalized,test/mae_19_normalized,test/mae_24_denormalized,test/mae_24_normalized,test/mae_28_denormalized,test/mae_28_normalized,test/mae_6_denormalized,test/mae_6_normalized,test/mae_8_denormalized,test/mae_8_normalized,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_16_denormalized,test/mape_16_normalized,test/mape_19_denormalized,test/mape_19_normalized,test/mape_24_denormalized,test/mape_24_normalized,test/mape_28_denormalized,test/mape_28_normalized,test/mape_6_denormalized,test/mape_6_normalized,test/mape_8_denormalized,test/mape_8_normalized,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_16_denormalized,test/mse_16_normalized,test/mse_19_denormalized,test/mse_19_normalized,test/mse_24_denormalized,test/mse_24_normalized,test/mse_28_denormalized,test/mse_28_normalized,test/mse_6_denormalized,test/mse_6_normalized,test/mse_8_denormalized,test/mse_8_normalized,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_16_denormalized,test/phm_score_16_normalized,test/phm_score_19_denormalized,test/phm_score_19_normalized,test/phm_score_24_denormalized,test/phm_score_24_normalized,test/phm_score_28_denormalized,test/phm_score_28_normalized,test/phm_score_6_denormalized,test/phm_score_6_normalized,test/phm_score_8_denormalized,test/phm_score_8_normalized,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_16_denormalized,test/rmse_16_normalized,test/rmse_19_denormalized,test/rmse_19_normalized,test/rmse_24_denormalized,test/rmse_24_normalized,test/rmse_28_denormalized,test/rmse_28_normalized,test/rmse_6_denormalized,test/rmse_6_normalized,test/rmse_8_denormalized,test/rmse_8_normalized,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_16_denormalized,test_best_rerun/mae_16_normalized,test_best_rerun/mae_19_denormalized,test_best_rerun/mae_19_normalized,test_best_rerun/mae_24_denormalized,test_best_rerun/mae_24_normalized,test_best_rerun/mae_28_denormalized,test_best_rerun/mae_28_normalized,test_best_rerun/mae_6_denormalized,test_best_rerun/mae_6_normalized,test_best_rerun/mae_8_denormalized,test_best_rerun/mae_8_normalized,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_16_denormalized,test_best_rerun/mape_16_normalized,test_best_rerun/mape_19_denormalized,test_best_rerun/mape_19_normalized,test_best_rerun/mape_24_denormalized,test_best_rerun/mape_24_normalized,test_best_rerun/mape_28_denormalized,test_best_rerun/mape_28_normalized,test_best_rerun/mape_6_denormalized,test_best_rerun/mape_6_normalized,test_best_rerun/mape_8_denormalized,test_best_rerun/mape_8_normalized,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_16_denormalized,test_best_rerun/mse_16_normalized,test_best_rerun/mse_19_denormalized,test_best_rerun/mse_19_normalized,test_best_rerun/mse_24_denormalized,test_best_rerun/mse_24_normalized,test_best_rerun/mse_28_denormalized,test_best_rerun/mse_28_normalized,test_best_rerun/mse_6_denormalized,test_best_rerun/mse_6_normalized,test_best_rerun/mse_8_denormalized,test_best_rerun/mse_8_normalized,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_16_denormalized,test_best_rerun/phm_score_16_normalized,test_best_rerun/phm_score_19_denormalized,test_best_rerun/phm_score_19_normalized,test_best_rerun/phm_score_24_denormalized,test_best_rerun/phm_score_24_normalized,test_best_rerun/phm_score_28_denormalized,test_best_rerun/phm_score_28_normalized,test_best_rerun/phm_score_6_denormalized,test_best_rerun/phm_score_6_normalized,test_best_rerun/phm_score_8_denormalized,test_best_rerun/phm_score_8_normalized,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_16_denormalized,test_best_rerun/rmse_16_normalized,test_best_rerun/rmse_19_denormalized,test_best_rerun/rmse_19_normalized,test_best_rerun/rmse_24_denormalized,test_best_rerun/rmse_24_normalized,test_best_rerun/rmse_28_denormalized,test_best_rerun/rmse_28_normalized,test_best_rerun/rmse_6_denormalized,test_best_rerun/rmse_6_normalized,test_best_rerun/rmse_8_denormalized,test_best_rerun/rmse_8_normalized,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,train/loss_epoch,train/loss_step,trainer/global_step,val/loss,val/mae_15_denormalized,val/mae_15_normalized,val/mae_18_denormalized,val/mae_18_normalized,val/mae_23_denormalized,val/mae_23_normalized,val/mae_27_denormalized,val/mae_27_normalized,val/mae_5_denormalized,val/mae_5_normalized,val/mae_7_denormalized,val/mae_7_normalized,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_15_denormalized,val/mape_15_normalized,val/mape_18_denormalized,val/mape_18_normalized,val/mape_23_denormalized,val/mape_23_normalized,val/mape_27_denormalized,val/mape_27_normalized,val/mape_5_denormalized,val/mape_5_normalized,val/mape_7_denormalized,val/mape_7_normalized,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_15_denormalized,val/mse_15_normalized,val/mse_18_denormalized,val/mse_18_normalized,val/mse_23_denormalized,val/mse_23_normalized,val/mse_27_denormalized,val/mse_27_normalized,val/mse_5_denormalized,val/mse_5_normalized,val/mse_7_denormalized,val/mse_7_normalized,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_15_denormalized,val/phm_score_15_normalized,val/phm_score_18_denormalized,val/phm_score_18_normalized,val/phm_score_23_denormalized,val/phm_score_23_normalized,val/phm_score_27_denormalized,val/phm_score_27_normalized,val/phm_score_5_denormalized,val/phm_score_5_normalized,val/phm_score_7_denormalized,val/phm_score_7_normalized,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_15_denormalized,val/rmse_15_normalized,val/rmse_18_denormalized,val/rmse_18_normalized,val/rmse_23_denormalized,val/rmse_23_normalized,val/rmse_27_denormalized,val/rmse_27_normalized,val/rmse_5_denormalized,val/rmse_5_normalized,val/rmse_7_denormalized,val/rmse_7_normalized,val/rmse_denormalized_mean,val/rmse_normalized_mean,d_x,d_ff,d_yc,d_yt,loss,norm,seed,tags,test,cache,train,head_f,logger,base_lr,d_model,n_heads,trainer,verbose,d_layers,d_values,e_layers,exp_name,mask_y_c,metadata,use_time,evaluator,hydra_cfg,task_type,use_given,use_revin,use_space,activation,dropout_ff,evaluators,pin_memory,transforms,use_tt_dec,use_tt_enc,attn_factor,dropout_emb,dropout_qkv,max_seq_len,num_threads,num_workers,shuffle_val,subset_seed,use_val_dec,use_val_enc,embed_method,optimization,pos_emb_type,shuffle_test,time_emb_dim,warmup_steps,linear_window,shuffle_train,time_emb_type,class_loss_imp,d_queries_keys,n_timefeatures,performer_relu,recon_loss_imp,use_final_norm,val_batch_size,flash_attention,local_self_attn,prefetch_factor,start_token_len,test_batch_size,attention_method,dropout_attn_out,experiment_group,global_self_attn,inverted_encoder,local_cross_attn,performer_kernel,train_batch_size,attn_time_windows,global_cross_attn,use_batch_sampler,model/params/total,timetable_emb_type,train_subset_ratio,dropout_attn_matrix,enable_progress_bar,recon_mask_drop_seq,recon_mask_skip_all,use_seasonal_decomp,recon_mask_drop_full,linear_shared_weights,model/params/trainable,recon_mask_max_seq_len,scheduler_Loss_monitor,initial_downsample_convs,recon_mask_drop_standard,use_shifted_time_windows,performer_redraw_interval,intermediate_downsample_convs,run_name,val_best_rerun/loss,val_best_rerun/mae_15_denormalized,val_best_rerun/mae_15_normalized,val_best_rerun/mae_18_denormalized,val_best_rerun/mae_18_normalized,val_best_rerun/mae_23_denormalized,val_best_rerun/mae_23_normalized,val_best_rerun/mae_27_denormalized,val_best_rerun/mae_27_normalized,val_best_rerun/mae_5_denormalized,val_best_rerun/mae_5_normalized,val_best_rerun/mae_7_denormalized,val_best_rerun/mae_7_normalized,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_15_denormalized,val_best_rerun/mape_15_normalized,val_best_rerun/mape_18_denormalized,val_best_rerun/mape_18_normalized,val_best_rerun/mape_23_denormalized,val_best_rerun/mape_23_normalized,val_best_rerun/mape_27_denormalized,val_best_rerun/mape_27_normalized,val_best_rerun/mape_5_denormalized,val_best_rerun/mape_5_normalized,val_best_rerun/mape_7_denormalized,val_best_rerun/mape_7_normalized,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_15_denormalized,val_best_rerun/mse_15_normalized,val_best_rerun/mse_18_denormalized,val_best_rerun/mse_18_normalized,val_best_rerun/mse_23_denormalized,val_best_rerun/mse_23_normalized,val_best_rerun/mse_27_denormalized,val_best_rerun/mse_27_normalized,val_best_rerun/mse_5_denormalized,val_best_rerun/mse_5_normalized,val_best_rerun/mse_7_denormalized,val_best_rerun/mse_7_normalized,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_15_denormalized,val_best_rerun/phm_score_15_normalized,val_best_rerun/phm_score_18_denormalized,val_best_rerun/phm_score_18_normalized,val_best_rerun/phm_score_23_denormalized,val_best_rerun/phm_score_23_normalized,val_best_rerun/phm_score_27_denormalized,val_best_rerun/phm_score_27_normalized,val_best_rerun/phm_score_5_denormalized,val_best_rerun/phm_score_5_normalized,val_best_rerun/phm_score_7_denormalized,val_best_rerun/phm_score_7_normalized,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_15_denormalized,val_best_rerun/rmse_15_normalized,val_best_rerun/rmse_18_denormalized,val_best_rerun/rmse_18_normalized,val_best_rerun/rmse_23_denormalized,val_best_rerun/rmse_23_normalized,val_best_rerun/rmse_27_denormalized,val_best_rerun/rmse_27_normalized,val_best_rerun/rmse_5_denormalized,val_best_rerun/rmse_5_normalized,val_best_rerun/rmse_7_denormalized,val_best_rerun/rmse_7_normalized,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean,"plots/test/pred_vs_target_unit_(16,)","plots/test/pred_vs_target_unit_(19,)","plots/test/pred_vs_target_unit_(24,)","plots/test/pred_vs_target_unit_(28,)","plots/test/pred_vs_target_unit_(6,)","plots/test/pred_vs_target_unit_(8,)","test/mae_(16,)_denormalized","test/mae_(16,)_normalized","test/mae_(19,)_denormalized","test/mae_(19,)_normalized","test/mae_(24,)_denormalized","test/mae_(24,)_normalized","test/mae_(28,)_denormalized","test/mae_(28,)_normalized","test/mae_(6,)_denormalized","test/mae_(6,)_normalized","test/mae_(8,)_denormalized","test/mae_(8,)_normalized","test/mape_(16,)_denormalized","test/mape_(16,)_normalized","test/mape_(19,)_denormalized","test/mape_(19,)_normalized","test/mape_(24,)_denormalized","test/mape_(24,)_normalized","test/mape_(28,)_denormalized","test/mape_(28,)_normalized","test/mape_(6,)_denormalized","test/mape_(6,)_normalized","test/mape_(8,)_denormalized","test/mape_(8,)_normalized","test/mse_(16,)_denormalized","test/mse_(16,)_normalized","test/mse_(19,)_denormalized","test/mse_(19,)_normalized","test/mse_(24,)_denormalized","test/mse_(24,)_normalized","test/mse_(28,)_denormalized","test/mse_(28,)_normalized","test/mse_(6,)_denormalized","test/mse_(6,)_normalized","test/mse_(8,)_denormalized","test/mse_(8,)_normalized","test/phm_score_(16,)_denormalized","test/phm_score_(16,)_normalized","test/phm_score_(19,)_denormalized","test/phm_score_(19,)_normalized","test/phm_score_(24,)_denormalized","test/phm_score_(24,)_normalized","test/phm_score_(28,)_denormalized","test/phm_score_(28,)_normalized","test/phm_score_(6,)_denormalized","test/phm_score_(6,)_normalized","test/phm_score_(8,)_denormalized","test/phm_score_(8,)_normalized","test/rmse_(16,)_denormalized","test/rmse_(16,)_normalized","test/rmse_(19,)_denormalized","test/rmse_(19,)_normalized","test/rmse_(24,)_denormalized","test/rmse_(24,)_normalized","test/rmse_(28,)_denormalized","test/rmse_(28,)_normalized","test/rmse_(6,)_denormalized","test/rmse_(6,)_normalized","test/rmse_(8,)_denormalized","test/rmse_(8,)_normalized",datasource._target_,datasource.data_dir,datasource.data_name,datasource.task_mode,task_definition.stride,task_definition.seq_len,task_definition.pred_len,task_definition.label_len,task_definition.task_type,task_definition.subset_seed,task_definition.stride_train,task_definition.subset_ratio,task_definition.target_metric,task_definition.requires_training,task_definition.target_metric_mode,task_definition.model.data_requirements.input_tensors,model.d_x,model.d_ff,model.d_yc,model.d_yt,model.base_lr,model.d_model,model.n_heads,model._target_,model.d_layers,model.e_layers,model.task_type,model.use_revin,model.dropout_ff,model.dropout_emb,model.dropout_qkv,model.max_seq_len,model.pos_emb_type,model.time_emb_dim,model.warmup_steps,model.time_emb_type,model.n_timefeatures,model.local_self_attn,model.start_token_len,model.global_self_attn,model.local_cross_attn,model.global_cross_attn,model.timetable_emb_type,model.dropout_attn_matrix,model.use_seasonal_decomp,model.metadata.lightning_model,model.device,model.n_jobs,model.fit_mode,model.random_state,model.yield_strategy,model.model_cache_path,model.yield_batch_size,model.ignore_pretraining_limits,dataset._target_,dataset._recursive_,dataset.dataset_cfg.stride,dataset.dataset_cfg.seq_len,dataset.dataset_cfg._target_,dataset.dataset_cfg.pred_len,dataset.dataset_cfg.label_len,dataset.dataset_cfg.task_type,dataset.dataset_cfg.get_unit_id,dataset.task_type,datamodule._target_,datamodule.num_workers,datamodule.shuffle_val,datamodule.subset_seed,datamodule.shuffle_test,datamodule.shuffle_train,datamodule.val_batch_size,datamodule.prefetch_factor,datamodule.test_batch_size,datamodule.train_batch_size,datamodule.train_subset_ratio,callbacks.model_timer._target_,callbacks.model_summary._target_,callbacks.model_summary.max_depth,callbacks.early_stopping.mode,callbacks.early_stopping.strict,callbacks.early_stopping.monitor,callbacks.early_stopping.verbose,callbacks.early_stopping._target_,callbacks.early_stopping.patience,callbacks.early_stopping.min_delta,callbacks.early_stopping.check_finite,callbacks.model_checkpoint.mode,callbacks.model_checkpoint.dirpath,callbacks.model_checkpoint.monitor,callbacks.model_checkpoint.verbose,callbacks.model_checkpoint._target_,callbacks.model_checkpoint.filename,callbacks.model_checkpoint.save_last,callbacks.model_checkpoint.save_top_k,callbacks.model_checkpoint.save_weights_only,callbacks.model_checkpoint.auto_insert_metric_name,callbacks.learning_rate_monitor._target_,callbacks.learning_rate_monitor.logging_interval,Model

  Model key: lmetk.model.wrappers.fit_predict_tabdpt_wrapper.FitPredictTabDPTWrapper
 best_hyperparameters     task_definition.seq_len: 1
 best_hyperparameters     task_definition.stride_train: 1
 best_hyperparameters     model.model_cache_path: /workspace/experiments/2025-09-18_TabPHM/debug/runs/debug+nb14+prognostics+combined+tabdpt_fit_predict/2026-01-22_12-57-04/model_cache_dir
 best_hyperparameters     run_names: ['debug+nb14+prognostics+combined+tabdpt_fit_predict_068f193e']
 best_performance     optimized_on: {'metric': 'val/loss', 'strategy': 'min'}
 best_performance     metrics: defaultdict(<class 'dict'>, {'loss': {'val': {'mean': np.float64(nan), 'std': np.float64(nan), 'count': np.int64(0)}, 'test': {'mean': np.float64(1.0), 'std': np.float64(nan), 'count': np.int64(1)}, 'test_best_rerun': {'mean': np.float64(nan), 'std': np.float64(nan), 'count': np.int64(0)}, 'val_best_rerun': {'mean': np.float64(nan), 'std': np.float64(nan), 'count': np.int64(0)}}})
    best_run_names: ['debug+nb14+prognostics+combined+tabdpt_fit_predict_068f193e']
    best_checkpoint_path: None
 avg_epoch_time     mean: nan
 avg_epoch_time     std: nan
 avg_runtime     mean: 114.3623188405797
 avg_runtime     std: 122.74914292434613
    sorted_aggregated_results:

                                               Model task_definition.seq_len task_definition.stride_train                             model.model_cache_path val/loss           test/loss            \
                                                                                                                                                                 mean std count      mean std count
0  lmetk.model.wrappers.fit_predict_tabdpt_wrappe...                       1                            1  /workspace/experiments/2025-09-18_TabPHM/debug...      NaN NaN     0       1.0 NaN     1
1  lmetk.model.wrappers.fit_predict_tabdpt_wrappe...                       1                            1  /workspace/experiments/2025-09-18_TabPHM/debug...      NaN NaN     0       1.0 NaN     1

  test_best_rerun/loss           val_best_rerun/loss                                                     run_name
                  mean std count                mean std count                                               list
0                  NaN NaN     0                 NaN NaN     0  [debug+nb14+prognostics+combined+tabdpt_fit_pr...
1                  NaN NaN     0                 NaN NaN     0  [debug+nb14+prognostics+combined+tabdpt_fit_pr...

    non_aggregated_df:

,AvgTime/train_batch_mean,AvgTime/train_batch_std,AvgTime/train_epoch_mean,AvgTime/train_epoch_std,AvgTime/val_batch_mean,AvgTime/val_batch_std,AvgTime/val_epoch_mean,AvgTime/val_epoch_std,_runtime,_step,_timestamp,_wandb,epoch,lr-AdamW,plots/test/pred_vs_target_unit_15,plots/test/pred_vs_target_unit_16,plots/test/pred_vs_target_unit_18,plots/test/pred_vs_target_unit_19,plots/test/pred_vs_target_unit_23,plots/test/pred_vs_target_unit_24,plots/test/pred_vs_target_unit_27,plots/test/pred_vs_target_unit_28,plots/test/pred_vs_target_unit_5,plots/test/pred_vs_target_unit_6,plots/test/pred_vs_target_unit_7,plots/test/pred_vs_target_unit_8,plots/val/pred_vs_target_unit_15,plots/val/pred_vs_target_unit_18,plots/val/pred_vs_target_unit_23,plots/val/pred_vs_target_unit_27,plots/val/pred_vs_target_unit_5,plots/val/pred_vs_target_unit_7,test/loss,test/mae_16_denormalized,test/mae_16_normalized,test/mae_19_denormalized,test/mae_19_normalized,test/mae_24_denormalized,test/mae_24_normalized,test/mae_28_denormalized,test/mae_28_normalized,test/mae_6_denormalized,test/mae_6_normalized,test/mae_8_denormalized,test/mae_8_normalized,test/mae_denormalized_mean,test/mae_normalized_mean,test/mape_16_denormalized,test/mape_16_normalized,test/mape_19_denormalized,test/mape_19_normalized,test/mape_24_denormalized,test/mape_24_normalized,test/mape_28_denormalized,test/mape_28_normalized,test/mape_6_denormalized,test/mape_6_normalized,test/mape_8_denormalized,test/mape_8_normalized,test/mape_denormalized_mean,test/mape_normalized_mean,test/mse_16_denormalized,test/mse_16_normalized,test/mse_19_denormalized,test/mse_19_normalized,test/mse_24_denormalized,test/mse_24_normalized,test/mse_28_denormalized,test/mse_28_normalized,test/mse_6_denormalized,test/mse_6_normalized,test/mse_8_denormalized,test/mse_8_normalized,test/mse_denormalized_mean,test/mse_normalized_mean,test/phm_score_16_denormalized,test/phm_score_16_normalized,test/phm_score_19_denormalized,test/phm_score_19_normalized,test/phm_score_24_denormalized,test/phm_score_24_normalized,test/phm_score_28_denormalized,test/phm_score_28_normalized,test/phm_score_6_denormalized,test/phm_score_6_normalized,test/phm_score_8_denormalized,test/phm_score_8_normalized,test/phm_score_denormalized_mean,test/phm_score_normalized_mean,test/rmse_16_denormalized,test/rmse_16_normalized,test/rmse_19_denormalized,test/rmse_19_normalized,test/rmse_24_denormalized,test/rmse_24_normalized,test/rmse_28_denormalized,test/rmse_28_normalized,test/rmse_6_denormalized,test/rmse_6_normalized,test/rmse_8_denormalized,test/rmse_8_normalized,test/rmse_denormalized_mean,test/rmse_normalized_mean,test_best_rerun/loss,test_best_rerun/mae_16_denormalized,test_best_rerun/mae_16_normalized,test_best_rerun/mae_19_denormalized,test_best_rerun/mae_19_normalized,test_best_rerun/mae_24_denormalized,test_best_rerun/mae_24_normalized,test_best_rerun/mae_28_denormalized,test_best_rerun/mae_28_normalized,test_best_rerun/mae_6_denormalized,test_best_rerun/mae_6_normalized,test_best_rerun/mae_8_denormalized,test_best_rerun/mae_8_normalized,test_best_rerun/mae_denormalized_mean,test_best_rerun/mae_normalized_mean,test_best_rerun/mape_16_denormalized,test_best_rerun/mape_16_normalized,test_best_rerun/mape_19_denormalized,test_best_rerun/mape_19_normalized,test_best_rerun/mape_24_denormalized,test_best_rerun/mape_24_normalized,test_best_rerun/mape_28_denormalized,test_best_rerun/mape_28_normalized,test_best_rerun/mape_6_denormalized,test_best_rerun/mape_6_normalized,test_best_rerun/mape_8_denormalized,test_best_rerun/mape_8_normalized,test_best_rerun/mape_denormalized_mean,test_best_rerun/mape_normalized_mean,test_best_rerun/mse_16_denormalized,test_best_rerun/mse_16_normalized,test_best_rerun/mse_19_denormalized,test_best_rerun/mse_19_normalized,test_best_rerun/mse_24_denormalized,test_best_rerun/mse_24_normalized,test_best_rerun/mse_28_denormalized,test_best_rerun/mse_28_normalized,test_best_rerun/mse_6_denormalized,test_best_rerun/mse_6_normalized,test_best_rerun/mse_8_denormalized,test_best_rerun/mse_8_normalized,test_best_rerun/mse_denormalized_mean,test_best_rerun/mse_normalized_mean,test_best_rerun/phm_score_16_denormalized,test_best_rerun/phm_score_16_normalized,test_best_rerun/phm_score_19_denormalized,test_best_rerun/phm_score_19_normalized,test_best_rerun/phm_score_24_denormalized,test_best_rerun/phm_score_24_normalized,test_best_rerun/phm_score_28_denormalized,test_best_rerun/phm_score_28_normalized,test_best_rerun/phm_score_6_denormalized,test_best_rerun/phm_score_6_normalized,test_best_rerun/phm_score_8_denormalized,test_best_rerun/phm_score_8_normalized,test_best_rerun/phm_score_denormalized_mean,test_best_rerun/phm_score_normalized_mean,test_best_rerun/rmse_16_denormalized,test_best_rerun/rmse_16_normalized,test_best_rerun/rmse_19_denormalized,test_best_rerun/rmse_19_normalized,test_best_rerun/rmse_24_denormalized,test_best_rerun/rmse_24_normalized,test_best_rerun/rmse_28_denormalized,test_best_rerun/rmse_28_normalized,test_best_rerun/rmse_6_denormalized,test_best_rerun/rmse_6_normalized,test_best_rerun/rmse_8_denormalized,test_best_rerun/rmse_8_normalized,test_best_rerun/rmse_denormalized_mean,test_best_rerun/rmse_normalized_mean,train/loss_epoch,train/loss_step,trainer/global_step,val/loss,val/mae_15_denormalized,val/mae_15_normalized,val/mae_18_denormalized,val/mae_18_normalized,val/mae_23_denormalized,val/mae_23_normalized,val/mae_27_denormalized,val/mae_27_normalized,val/mae_5_denormalized,val/mae_5_normalized,val/mae_7_denormalized,val/mae_7_normalized,val/mae_denormalized_mean,val/mae_normalized_mean,val/mape_15_denormalized,val/mape_15_normalized,val/mape_18_denormalized,val/mape_18_normalized,val/mape_23_denormalized,val/mape_23_normalized,val/mape_27_denormalized,val/mape_27_normalized,val/mape_5_denormalized,val/mape_5_normalized,val/mape_7_denormalized,val/mape_7_normalized,val/mape_denormalized_mean,val/mape_normalized_mean,val/mse_15_denormalized,val/mse_15_normalized,val/mse_18_denormalized,val/mse_18_normalized,val/mse_23_denormalized,val/mse_23_normalized,val/mse_27_denormalized,val/mse_27_normalized,val/mse_5_denormalized,val/mse_5_normalized,val/mse_7_denormalized,val/mse_7_normalized,val/mse_denormalized_mean,val/mse_normalized_mean,val/phm_score_15_denormalized,val/phm_score_15_normalized,val/phm_score_18_denormalized,val/phm_score_18_normalized,val/phm_score_23_denormalized,val/phm_score_23_normalized,val/phm_score_27_denormalized,val/phm_score_27_normalized,val/phm_score_5_denormalized,val/phm_score_5_normalized,val/phm_score_7_denormalized,val/phm_score_7_normalized,val/phm_score_denormalized_mean,val/phm_score_normalized_mean,val/rmse_15_denormalized,val/rmse_15_normalized,val/rmse_18_denormalized,val/rmse_18_normalized,val/rmse_23_denormalized,val/rmse_23_normalized,val/rmse_27_denormalized,val/rmse_27_normalized,val/rmse_5_denormalized,val/rmse_5_normalized,val/rmse_7_denormalized,val/rmse_7_normalized,val/rmse_denormalized_mean,val/rmse_normalized_mean,d_x,d_ff,d_yc,d_yt,loss,norm,seed,tags,test,cache,train,head_f,logger,base_lr,d_model,n_heads,trainer,verbose,d_layers,d_values,e_layers,exp_name,mask_y_c,metadata,use_time,evaluator,hydra_cfg,task_type,use_given,use_revin,use_space,activation,dropout_ff,evaluators,pin_memory,transforms,use_tt_dec,use_tt_enc,attn_factor,dropout_emb,dropout_qkv,max_seq_len,num_threads,num_workers,shuffle_val,subset_seed,use_val_dec,use_val_enc,embed_method,optimization,pos_emb_type,shuffle_test,time_emb_dim,warmup_steps,linear_window,shuffle_train,time_emb_type,class_loss_imp,d_queries_keys,n_timefeatures,performer_relu,recon_loss_imp,use_final_norm,val_batch_size,flash_attention,local_self_attn,prefetch_factor,start_token_len,test_batch_size,attention_method,dropout_attn_out,experiment_group,global_self_attn,inverted_encoder,local_cross_attn,performer_kernel,train_batch_size,attn_time_windows,global_cross_attn,use_batch_sampler,model/params/total,timetable_emb_type,train_subset_ratio,dropout_attn_matrix,enable_progress_bar,recon_mask_drop_seq,recon_mask_skip_all,use_seasonal_decomp,recon_mask_drop_full,linear_shared_weights,model/params/trainable,recon_mask_max_seq_len,scheduler_Loss_monitor,initial_downsample_convs,recon_mask_drop_standard,use_shifted_time_windows,performer_redraw_interval,intermediate_downsample_convs,run_name,val_best_rerun/loss,val_best_rerun/mae_15_denormalized,val_best_rerun/mae_15_normalized,val_best_rerun/mae_18_denormalized,val_best_rerun/mae_18_normalized,val_best_rerun/mae_23_denormalized,val_best_rerun/mae_23_normalized,val_best_rerun/mae_27_denormalized,val_best_rerun/mae_27_normalized,val_best_rerun/mae_5_denormalized,val_best_rerun/mae_5_normalized,val_best_rerun/mae_7_denormalized,val_best_rerun/mae_7_normalized,val_best_rerun/mae_denormalized_mean,val_best_rerun/mae_normalized_mean,val_best_rerun/mape_15_denormalized,val_best_rerun/mape_15_normalized,val_best_rerun/mape_18_denormalized,val_best_rerun/mape_18_normalized,val_best_rerun/mape_23_denormalized,val_best_rerun/mape_23_normalized,val_best_rerun/mape_27_denormalized,val_best_rerun/mape_27_normalized,val_best_rerun/mape_5_denormalized,val_best_rerun/mape_5_normalized,val_best_rerun/mape_7_denormalized,val_best_rerun/mape_7_normalized,val_best_rerun/mape_denormalized_mean,val_best_rerun/mape_normalized_mean,val_best_rerun/mse_15_denormalized,val_best_rerun/mse_15_normalized,val_best_rerun/mse_18_denormalized,val_best_rerun/mse_18_normalized,val_best_rerun/mse_23_denormalized,val_best_rerun/mse_23_normalized,val_best_rerun/mse_27_denormalized,val_best_rerun/mse_27_normalized,val_best_rerun/mse_5_denormalized,val_best_rerun/mse_5_normalized,val_best_rerun/mse_7_denormalized,val_best_rerun/mse_7_normalized,val_best_rerun/mse_denormalized_mean,val_best_rerun/mse_normalized_mean,val_best_rerun/phm_score_15_denormalized,val_best_rerun/phm_score_15_normalized,val_best_rerun/phm_score_18_denormalized,val_best_rerun/phm_score_18_normalized,val_best_rerun/phm_score_23_denormalized,val_best_rerun/phm_score_23_normalized,val_best_rerun/phm_score_27_denormalized,val_best_rerun/phm_score_27_normalized,val_best_rerun/phm_score_5_denormalized,val_best_rerun/phm_score_5_normalized,val_best_rerun/phm_score_7_denormalized,val_best_rerun/phm_score_7_normalized,val_best_rerun/phm_score_denormalized_mean,val_best_rerun/phm_score_normalized_mean,val_best_rerun/rmse_15_denormalized,val_best_rerun/rmse_15_normalized,val_best_rerun/rmse_18_denormalized,val_best_rerun/rmse_18_normalized,val_best_rerun/rmse_23_denormalized,val_best_rerun/rmse_23_normalized,val_best_rerun/rmse_27_denormalized,val_best_rerun/rmse_27_normalized,val_best_rerun/rmse_5_denormalized,val_best_rerun/rmse_5_normalized,val_best_rerun/rmse_7_denormalized,val_best_rerun/rmse_7_normalized,val_best_rerun/rmse_denormalized_mean,val_best_rerun/rmse_normalized_mean,"plots/test/pred_vs_target_unit_(16,)","plots/test/pred_vs_target_unit_(19,)","plots/test/pred_vs_target_unit_(24,)","plots/test/pred_vs_target_unit_(28,)","plots/test/pred_vs_target_unit_(6,)","plots/test/pred_vs_target_unit_(8,)","test/mae_(16,)_denormalized","test/mae_(16,)_normalized","test/mae_(19,)_denormalized","test/mae_(19,)_normalized","test/mae_(24,)_denormalized","test/mae_(24,)_normalized","test/mae_(28,)_denormalized","test/mae_(28,)_normalized","test/mae_(6,)_denormalized","test/mae_(6,)_normalized","test/mae_(8,)_denormalized","test/mae_(8,)_normalized","test/mape_(16,)_denormalized","test/mape_(16,)_normalized","test/mape_(19,)_denormalized","test/mape_(19,)_normalized","test/mape_(24,)_denormalized","test/mape_(24,)_normalized","test/mape_(28,)_denormalized","test/mape_(28,)_normalized","test/mape_(6,)_denormalized","test/mape_(6,)_normalized","test/mape_(8,)_denormalized","test/mape_(8,)_normalized","test/mse_(16,)_denormalized","test/mse_(16,)_normalized","test/mse_(19,)_denormalized","test/mse_(19,)_normalized","test/mse_(24,)_denormalized","test/mse_(24,)_normalized","test/mse_(28,)_denormalized","test/mse_(28,)_normalized","test/mse_(6,)_denormalized","test/mse_(6,)_normalized","test/mse_(8,)_denormalized","test/mse_(8,)_normalized","test/phm_score_(16,)_denormalized","test/phm_score_(16,)_normalized","test/phm_score_(19,)_denormalized","test/phm_score_(19,)_normalized","test/phm_score_(24,)_denormalized","test/phm_score_(24,)_normalized","test/phm_score_(28,)_denormalized","test/phm_score_(28,)_normalized","test/phm_score_(6,)_denormalized","test/phm_score_(6,)_normalized","test/phm_score_(8,)_denormalized","test/phm_score_(8,)_normalized","test/rmse_(16,)_denormalized","test/rmse_(16,)_normalized","test/rmse_(19,)_denormalized","test/rmse_(19,)_normalized","test/rmse_(24,)_denormalized","test/rmse_(24,)_normalized","test/rmse_(28,)_denormalized","test/rmse_(28,)_normalized","test/rmse_(6,)_denormalized","test/rmse_(6,)_normalized","test/rmse_(8,)_denormalized","test/rmse_(8,)_normalized",datasource._target_,datasource.data_dir,datasource.data_name,datasource.task_mode,task_definition.stride,task_definition.seq_len,task_definition.pred_len,task_definition.label_len,task_definition.task_type,task_definition.subset_seed,task_definition.stride_train,task_definition.subset_ratio,task_definition.target_metric,task_definition.requires_training,task_definition.target_metric_mode,task_definition.model.data_requirements.input_tensors,model.d_x,model.d_ff,model.d_yc,model.d_yt,model.base_lr,model.d_model,model.n_heads,model._target_,model.d_layers,model.e_layers,model.task_type,model.use_revin,model.dropout_ff,model.dropout_emb,model.dropout_qkv,model.max_seq_len,model.pos_emb_type,model.time_emb_dim,model.warmup_steps,model.time_emb_type,model.n_timefeatures,model.local_self_attn,model.start_token_len,model.global_self_attn,model.local_cross_attn,model.global_cross_attn,model.timetable_emb_type,model.dropout_attn_matrix,model.use_seasonal_decomp,model.metadata.lightning_model,model.device,model.n_jobs,model.fit_mode,model.random_state,model.yield_strategy,model.model_cache_path,model.yield_batch_size,model.ignore_pretraining_limits,dataset._target_,dataset._recursive_,dataset.dataset_cfg.stride,dataset.dataset_cfg.seq_len,dataset.dataset_cfg._target_,dataset.dataset_cfg.pred_len,dataset.dataset_cfg.label_len,dataset.dataset_cfg.task_type,dataset.dataset_cfg.get_unit_id,dataset.task_type,datamodule._target_,datamodule.num_workers,datamodule.shuffle_val,datamodule.subset_seed,datamodule.shuffle_test,datamodule.shuffle_train,datamodule.val_batch_size,datamodule.prefetch_factor,datamodule.test_batch_size,datamodule.train_batch_size,datamodule.train_subset_ratio,callbacks.model_timer._target_,callbacks.model_summary._target_,callbacks.model_summary.max_depth,callbacks.early_stopping.mode,callbacks.early_stopping.strict,callbacks.early_stopping.monitor,callbacks.early_stopping.verbose,callbacks.early_stopping._target_,callbacks.early_stopping.patience,callbacks.early_stopping.min_delta,callbacks.early_stopping.check_finite,callbacks.model_checkpoint.mode,callbacks.model_checkpoint.dirpath,callbacks.model_checkpoint.monitor,callbacks.model_checkpoint.verbose,callbacks.model_checkpoint._target_,callbacks.model_checkpoint.filename,callbacks.model_checkpoint.save_last,callbacks.model_checkpoint.save_top_k,callbacks.model_checkpoint.save_weights_only,callbacks.model_checkpoint.auto_insert_metric_name,callbacks.learning_rate_monitor._target_,callbacks.learning_rate_monitor.logging_interval,Model
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,274,7,1.769083e+09,{'runtime': 274},1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.488209,0.037377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.376313,1.376313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2706.514893,0.002307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25186,0.25186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.397102,0.047448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'_target_': 'lmetk.loss.default.MSELoss'},NaN,42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,NaN,{'wandb': {'id': 'debug+nb14+prognostics+combi...,NaN,NaN,NaN,"{'devices': 1, '_target_': 'lightning.pytorch....",NaN,NaN,NaN,NaN,nb14/prognostics/combined/tabdpt_fit_predict,NaN,NaN,NaN,{'val': {'paths': {'log_dir': '/workspace/expe...,"{'job': {'id': '???', 'num': '???', 'name': '$...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,{'scaler_target': {'metadata': {'fit_on': 'tra...,NaN,NaN,NaN,NaN,NaN,NaN,32,4,False,42,NaN,NaN,NaN,"{'lr': 0.001, 'optimizer': {'lr': 0.001, '_tar...",NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,True,NaN,10,NaN,1,NaN,NaN,debug,NaN,NaN,NaN,NaN,1,NaN,NaN,True,0,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,debug+nb14+prognostics+combined+tabdpt_fit_pre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",44.163700,0.040770,22.442686,0.020718,36.455959,0.033655,40.467197,0.037358,47.529469,0.043877,51.870247,0.047885,1.164886,1.164886,2.114726,2.114726,0.703857,0.703857,2.032989,2.032989,1.569433,1.569433,0.671988,0.671988,2958.088623,0.002521,1286.171875,0.001096,2309.209473,0.001968,2805.936523,0.002391,3044.403564,0.002595,3835.278076,0.003269,0.146434,0.146434,0.250058,0.250058,0.467127,0.467127,0.249610,0.249610,0.068433,0.068433,0.329497,0.329497,54.388313,0.050209,35.863239,0.033108,48.054237,0.044362,52.971092,0.048901,55.176113,0.050936,61.929623,0.057171,lmetk.data.datasources.nb14.loader.NB14Loader,/workspace/datasets,NB14,ahRul,1,1,1,0,rul,42,1,1,val/loss,True,min,"[features, rul, unit_id]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,lmetk.model.wrappers.fit_predict_tabdpt_wrappe...,NaN,NaN,rul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gpu,32.0,fit_with_cache_single_step_inference,42.0,False,/workspace/experiments/2025-09-18_TabPHM/debug...,1.0,True,lmetk.data.datasets.fit_predict_dataset.FitPre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,rul,lmetk.data.datamodules.base.BaseDataModule,4,False,42,False,False,1,10,1,1,NaN,NaN,lightning.pytorch.callbacks.RichModelSummary,-1,min,NaN,val/loss,NaN,NaN,NaN,NaN,NaN,min,NaN,val/loss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lmetk.model.wrappers.fit_predict_tabdpt_wrappe...

In [4]:
display(all_results[key][key_2]['sorted_aggregated_results'])

                                               Model                    model.kernels                   model.strides                 model.dilations                     model.output_channels  \

0  lmetk.model.autoencoder.wrapper.AutoencoderWra...                  (5, 5, 5, 5, 5)                 (1, 1, 1, 1, 1)                 (1, 2, 4, 8, 1)                      (16, 32, 64, 64, 64)
2  lmetk.model.autoencoder.wrapper.AutoencoderWra...  (10, 7, 7, 7, 7, 7, 7, 7, 7, 7)  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1)  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1)  (16, 32, 64, 64, 64, 16, 32, 64, 64, 64)
1  lmetk.model.autoencoder.wrapper.AutoencoderWra...                  (7, 7, 5, 5, 5)                 (2, 2, 1, 1, 1)                 (1, 1, 1, 1, 1)                      (16, 32, 64, 64, 64)

   val/loss       val/mse       val/mae      val/rmse     test/loss      test/mse      test/mae     test/rmse                                               run_name
       mean std      mean std      mean std      mean std      mean std      mean std      mean std      mean std                                               list
0  0.000058 NaN  0.000058 NaN  0.004978 NaN  0.007645 NaN  0.000058 NaN  0.000058 NaN  0.004978 NaN  0.007645 NaN  [pronostia+reconstruction+residual_autoencoder...
2  0.000063 NaN  0.000063 NaN  0.005087 NaN  0.007926 NaN  0.000063 NaN  0.000063 NaN  0.005087 NaN  0.007926 NaN  [pronostia+reconstruction+residual_autoencoder...
1  0.000082 NaN  0.000082 NaN  0.005265 NaN  0.009032 NaN  0.000082 NaN  0.000082 NaN  0.005265 NaN  0.009032 NaN  [pronostia+reconstruction+residual_autoencoder...

In [ ]:
for i in all_results[key][key_2]['non_aggregated_df']['callbacks.model_checkpoint.dirpath']:
    print(str(i))

/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_03-30-38/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_03-30-47/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_11-49-26/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_12-25-24/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_20-06-41/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-02_21-16-34/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-03_04-29-43/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-03_06-05-58/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-03_12-52-08/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-03_15-00-09/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-04_00-04-10/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-04_03-44-54/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-04_12-47-45/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-04_15-23-25/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-04_20-14-20/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_01-07-47/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_04-02-29/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_08-46-10/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_09-27-12/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_13-37-17/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_17-48-13/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_18-18-10/checkpoints/checkpoints
/home/levtel/projects/TabPHM/artifacts/debug/runs/pronostia+reconstruction+residual_autoencoder/2025-10-05_22-49-19/checkpoints/checkpoints

In [45]:
all_results[key][key_2]['non_aggregated_df']

,_runtime,_step,_timestamp,_wandb,epoch,lr-Adam,train/loss_step,trainer/global_step,loss,seed,tags,test,cache,train,logger,trainer,exp_name,evaluator,hydra_cfg,pin_memory,transforms,num_workers,shuffle_val,shuffle_test,shuffle_train,val_batch_size,prefetch_factor,test_batch_size,experiment_group,train_batch_size,use_batch_sampler,model/params/total,model/params/trainable,run_name,AvgTime/train_batch_mean,AvgTime/train_batch_std,AvgTime/train_epoch_mean,AvgTime/train_epoch_std,AvgTime/val_batch_mean,AvgTime/val_batch_std,AvgTime/val_epoch_mean,AvgTime/val_epoch_std,plots/test/reconstructions_overview,plots/train/reconstructions_overview,plots/val/reconstructions_overview,test/loss,test/mae,test/mse,test/rmse,train/loss_epoch,train/mae,train/mse,train/rmse,val/loss,val/mae,val/mse,val/rmse,num_threads,optimizer._target_,optimizer.optimizer_id,optimizer.scheduler.scheduler_id,optimizer.scheduler.scheduler_params.gamma,optimizer.scheduler.scheduler_params.step_size,optimizer.parameters.lr,optimizer.parameters.weight_decay,datasource._target_,datasource.data_dir,datasource.data_name,datasource.task_mode,datasource.fold,datasource.cache_dir,task_definition.stride,task_definition.seq_len,task_definition.pred_len,task_definition.label_len,task_definition.task_type,task_definition.requires_training,task_definition.model.data_requirements.input_tensors,model.kernels,model.strides,model._target_,model.dilations,model.latent_dim,model.dropout_prob,model.input_seq_len,model.input_channels,model.output_channels,model.blocks_config,dataset._target_,dataset._recursive_,dataset.dataset_cfg.stride,dataset.dataset_cfg.seq_len,dataset.dataset_cfg._target_,dataset.dataset_cfg.pred_len,dataset.dataset_cfg.label_len,datamodule._target_,datamodule.num_workers,datamodule.shuffle_val,datamodule.shuffle_test,datamodule.shuffle_train,datamodule.val_batch_size,datamodule.prefetch_factor,datamodule.test_batch_size,datamodule.train_batch_size,callbacks.model_timer._target_,callbacks.model_summary._target_,callbacks.model_summary.max_depth,callbacks.early_stopping.mode,callbacks.early_stopping.strict,callbacks.early_stopping.monitor,callbacks.early_stopping.verbose,callbacks.early_stopping._target_,callbacks.early_stopping.patience,callbacks.early_stopping.min_delta,callbacks.early_stopping.check_finite,callbacks.model_checkpoint.mode,callbacks.model_checkpoint.dirpath,callbacks.model_checkpoint.monitor,callbacks.model_checkpoint.verbose,callbacks.model_checkpoint._target_,callbacks.model_checkpoint.filename,callbacks.model_checkpoint.save_last,callbacks.model_checkpoint.save_top_k,callbacks.model_checkpoint.save_weights_only,callbacks.model_checkpoint.auto_insert_metric_name,callbacks.learning_rate_monitor._target_,callbacks.learning_rate_monitor.logging_interval,Model
52,29813,31573,1.759431e+09,{'runtime': 29813},20,0.00500,6.167217e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,183208,183208,pronostia+reconstruction+residual_autoencoder_...,0.015844,0.003353,1487.310064,21.117129,0.006290,0.001688,67.621402,2.877372,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",1.429764e-04,0.007379,2.859528e-04,0.011957,6.198527e-02,0.012541,1.239705e-01,2.489684e-01,1.429764e-04,0.007379,2.859528e-04,0.011957,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,10,0.0100,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[7, 7, 5, 5, 5]","[2, 2, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 1, 1, 1, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
53,32048,31573,1.759433e+09,{'runtime': 32048},20,0.00500,4.372379e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,380712,380712,pronostia+reconstruction+residual_autoencoder_...,0.016962,0.002840,1582.755228,26.869932,0.007970,0.000694,81.114039,0.254347,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",1.431614e-04,0.007391,2.863229e-04,0.011965,9.220403e-01,0.049927,1.844081e+00,9.602293e-01,1.431614e-04,0.007391,2.863229e-04,0.011965,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,10,0.0100,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[5, 5, 5, 5, 5]","[1, 1, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 2, 4, 8, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
54,29719,31573,1.759461e+09,{'runtime': 29719},20,0.01000,1.288899e+01,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,183208,183208,pronostia+reconstruction+residual_autoencoder_...,0.015785,0.003377,1466.348889,18.812763,0.006267,0.001886,66.962645,0.504608,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",9.710656e-01,0.426614,1.942131e+00,0.985427,2.933880e+03,1.730053,5.867761e+03,5.416531e+01,9.710656e-01,0.426614,1.942131e+00,0.985427,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,20,0.0100,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[7, 7, 5, 5, 5]","[2, 2, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 1, 1, 1, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
55,31840,31573,1.759465e+09,{'runtime': 31840},20,0.01000,1.099149e+01,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,380712,380712,pronostia+reconstruction+residual_autoencoder_...,0.016877,0.003119,1573.297565,33.722049,0.007571,0.001190,78.034014,1.464498,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",4.378249e+01,4.490829,8.756498e+01,6.616834,2.274193e+05,21.161001,4.548386e+05,4.768850e+02,4.378249e+01,4.490829,8.756498e+01,6.616834,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,20,0.0100,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[5, 5, 5, 5, 5]","[1, 1, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 2, 4, 8, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
56,30068,31573,1.759491e+09,{'runtime': 30068},20,0.00050,2.982121e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,183208,183208,pronostia+reconstruction+residual_autoencoder_...,0.015984,0.003201,1490.208160,17.926115,0.006117,0.001502,67.302623,0.425205,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",8.658919e-05,0.005517,1.731784e-04,0.009305,3.515945e-05,0.003662,7.031889e-05,5.929540e-03,8.658919e-05,0.005517,1.731784e-04,0.009305,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,10,0.0010,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[7, 7, 5, 5, 5]","[2, 2, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 1, 1, 1, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
57,31734,31573,1.759497e+09,{'runtime': 31734},20,0.00050,1.169748e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,380712,380712,pronostia+reconstruction+residual_autoencoder_...,0.016780,0.002908,1576.646617,19.061020,0.007803,0.001785,80.200998,1.764167,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",6.953782e-05,0.005220,1.390756e-04,0.008339,1.802474e-05,0.002906,3.604949e-05,4.245555e-03,6.953782e-05,0.005220,1.390756e-04,0.008339,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,10,0.0010,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[5, 5, 5, 5, 5]","[1, 1, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 2, 4, 8, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
58,30116,31573,1.759521e+09,{'runtime': 30116},20,0.00100,3.482414e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,183208,183208,pronostia+reconstruction+residual_autoencoder_...,0.015997,0.003466,1479.457636,22.711976,0.006192,0.002118,66.938652,0.629522,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",8.837935e-05,0.005524,1.767587e-04,0.009401,4.051581e-05,0.003861,8.103161e-05,6.365203e-03,8.837935e-05,0.005524,1.767587e-04,0.009401,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,20,0.0010,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[7, 7, 5, 5, 5]","[2, 2, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 1, 1, 1, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...
59,31937,31573,1.759529e+09,{'runtime': 31937},20,0.00100,1.176501e-05,1573580,{'_target_': 'lmetk.loss.default.MSELoss'},42,[dev],True,"{'use_cache_after_loading': True, 'use_cache_a...",True,{'wandb': {'id': 'pronostia+reconstruction+res...,"{'devices': [1], '_target_': 'lightning.pytorc...",pronostia/reconstruction/residual_autoencoder,{'val': {'paths': {'log_dir': '/home/levtel/pr...,"{'job': {'id': '???', 'num': '???', 'name': '$...",True,{'scaler_features': {'metadata': {'fit_on': 't...,4,False,False,True,1024,10,1024,debug,128,True,380712,380712,pronostia+reconstruction+residual_autoencoder_...,0.016918,0.002919,1595.559204,18.665088,0.007718,0.001875,78.878340,1.629463,"{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...","{'_type': 'plotly-file', 'path': 'media/plotly...",7.206259e-05,0.005244,1.441252e-04,0.008489,1.820032e-05,0.002917,3.640064e-05,4.266183e-03,7.206259e-05,0.005244,1.441252e-04,0.008489,NaN,lmetk.optimizer.default.DefaultOptimizer,Adam,StepLR,0.5,20,0.0010,0,lmetk.data.datasources.phmd_pronostia.Pronosti...,NaN,PRONOSTIA,rul,0.0,/home/levtel/projects/TabPHM/datasets/phmd_cache,1,64,0,0,reconstruction,True,[features],"[5, 5, 5, 5, 5]","[1, 1, 1, 1, 1]",lmetk.model.autoencoder.wrapper.AutoencoderWra...,"[1, 2, 4, 8, 1]",32,0.2,64,2,"[16, 32, 64, 64, 64]","[{'in': 2, 'out': 16, 'kernel': 7, 'stride': 2...",lmetk.data.datasets.hydra_concat_dataset.Hydra...,False,1,64,lmetk.data.datasets.sliding_window_batch_datas...,0,0,lmetk.data.datamodules.base.BaseDataModule,4,False,False,True,1024,10,1024,128,lmetk.callbacks.timer_callback.PipelineTimer,lightning.pytorch.callbacks.RichModelSummary,-1,min,True,val/loss,True,lightning.pytorch.callbacks.EarlyStopping,25,0,True,min,/home/levtel/projects/TabPHM/artifacts/debug/r...,val/loss,False,lightning.pytorch.callbacks.ModelCheckpoint,epoch{epoch:03d}-val_loss{val/loss:.2f},False,1,False,False,lightning.pytorch.callbacks.LearningRateMonitor,epoch,lmetk.model.autoencoder.wrapper.AutoencoderWra...

In [36]:
# If run_name is the first element in the tuple